// Auto-generated by flexsoc.backend.design.rtl.
module uart_master
  import uart_master_reg_pkg::*;
(
 input logic clk_i,
 input logic rst_ni,
 output logic req_o,
 input logic gnt_i,
 output logic [31:0] addr_o,
 output logic we_o,
 output logic [31:0] wdata_o,
 output logic [3:0] be_o,
 input logic valid_i,
 input logic [31:0] rdata_i,
 input logic err_i,
 input logic cio_rx_i,
 output logic cio_tx_o,
 output logic cio_tx_en_o,
 input tlul_pkg::tl_h2d_t tl_i,
 output tlul_pkg::tl_d2h_t tl_o
);

  uart_master_reg2hw_t reg2hw;
  uart_master_hw2reg_t hw2reg;

  logic reg_rst_sync_ni;
  logic core_rst_sync_ni;
  // Async assertion, synchronous release.
  // The register island is released after the two-stage synchronizer.
  // The functional core is released one cycle later.
  prim_ff_2sync #(
    .Width      (1),
    .ResetValue (1'b0)
  ) u_reset_sync (
    .clk_i (clk_i),
    .rst_ni(rst_ni),
    .d_i   (1'b1),
    .q_o   (reg_rst_sync_ni)
  );

  prim_flop #(
    .Width      (1),
    .ResetValue (1'b0)
  ) u_core_reset_stage (
    .clk_i (clk_i),
    .rst_ni(rst_ni),
    .d_i   (reg_rst_sync_ni),
    .q_o   (core_rst_sync_ni)
  );

  uart_master_reg_top u_uart_master_reg (
    .clk_i(clk_i),
    .rst_ni(reg_rst_sync_ni),
    .tl_i(tl_i),
    .tl_o(tl_o),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg),
    .devmode_i(1'b1)
  );

  uart_master_core u_uart_master_core (
    .clk_i(clk_i),
    .rst_ni(core_rst_sync_ni),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg),
    .req_o(req_o),
    .gnt_i(gnt_i),
    .addr_o(addr_o),
    .we_o(we_o),
    .wdata_o(wdata_o),
    .be_o(be_o),
    .valid_i(valid_i),
    .rdata_i(rdata_i),
    .err_i(err_i),
    .cio_rx_i(cio_rx_i),
    .cio_tx_o(cio_tx_o),
    .cio_tx_en_o(cio_tx_en_o)
  );

endmodule
