// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package uart_master_reg_pkg;

  // Param list
  parameter int RxFifoDepth = 16;
  parameter int TxFifoDepth = 8;

  // Address widths within the block
  parameter int BlockAw = 5;
  parameter int AW = BlockAw;
  parameter int DW = 32;
  parameter int DBW = DW/8;                    // Byte Width

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } nco;
    struct packed {
      logic        q;
    } parity_odd;
    struct packed {
      logic        q;
    } parity_en;
    struct packed {
      logic        q;
    } llpbk;
    struct packed {
      logic        q;
    } slpbk;
    struct packed {
      logic        q;
    } nf;
    struct packed {
      logic        q;
    } rx;
    struct packed {
      logic        q;
    } tx;
  } uart_master_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        re;
    } rxempty;
    struct packed {
      logic        q;
      logic        re;
    } rxidle;
    struct packed {
      logic        q;
      logic        re;
    } txidle;
    struct packed {
      logic        q;
      logic        re;
    } txempty;
    struct packed {
      logic        q;
      logic        re;
    } rxfull;
    struct packed {
      logic        q;
      logic        re;
    } txfull;
  } uart_master_reg2hw_status_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        re;
  } uart_master_reg2hw_rdata_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } uart_master_reg2hw_wdata_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } txrst;
    struct packed {
      logic        q;
      logic        qe;
    } rxrst;
  } uart_master_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } txfull;
    struct packed {
      logic        d;
    } rxfull;
    struct packed {
      logic        d;
    } txempty;
    struct packed {
      logic        d;
    } txidle;
    struct packed {
      logic        d;
    } rxidle;
    struct packed {
      logic        d;
    } rxempty;
  } uart_master_hw2reg_status_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } uart_master_hw2reg_rdata_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } txlvl;
    struct packed {
      logic [7:0]  d;
    } rxlvl;
  } uart_master_hw2reg_fifo_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    uart_master_reg2hw_ctrl_reg_t ctrl; // [56:34]
    uart_master_reg2hw_status_reg_t status; // [33:22]
    uart_master_reg2hw_rdata_reg_t rdata; // [21:13]
    uart_master_reg2hw_wdata_reg_t wdata; // [12:4]
    uart_master_reg2hw_fifo_ctrl_reg_t fifo_ctrl; // [3:0]
  } uart_master_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    uart_master_hw2reg_status_reg_t status; // [29:24]
    uart_master_hw2reg_rdata_reg_t rdata; // [23:16]
    uart_master_hw2reg_fifo_status_reg_t fifo_status; // [15:0]
  } uart_master_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] UART_MASTER_CTRL_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] UART_MASTER_STATUS_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] UART_MASTER_RDATA_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] UART_MASTER_WDATA_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] UART_MASTER_FIFO_CTRL_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] UART_MASTER_FIFO_STATUS_OFFSET = 5'h 14;

  // Reset values for hwext registers and their fields
  parameter logic [5:0] UART_MASTER_STATUS_RESVAL = 6'h 3c;
  parameter logic [0:0] UART_MASTER_STATUS_TXEMPTY_RESVAL = 1'h 1;
  parameter logic [0:0] UART_MASTER_STATUS_TXIDLE_RESVAL = 1'h 1;
  parameter logic [0:0] UART_MASTER_STATUS_RXIDLE_RESVAL = 1'h 1;
  parameter logic [0:0] UART_MASTER_STATUS_RXEMPTY_RESVAL = 1'h 1;
  parameter logic [7:0] UART_MASTER_RDATA_RESVAL = 8'h 0;
  parameter logic [23:0] UART_MASTER_FIFO_STATUS_RESVAL = 24'h 0;

  // Register index
  typedef enum int {
    UART_MASTER_CTRL,
    UART_MASTER_STATUS,
    UART_MASTER_RDATA,
    UART_MASTER_WDATA,
    UART_MASTER_FIFO_CTRL,
    UART_MASTER_FIFO_STATUS
  } uart_master_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] UART_MASTER_PERMIT [6] = '{
    4'b 1111, // index[0] UART_MASTER_CTRL
    4'b 0001, // index[1] UART_MASTER_STATUS
    4'b 0001, // index[2] UART_MASTER_RDATA
    4'b 0001, // index[3] UART_MASTER_WDATA
    4'b 0001, // index[4] UART_MASTER_FIFO_CTRL
    4'b 0111  // index[5] UART_MASTER_FIFO_STATUS
  };

  parameter type reg_req_t = struct packed {
    logic           valid;
    logic           write;
    logic [AW-1:0]  addr;
    logic [DW-1:0]  wdata;
    logic [DBW-1:0] wstrb;
  };

  parameter type reg_rsp_t = struct packed {
    logic [DW-1:0]  rdata;
    logic           error;
    logic           ready;
  };

endpackage
