// -----------------------------------------------------------------------------
// Auto-generated CORDIC LUT package
// -----------------------------------------------------------------------------
// Generated by:
//   py/gen_cordic_rtl_lut.py
//
// Do not edit manually.
// -----------------------------------------------------------------------------

package cordic_lut_pkg;

  // Signed fixed-point angle constants in Q format with:
  //   width = 16
  //   frac  = 13
  localparam logic signed [15:0] PI_Q      = 16'sd25736;
  localparam logic signed [15:0] HALF_PI_Q = 16'sd12868;

  // atan(2^-i) lookup table
  localparam logic signed [15:0] AtanLut [0:15] = '{
    16'sd6434,
    16'sd3798,
    16'sd2007,
    16'sd1019,
    16'sd511,
    16'sd256,
    16'sd128,
    16'sd64,
    16'sd32,
    16'sd16,
    16'sd8,
    16'sd4,
    16'sd2,
    16'sd1,
    16'sd0,
    16'sd0
  };

endpackage
