// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "prim_assert.sv"

module cordic_reg_top
  import cordic_reg_pkg::* ;
(
  input logic clk_i,
  input logic rst_ni,
  // From TLUL
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output cordic_reg_pkg::cordic_reg2hw_t reg2hw, // Write
  input  cordic_reg_pkg::cordic_hw2reg_t hw2reg, // Read

  // Devmode
  input logic devmode_i // If 1, explicit error return for unmapped register access
);

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(0),
    .EnableDataIntgGen(0)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;


  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_we;
  logic ctrl_start_qs;
  logic ctrl_start_wd;
  logic ctrl_mode_qs;
  logic ctrl_mode_wd;
  logic ctrl_soft_rst_qs;
  logic ctrl_soft_rst_wd;
  logic [4:0] ctrl_rsvd_qs;
  logic [4:0] ctrl_rsvd_wd;
  logic [7:0] ctrl_n_iter_qs;
  logic [7:0] ctrl_n_iter_wd;
  logic [15:0] ctrl_rsvd2_qs;
  logic [15:0] ctrl_rsvd2_wd;
  logic status_re;
  logic status_busy_qs;
  logic status_valid_qs;
  logic status_error_qs;
  logic [28:0] status_rsvd_qs;
  logic x_in_we;
  logic [31:0] x_in_qs;
  logic [31:0] x_in_wd;
  logic y_in_we;
  logic [31:0] y_in_qs;
  logic [31:0] y_in_wd;
  logic z_in_we;
  logic [31:0] z_in_qs;
  logic [31:0] z_in_wd;
  logic x_out_re;
  logic [31:0] x_out_qs;
  logic y_out_re;
  logic [31:0] y_out_qs;
  logic z_out_re;
  logic [31:0] z_out_qs;
  logic cfg_re;
  logic [7:0] cfg_data_width_qs;
  logic [7:0] cfg_frac_width_qs;
  logic [7:0] cfg_max_iter_qs;
  logic [7:0] cfg_rsvd_qs;

  // Register instances
  // R[ctrl]: V(False)
  //   F[start]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_start (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_start_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.start.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_start_qs)
  );

  //   F[mode]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_mode (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_mode_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_mode_qs)
  );

  //   F[soft_rst]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_soft_rst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_soft_rst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.soft_rst.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_soft_rst_qs)
  );

  //   F[rsvd]: 7:3
  prim_subreg #(
    .DW      (5),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (5'h0),
    .Mubi    (1'b0)
  ) u_ctrl_rsvd (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_rsvd_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.rsvd.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_rsvd_qs)
  );

  //   F[n_iter]: 15:8
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_ctrl_n_iter (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_n_iter_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.n_iter.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_n_iter_qs)
  );

  //   F[rsvd2]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_ctrl_rsvd2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_rsvd2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.rsvd2.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_rsvd2_qs)
  );


  // R[status]: V(True)
  //   F[busy]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_busy (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.busy.d),
    .qre    (reg2hw.status.busy.re),
    .qe     (),
    .q      (reg2hw.status.busy.q),
    .ds     (),
    .qs     (status_busy_qs)
  );

  //   F[valid]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_valid (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.valid.d),
    .qre    (reg2hw.status.valid.re),
    .qe     (),
    .q      (reg2hw.status.valid.q),
    .ds     (),
    .qs     (status_valid_qs)
  );

  //   F[error]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_error (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.error.d),
    .qre    (reg2hw.status.error.re),
    .qe     (),
    .q      (reg2hw.status.error.q),
    .ds     (),
    .qs     (status_error_qs)
  );

  //   F[rsvd]: 31:3
  prim_subreg_ext #(
    .DW    (29)
  ) u_status_rsvd (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rsvd.d),
    .qre    (reg2hw.status.rsvd.re),
    .qe     (),
    .q      (reg2hw.status.rsvd.q),
    .ds     (),
    .qs     (status_rsvd_qs)
  );


  // R[x_in]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_x_in (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (x_in_we),
    .wd     (x_in_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.x_in.q),
    .ds     (),

    // to register interface (read)
    .qs     (x_in_qs)
  );


  // R[y_in]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_y_in (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (y_in_we),
    .wd     (y_in_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.y_in.q),
    .ds     (),

    // to register interface (read)
    .qs     (y_in_qs)
  );


  // R[z_in]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_z_in (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (z_in_we),
    .wd     (z_in_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.z_in.q),
    .ds     (),

    // to register interface (read)
    .qs     (z_in_qs)
  );


  // R[x_out]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_x_out (
    .re     (x_out_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.x_out.d),
    .qre    (reg2hw.x_out.re),
    .qe     (),
    .q      (reg2hw.x_out.q),
    .ds     (),
    .qs     (x_out_qs)
  );


  // R[y_out]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_y_out (
    .re     (y_out_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.y_out.d),
    .qre    (reg2hw.y_out.re),
    .qe     (),
    .q      (reg2hw.y_out.q),
    .ds     (),
    .qs     (y_out_qs)
  );


  // R[z_out]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_z_out (
    .re     (z_out_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.z_out.d),
    .qre    (reg2hw.z_out.re),
    .qe     (),
    .q      (reg2hw.z_out.q),
    .ds     (),
    .qs     (z_out_qs)
  );


  // R[cfg]: V(True)
  //   F[data_width]: 7:0
  prim_subreg_ext #(
    .DW    (8)
  ) u_cfg_data_width (
    .re     (cfg_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.cfg.data_width.d),
    .qre    (reg2hw.cfg.data_width.re),
    .qe     (),
    .q      (reg2hw.cfg.data_width.q),
    .ds     (),
    .qs     (cfg_data_width_qs)
  );

  //   F[frac_width]: 15:8
  prim_subreg_ext #(
    .DW    (8)
  ) u_cfg_frac_width (
    .re     (cfg_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.cfg.frac_width.d),
    .qre    (reg2hw.cfg.frac_width.re),
    .qe     (),
    .q      (reg2hw.cfg.frac_width.q),
    .ds     (),
    .qs     (cfg_frac_width_qs)
  );

  //   F[max_iter]: 23:16
  prim_subreg_ext #(
    .DW    (8)
  ) u_cfg_max_iter (
    .re     (cfg_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.cfg.max_iter.d),
    .qre    (reg2hw.cfg.max_iter.re),
    .qe     (),
    .q      (reg2hw.cfg.max_iter.q),
    .ds     (),
    .qs     (cfg_max_iter_qs)
  );

  //   F[rsvd]: 31:24
  prim_subreg_ext #(
    .DW    (8)
  ) u_cfg_rsvd (
    .re     (cfg_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.cfg.rsvd.d),
    .qre    (reg2hw.cfg.rsvd.re),
    .qe     (),
    .q      (reg2hw.cfg.rsvd.q),
    .ds     (),
    .qs     (cfg_rsvd_qs)
  );



  logic [8:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CORDIC_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == CORDIC_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == CORDIC_X_IN_OFFSET);
    addr_hit[3] = (reg_addr == CORDIC_Y_IN_OFFSET);
    addr_hit[4] = (reg_addr == CORDIC_Z_IN_OFFSET);
    addr_hit[5] = (reg_addr == CORDIC_X_OUT_OFFSET);
    addr_hit[6] = (reg_addr == CORDIC_Y_OUT_OFFSET);
    addr_hit[7] = (reg_addr == CORDIC_Z_OUT_OFFSET);
    addr_hit[8] = (reg_addr == CORDIC_CFG_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CORDIC_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(CORDIC_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(CORDIC_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(CORDIC_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(CORDIC_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(CORDIC_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(CORDIC_PERMIT[6] & ~reg_be))) |
               (addr_hit[7] & (|(CORDIC_PERMIT[7] & ~reg_be))) |
               (addr_hit[8] & (|(CORDIC_PERMIT[8] & ~reg_be)))));
  end

  // Generate write-enables
  assign ctrl_we = addr_hit[0] & reg_we & !reg_error;

  assign ctrl_start_wd = reg_wdata[0];

  assign ctrl_mode_wd = reg_wdata[1];

  assign ctrl_soft_rst_wd = reg_wdata[2];

  assign ctrl_rsvd_wd = reg_wdata[7:3];

  assign ctrl_n_iter_wd = reg_wdata[15:8];

  assign ctrl_rsvd2_wd = reg_wdata[31:16];
  assign status_re = addr_hit[1] & reg_re & !reg_error;
  assign x_in_we = addr_hit[2] & reg_we & !reg_error;

  assign x_in_wd = reg_wdata[31:0];
  assign y_in_we = addr_hit[3] & reg_we & !reg_error;

  assign y_in_wd = reg_wdata[31:0];
  assign z_in_we = addr_hit[4] & reg_we & !reg_error;

  assign z_in_wd = reg_wdata[31:0];
  assign x_out_re = addr_hit[5] & reg_re & !reg_error;
  assign y_out_re = addr_hit[6] & reg_re & !reg_error;
  assign z_out_re = addr_hit[7] & reg_re & !reg_error;
  assign cfg_re = addr_hit[8] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_start_qs;
        reg_rdata_next[1] = ctrl_mode_qs;
        reg_rdata_next[2] = ctrl_soft_rst_qs;
        reg_rdata_next[7:3] = ctrl_rsvd_qs;
        reg_rdata_next[15:8] = ctrl_n_iter_qs;
        reg_rdata_next[31:16] = ctrl_rsvd2_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_busy_qs;
        reg_rdata_next[1] = status_valid_qs;
        reg_rdata_next[2] = status_error_qs;
        reg_rdata_next[31:3] = status_rsvd_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = x_in_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = y_in_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = z_in_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = x_out_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = y_out_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = z_out_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[7:0] = cfg_data_width_qs;
        reg_rdata_next[15:8] = cfg_frac_width_qs;
        reg_rdata_next[23:16] = cfg_max_iter_qs;
        reg_rdata_next[31:24] = cfg_rsvd_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule


