// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package cordic_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;
  parameter int AW = BlockAw;
  parameter int DW = 32;
  parameter int DBW = DW/8;                    // Byte Width

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } rsvd2;
    struct packed {
      logic [7:0]  q;
    } n_iter;
    struct packed {
      logic [4:0]  q;
    } rsvd;
    struct packed {
      logic        q;
    } soft_rst;
    struct packed {
      logic        q;
    } mode;
    struct packed {
      logic        q;
    } start;
  } cordic_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [28:0] q;
      logic        re;
    } rsvd;
    struct packed {
      logic        q;
      logic        re;
    } error;
    struct packed {
      logic        q;
      logic        re;
    } valid;
    struct packed {
      logic        q;
      logic        re;
    } busy;
  } cordic_reg2hw_status_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } cordic_reg2hw_x_in_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } cordic_reg2hw_y_in_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } cordic_reg2hw_z_in_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } cordic_reg2hw_x_out_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } cordic_reg2hw_y_out_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } cordic_reg2hw_z_out_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
      logic        re;
    } rsvd;
    struct packed {
      logic [7:0]  q;
      logic        re;
    } max_iter;
    struct packed {
      logic [7:0]  q;
      logic        re;
    } frac_width;
    struct packed {
      logic [7:0]  q;
      logic        re;
    } data_width;
  } cordic_reg2hw_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } busy;
    struct packed {
      logic        d;
    } valid;
    struct packed {
      logic        d;
    } error;
    struct packed {
      logic [28:0] d;
    } rsvd;
  } cordic_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } cordic_hw2reg_x_out_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } cordic_hw2reg_y_out_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } cordic_hw2reg_z_out_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } data_width;
    struct packed {
      logic [7:0]  d;
    } frac_width;
    struct packed {
      logic [7:0]  d;
    } max_iter;
    struct packed {
      logic [7:0]  d;
    } rsvd;
  } cordic_hw2reg_cfg_reg_t;

  // Register -> HW type
  typedef struct packed {
    cordic_reg2hw_ctrl_reg_t ctrl; // [298:267]
    cordic_reg2hw_status_reg_t status; // [266:231]
    cordic_reg2hw_x_in_reg_t x_in; // [230:199]
    cordic_reg2hw_y_in_reg_t y_in; // [198:167]
    cordic_reg2hw_z_in_reg_t z_in; // [166:135]
    cordic_reg2hw_x_out_reg_t x_out; // [134:102]
    cordic_reg2hw_y_out_reg_t y_out; // [101:69]
    cordic_reg2hw_z_out_reg_t z_out; // [68:36]
    cordic_reg2hw_cfg_reg_t cfg; // [35:0]
  } cordic_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    cordic_hw2reg_status_reg_t status; // [159:128]
    cordic_hw2reg_x_out_reg_t x_out; // [127:96]
    cordic_hw2reg_y_out_reg_t y_out; // [95:64]
    cordic_hw2reg_z_out_reg_t z_out; // [63:32]
    cordic_hw2reg_cfg_reg_t cfg; // [31:0]
  } cordic_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CORDIC_CTRL_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] CORDIC_STATUS_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] CORDIC_X_IN_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] CORDIC_Y_IN_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] CORDIC_Z_IN_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] CORDIC_X_OUT_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] CORDIC_Y_OUT_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] CORDIC_Z_OUT_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] CORDIC_CFG_OFFSET = 6'h 20;

  // Reset values for hwext registers and their fields
  parameter logic [31:0] CORDIC_STATUS_RESVAL = 32'h 0;
  parameter logic [31:0] CORDIC_X_OUT_RESVAL = 32'h 0;
  parameter logic [31:0] CORDIC_Y_OUT_RESVAL = 32'h 0;
  parameter logic [31:0] CORDIC_Z_OUT_RESVAL = 32'h 0;
  parameter logic [31:0] CORDIC_CFG_RESVAL = 32'h 0;

  // Register index
  typedef enum int {
    CORDIC_CTRL,
    CORDIC_STATUS,
    CORDIC_X_IN,
    CORDIC_Y_IN,
    CORDIC_Z_IN,
    CORDIC_X_OUT,
    CORDIC_Y_OUT,
    CORDIC_Z_OUT,
    CORDIC_CFG
  } cordic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CORDIC_PERMIT [9] = '{
    4'b 1111, // index[0] CORDIC_CTRL
    4'b 1111, // index[1] CORDIC_STATUS
    4'b 1111, // index[2] CORDIC_X_IN
    4'b 1111, // index[3] CORDIC_Y_IN
    4'b 1111, // index[4] CORDIC_Z_IN
    4'b 1111, // index[5] CORDIC_X_OUT
    4'b 1111, // index[6] CORDIC_Y_OUT
    4'b 1111, // index[7] CORDIC_Z_OUT
    4'b 1111  // index[8] CORDIC_CFG
  };

  parameter type reg_req_t = struct packed {
    logic           valid;
    logic           write;
    logic [AW-1:0]  addr;
    logic [DW-1:0]  wdata;
    logic [DBW-1:0] wstrb;
  };

  parameter type reg_rsp_t = struct packed {
    logic [DW-1:0]  rdata;
    logic           error;
    logic           ready;
  };

endpackage
