// Auto-generated by flexsoc.backend.design.rtl.
module cordic
  import cordic_reg_pkg::*;
(
 input logic clk_i,
 input logic rst_ni,
 input tlul_pkg::tl_h2d_t tl_i,
 output tlul_pkg::tl_d2h_t tl_o
);

  cordic_reg2hw_t reg2hw;
  cordic_hw2reg_t hw2reg;

  logic core_rst_sync_ni;
  prim_ff_2sync #(
    .Width      (1),
    .ResetValue (1'b0)
  ) u_core_reset_sync (
    .clk_i (clk_i),
    .rst_ni(rst_ni),
    .d_i   (1'b1),
    .q_o   (core_rst_sync_ni)
  );

  cordic_reg_top u_cordic_reg (
    .clk_i(clk_i),
    .rst_ni(core_rst_sync_ni),
    .tl_i(tl_i),
    .tl_o(tl_o),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg),
    .devmode_i(1'b1)
  );

  cordic_core u_cordic_core (
    .clk_i(clk_i),
    .rst_ni(core_rst_sync_ni),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg)
  );

endmodule
