/* Generated by Yosys 0.52+102 (git sha1 b69394783, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "rtl/spi_host.sv:1.8" *)
module spi_host(clk_i, rst_ni, tl_i, tl_o, spi_cs_o, spi_sclk_o, spi_sdioz_o, spi_sdio_i, spi_sdio_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  (* src = "rtl/spi_host.sv:7.19" *)
  input clk_i;
  wire clk_i;
  (* src = "rtl/spi_host.sv:22.21" *)
  (* unused_bits = "9" *)
  wire [28:0] reg2hw;
  (* src = "rtl/spi_host.sv:8.19" *)
  input rst_ni;
  wire rst_ni;
  (* src = "rtl/spi_host.sv:15.16" *)
  output spi_cs_o;
  wire spi_cs_o;
  (* src = "rtl/spi_host.sv:16.16" *)
  output spi_sclk_o;
  wire spi_sclk_o;
  (* src = "rtl/spi_host.sv:18.16" *)
  input spi_sdio_i;
  wire spi_sdio_i;
  (* src = "rtl/spi_host.sv:19.16" *)
  output spi_sdio_o;
  wire spi_sdio_o;
  (* src = "rtl/spi_host.sv:17.16" *)
  output spi_sdioz_o;
  wire spi_sdioz_o;
  (* src = "rtl/spi_host.sv:11.29" *)
  input [108:0] tl_i;
  wire [108:0] tl_i;
  (* src = "rtl/spi_host.sv:12.29" *)
  output [65:0] tl_o;
  wire [65:0] tl_o;
  (* src = "rtl/spi_host_core.sv:39.15" *)
  wire [3:0] \u_spi_host_core.bit_cnt_q ;
  (* src = "rtl/spi_host_core.sv:38.15" *)
  wire [2:0] \u_spi_host_core.byte_cnt_q ;
  (* src = "rtl/spi_host_core.sv:33.15" *)
  wire [7:0] \u_spi_host_core.current_byte_q ;
  (* src = "rtl/spi_host_core.sv:26.11" *)
  wire [1:0] \u_spi_host_core.current_state ;
  (* src = "rtl/spi_host_core.sv:43.23" *)
  wire \u_spi_host_core.r_wn_q ;
  (* src = "rtl/spi_host_core.sv:51.15" *)
  wire \u_spi_host_core.rx_fifo_wvalid ;
  (* src = "rtl/spi_host_core.sv:41.33" *)
  wire \u_spi_host_core.rx_fifo_wvalid_d ;
  (* src = "rtl/spi_host_core.sv:47.23" *)
  wire \u_spi_host_core.sclk ;
  (* src = "rtl/spi_host_core.sv:36.24" *)
  wire \u_spi_host_core.sdioz_d ;
  (* src = "rtl/spi_host_core.sv:52.15" *)
  wire \u_spi_host_core.tx_fifo_rready ;
  (* src = "rtl/spi_host_core.sv:40.33" *)
  wire \u_spi_host_core.tx_fifo_rready_d ;
  (* src = "ips/prim_opentitan/prim_flop.sv:13.28" *)
  wire \u_spi_host_core.u_clk_div2.d_i ;
  (* src = "ips/prim_opentitan/prim_flop.sv:13.28" *)
  wire \u_spi_host_core.u_sclk_driver.d_i ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:63.33" *)
  wire [1:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:63.22" *)
  wire [1:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:105.34" *)
  wire [23:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage ;
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:38.24" *)
  wire [2:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q ;
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:37.24" *)
  wire [2:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:67.11" *)
  wire \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:63.33" *)
  wire [1:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:63.22" *)
  wire [1:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr ;
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:105.34" *)
  wire [23:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage ;
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:38.24" *)
  wire [2:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q ;
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:37.24" *)
  wire [2:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q ;
  (* src = "ips/prim_opentitan/prim_subreg.sv:28.25" *)
  wire \u_spi_host_reg.u_wdata.qe ;
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(\u_spi_host_core.current_state [0]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _325_ (
    .A(reg2hw[0]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(tl_o[65]),
    .Y(tl_o[0])
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(reg2hw[28]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(\u_spi_host_core.bit_cnt_q [0]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xor2_1 _329_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .X(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _330_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .X(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _332_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .X(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _333_ (
    .A1(_077_),
    .A2(_078_),
    .B1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(\u_spi_host_core.rx_fifo_wvalid ),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _336_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .C(_080_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(_082_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand3_1 _339_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(\u_spi_host_core.rx_fifo_wvalid ),
    .C(_079_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_083_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _341_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _342_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xor2_1 _343_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .X(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a31oi_1 _345_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .B1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a311oi_1 _346_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .B1(_072_),
    .C1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(reg2hw[0]),
    .B(_088_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _348_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor3_1 _349_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .C(_090_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(_092_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_089_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_093_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and3_1 _354_ (
    .A(_084_),
    .B(_085_),
    .C(_087_),
    .X(_094_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_087_),
    .B1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a31o_1 _356_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_087_),
    .B1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .X(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(\u_spi_host_core.current_state [1]),
    .B(_071_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2b_1 _358_ (
    .A_N(\u_spi_host_core.current_state [1]),
    .B(\u_spi_host_core.current_state [0]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _360_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .B(\u_spi_host_core.byte_cnt_q [0]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand4_1 _361_ (
    .A(\u_spi_host_core.byte_cnt_q [1]),
    .B(reg2hw[26]),
    .C(_089_),
    .D(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__or3_1 _362_ (
    .A(\u_spi_host_core.current_state [1]),
    .B(\u_spi_host_core.current_state [0]),
    .C(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _363_ (
    .A1(_096_),
    .A2(_099_),
    .B1(_102_),
    .Y(\u_spi_host_core.tx_fifo_rready_d )
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _364_ (
    .A(tl_i[108]),
    .SLEEP(tl_o[65]),
    .X(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(tl_i[108]),
    .B(tl_o[0]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor3_1 _366_ (
    .A(tl_i[107]),
    .B(tl_i[106]),
    .C(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(tl_i[61]),
    .B(tl_i[60]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(tl_i[56]),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor4_1 _369_ (
    .A(tl_i[107]),
    .B(tl_i[106]),
    .C(_104_),
    .D(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__and3_1 _370_ (
    .A(tl_i[62]),
    .B(tl_i[63]),
    .C(_108_),
    .X(\u_spi_host_reg.u_wdata.qe )
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .B(\u_spi_host_core.byte_cnt_q [1]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _372_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(_096_),
    .C(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _373_ (
    .A(_097_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(\u_spi_host_core.sclk ),
    .B(_111_),
    .Y(\u_spi_host_core.u_clk_div2.d_i )
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _375_ (
    .A(\u_spi_host_core.sclk ),
    .SLEEP(spi_cs_o),
    .X(\u_spi_host_core.u_sclk_driver.d_i )
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(\u_spi_host_core.r_wn_q ),
    .B(_109_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(_098_),
    .B(_112_),
    .Y(\u_spi_host_core.sdioz_d )
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(_099_),
    .B(_112_),
    .Y(\u_spi_host_core.rx_fifo_wvalid_d )
  );
  sky130_fd_sc_hd__a22o_1 _379_ (
    .A1(tl_o[1]),
    .A2(_104_),
    .B1(_105_),
    .B2(_107_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(tl_o[16]),
    .B(_103_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _381_ (
    .A(tl_i[62]),
    .SLEEP(tl_i[63]),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2b_1 _382_ (
    .A_N(_088_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor3_1 _383_ (
    .A(_075_),
    .B(_076_),
    .C(_078_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3b_1 _384_ (
    .A(tl_i[62]),
    .B(_116_),
    .C_N(tl_i[63]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _385_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .SLEEP(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _386_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [16]),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__mux2i_1 _387_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [0]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [8]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _388_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_120_),
    .B1(_119_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _389_ (
    .A(_117_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(tl_i[62]),
    .B(tl_i[63]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(reg2hw[26]),
    .B(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _392_ (
    .A(_104_),
    .B(_105_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a41oi_1 _393_ (
    .A1(_115_),
    .A2(_122_),
    .A3(_124_),
    .A4(_125_),
    .B1(_113_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _394_ (
    .A(tl_o[17]),
    .B(_103_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _395_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [17]),
    .B(_118_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__mux2i_1 _396_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [1]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [9]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _397_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_128_),
    .B1(_127_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _398_ (
    .A(_117_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_096_),
    .B(_114_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _400_ (
    .A(reg2hw[27]),
    .B(_123_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a41oi_1 _401_ (
    .A1(_125_),
    .A2(_130_),
    .A3(_131_),
    .A4(_132_),
    .B1(_126_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(tl_o[18]),
    .B(_103_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [18]),
    .B(_118_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__mux2i_1 _404_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [2]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [10]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _405_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_135_),
    .B1(_134_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2b_1 _406_ (
    .A_N(_079_),
    .B(_114_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a22oi_1 _407_ (
    .A1(reg2hw[28]),
    .A2(_123_),
    .B1(_136_),
    .B2(_117_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a31oi_1 _408_ (
    .A1(_125_),
    .A2(_137_),
    .A3(_138_),
    .B1(_133_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _409_ (
    .A(tl_o[19]),
    .B(_103_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [19]),
    .B(_118_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__mux2i_1 _411_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [3]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [11]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _412_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_141_),
    .B1(_140_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _413_ (
    .A(_117_),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_0 _414_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .A2(_116_),
    .B1(_114_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a31oi_1 _415_ (
    .A1(_125_),
    .A2(_143_),
    .A3(_144_),
    .B1(_139_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [20]),
    .B(_118_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2i_1 _417_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [4]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [12]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21ai_0 _418_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_146_),
    .B1(_145_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand3_1 _419_ (
    .A(_103_),
    .B(_117_),
    .C(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _420_ (
    .A1(tl_o[20]),
    .A2(_104_),
    .B1(_105_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(_148_),
    .B(_149_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [21]),
    .B(_118_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__mux2i_1 _423_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [5]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [13]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _424_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_151_),
    .B1(_150_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand3_1 _425_ (
    .A(_103_),
    .B(_117_),
    .C(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _426_ (
    .A1(tl_o[21]),
    .A2(_104_),
    .B1(_105_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _427_ (
    .A(_153_),
    .B(_154_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [22]),
    .B(_118_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__mux2i_1 _429_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [6]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [14]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _430_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_156_),
    .B1(_155_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand3_1 _431_ (
    .A(_103_),
    .B(_117_),
    .C(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _432_ (
    .A1(tl_o[22]),
    .A2(_104_),
    .B1(_105_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_158_),
    .B(_159_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [23]),
    .B(_118_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__mux2i_1 _435_ (
    .A0(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [7]),
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [15]),
    .S(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21ai_0 _436_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_161_),
    .B1(_160_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3_1 _437_ (
    .A(_103_),
    .B(_117_),
    .C(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _438_ (
    .A1(tl_o[23]),
    .A2(_104_),
    .B1(_105_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_163_),
    .B(_164_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _440_ (
    .A(tl_o[47]),
    .B(_105_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(_125_),
    .B(_165_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(tl_i[92]),
    .B(_103_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(tl_o[49]),
    .B(_104_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _444_ (
    .A(_166_),
    .B(_167_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(tl_i[93]),
    .B(_103_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(tl_o[50]),
    .B(_104_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(_168_),
    .B(_169_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(tl_i[94]),
    .B(_103_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _449_ (
    .A(tl_o[51]),
    .B(_104_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_170_),
    .B(_171_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(tl_i[95]),
    .B(_103_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(tl_o[52]),
    .B(_104_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _453_ (
    .A(_172_),
    .B(_173_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(tl_i[96]),
    .B(_103_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _455_ (
    .A(tl_o[53]),
    .B(_104_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _456_ (
    .A(_174_),
    .B(_175_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(tl_i[97]),
    .B(_103_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(tl_o[54]),
    .B(_104_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(_176_),
    .B(_177_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(tl_i[98]),
    .B(_103_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(tl_o[55]),
    .B(_104_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _462_ (
    .A(_178_),
    .B(_179_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(tl_i[99]),
    .B(_103_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(tl_o[56]),
    .B(_104_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(_180_),
    .B(_181_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(tl_i[100]),
    .B(_103_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(tl_o[57]),
    .B(_104_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(_182_),
    .B(_183_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _469_ (
    .A(tl_i[101]),
    .B(_103_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(tl_o[58]),
    .B(_104_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _471_ (
    .A(_184_),
    .B(_185_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _472_ (
    .A1(tl_o[0]),
    .A2(tl_i[0]),
    .B1(_104_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(_108_),
    .B(_123_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__mux2_1 _474_ (
    .A0(tl_i[25]),
    .A1(reg2hw[27]),
    .S(_186_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _475_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .A2(_090_),
    .B1(_003_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _476_ (
    .A(reg2hw[27]),
    .B(_187_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_090_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _478_ (
    .A1(_092_),
    .A2(_188_),
    .B1(reg2hw[27]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _479_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .B(_093_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(reg2hw[27]),
    .B(_189_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _481_ (
    .A(tl_i[26]),
    .B(_186_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a21oi_1 _482_ (
    .A1(_073_),
    .A2(_186_),
    .B1(_190_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _483_ (
    .A0(tl_i[24]),
    .A1(reg2hw[26]),
    .S(_186_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor4b_1 _484_ (
    .A(tl_i[106]),
    .B(tl_i[105]),
    .C(_104_),
    .D_N(tl_i[107]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21o_1 _485_ (
    .A1(tl_o[62]),
    .A2(_104_),
    .B1(_191_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _486_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(\u_spi_host_core.tx_fifo_rready ),
    .C(_095_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21oi_1 _487_ (
    .A1(\u_spi_host_core.tx_fifo_rready ),
    .A2(_095_),
    .B1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a311o_1 _488_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(\u_spi_host_core.tx_fifo_rready ),
    .A3(_095_),
    .B1(_193_),
    .C1(reg2hw[27]),
    .X(_194_)
  );
  sky130_fd_sc_hd__a31oi_1 _489_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.tx_fifo_rready ),
    .A3(_095_),
    .B1(_194_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a31oi_1 _490_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.tx_fifo_rready ),
    .A3(_095_),
    .B1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a311oi_1 _491_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(\u_spi_host_core.tx_fifo_rready ),
    .A3(_095_),
    .B1(_195_),
    .C1(reg2hw[27]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _492_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .B(_192_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _493_ (
    .A(reg2hw[27]),
    .B(_196_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _494_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .A2(_080_),
    .B1(_000_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _495_ (
    .A(reg2hw[28]),
    .B(_197_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_080_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a21oi_1 _497_ (
    .A1(_082_),
    .A2(_198_),
    .B1(reg2hw[28]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _498_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .B(_083_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nor2_1 _499_ (
    .A(reg2hw[28]),
    .B(_199_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand3b_1 _500_ (
    .A_N(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .B(_117_),
    .C(_191_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand4b_1 _501_ (
    .A_N(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(_117_),
    .D(_191_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _502_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .SLEEP(_200_),
    .X(_202_)
  );
  sky130_fd_sc_hd__xnor2_1 _503_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(_200_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__and3_1 _504_ (
    .A(_073_),
    .B(_201_),
    .C(_203_),
    .X(_040_)
  );
  sky130_fd_sc_hd__o211a_1 _505_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .A2(_202_),
    .B1(_201_),
    .C1(_073_),
    .X(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _506_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .B(_201_),
    .X(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _507_ (
    .A(reg2hw[28]),
    .B(_204_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _508_ (
    .A(\u_spi_host_core.current_state [1]),
    .SLEEP(\u_spi_host_core.current_state [0]),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _509_ (
    .A(\u_spi_host_core.current_state [1]),
    .B(_071_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _510_ (
    .A1(\u_spi_host_core.sclk ),
    .A2(\u_spi_host_core.bit_cnt_q [3]),
    .B1(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _511_ (
    .A(_098_),
    .B(_206_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand3b_1 _512_ (
    .A_N(\u_spi_host_core.sdioz_d ),
    .B(_207_),
    .C(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _513_ (
    .A(spi_sdio_o),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(\u_spi_host_core.current_byte_q [7]),
    .B(_206_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o21ai_0 _515_ (
    .A1(_209_),
    .A2(_211_),
    .B1(_210_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _516_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .SLEEP(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .X(_212_)
  );
  sky130_fd_sc_hd__mux2i_1 _517_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [0]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [8]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _518_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a21oi_1 _519_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [16]),
    .A2(_212_),
    .B1(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o21ai_0 _520_ (
    .A1(\u_spi_host_core.current_byte_q [0]),
    .A2(_095_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _521_ (
    .A1(_095_),
    .A2(_215_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _522_ (
    .A(\u_spi_host_core.sclk ),
    .SLEEP(\u_spi_host_core.bit_cnt_q [3]),
    .X(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(\u_spi_host_core.current_byte_q [0]),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _524_ (
    .A(_112_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o221ai_1 _525_ (
    .A1(spi_sdio_i),
    .A2(_112_),
    .B1(_217_),
    .B2(_220_),
    .C1(_097_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _526_ (
    .A1(_071_),
    .A2(_101_),
    .B1(\u_spi_host_core.current_state [1]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o41a_1 _527_ (
    .A1(\u_spi_host_core.sclk ),
    .A2(_071_),
    .A3(\u_spi_host_core.bit_cnt_q [3]),
    .A4(_112_),
    .B1(_222_),
    .X(_223_)
  );
  sky130_fd_sc_hd__nor2_1 _528_ (
    .A(_094_),
    .B(_097_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__or3_1 _529_ (
    .A(_094_),
    .B(_097_),
    .C(_215_),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor2_1 _530_ (
    .A(\u_spi_host_core.current_byte_q [0]),
    .B(_223_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a31oi_1 _531_ (
    .A1(_221_),
    .A2(_223_),
    .A3(_225_),
    .B1(_226_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _532_ (
    .A(\u_spi_host_core.current_byte_q [1]),
    .B(_223_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o21ai_0 _533_ (
    .A1(\u_spi_host_core.sclk ),
    .A2(\u_spi_host_core.bit_cnt_q [3]),
    .B1(_112_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(\u_spi_host_core.current_byte_q [1]),
    .B(_218_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nor2_1 _535_ (
    .A(\u_spi_host_core.current_byte_q [1]),
    .B(_095_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__mux2i_1 _536_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [1]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [9]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _537_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [17]),
    .A2_N(_212_),
    .B1(_231_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__o21ai_0 _538_ (
    .A1(_096_),
    .A2(_232_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__o21ai_0 _539_ (
    .A1(_230_),
    .A2(_233_),
    .B1(_229_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__a22o_1 _540_ (
    .A1(\u_spi_host_core.current_byte_q [0]),
    .A2(_228_),
    .B1(_234_),
    .B2(_112_),
    .X(_235_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(_097_),
    .B(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(_224_),
    .B(_232_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a31oi_1 _543_ (
    .A1(_223_),
    .A2(_236_),
    .A3(_237_),
    .B1(_227_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _544_ (
    .A(\u_spi_host_core.current_byte_q [2]),
    .B(_223_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nand2_1 _545_ (
    .A(\u_spi_host_core.current_byte_q [2]),
    .B(_218_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor2_1 _546_ (
    .A(\u_spi_host_core.current_byte_q [2]),
    .B(_095_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__mux2i_1 _547_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [2]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [10]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _548_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [18]),
    .A2_N(_212_),
    .B1(_241_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__o21ai_0 _549_ (
    .A1(_096_),
    .A2(_242_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o21ai_0 _550_ (
    .A1(_240_),
    .A2(_243_),
    .B1(_239_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a22o_1 _551_ (
    .A1(\u_spi_host_core.current_byte_q [1]),
    .A2(_228_),
    .B1(_244_),
    .B2(_112_),
    .X(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _552_ (
    .A(_097_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand2_1 _553_ (
    .A(_224_),
    .B(_242_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a31oi_1 _554_ (
    .A1(_223_),
    .A2(_246_),
    .A3(_247_),
    .B1(_238_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _555_ (
    .A(\u_spi_host_core.current_byte_q [3]),
    .B(_223_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(\u_spi_host_core.current_byte_q [3]),
    .B(_218_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _557_ (
    .A(\u_spi_host_core.current_byte_q [3]),
    .B(_095_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__mux2i_1 _558_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [3]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [11]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _559_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [19]),
    .A2_N(_212_),
    .B1(_251_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o21ai_0 _560_ (
    .A1(_096_),
    .A2(_252_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_253_)
  );
  sky130_fd_sc_hd__o21ai_0 _561_ (
    .A1(_250_),
    .A2(_253_),
    .B1(_249_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a22o_1 _562_ (
    .A1(\u_spi_host_core.current_byte_q [2]),
    .A2(_228_),
    .B1(_254_),
    .B2(_112_),
    .X(_255_)
  );
  sky130_fd_sc_hd__nand2_1 _563_ (
    .A(_097_),
    .B(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nand2_1 _564_ (
    .A(_224_),
    .B(_252_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a31oi_1 _565_ (
    .A1(_223_),
    .A2(_256_),
    .A3(_257_),
    .B1(_248_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _566_ (
    .A(\u_spi_host_core.current_byte_q [4]),
    .B(_223_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(\u_spi_host_core.current_byte_q [4]),
    .B(_218_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _568_ (
    .A(\u_spi_host_core.current_byte_q [4]),
    .B(_095_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__mux2i_1 _569_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [4]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [12]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _570_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [20]),
    .A2_N(_212_),
    .B1(_261_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_262_)
  );
  sky130_fd_sc_hd__o21ai_0 _571_ (
    .A1(_096_),
    .A2(_262_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_263_)
  );
  sky130_fd_sc_hd__o21ai_0 _572_ (
    .A1(_260_),
    .A2(_263_),
    .B1(_259_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a22o_1 _573_ (
    .A1(\u_spi_host_core.current_byte_q [3]),
    .A2(_228_),
    .B1(_264_),
    .B2(_112_),
    .X(_265_)
  );
  sky130_fd_sc_hd__nand2_1 _574_ (
    .A(_097_),
    .B(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _575_ (
    .A(_224_),
    .B(_262_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a31oi_1 _576_ (
    .A1(_223_),
    .A2(_266_),
    .A3(_267_),
    .B1(_258_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _577_ (
    .A(\u_spi_host_core.current_byte_q [5]),
    .B(_223_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand2_1 _578_ (
    .A(\u_spi_host_core.current_byte_q [5]),
    .B(_218_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nor2_1 _579_ (
    .A(\u_spi_host_core.current_byte_q [5]),
    .B(_095_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__mux2i_1 _580_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [5]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [13]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_271_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _581_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [21]),
    .A2_N(_212_),
    .B1(_271_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_272_)
  );
  sky130_fd_sc_hd__o21ai_0 _582_ (
    .A1(_096_),
    .A2(_272_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_273_)
  );
  sky130_fd_sc_hd__o21ai_0 _583_ (
    .A1(_270_),
    .A2(_273_),
    .B1(_269_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__a22o_1 _584_ (
    .A1(\u_spi_host_core.current_byte_q [4]),
    .A2(_228_),
    .B1(_274_),
    .B2(_112_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _585_ (
    .A(_097_),
    .B(_275_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _586_ (
    .A(_224_),
    .B(_272_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__a31oi_1 _587_ (
    .A1(_223_),
    .A2(_276_),
    .A3(_277_),
    .B1(_268_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _588_ (
    .A(\u_spi_host_core.current_byte_q [6]),
    .B(_223_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nand2_1 _589_ (
    .A(\u_spi_host_core.current_byte_q [6]),
    .B(_218_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nor2_1 _590_ (
    .A(\u_spi_host_core.current_byte_q [6]),
    .B(_095_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__mux2i_1 _591_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [6]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [14]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_281_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _592_ (
    .A1_N(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [22]),
    .A2_N(_212_),
    .B1(_281_),
    .B2(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_282_)
  );
  sky130_fd_sc_hd__o21ai_0 _593_ (
    .A1(_096_),
    .A2(_282_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__o21ai_0 _594_ (
    .A1(_280_),
    .A2(_283_),
    .B1(_279_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a22o_1 _595_ (
    .A1(\u_spi_host_core.current_byte_q [5]),
    .A2(_228_),
    .B1(_284_),
    .B2(_112_),
    .X(_285_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_097_),
    .B(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__nand2_1 _597_ (
    .A(_224_),
    .B(_282_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__a31oi_1 _598_ (
    .A1(_223_),
    .A2(_286_),
    .A3(_287_),
    .B1(_278_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _599_ (
    .A(\u_spi_host_core.current_byte_q [6]),
    .B(_228_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__mux2i_1 _600_ (
    .A0(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [7]),
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [15]),
    .S(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nor2_1 _601_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__a21oi_1 _602_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [23]),
    .A2(_212_),
    .B1(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__and2_0 _603_ (
    .A(\u_spi_host_core.current_byte_q [7]),
    .B(_218_),
    .X(_292_)
  );
  sky130_fd_sc_hd__o21ai_0 _604_ (
    .A1(\u_spi_host_core.current_byte_q [7]),
    .A2(_095_),
    .B1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_293_)
  );
  sky130_fd_sc_hd__a21oi_1 _605_ (
    .A1(_095_),
    .A2(_291_),
    .B1(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__o21ai_0 _606_ (
    .A1(_292_),
    .A2(_294_),
    .B1(_112_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__a21oi_1 _607_ (
    .A1(_288_),
    .A2(_295_),
    .B1(_098_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__nor2_1 _608_ (
    .A(_094_),
    .B(_291_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nand2_1 _609_ (
    .A(_098_),
    .B(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand2_1 _610_ (
    .A(_223_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__o22a_1 _611_ (
    .A1(\u_spi_host_core.current_byte_q [7]),
    .A2(_223_),
    .B1(_296_),
    .B2(_299_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _612_ (
    .A(\u_spi_host_core.current_state [1]),
    .B(spi_cs_o),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nand2_1 _613_ (
    .A(\u_spi_host_core.current_state [0]),
    .B(_300_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _614_ (
    .A1(reg2hw[26]),
    .A2(_089_),
    .B1(\u_spi_host_core.current_state [1]),
    .Y(_301_)
  );
  sky130_fd_sc_hd__o22ai_1 _615_ (
    .A1(_096_),
    .A2(_099_),
    .B1(_301_),
    .B2(\u_spi_host_core.current_state [0]),
    .Y(_302_)
  );
  sky130_fd_sc_hd__o21ai_0 _616_ (
    .A1(\u_spi_host_core.byte_cnt_q [0]),
    .A2(_205_),
    .B1(_302_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__o21a_1 _617_ (
    .A1(\u_spi_host_core.byte_cnt_q [0]),
    .A2(_302_),
    .B1(_303_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _618_ (
    .A(\u_spi_host_core.byte_cnt_q [1]),
    .B(\u_spi_host_core.byte_cnt_q [0]),
    .Y(_304_)
  );
  sky130_fd_sc_hd__nand2_1 _619_ (
    .A(\u_spi_host_core.byte_cnt_q [1]),
    .B(\u_spi_host_core.byte_cnt_q [0]),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nand2b_1 _620_ (
    .A_N(_304_),
    .B(_305_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2_1 _621_ (
    .A(_097_),
    .B(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__o21ai_0 _622_ (
    .A1(_208_),
    .A2(_306_),
    .B1(_307_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__mux2_1 _623_ (
    .A0(\u_spi_host_core.byte_cnt_q [1]),
    .A1(_308_),
    .S(_302_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xor2_1 _624_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .B(_305_),
    .X(_309_)
  );
  sky130_fd_sc_hd__xnor2_1 _625_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .B(_304_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__o221ai_1 _626_ (
    .A1(_208_),
    .A2(_309_),
    .B1(_310_),
    .B2(_098_),
    .C1(_302_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__o21a_1 _627_ (
    .A1(\u_spi_host_core.byte_cnt_q [2]),
    .A2(_302_),
    .B1(_311_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _628_ (
    .A0(_297_),
    .A1(\u_spi_host_core.r_wn_q ),
    .S(_102_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _629_ (
    .A(_102_),
    .B(_111_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _630_ (
    .A(_098_),
    .B(_110_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _631_ (
    .A(tl_i[62]),
    .B(tl_i[63]),
    .C(_108_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__mux2_1 _632_ (
    .A0(tl_i[24]),
    .A1(reg2hw[1]),
    .S(_312_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _633_ (
    .A0(tl_i[25]),
    .A1(reg2hw[2]),
    .S(_312_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _634_ (
    .A0(tl_i[26]),
    .A1(reg2hw[3]),
    .S(_312_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _635_ (
    .A0(tl_i[27]),
    .A1(reg2hw[4]),
    .S(_312_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _636_ (
    .A0(tl_i[28]),
    .A1(reg2hw[5]),
    .S(_312_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _637_ (
    .A0(tl_i[29]),
    .A1(reg2hw[6]),
    .S(_312_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _638_ (
    .A0(tl_i[30]),
    .A1(reg2hw[7]),
    .S(_312_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _639_ (
    .A0(tl_i[31]),
    .A1(reg2hw[8]),
    .S(_312_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _640_ (
    .A1(_098_),
    .A2(_218_),
    .B1(_206_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o31ai_1 _641_ (
    .A1(_095_),
    .A2(_099_),
    .A3(_109_),
    .B1(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nor3_1 _642_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(\u_spi_host_core.bit_cnt_q [0]),
    .C(_205_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__nor2_1 _643_ (
    .A(_314_),
    .B(_315_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__a21oi_1 _644_ (
    .A1(_074_),
    .A2(_314_),
    .B1(_316_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _645_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(_205_),
    .C(_314_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__a21oi_1 _646_ (
    .A1(\u_spi_host_core.bit_cnt_q [0]),
    .A2(_317_),
    .B1(\u_spi_host_core.bit_cnt_q [1]),
    .Y(_318_)
  );
  sky130_fd_sc_hd__a21oi_1 _647_ (
    .A1(\u_spi_host_core.bit_cnt_q [1]),
    .A2(_316_),
    .B1(_318_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _648_ (
    .A(\u_spi_host_core.bit_cnt_q [0]),
    .B(\u_spi_host_core.bit_cnt_q [1]),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _649_ (
    .A(_314_),
    .B(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__a311oi_1 _650_ (
    .A1(\u_spi_host_core.bit_cnt_q [0]),
    .A2(\u_spi_host_core.bit_cnt_q [1]),
    .A3(\u_spi_host_core.bit_cnt_q [2]),
    .B1(_205_),
    .C1(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_321_)
  );
  sky130_fd_sc_hd__o22a_1 _651_ (
    .A1(\u_spi_host_core.bit_cnt_q [2]),
    .A2(_320_),
    .B1(_321_),
    .B2(_314_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _652_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(_314_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nand4_1 _653_ (
    .A(\u_spi_host_core.bit_cnt_q [0]),
    .B(\u_spi_host_core.bit_cnt_q [1]),
    .C(\u_spi_host_core.bit_cnt_q [2]),
    .D(_317_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__nand2_1 _654_ (
    .A(_322_),
    .B(_323_),
    .Y(_070_)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(tl_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _656_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(tl_o[16]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _657_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(tl_o[17]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _658_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(tl_o[18]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _659_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(tl_o[19]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _660_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(tl_o[20]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _661_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(tl_o[21]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _662_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(tl_o[22]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _663_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(tl_o[23]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _664_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(tl_o[47]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _665_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(tl_o[49]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _666_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(tl_o[50]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _667_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(tl_o[51]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _668_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(tl_o[52]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _669_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(tl_o[53]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _670_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(tl_o[54]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _671_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(tl_o[55]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _672_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(tl_o[56]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _673_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(tl_o[57]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _674_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(tl_o[58]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:94.3" *)
  sky130_fd_sc_hd__dfrtp_1 _675_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(tl_o[65]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _676_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(reg2hw[27]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _677_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _678_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _679_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _680_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(reg2hw[28]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _681_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(reg2hw[26]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _682_ (
    .CLK(clk_i),
    .D(\u_spi_host_reg.u_wdata.qe ),
    .Q(reg2hw[0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _683_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(tl_o[62]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _684_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.u_clk_div2.d_i ),
    .Q(\u_spi_host_core.sclk ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _685_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.u_sclk_driver.d_i ),
    .Q(spi_sclk_o),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _686_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _687_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _688_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _689_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _690_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _691_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:68.5" *)
  sky130_fd_sc_hd__dfstp_2 _692_ (
    .CLK(clk_i),
    .D(1'h0),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .SET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _693_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _694_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _695_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _696_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(spi_sdio_o),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _697_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(\u_spi_host_core.current_byte_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _698_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(\u_spi_host_core.current_byte_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _699_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(\u_spi_host_core.current_byte_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _700_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(\u_spi_host_core.current_byte_q [3]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _701_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(\u_spi_host_core.current_byte_q [4]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _702_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(\u_spi_host_core.current_byte_q [5]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _703_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(\u_spi_host_core.current_byte_q [6]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _704_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(\u_spi_host_core.current_byte_q [7]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfstp_2 _705_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(spi_cs_o),
    .SET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _706_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(\u_spi_host_core.byte_cnt_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _707_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(\u_spi_host_core.byte_cnt_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _708_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(\u_spi_host_core.byte_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _709_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\u_spi_host_core.r_wn_q ),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _710_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.sdioz_d ),
    .Q(spi_sdioz_o),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _711_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.tx_fifo_rready_d ),
    .Q(\u_spi_host_core.tx_fifo_rready ),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _712_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.rx_fifo_wvalid_d ),
    .Q(\u_spi_host_core.rx_fifo_wvalid ),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:156.3" *)
  sky130_fd_sc_hd__dfrtp_1 _713_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(\u_spi_host_core.current_state [0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:156.3" *)
  sky130_fd_sc_hd__dfrtp_1 _714_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(\u_spi_host_core.current_state [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _715_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(reg2hw[1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _716_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(reg2hw[2]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _717_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(reg2hw[3]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _718_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(reg2hw[4]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _719_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(reg2hw[5]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _720_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(reg2hw[6]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _721_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(reg2hw[7]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _722_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(reg2hw[8]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _723_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(\u_spi_host_core.bit_cnt_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _724_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(\u_spi_host_core.bit_cnt_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _725_ (
    .CLK(clk_i),
    .D(_069_),
    .Q(\u_spi_host_core.bit_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _726_ (
    .CLK(clk_i),
    .D(_070_),
    .Q(\u_spi_host_core.bit_cnt_q [3]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _727_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [7])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _728_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [15])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _729_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [23])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _730_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [7])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _731_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [15])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _732_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [23])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _733_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [16])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _734_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [17])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _735_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [18])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _736_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [19])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _737_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [20])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _738_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [21])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _739_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [22])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _740_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [0])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _741_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [1])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _742_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [2])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _743_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [3])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _744_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [4])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _745_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [5])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _746_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [6])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _747_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [8])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _748_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [9])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _749_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [10])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _750_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [11])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _751_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [12])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _752_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [13])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _753_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [14])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _754_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [16])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _755_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [17])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _756_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [18])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _757_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [19])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _758_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [20])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _759_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [21])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _760_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [22])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _761_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [0])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _762_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [1])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _763_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [2])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _764_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [3])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _765_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [4])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _766_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [5])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _767_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [6])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _768_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [8])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _769_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [9])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _770_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [10])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _771_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [11])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _772_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [12])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _773_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [13])
  );
  (* src = "ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _774_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [14])
  );
  assign reg2hw[25:10] = 16'b0x0x0x0x00000000;
  assign { tl_o[64:63], tl_o[61:59], tl_o[48], tl_o[46:24], tl_o[15:2] } = { 6'h00, tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], 14'h0000 };
  assign \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr ;
  assign \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr ;
  assign \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr ;
  assign \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr ;
endmodule
