// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"

VL_ATTR_COLD void Vtop_axi_pkg___configure_coverage(Vtop_axi_pkg* vlSelf, bool first) {
    VL_DEBUG_IF(VL_DBG_MSGF("+        Vtop_axi_pkg___configure_coverage\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    (void)first;  // Prevent unused variable warning
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 0, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 116, 40, "", "v_line/axi_pkg", "block", "116-117", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5863, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 116, 40, "", "v_line/axi_pkg", "block", "116-117", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 1, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 126, 37, "", "v_line/axi_pkg", "block", "126-127", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5864, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 126, 37, "", "v_line/axi_pkg", "block", "126-127", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 2, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 156, 15, "", "v_line/axi_pkg", "case", "156", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5865, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 156, 15, "", "v_line/axi_pkg", "case", "156", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 3, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 157, 15, "", "v_line/axi_pkg", "case", "157", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5866, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 157, 15, "", "v_line/axi_pkg", "case", "157", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 4, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 158, 15, "", "v_line/axi_pkg", "case", "158", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5867, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 158, 15, "", "v_line/axi_pkg", "case", "158", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 5, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 159, 15, "", "v_line/axi_pkg", "case", "159", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5868, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 159, 15, "", "v_line/axi_pkg", "case", "159", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 6, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 160, 7, "", "v_line/axi_pkg", "case", "160", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5869, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 160, 7, "", "v_line/axi_pkg", "case", "160", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 7, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 134, 37, "", "v_line/axi_pkg", "block", "134-135,155,162", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5870, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 134, 37, "", "v_line/axi_pkg", "block", "134-135,155,162", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 8, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 170, 5, "", "v_branch/axi_pkg", "if", "170,172", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5871, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 170, 5, "", "v_branch/axi_pkg", "if", "170,172", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 9, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 170, 6, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5872, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 170, 6, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 10, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 7, "", "v_branch/axi_pkg", "if", "191-192", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5873, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 7, "", "v_branch/axi_pkg", "if", "191-192", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 11, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 8, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5874, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 8, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 12, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((burst == BURST_WRAP)==1 && (ret_addr >= (wrp_bond + (num_bytes(size) * (len + 128'h1))))==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5875, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((burst == BURST_WRAP)==1 && (ret_addr >= (wrp_bond + (num_bytes(size) * (len + 128'h1))))==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 13, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((ret_addr >= (wrp_bond + (num_bytes(size) * (len + 128'h1))))==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5876, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((ret_addr >= (wrp_bond + (num_bytes(size) * (len + 128'h1))))==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 14, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((burst == BURST_WRAP)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5877, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 191, 31, "", "v_expr/axi_pkg", "((burst == BURST_WRAP)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 15, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 5, "", "v_branch/axi_pkg", "if", "174,179", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5878, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 5, "", "v_branch/axi_pkg", "if", "174,179", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 16, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 6, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5879, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 6, "", "v_branch/axi_pkg", "else", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 17, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((i_beat != 32'sh0)==1 && (burst != BURST_FIXED)==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5880, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((i_beat != 32'sh0)==1 && (burst != BURST_FIXED)==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 18, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((burst != BURST_FIXED)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5881, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((burst != BURST_FIXED)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 19, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((i_beat != 32'sh0)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5882, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 174, 21, "", "v_expr/axi_pkg", "((i_beat != 32'sh0)==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 20, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 167, 3, "", "v_line/axi_pkg", "block", "167-169,195", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5883, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 167, 3, "", "v_line/axi_pkg", "block", "167-169,195", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 21, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 200, 3, "", "v_line/axi_pkg", "block", "200,202-203", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5884, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 200, 3, "", "v_line/axi_pkg", "block", "200,202-203", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 22, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 210, 5, "", "v_branch/axi_pkg", "if", "210-211", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5885, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 210, 5, "", "v_branch/axi_pkg", "if", "210-211", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 23, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 210, 6, "", "v_branch/axi_pkg", "else", "212-213", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5886, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 210, 6, "", "v_branch/axi_pkg", "else", "212-213", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 24, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 208, 3, "", "v_line/axi_pkg", "block", "208", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5887, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 208, 3, "", "v_line/axi_pkg", "block", "208", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 25, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[3]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5888, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[3]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 26, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[2]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5889, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[2]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 27, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[1]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5890, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[1]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 28, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[0]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5891, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[0]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 29, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[0]==0 && (cache & CACHE_BUFFERABLE)[1]==0 && (cache & CACHE_BUFFERABLE)[2]==0 && (cache & CACHE_BUFFERABLE)[3]==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5892, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 219, 12, "", "v_expr/axi_pkg", "((cache & CACHE_BUFFERABLE)[0]==0 && (cache & CACHE_BUFFERABLE)[1]==0 && (cache & CACHE_BUFFERABLE)[2]==0 && (cache & CACHE_BUFFERABLE)[3]==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 30, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 218, 28, "", "v_line/axi_pkg", "block", "218-219", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5893, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 218, 28, "", "v_line/axi_pkg", "block", "218-219", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 31, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[3]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5894, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[3]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 32, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[2]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5895, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[2]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 33, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[1]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5896, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[1]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 34, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[0]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5897, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[0]==1) => 1", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 35, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[0]==0 && (cache & CACHE_MODIFIABLE)[1]==0 && (cache & CACHE_MODIFIABLE)[2]==0 && (cache & CACHE_MODIFIABLE)[3]==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5898, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 224, 12, "", "v_expr/axi_pkg", "((cache & CACHE_MODIFIABLE)[0]==0 && (cache & CACHE_MODIFIABLE)[1]==0 && (cache & CACHE_MODIFIABLE)[2]==0 && (cache & CACHE_MODIFIABLE)[3]==0) => 0", "", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 36, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 223, 28, "", "v_line/axi_pkg", "block", "223-224", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5899, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 223, 28, "", "v_line/axi_pkg", "block", "223-224", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 37, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 246, 41, "", "v_line/axi_pkg", "case", "246", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5900, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 246, 41, "", "v_line/axi_pkg", "case", "246", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 38, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 247, 41, "", "v_line/axi_pkg", "case", "247", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5901, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 247, 41, "", "v_line/axi_pkg", "case", "247", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 39, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 248, 41, "", "v_line/axi_pkg", "case", "248", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5902, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 248, 41, "", "v_line/axi_pkg", "case", "248", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 40, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 249, 41, "", "v_line/axi_pkg", "case", "249", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5903, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 249, 41, "", "v_line/axi_pkg", "case", "249", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 41, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 250, 41, "", "v_line/axi_pkg", "case", "250", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5904, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 250, 41, "", "v_line/axi_pkg", "case", "250", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 42, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 251, 41, "", "v_line/axi_pkg", "case", "251", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5905, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 251, 41, "", "v_line/axi_pkg", "case", "251", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 43, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 252, 41, "", "v_line/axi_pkg", "case", "252", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5906, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 252, 41, "", "v_line/axi_pkg", "case", "252", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 44, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 253, 41, "", "v_line/axi_pkg", "case", "253", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5907, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 253, 41, "", "v_line/axi_pkg", "case", "253", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 45, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 254, 41, "", "v_line/axi_pkg", "case", "254", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5908, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 254, 41, "", "v_line/axi_pkg", "case", "254", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 46, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 255, 41, "", "v_line/axi_pkg", "case", "255", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5909, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 255, 41, "", "v_line/axi_pkg", "case", "255", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 47, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 256, 41, "", "v_line/axi_pkg", "case", "256", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5910, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 256, 41, "", "v_line/axi_pkg", "case", "256", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 48, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 257, 41, "", "v_line/axi_pkg", "case", "257", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5911, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 257, 41, "", "v_line/axi_pkg", "case", "257", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 49, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 244, 34, "", "v_line/axi_pkg", "block", "244-245", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5912, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 244, 34, "", "v_line/axi_pkg", "block", "244-245", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 50, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 264, 41, "", "v_line/axi_pkg", "case", "264", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5913, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 264, 41, "", "v_line/axi_pkg", "case", "264", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 51, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 265, 41, "", "v_line/axi_pkg", "case", "265", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5914, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 265, 41, "", "v_line/axi_pkg", "case", "265", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 52, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 266, 41, "", "v_line/axi_pkg", "case", "266", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5915, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 266, 41, "", "v_line/axi_pkg", "case", "266", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 53, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 267, 41, "", "v_line/axi_pkg", "case", "267", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5916, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 267, 41, "", "v_line/axi_pkg", "case", "267", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 54, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 268, 41, "", "v_line/axi_pkg", "case", "268", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5917, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 268, 41, "", "v_line/axi_pkg", "case", "268", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 55, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 269, 41, "", "v_line/axi_pkg", "case", "269", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5918, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 269, 41, "", "v_line/axi_pkg", "case", "269", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 56, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 270, 41, "", "v_line/axi_pkg", "case", "270", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5919, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 270, 41, "", "v_line/axi_pkg", "case", "270", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 57, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 271, 41, "", "v_line/axi_pkg", "case", "271", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5920, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 271, 41, "", "v_line/axi_pkg", "case", "271", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 58, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 272, 41, "", "v_line/axi_pkg", "case", "272", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5921, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 272, 41, "", "v_line/axi_pkg", "case", "272", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 59, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 273, 41, "", "v_line/axi_pkg", "case", "273", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5922, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 273, 41, "", "v_line/axi_pkg", "case", "273", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 60, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 274, 41, "", "v_line/axi_pkg", "case", "274", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5923, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 274, 41, "", "v_line/axi_pkg", "case", "274", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 61, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 275, 41, "", "v_line/axi_pkg", "case", "275", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5924, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 275, 41, "", "v_line/axi_pkg", "case", "275", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 62, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 262, 34, "", "v_line/axi_pkg", "block", "262-263", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5925, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 262, 34, "", "v_line/axi_pkg", "block", "262-263", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 63, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 293, 9, "", "v_branch/axi_pkg", "if", "293-294", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5926, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 293, 9, "", "v_branch/axi_pkg", "if", "293-294", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 64, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 293, 10, "", "v_branch/axi_pkg", "else", "295-296", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5927, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 293, 10, "", "v_branch/axi_pkg", "else", "295-296", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 65, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 291, 16, "", "v_line/axi_pkg", "case", "291", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5928, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 291, 16, "", "v_line/axi_pkg", "case", "291", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 66, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 299, 18, "", "v_line/axi_pkg", "case", "299,301", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5929, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 299, 18, "", "v_line/axi_pkg", "case", "299,301", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 67, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 305, 9, "", "v_branch/axi_pkg", "if", "305-306", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5930, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 305, 9, "", "v_branch/axi_pkg", "if", "305-306", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 68, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 305, 10, "", "v_branch/axi_pkg", "else", "307-308", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5931, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 305, 10, "", "v_branch/axi_pkg", "else", "307-308", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 69, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 303, 18, "", "v_line/axi_pkg", "case", "303", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5932, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 303, 18, "", "v_line/axi_pkg", "case", "303", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 70, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 311, 18, "", "v_line/axi_pkg", "case", "311,313", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5933, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 311, 18, "", "v_line/axi_pkg", "case", "311,313", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 71, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 289, 29, "", "v_line/axi_pkg", "block", "289-290", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5934, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 289, 29, "", "v_line/axi_pkg", "block", "289-290", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 72, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 319, 35, "", "v_line/axi_pkg", "block", "319,322-323", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5935, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 319, 35, "", "v_line/axi_pkg", "block", "319,322-323", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 73, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 327, 35, "", "v_line/axi_pkg", "block", "327,329", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5936, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 327, 35, "", "v_line/axi_pkg", "block", "327,329", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 74, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 334, 35, "", "v_line/axi_pkg", "block", "334,336", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5937, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 334, 35, "", "v_line/axi_pkg", "block", "334,336", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 75, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 340, 35, "", "v_line/axi_pkg", "block", "340,343-344", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5938, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 340, 35, "", "v_line/axi_pkg", "block", "340,343-344", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 76, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 348, 35, "", "v_line/axi_pkg", "block", "348,351", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5939, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 348, 35, "", "v_line/axi_pkg", "block", "348,351", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 77, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 356, 35, "", "v_line/axi_pkg", "block", "356,361-363", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5940, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 356, 35, "", "v_line/axi_pkg", "block", "356,361-363", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSelf->__Vcoverage + 78, first, true, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 368, 35, "", "v_line/axi_pkg", "block", "368,372-373", "", "", "", "");
    vlSelf->__vlCoverInsert(vlSymsp->__Vcoverage + 5941, first, false, "/home/eneadim/github/flexsoc/vendor/pulp/axi/src/axi_pkg.sv", 368, 35, "", "v_line/axi_pkg", "block", "368,372-373", "", "", "", "");
}
