# Auto-generated common RTL
+incdir+hw/ips/pkgs
+incdir+hw/ips/prim
+incdir+hw/ips/prim_opentitan
+incdir+hw/ips/tlul
hw/ips/pkgs/top_pkg.sv
hw/ips/prim/prim_reg_pkg.sv
hw/ips/pkgs/prim_mubi_pkg.sv
hw/ips/pkgs/prim_secded_pkg.sv
hw/ips/pkgs/prim_subreg_pkg.sv
hw/ips/pkgs/prim_util_pkg.sv
hw/ips/pkgs/tlul_pkg.sv
hw/ips/pkgs/prim_assert.sv
hw/ips/pkgs/prim_count_pkg.sv
hw/ips/pkgs/prim_flop_macros.sv
hw/ips/pkgs/prim_alert_pkg.sv
hw/ips/prim/prim_bin2gray.sv
hw/ips/prim/prim_cdc_2phase.sv
hw/ips/prim/prim_clk_div.sv
hw/ips/prim/prim_clk_gate.sv
hw/ips/prim/prim_counter.sv
hw/ips/prim/prim_deglitch.sv
hw/ips/prim/prim_edge_detect.sv
hw/ips/prim/prim_ff.sv
hw/ips/prim/prim_ff_2sync.sv
hw/ips/prim/prim_ff_sr.sv
hw/ips/prim/prim_fifo.sv
hw/ips/prim/prim_gray2bin.sv
hw/ips/prim/prim_lifo.sv
hw/ips/prim/prim_lzc.sv
hw/ips/prim/prim_ram.sv
hw/ips/prim/prim_reg.sv
hw/ips/prim/prim_rom.sv
hw/ips/prim/prim_rrarbiter.sv
hw/ips/prim/prim_shreg.sv
hw/ips/prim_opentitan/prim_alert_sender.sv
hw/ips/prim_opentitan/prim_arbiter_ppc.sv
hw/ips/prim_opentitan/prim_buf.sv
hw/ips/prim_opentitan/prim_cdc_rand_delay.sv
hw/ips/prim_opentitan/prim_count.sv
hw/ips/prim_opentitan/prim_diff_decode.sv
hw/ips/prim_opentitan/prim_fifo_async.sv
hw/ips/prim_opentitan/prim_fifo_async_simple.sv
hw/ips/prim_opentitan/prim_fifo_async_sram_adapter.sv
hw/ips/prim_opentitan/prim_fifo_sync.sv
hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv
hw/ips/prim_opentitan/prim_filter.sv
hw/ips/prim_opentitan/prim_filter_ctr.sv
hw/ips/prim_opentitan/prim_flop.sv
hw/ips/prim_opentitan/prim_flop_2sync.sv
hw/ips/prim_opentitan/prim_intr_hw.sv
hw/ips/prim_opentitan/prim_onehot_check.sv
hw/ips/prim_opentitan/prim_pulse_sync.sv
hw/ips/prim_opentitan/prim_reg_cdc.sv
hw/ips/prim_opentitan/prim_reg_cdc_arb.sv
hw/ips/prim_opentitan/prim_reg_we_check.sv
hw/ips/prim_opentitan/prim_sec_anchor_buf.sv
hw/ips/prim_opentitan/prim_sec_anchor_flop.sv
hw/ips/prim_opentitan/prim_secded_inv_39_32_dec.sv
hw/ips/prim_opentitan/prim_secded_inv_39_32_enc.sv
hw/ips/prim_opentitan/prim_secded_inv_64_57_dec.sv
hw/ips/prim_opentitan/prim_secded_inv_64_57_enc.sv
hw/ips/prim_opentitan/prim_subreg.sv
hw/ips/prim_opentitan/prim_subreg_arb.sv
hw/ips/prim_opentitan/prim_subreg_ext.sv
hw/ips/prim_opentitan/prim_sync_reqack.sv
hw/ips/tlul/sram2tlul.sv
hw/ips/tlul/tlul_adapter_host.sv
hw/ips/tlul/tlul_adapter_reg.sv
hw/ips/tlul/tlul_adapter_sram.sv
hw/ips/tlul/tlul_assert.sv
hw/ips/tlul/tlul_assert_multiple.sv
hw/ips/tlul/tlul_cmd_intg_chk.sv
hw/ips/tlul/tlul_cmd_intg_gen.sv
hw/ips/tlul/tlul_data_integ_dec.sv
hw/ips/tlul/tlul_data_integ_enc.sv
hw/ips/tlul/tlul_err.sv
hw/ips/tlul/tlul_err_resp.sv
hw/ips/tlul/tlul_fifo_async.sv
hw/ips/tlul/tlul_fifo_sync.sv
hw/ips/tlul/tlul_rsp_intg_chk.sv
hw/ips/tlul/tlul_rsp_intg_gen.sv
hw/ips/tlul/tlul_socket_1n.sv
hw/ips/tlul/tlul_socket_m1.sv
hw/ips/tlul/tlul_sram_byte.sv
