#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
app.py — General-purpose FSM generator for HW / Protocol / RTL specs (Ollama)
Pipeline: C01..C12 (incremental contracts), multi-sampling, verifier + patch plan,
deterministic invariants, trace tests, exports + report.

Key design points:
- Transitions use "on" (event base name) instead of free-form "cond".
- Events are the only triggers (guards can be added later as a separate field).
- Two loops:
  - Semantic loop: normalize spec, canonicalize entities, audit vs spec.
  - Structural loop: draft transitions, critic, patch plan, deterministic repairs.
- Trace tests generated by LLM + deterministic simulation.
- Exports:
  - inputs/ <fsm>.txt (GraphViz-like "FROM -> TO : "event_i"")
  - inputs/ <fsm>.csv (state outputs, 0/1)
  - inputs/ <fsm>.report.json (provenance, assumptions, issues, patches)
"""

import os, re, sys, json, csv, time, urllib.request, urllib.error, argparse
from dataclasses import dataclass, field
from typing import Any, Dict, List, Tuple, Set, Optional

# ---------------- CONFIG ----------------
EXPORT_DIR = "fsm_gen/inputs"
MODEL_GEN = "qwen2.5:3b-instruct"  # generator model
MODEL_VER = "qwen2.5:3b-instruct"  # verifier model (can be same)
OLLAMA_URL = "http://127.0.0.1:11434/api/generate"

IN_SUFFIX = "_i"
OUT_SUFFIX = "_o"

DONE_CLEAR_BASE = "clear"       # -> clear_i
ERR_CLEAR_BASE  = "clear_err"   # -> clear_err_i

# Multi-sampling controls
N_TRANSITION_SAMPLES = 3
N_TAG_SAMPLES = 2
MAX_PATCH_ITERS = 2

# JSON parsing
JSON_BLOCK = re.compile(r"<<<JSON\s*(\{.*?\})\s*JSON", re.S)

# Terminal detection
TERM_RE = re.compile(r"^(done|final|complete|end|finish)$", re.I)

# Forbidden event triggers
BAD_EVENTS = {"1", "true", "always", "default", ""}

# Heuristic detection
RX_RESET = re.compile(r"\b(reset|rst|nreset|nrst)\b", re.I)
RX_TIMEOUT = re.compile(r"\b(timeout|watchdog|wdt)\b", re.I)
RX_ERROR = re.compile(r"\b(error|errore|fault|fail|failure|exception)\b", re.I)

# Common mode patterns (very general)
MODE_PATTERNS = [
    (re.compile(r"\blow\s*power\b", re.I), "low_power"),
    (re.compile(r"\bsleep\b", re.I), "sleep"),
    (re.compile(r"\bstandby\b", re.I), "standby"),
    (re.compile(r"\bcharging\b", re.I), "charging"),
]

# Handshake patterns (best-effort, general RTL/protocol)
RX_VALID_READY = re.compile(r"\b(valid|ready)\b", re.I)
RX_REQ_ACK = re.compile(r"\b(req|request|ack|acknowledge)\b", re.I)

# ---------------- DEBUG ----------------
DEBUG = True

def dbg(msg: str) -> None:
    if DEBUG:
        print(f"[DBG] {msg}", flush=True)

def clip(s: str, n: int = 260) -> str:
    return s if len(s) <= n else s[:n] + " ..."

# ---------------- UTIL (naming) ----------------
def snake_token(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"[\s\-]+", "_", s)
    s = re.sub(r"[^a-z0-9_]", "", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s

def to_input_name(base: str) -> str:
    b = snake_token(base) or "event"
    return b if b.endswith(IN_SUFFIX) else (b + IN_SUFFIX)

def to_output_name(base: str) -> str:
    b = snake_token(base) or "out"
    return b if b.endswith(OUT_SUFFIX) else (b + OUT_SUFFIX)

# ---------------- OLLAMA ----------------
def ollama(prompt: str, model: str, temperature: float, top_p: float = 0.9, timeout_s: int = 60) -> str:
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": temperature, "top_p": top_p},
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        OLLAMA_URL, data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    dbg(f"Ollama POST model={model} temp={temperature} bytes={len(data)}")
    t0 = time.time()
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.URLError as e:
        raise RuntimeError(f"Ollama connection error: {e} (run: ollama serve)") from e
    dbg(f"Ollama OK {time.time()-t0:.2f}s chars={len(body)}")
    obj = json.loads(body)
    if not isinstance(obj.get("response"), str):
        raise RuntimeError("Ollama response missing 'response'")
    return obj["response"]

# ---------------- JSON SALVAGE ----------------
def strip_code_fences(s: str) -> str:
    s = s.strip()
    if s.startswith("```"):
        s = re.sub(r"^```[a-zA-Z]*\s*", "", s)
        s = re.sub(r"\s*```$", "", s)
    return s.strip()

def salvage_json_text(js: str) -> str:
    js = strip_code_fences(js)
    js = js.replace("[...]", "[]")
    js = re.sub(r':\s*\.\.\.\s*([,\}])', r": null\1", js)
    return js

def parse_json_block(text: str) -> Dict[str, Any]:
    dbg("LLM head: " + clip(text.replace("\n", "\\n")))
    m = JSON_BLOCK.search(text)
    if m:
        js = m.group(1)
        dbg(f"JSON block found len={len(js)}")
    else:
        i, j = text.find("{"), text.rfind("}")
        if i < 0 or j < 0 or j <= i:
            raise ValueError("No JSON found in LLM output")
        js = text[i:j+1]
        dbg(f"JSON fallback slice len={len(js)}")

    js2 = salvage_json_text(js)
    if js2 != js:
        dbg("JSON salvage applied.")
    return json.loads(js2)

# ---------------- CANONICALIZERS ----------------
def uniq_upper_list(xs: Any, default: List[str]) -> List[str]:
    if not isinstance(xs, list):
        return default[:]
    out = [x.strip().upper() for x in xs if isinstance(x, str) and x.strip()]
    out = list(dict.fromkeys(out))
    return out or default[:]

def uniq_lower_list(xs: Any, default: List[str]) -> List[str]:
    if not isinstance(xs, list):
        return default[:]
    out = [snake_token(x) for x in xs if isinstance(x, str)]
    out = [x for x in out if x]
    out = list(dict.fromkeys(out))
    return out or default[:]

def infer_terminals(states: List[str], terms: List[str]) -> List[str]:
    norm = []
    for t in terms:
        if isinstance(t, str):
            norm.append(t.strip().upper())
    s = set(norm)
    for st in states:
        if TERM_RE.match(st.lower()):
            s.add(st)
    out = list(dict.fromkeys(list(s)))
    return out or ["DONE"]

# ---------------- MODE HELPERS ----------------
def detect_modes_from_text(spec: str) -> List[str]:
    found: List[str] = []
    for rx, mode in MODE_PATTERNS:
        if rx.search(spec):
            found.append(mode)
    return list(dict.fromkeys(found))

def mode_state_name(mode: str) -> str:
    return mode.upper()

def mode_enter_event(mode: str) -> str:
    return f"enter_{mode}"

def mode_exit_event(mode: str) -> str:
    # Wake is a common generic exit for low power states
    if mode in ("sleep", "standby", "low_power"):
        return "wake"
    return f"exit_{mode}"

# ---------------- TRANSITIONS ----------------
Transition = Dict[str, str]  # {"from": "STATE", "to":"STATE", "on":"event_base"}

def canon_transitions(x: Any, states: List[str], events: List[str]) -> List[Transition]:
    stset = set(states)
    evset = set(events)
    out: List[Transition] = []
    if isinstance(x, list):
        for t in x:
            if not isinstance(t, dict):
                continue
            fr, to, on = t.get("from"), t.get("to"), t.get("on")
            if isinstance(fr, str) and isinstance(to, str) and isinstance(on, str):
                fru, tou = fr.strip().upper(), to.strip().upper()
                onb = snake_token(on)
                if fru in stset and tou in stset and onb in evset and onb not in BAD_EVENTS:
                    out.append({"from": fru, "to": tou, "on": onb})
    # de-dup
    uniq = []
    seen = set()
    for t in out:
        key = (t["from"], t["to"], t["on"])
        if key not in seen:
            uniq.append(t)
            seen.add(key)
    return uniq

def degrees(states: List[str], trans: List[Transition]) -> Tuple[Dict[str, int], Dict[str, int]]:
    indeg = {s: 0 for s in states}
    outdeg = {s: 0 for s in states}
    for t in trans:
        outdeg[t["from"]] += 1
        indeg[t["to"]] += 1
    return indeg, outdeg

def add_if_missing(trans: List[Transition], fr: str, to: str, on: str, provenance: List[Dict[str, Any]], origin: str) -> None:
    onb = snake_token(on)
    for t in trans:
        if t["from"] == fr and t["to"] == to and t["on"] == onb:
            return
    trans.append({"from": fr, "to": to, "on": onb})
    provenance.append({"op": "add_transition", "from": fr, "to": to, "on": onb, "origin": origin})
    dbg(f"repair add {fr}->{to} on {onb} ({origin})")

def has_edge(trans: List[Transition], fr: str, to: str, on: Optional[str] = None) -> bool:
    if on is None:
        return any(t["from"] == fr and t["to"] == to for t in trans)
    onb = snake_token(on)
    return any(t["from"] == fr and t["to"] == to and t["on"] == onb for t in trans)

# ---------------- OUTPUT TAGS ----------------
def sanitize_state_tags(tags: Dict[str, List[str]], states: List[str]) -> Dict[str, List[str]]:
    out: Dict[str, List[str]] = {}
    for st in states:
        arr = tags.get(st, [])
        if not isinstance(arr, list):
            arr = []
        cleaned = [snake_token(x) for x in arr if isinstance(x, str)]
        cleaned = [x for x in cleaned if x]
        out[st] = list(dict.fromkeys(cleaned))
    return out

def remove_state_name_outputs(outputs: List[str], states: List[str], protected: Set[str]) -> List[str]:
    st_tokens = {snake_token(s) for s in states}
    out = []
    for o in outputs:
        if o in protected:
            out.append(o)
        elif o not in st_tokens:
            out.append(o)
    return list(dict.fromkeys(out))

def build_outputs_from_tags(states: List[str],
                            tags: Dict[str, List[str]],
                            extra_outputs: List[str],
                            mode_tags: Dict[str, str],
                            mode_states: Dict[str, str],
                            state_roles: Dict[str, List[str]]) -> Tuple[List[str], Dict[str, Dict[str, int]]]:
    # Protect mode tags from "state-name output" removal
    protected = {snake_token(v) for v in mode_tags.values() if v}

    out_set: Set[str] = set()
    for st in states:
        for t in tags.get(st, []):
            out_set.add(t)
    for o in extra_outputs:
        if o:
            out_set.add(o)

    # Always include mode tags
    for _, tag in mode_tags.items():
        t = snake_token(tag)
        if t:
            out_set.add(t)

    # Backstop from roles (general RTL-friendly)
    if "WORKING" in states and not tags.get("WORKING"):
        tags["WORKING"] = tags.get("WORKING", []) + ["busy"]
        out_set.add("busy")
    if "DONE" in states and not tags.get("DONE"):
        tags["DONE"] = tags.get("DONE", []) + ["done"]
        out_set.add("done")
    if "ERROR" in states and not tags.get("ERROR"):
        tags["ERROR"] = tags.get("ERROR", []) + ["error"]
        out_set.add("error")
    if "IDLE" in states and not tags.get("IDLE"):
        # Common safe output: idle
        tags["IDLE"] = tags.get("IDLE", []) + ["idle"]
        out_set.add("idle")

    # Additional role-based hints
    for st, roles in state_roles.items():
        rset = set(roles or [])
        if "fault" in rset and "error" not in tags.get(st, []):
            tags[st] = tags.get(st, []) + ["error"]
            out_set.add("error")
        if "terminal" in rset and "done" not in tags.get(st, []):
            tags[st] = tags.get(st, []) + ["done"]
            out_set.add("done")

    outputs = sorted(out_set)
    outputs = remove_state_name_outputs(outputs, states, protected)
    outputs = list(dict.fromkeys([snake_token(x) for x in outputs if snake_token(x)]))

    so: Dict[str, Dict[str, int]] = {}
    for st in states:
        tset = set(tags.get(st, []))

        # enforce mode tag ON in the mode state
        for mode, stname in mode_states.items():
            if st == stname:
                t = snake_token(mode_tags.get(mode, mode))
                if t:
                    tset.add(t)

        so[st] = {o: (1 if o in tset else 0) for o in outputs}

    return outputs, so

# ---------------- APPLY SUFFIXING ----------------
def apply_suffixing(events: List[str],
                    trans: List[Transition],
                    outputs_base: List[str],
                    so_base: Dict[str, Dict[str, int]]) -> Tuple[List[str], List[Dict[str, str]], List[str], Dict[str, Dict[str, int]]]:
    dbg("Applying deterministic suffixing (_i/_o)...")
    inputs_i = list(dict.fromkeys([to_input_name(e) for e in events]))
    dbg(f"events(base)={events} -> inputs={inputs_i}")

    trans_i: List[Dict[str, str]] = []
    for t in trans:
        onb = snake_token(t["on"])
        if onb in BAD_EVENTS or not onb:
            onb = "event"
        trans_i.append({"from": t["from"], "to": t["to"], "on": to_input_name(onb)})

    outputs_o = list(dict.fromkeys([to_output_name(o) for o in outputs_base]))
    dbg(f"outputs(base)={outputs_base} -> outputs={outputs_o}")

    so_o: Dict[str, Dict[str, int]] = {}
    for st, m in so_base.items():
        so_o[st] = {}
        for o in outputs_base:
            so_o[st][to_output_name(o)] = 1 if m.get(o, 0) == 1 else 0
        for o in outputs_o:
            if so_o[st].get(o) not in (0, 1):
                so_o[st][o] = 0

    return inputs_i, trans_i, outputs_o, so_o

# ---------------- DETERMINISTIC INVARIANTS + REPAIR ----------------
def ensure_core_entities(spec: str, states: List[str], events: List[str], terminals: List[str], provenance: List[Dict[str, Any]]) -> None:
    # Core baseline
    for core in ("IDLE", "WORKING", "DONE"):
        if core not in states:
            states.append(core)
            provenance.append({"op": "add_state", "state": core, "origin": "repair_core"})
    for ev in ("start", "done", DONE_CLEAR_BASE):
        if ev not in events:
            events.append(ev)
            provenance.append({"op": "add_event", "event": ev, "origin": "repair_core"})

    # Reset/timeout/error inference (very general)
    if RX_RESET.search(spec) and "reset" not in events:
        events.append("reset")
        provenance.append({"op": "add_event", "event": "reset", "origin": "repair_infer"})
    if RX_TIMEOUT.search(spec) and "timeout" not in events:
        events.append("timeout")
        provenance.append({"op": "add_event", "event": "timeout", "origin": "repair_infer"})
    if RX_ERROR.search(spec):
        if "ERROR" not in states:
            states.append("ERROR")
            provenance.append({"op": "add_state", "state": "ERROR", "origin": "repair_infer"})
        if "error" not in events:
            events.append("error")
            provenance.append({"op": "add_event", "event": "error", "origin": "repair_infer"})
        if ERR_CLEAR_BASE not in events:
            events.append(ERR_CLEAR_BASE)
            provenance.append({"op": "add_event", "event": ERR_CLEAR_BASE, "origin": "repair_infer"})

    # Ensure clear events for DONE/ERROR
    if "DONE" in states and DONE_CLEAR_BASE not in events:
        events.append(DONE_CLEAR_BASE)
        provenance.append({"op": "add_event", "event": DONE_CLEAR_BASE, "origin": "repair_core"})
    if "ERROR" in states and ERR_CLEAR_BASE not in events:
        events.append(ERR_CLEAR_BASE)
        provenance.append({"op": "add_event", "event": ERR_CLEAR_BASE, "origin": "repair_core"})

    # Terminals
    terminals[:] = infer_terminals(states, terminals)

def ensure_mode_entities(spec: str, states: List[str], events: List[str], modes: List[str],
                         mode_states: Dict[str, str], mode_tags: Dict[str, str], provenance: List[Dict[str, Any]]) -> None:
    # Backup mode detect
    for m in detect_modes_from_text(spec):
        if m not in modes:
            modes.append(m)
            provenance.append({"op": "add_mode", "mode": m, "origin": "repair_infer"})

    for m in modes:
        st = mode_states.get(m) or mode_state_name(m)
        st = st.strip().upper()
        mode_states[m] = st
        tagv = mode_tags.get(m, m)
        mode_tags[m] = snake_token(tagv) or m

        if st not in states:
            states.append(st)
            provenance.append({"op": "add_state", "state": st, "origin": "repair_mode", "mode": m})

        ent = mode_enter_event(m)
        ext = mode_exit_event(m)
        if ent not in events:
            events.append(ent)
            provenance.append({"op": "add_event", "event": ent, "origin": "repair_mode", "mode": m})
        if ext not in events:
            events.append(ext)
            provenance.append({"op": "add_event", "event": ext, "origin": "repair_mode", "mode": m})

def deterministic_repair_transitions(states: List[str], events: List[str], terminals: List[str],
                                    trans: List[Transition], provenance: List[Dict[str, Any]]) -> None:
    # Basic arcs if present
    if "start" in events:
        add_if_missing(trans, "IDLE", "WORKING", "start", provenance, "repair_edges")
    if "done" in events:
        add_if_missing(trans, "WORKING", "DONE", "done", provenance, "repair_edges")

    # Error path
    if "ERROR" in states and "error" in events:
        add_if_missing(trans, "WORKING", "ERROR", "error", provenance, "repair_edges")

    # Default returns
    if "DONE" in states and "clear" in events:
        add_if_missing(trans, "DONE", "IDLE", "clear", provenance, "repair_edges")
    if "ERROR" in states and "clear_err" in events:
        add_if_missing(trans, "ERROR", "IDLE", "clear_err", provenance, "repair_edges")

    # Reset global behavior (general RTL best practice)
    if "reset" in events:
        for st in states:
            if st == "IDLE":
                continue
            # do not force reset from terminal? in HW it's often still valid; keep it.
            add_if_missing(trans, st, "IDLE", "reset", provenance, "repair_reset")

    # Degree repair (avoid dead states). Use "clear" as generic safe event; if missing, use "reset" else "start".
    indeg, outdeg = degrees(states, trans)
    fallback_on = "clear" if "clear" in events else ("reset" if "reset" in events else "start")

    # Ensure outgoing
    for st in list(states):
        if outdeg.get(st, 0) >= 1:
            continue
        if st == "DONE" and "clear" in events:
            add_if_missing(trans, "DONE", "IDLE", "clear", provenance, "repair_deg")
        elif st == "ERROR" and "clear_err" in events:
            add_if_missing(trans, "ERROR", "IDLE", "clear_err", provenance, "repair_deg")
        elif st != "IDLE":
            add_if_missing(trans, st, "IDLE", fallback_on, provenance, "repair_deg")
        else:
            # IDLE with no outgoing: use start if possible else reset
            on = "start" if "start" in events else fallback_on
            add_if_missing(trans, "IDLE", "WORKING" if "WORKING" in states else states[0], on, provenance, "repair_deg")

    # Ensure incoming
    indeg, outdeg = degrees(states, trans)
    for st in list(states):
        if indeg.get(st, 0) >= 1:
            continue
        if st == "IDLE":
            # someone -> IDLE on clear/reset
            cand = [x for x in states if x != "IDLE"]
            if cand:
                add_if_missing(trans, cand[0], "IDLE", fallback_on, provenance, "repair_deg")
        else:
            # IDLE -> st on a generic enter event if exists, else start, else reset
            on = "start" if "start" in events else ("reset" if "reset" in events else fallback_on)
            add_if_missing(trans, "IDLE", st, on, provenance, "repair_deg")

    # Remove terminal self-loops
    termset = set(terminals)
    before = len(trans)
    trans[:] = [t for t in trans if not (t["from"] == t["to"] and t["from"] in termset)]
    if len(trans) != before:
        provenance.append({"op": "remove_terminal_self_loops", "count": before - len(trans), "origin": "repair_edges"})

# ---------------- VALIDATION ----------------
def validate(states: List[str], events: List[str], terminals: List[str], trans: List[Transition]) -> List[str]:
    errs: List[str] = []
    stset = set(states)
    evset = set(events)
    indeg, outdeg = degrees(states, trans)
    termset = set(terminals)

    for s in states:
        if indeg.get(s, 0) < 1:
            errs.append(f"State {s} has no incoming")
        if outdeg.get(s, 0) < 1:
            errs.append(f"State {s} has no outgoing")

    for t in trans:
        if t["from"] not in stset:
            errs.append(f"Unknown from {t['from']}")
        if t["to"] not in stset:
            errs.append(f"Unknown to {t['to']}")
        if t["on"] not in evset:
            errs.append(f"Transition uses unknown event: {t}")
        if t["on"] in BAD_EVENTS:
            errs.append(f"Forbidden event name: {t}")
        if t["from"] == t["to"] and t["from"] in termset:
            errs.append(f"Forbidden terminal self-loop: {t}")

    # default returns required (as policy)
    if "DONE" in states and "clear" in events:
        if not any(t["from"] == "DONE" and t["to"] == "IDLE" and t["on"] == "clear" for t in trans):
            errs.append("Missing default DONE->IDLE on clear")
    if "ERROR" in states and "clear_err" in events:
        if not any(t["from"] == "ERROR" and t["to"] == "IDLE" and t["on"] == "clear_err" for t in trans):
            errs.append("Missing default ERROR->IDLE on clear_err")

    # reset global (if reset exists, expect at least one reset edge)
    if "reset" in events:
        if not any(t["on"] == "reset" for t in trans):
            errs.append("Event reset exists but no transition uses reset")

    # event coverage
    used = set(t["on"] for t in trans)
    for ev in events:
        if ev not in used:
            errs.append(f"Event {ev} is unused in transitions")

    return errs

# ---------------- SIMULATION (traces) ----------------
def simulate_trace(states: List[str], trans: List[Transition], start_state: str, events: List[str]) -> Tuple[str, List[str]]:
    """
    Deterministic simulation:
    - For each event, if there is exactly one outgoing transition on that event, take it.
    - If multiple, take the first in list order (stable).
    - If none, stay (record miss).
    """
    st = start_state
    misses: List[str] = []
    for ev in events:
        next_st = None
        for t in trans:
            if t["from"] == st and t["on"] == ev:
                next_st = t["to"]
                break
        if next_st is None:
            misses.append(f"no_edge:{st} on {ev}")
        else:
            st = next_st
    return st, misses

def check_expectations(final_state: str, visited: Set[str], expects: List[str]) -> List[str]:
    fails: List[str] = []
    for e in expects:
        if not isinstance(e, str):
            continue
        e = e.strip()
        if e.startswith("reach:"):
            st = e.split(":", 1)[1].strip().upper()
            if st and st not in visited:
                fails.append(f"expect {e} failed")
        elif e.startswith("end:"):
            st = e.split(":", 1)[1].strip().upper()
            if st and final_state != st:
                fails.append(f"expect {e} failed (got end:{final_state})")
    return fails

# ---------------- EXPORT ----------------
def export_files(fsm_name: str,
                 states: List[str],
                 outputs_o: List[str],
                 so_o: Dict[str, Dict[str, int]],
                 trans_i: List[Dict[str, str]],
                 report: Dict[str, Any]) -> None:
    os.makedirs(EXPORT_DIR, exist_ok=True)
    txtp = os.path.join(EXPORT_DIR, f"{fsm_name}.txt")
    csvp = os.path.join(EXPORT_DIR, f"{fsm_name}.csv")
    rep = os.path.join(EXPORT_DIR, f"{fsm_name}.report.json")
    dbg(f"EXPORT -> {txtp}, {csvp}, {rep}")

    with open(txtp, "w", encoding="utf-8") as f:
        for t in trans_i:
            f.write(f"{t['from']} -> {t['to']} : \"{t['on']}\";\n")

    with open(csvp, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["StateName"] + outputs_o)
        for s in states:
            w.writerow([s] + [so_o[s][o] for o in outputs_o])

    with open(rep, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

# ---------------- CONTRACTS (C01..C12) ----------------
def C01(spec: str) -> str:
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C01_SPEC_NORMALIZE

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Return exactly:
<<<JSON
{{
  "domain":"hw_fsm",
  "glossary":{{}},
  "requirements":[...],
  "assumptions":[...],
  "forbidden":[...],
  "signals":[{{"name":"...","dir":"in|out|internal","role":"..."}}, ...],
  "timing":[{{"name":"...","kind":"event_or_counter","notes":"..."}}, ...]
}}
JSON

Rules (IMPORTANT):
- Be general for HW/protocol/RTL FSMs.
- Do NOT invent requirements. Only include requirements explicitly stated in the spec text.
- "requirements" are explicit must-haves from spec.
- If something is not explicit but common in HW, put it in "assumptions" (optional), not in "requirements".
- "assumptions" only if needed (mark as assumptions).
- Only mention reset/timeout/handshake in requirements if the spec explicitly contains those words/signals.
- Include reset/timeout/handshake keywords in requirements if present.
- Use only JSON, no extra keys, no notes.
- Arrays must be valid JSON arrays (use [] if none)."""

def C02(spec: str, norm: Dict[str, Any]) -> str:
    # Include normalized reqs to reduce hallucinations
    reqs = norm.get("requirements", [])
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C02_ENTITIES_EXTRACT

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(reqs, ensure_ascii=False)}

Return exactly:
<<<JSON
{{
  "states":[...],
  "events":[...],
  "terminal_states":[...],
  "modes":[...],
  "mode_states":{{"mode":"STATE"}},
  "mode_tags":{{"mode":"tag"}}
}}
JSON

Rules:
- If underspecified: states=[IDLE,WORKING,DONE], events=[start,done,clear], terminal_states=[DONE]
- If mentions error/errore/fault: include state ERROR and event error, plus event clear_err
- If mentions reset/rst: include event reset
- If mentions timeout/watchdog: include event timeout
- Detect modes like "low power", "sleep", "standby", "charging"
- states uppercase; events/modes/tags lowercase snake_case base names only
- Ensure DONE has event 'clear'
- Ensure ERROR has event 'clear_err' if ERROR exists
- JSON only. No ... or [...].
- No additional keys.
"""

def C03(spec: str, norm: Dict[str, Any], states: List[str], events: List[str], modes: List[str]) -> str:
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C03_CANONICAL_MAP

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized glossary (may be empty):
{json.dumps(norm.get("glossary", {}), ensure_ascii=False)}

States: {states}
Events: {events}
Modes: {modes}

Return exactly:
<<<JSON
{{
  "state_map":{{}},
  "event_map":{{}},
  "mode_map":{{}},
  "tag_map":{{}}
}}
JSON

Rules:
- Maps should only map synonyms/variants to existing canonical items in the provided lists.
- Do NOT invent new states/events/modes/tags.
- Keys can be variants; values must be canonical.
- JSON only. No additional keys.
"""

def C04(spec: str, norm: Dict[str, Any], states: List[str]) -> str:
    reqs = norm.get("requirements", [])
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C04_STATE_ROLE_ANNOTATION

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(reqs, ensure_ascii=False)}

States: {states}

Return exactly:
<<<JSON
{{
  "state_roles":{{"STATE":[...]}}
}}
JSON

Rules:
- Assign 0..N roles per state (general RTL-friendly):
  allowed roles: safe, active, terminal, fault, reset_sink, wait_handshake, low_power
- If a state is ERROR-like -> include fault
- If a state is DONE-like -> include terminal
- If IDLE -> include safe and reset_sink
- JSON only. No additional keys.
"""

def C05(spec: str, norm: Dict[str, Any], states: List[str], events: List[str], terminals: List[str]) -> str:
    reqs = norm.get("requirements", [])
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C05_TRANSITIONS_DRAFT

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(reqs, ensure_ascii=False)}

States: {states}
Events (base): {events}
Terminal states: {terminals}

Return exactly:
<<<JSON
{{"transitions":[{{"from":"...","to":"...","on":"..."}}, ...]}}
JSON

Rules:
- Use ONLY the given States.
- "on" MUST be exactly one of Events (base), no other strings.
- Each event in Events must appear in >=1 transition "on".
- Forbidden on: "1","true","always","default",""
- No terminal self-loop (DONE->DONE forbidden).
- Every state should have >=1 incoming and >=1 outgoing if possible.
- Include default returns if relevant:
  - DONE -> IDLE on clear
  - ERROR -> IDLE on clear_err (if ERROR exists)
- JSON only. No ... or [...].
- No additional keys.
"""

def C06(spec: str, norm: Dict[str, Any], states: List[str], events: List[str], terminals: List[str], trans: List[Transition]) -> str:
    payload = {"states": states, "events": events, "terminal_states": terminals, "transitions": trans}
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C06_TRANSITIONS_COVERAGE_CRITIC

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(norm.get("requirements", []), ensure_ascii=False)}

Candidate FSM (base):
{json.dumps(payload, ensure_ascii=False)}

Return exactly:
<<<JSON
{{
  "issues":[{{"type":"...","detail":"...","hint":"..."}}, ...],
  "must_fix":[{{"type":"...","detail":"...","hint":"..."}}, ...],
  "optional":[{{"type":"...","detail":"...","hint":"..."}}, ...]
}}
JSON

Rules:
- Be strict about: missing events usage, unreachable states, missing reset behavior (if reset in events), missing error recovery, missing done/clear return.
- Do NOT invent new events/states. Hints must reference existing ones.
- JSON only. No additional keys.
"""

def C07(spec: str, norm: Dict[str, Any], states: List[str], events: List[str], trans: List[Transition], critic: Dict[str, Any]) -> str:
    payload = {"states": states, "events": events, "transitions": trans, "critic": critic}
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C07_TRANSITIONS_PATCH_PLAN

Given this candidate FSM and critic issues, output a minimal safe patch plan.

Input:
{json.dumps(payload, ensure_ascii=False)}

Return exactly:
<<<JSON
{{
  "patches":[
    {{"op":"add_transition","from":"STATE","to":"STATE","on":"event"}},
    {{"op":"remove_transition","from":"STATE","to":"STATE","on":"event"}}
  ]
}}
JSON

Rules:
- Only use provided states/events.
- Prefer add_transition over remove_transition unless necessary.
- Keep patch plan minimal.
- JSON only. No additional keys.
"""

def C09(spec: str, norm: Dict[str, Any], states: List[str], state_roles: Dict[str, List[str]]) -> str:
    reqs = norm.get("requirements", [])
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C09_OUTPUT_TAGS_DRAFT

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(reqs, ensure_ascii=False)}

States: {states}
State roles:
{json.dumps(state_roles, ensure_ascii=False)}

Return exactly:
<<<JSON
{{"state_tags":{{"STATE":[...]}}, "extra_outputs":[]}}
JSON

Rules:
- state_tags maps each state to 0..3 output tags (base names, snake_case).
- Do NOT use event names as tags if avoidable.
- Use roles to guide: safe->idle/safe, active->busy/active, terminal->done, fault->error.
- extra_outputs must be a valid JSON list (use []).
- JSON only. No additional keys.
"""

def C10(spec: str, norm: Dict[str, Any], states: List[str], state_roles: Dict[str, List[str]], tags: Dict[str, List[str]]) -> str:
    payload = {"states": states, "state_roles": state_roles, "state_tags": tags}
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C10_OUTPUTS_SEMANTIC_AUDIT

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(norm.get("requirements", []), ensure_ascii=False)}

Candidate outputs (base):
{json.dumps(payload, ensure_ascii=False)}

Return exactly:
<<<JSON
{{
  "pass": true,
  "issues":[{{"type":"...","detail":"...","hint":"..."}}, ...]
}}
JSON

Rules:
- If a state has role terminal, ensure it has done-like tag.
- If a state has role fault, ensure it has error-like tag.
- If IDLE has safe/reset_sink, prefer idle/safe tag.
- JSON only. No additional keys.
"""

def C11(spec: str, norm: Dict[str, Any], events: List[str], states: List[str]) -> str:
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C11_TRACE_TESTGEN

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Events (base): {events}
States: {states}

Return exactly:
<<<JSON
{{
  "traces":[
    {{"events":[...], "expect":[...]}}
  ]
}}
JSON

Rules:
- Generate 5..12 traces.
- Include reset behavior if "reset" in events.
- Include nominal start->done->clear if start/done/clear exist.
- Include error recovery if ERROR exists or "error/clear_err" events exist.
- Include timeout path if "timeout" in events.
- "expect" items can be: "reach:STATE", "end:STATE".
- JSON only. No additional keys.
"""

def C12(spec: str, norm: Dict[str, Any], fsm_payload: Dict[str, Any], trace_results: Dict[str, Any]) -> str:
    return f"""SYSTEM: You output ONLY a JSON block.
USER:
Contract: C12_SPEC_COVERAGE_AUDIT

Spec (IT/EN):
<<<SPEC
{spec}
SPEC

Normalized requirements:
{json.dumps(norm.get("requirements", []), ensure_ascii=False)}

FSM (base):
{json.dumps(fsm_payload, ensure_ascii=False)}

Trace test results:
{json.dumps(trace_results, ensure_ascii=False)}

Return exactly:
<<<JSON
{{
  "pass": true,
  "missing": [...],
  "contradictions": [...],
  "hallucinations": [...],
  "suggested_actions":[...]
}}
JSON

Rules:
- "missing": requirements not reflected in FSM.
- "hallucinations": events/states/tags that are not implied by spec/requirements (be conservative).
- Suggested actions must only reference existing states/events (or indicate "revise entities").
- JSON only. No additional keys.
"""

# ---------------- APPLY CANONICAL MAP ----------------
def apply_maps(states: List[str], events: List[str], modes: List[str],
               mode_states: Dict[str, str], mode_tags: Dict[str, str],
               maps: Dict[str, Any], provenance: List[Dict[str, Any]]) -> Tuple[List[str], List[str], List[str], Dict[str, str], Dict[str, str]]:
    state_map = maps.get("state_map") if isinstance(maps.get("state_map"), dict) else {}
    event_map = maps.get("event_map") if isinstance(maps.get("event_map"), dict) else {}
    mode_map  = maps.get("mode_map") if isinstance(maps.get("mode_map"), dict) else {}
    tag_map   = maps.get("tag_map") if isinstance(maps.get("tag_map"), dict) else {}

    # states
    canon_states = []
    for s in states:
        key = s
        # accept mapping by case-insensitive keys
        mapped = None
        for k, v in state_map.items():
            if isinstance(k, str) and isinstance(v, str) and k.strip().upper() == s.strip().upper():
                mapped = v.strip().upper()
                break
        canon_states.append(mapped or s.strip().upper())
    canon_states = list(dict.fromkeys([s for s in canon_states if s]))
    if canon_states != states:
        provenance.append({"op": "apply_state_map", "origin": "C03", "diff": {"before": states, "after": canon_states}})
    states = canon_states

    # events
    canon_events = []
    for e in events:
        mapped = None
        for k, v in event_map.items():
            if isinstance(k, str) and isinstance(v, str) and snake_token(k) == snake_token(e):
                mapped = snake_token(v)
                break
        canon_events.append(mapped or snake_token(e))
    canon_events = list(dict.fromkeys([e for e in canon_events if e]))
    if canon_events != events:
        provenance.append({"op": "apply_event_map", "origin": "C03", "diff": {"before": events, "after": canon_events}})
    events = canon_events

    # modes
    canon_modes = []
    for m in modes:
        mapped = None
        for k, v in mode_map.items():
            if isinstance(k, str) and isinstance(v, str) and snake_token(k) == snake_token(m):
                mapped = snake_token(v)
                break
        canon_modes.append(mapped or snake_token(m))
    canon_modes = list(dict.fromkeys([m for m in canon_modes if m]))
    if canon_modes != modes:
        provenance.append({"op": "apply_mode_map", "origin": "C03", "diff": {"before": modes, "after": canon_modes}})
    modes = canon_modes

    # mode_states/tags (best effort)
    new_mode_states: Dict[str, str] = {}
    new_mode_tags: Dict[str, str] = {}
    for m in modes:
        st = mode_states.get(m, mode_state_name(m)).strip().upper()
        new_mode_states[m] = st
        tag = mode_tags.get(m, m)
        tag = snake_token(tag)
        # apply tag_map if provided
        for k, v in tag_map.items():
            if isinstance(k, str) and isinstance(v, str) and snake_token(k) == tag:
                tag = snake_token(v)
                break
        new_mode_tags[m] = tag or m
    mode_states = new_mode_states
    mode_tags = new_mode_tags

    return states, events, modes, mode_states, mode_tags

# ---------------- PATCH APPLICATION ----------------
def apply_patch_plan(states: List[str], events: List[str], trans: List[Transition],
                     plan: Dict[str, Any], provenance: List[Dict[str, Any]]) -> None:
    patches = plan.get("patches")
    if not isinstance(patches, list):
        return
    stset = set(states)
    evset = set(events)

    def remove_one(fr: str, to: str, on: str) -> bool:
        onb = snake_token(on)
        for i, t in enumerate(trans):
            if t["from"] == fr and t["to"] == to and t["on"] == onb:
                trans.pop(i)
                return True
        return False

    for p in patches:
        if not isinstance(p, dict):
            continue
        op = p.get("op")
        fr = p.get("from")
        to = p.get("to")
        on = p.get("on")
        if not (isinstance(op, str) and isinstance(fr, str) and isinstance(to, str) and isinstance(on, str)):
            continue
        fru = fr.strip().upper()
        tou = to.strip().upper()
        onb = snake_token(on)
        if fru not in stset or tou not in stset or onb not in evset:
            continue
        if op == "add_transition":
            add_if_missing(trans, fru, tou, onb, provenance, "C07_patch")
        elif op == "remove_transition":
            if remove_one(fru, tou, onb):
                provenance.append({"op": "remove_transition", "from": fru, "to": tou, "on": onb, "origin": "C07_patch"})

# ---------------- SCORING ----------------
def score_candidate(validate_errs: List[str],
                    critic: Optional[Dict[str, Any]],
                    provenance: List[Dict[str, Any]],
                    events: List[str],
                    trans: List[Transition]) -> int:
    score = 0
    score += 100 * len(validate_errs)

    if critic and isinstance(critic, dict):
        must_fix = critic.get("must_fix") if isinstance(critic.get("must_fix"), list) else []
        issues = critic.get("issues") if isinstance(critic.get("issues"), list) else []
        score += 10 * len(must_fix)
        score += 3 * len(issues)

    # penalize repair-heavy solutions
    score += 2 * sum(1 for p in provenance if p.get("op") == "add_transition" and p.get("origin", "").startswith("repair"))

    # penalize unused events
    used = set(t["on"] for t in trans)
    score += 5 * sum(1 for e in events if e not in used)

    # reset policy
    if "reset" in events and not any(t["on"] == "reset" for t in trans):
        score += 25

    return score

# ---------------- PIPELINE ----------------
def run_pipeline(spec: str, fsm_name: str) -> None:
    dbg("=== PIPELINE START ===")
    dbg(f"fsm_name={fsm_name} spec_len={len(spec)}")

    report: Dict[str, Any] = {
        "fsm_name": fsm_name,
        "model_gen": MODEL_GEN,
        "model_ver": MODEL_VER,
        "contracts": [],
        "provenance": [],
        "scores": [],
        "final": {},
    }
    provenance: List[Dict[str, Any]] = report["provenance"]

    # ---- C01 normalize
    r01 = parse_json_block(ollama(C01(spec), MODEL_VER, temperature=0.1))
    report["contracts"].append({"id": "C01", "out": r01})

    # ---- C02 entities extract
    r02 = parse_json_block(ollama(C02(spec, r01), MODEL_GEN, temperature=0.2))
    report["contracts"].append({"id": "C02", "out": r02})

    states = uniq_upper_list(r02.get("states"), ["IDLE", "WORKING", "DONE"])
    events = uniq_lower_list(r02.get("events"), ["start", "done", DONE_CLEAR_BASE])
    terminals = infer_terminals(states, uniq_upper_list(r02.get("terminal_states"), ["DONE"]))

    modes = uniq_lower_list(r02.get("modes"), [])
    mode_states_in = r02.get("mode_states") if isinstance(r02.get("mode_states"), dict) else {}
    mode_tags_in   = r02.get("mode_tags") if isinstance(r02.get("mode_tags"), dict) else {}

    mode_states: Dict[str, str] = {}
    mode_tags: Dict[str, str] = {}
    for m in modes:
        st = mode_state_name(m)
        if isinstance(mode_states_in.get(m), str) and mode_states_in[m].strip():
            st = mode_states_in[m].strip().upper()
        mode_states[m] = st
        tagv = mode_tags_in.get(m, m)
        mode_tags[m] = snake_token(tagv) if isinstance(tagv, str) else m

    # deterministic enrich
    ensure_core_entities(spec, states, events, terminals, provenance)
    ensure_mode_entities(spec, states, events, modes, mode_states, mode_tags, provenance)

    dbg(f"S2 states={states}")
    dbg(f"S2 events={events}")
    dbg(f"S2 modes={modes} mode_states={mode_states} mode_tags={mode_tags}")

    # ---- C03 canonical map + apply
    r03 = parse_json_block(ollama(C03(spec, r01, states, events, modes), MODEL_VER, temperature=0.0))
    report["contracts"].append({"id": "C03", "out": r03})
    states, events, modes, mode_states, mode_tags = apply_maps(states, events, modes, mode_states, mode_tags, r03, provenance)

    # Re-run core ensures after mapping
    ensure_core_entities(spec, states, events, terminals, provenance)
    ensure_mode_entities(spec, states, events, modes, mode_states, mode_tags, provenance)
    terminals = infer_terminals(states, terminals)

    # ---- C04 roles
    r04 = parse_json_block(ollama(C04(spec, r01, states), MODEL_VER, temperature=0.0))
    report["contracts"].append({"id": "C04", "out": r04})
    state_roles_in = r04.get("state_roles") if isinstance(r04.get("state_roles"), dict) else {}
    state_roles: Dict[str, List[str]] = {}
    allowed_roles = {"safe","active","terminal","fault","reset_sink","wait_handshake","low_power"}
    for st in states:
        arr = state_roles_in.get(st, [])
        if not isinstance(arr, list):
            arr = []
        roles = []
        for x in arr:
            if isinstance(x, str):
                r = snake_token(x)
                if r in allowed_roles:
                    roles.append(r)
        # backstops
        if st == "IDLE":
            roles = list(dict.fromkeys(["safe","reset_sink"] + roles))
        if st == "DONE":
            roles = list(dict.fromkeys(["terminal"] + roles))
        if st == "ERROR":
            roles = list(dict.fromkeys(["fault"] + roles))
        state_roles[st] = roles

    # ---- C05 multi-sample transitions
    best = None
    best_score = 10**9
    best_bundle = None

    for k in range(N_TRANSITION_SAMPLES):
        dbg(f"--- C05 sample {k+1}/{N_TRANSITION_SAMPLES} ---")
        local_prov: List[Dict[str, Any]] = []
        r05 = parse_json_block(ollama(C05(spec, r01, states, events, terminals), MODEL_GEN, temperature=0.35))
        trans = canon_transitions(r05.get("transitions"), states, events)

        # add mode enter/exit scaffolding (policy)
        for m, st in mode_states.items():
            if st in states:
                add_if_missing(trans, "IDLE", st, mode_enter_event(m), local_prov, "repair_mode_edges")
                add_if_missing(trans, st, "IDLE", mode_exit_event(m), local_prov, "repair_mode_edges")

        deterministic_repair_transitions(states, events, terminals, trans, local_prov)

        # critic + patch loop
        critic = None
        for it in range(MAX_PATCH_ITERS):
            errs = validate(states, events, terminals, trans)
            r06 = parse_json_block(ollama(C06(spec, r01, states, events, terminals, trans), MODEL_VER, temperature=0.0))
            critic = r06
            if errs:
                # Try patch plan
                r07 = parse_json_block(ollama(C07(spec, r01, states, events, trans, r06), MODEL_VER, temperature=0.0))
                apply_patch_plan(states, events, trans, r07, local_prov)
                deterministic_repair_transitions(states, events, terminals, trans, local_prov)
                continue
            # If validate ok, still apply must-fix minimal patches (optional)
            must_fix = r06.get("must_fix") if isinstance(r06.get("must_fix"), list) else []
            if must_fix:
                r07 = parse_json_block(ollama(C07(spec, r01, states, events, trans, r06), MODEL_VER, temperature=0.0))
                apply_patch_plan(states, events, trans, r07, local_prov)
                deterministic_repair_transitions(states, events, terminals, trans, local_prov)
                continue
            break

        errs_final = validate(states, events, terminals, trans)
        s = score_candidate(errs_final, critic, local_prov, events, trans)

        report["scores"].append({
            "sample": k,
            "score": s,
            "validate_errs": errs_final[:40],
            "prov_adds": sum(1 for p in local_prov if p.get("op") == "add_transition"),
            "critic_issues": len(critic.get("issues", [])) if isinstance(critic, dict) else None,
            "critic_must_fix": len(critic.get("must_fix", [])) if isinstance(critic, dict) else None,
        })

        if s < best_score:
            best_score = s
            best = trans
            best_bundle = {"C05": r05, "C06": critic, "prov": local_prov, "validate_errs": errs_final}

    if best is None:
        raise RuntimeError("No transitions candidate produced.")

    # Merge chosen provenance into global provenance
    for p in best_bundle["prov"]:
        provenance.append(p)

    trans = best
    if best_bundle["validate_errs"]:
        # Hard fail: even best candidate invalid
        dbg("Best candidate still invalid. Top errs: " + "; ".join(best_bundle["validate_errs"][:10]))
        raise RuntimeError("Invalid FSM after multi-sampling + patch loops (see report).")

    # ---- C09 multi-sample tags
    best_tags = None
    best_tag_score = 10**9
    best_extra: List[str] = []

    for k in range(N_TAG_SAMPLES):
        dbg(f"--- C09 tags sample {k+1}/{N_TAG_SAMPLES} ---")
        r09 = parse_json_block(ollama(C09(spec, r01, states, state_roles), MODEL_GEN, temperature=0.25))
        state_tags_in = r09.get("state_tags") if isinstance(r09.get("state_tags"), dict) else {}
        extra_outs = uniq_lower_list(r09.get("extra_outputs"), [])

        tags: Dict[str, List[str]] = {}
        for st, arr in state_tags_in.items():
            if isinstance(st, str) and isinstance(arr, list):
                tags[st.strip().upper()] = [snake_token(x) for x in arr if isinstance(x, str)]
        tags = sanitize_state_tags(tags, states)

        # Audit tags
        r10 = parse_json_block(ollama(C10(spec, r01, states, state_roles, tags), MODEL_VER, temperature=0.0))
        issues = r10.get("issues") if isinstance(r10.get("issues"), list) else []
        # Score: fewer issues is better
        sc = 5 * len(issues)
        # Penalty if DONE missing done tag etc. (extra hardening)
        if "DONE" in states and "done" not in tags.get("DONE", []):
            sc += 20
        if "ERROR" in states and "error" not in tags.get("ERROR", []):
            sc += 20
        if sc < best_tag_score:
            best_tag_score = sc
            best_tags = tags
            best_extra = extra_outs
            report["contracts"].append({"id": "C09", "out": r09})
            report["contracts"].append({"id": "C10", "out": r10})

    if best_tags is None:
        best_tags = sanitize_state_tags({}, states)

    # ---- build outputs
    outputs_base, so_base = build_outputs_from_tags(states, best_tags, best_extra, mode_tags, mode_states, state_roles)

    # ---- C11 traces
    r11 = parse_json_block(ollama(C11(spec, r01, events, states), MODEL_VER, temperature=0.15))
    report["contracts"].append({"id": "C11", "out": r11})
    traces = r11.get("traces") if isinstance(r11.get("traces"), list) else []

    # run trace tests
    trace_results: Dict[str, Any] = {"runs": [], "failures": 0}
    for tr in traces[:30]:
        if not isinstance(tr, dict):
            continue
        evs = tr.get("events")
        exp = tr.get("expect")
        if not isinstance(evs, list) or not isinstance(exp, list):
            continue
        evs_b = [snake_token(x) for x in evs if isinstance(x, str)]
        evs_b = [e for e in evs_b if e in set(events)]
        start_state = "IDLE" if "IDLE" in states else states[0]
        visited = {start_state}
        st = start_state
        misses = []
        for e in evs_b:
            st, miss = simulate_trace(states, trans, st, [e])
            visited.add(st)
            misses.extend(miss)
        fails = check_expectations(st, visited, [x for x in exp if isinstance(x, str)])
        if fails:
            trace_results["failures"] += 1
        trace_results["runs"].append({
            "events": evs_b,
            "expect": exp,
            "end": st,
            "visited": sorted(list(visited)),
            "misses": misses,
            "fails": fails
        })

    trace_summary = {
      "failures": trace_results["failures"],
      "num_runs": len(trace_results["runs"]),
      "failed_examples": [
         {"events": r["events"], "fails": r["fails"], "end": r["end"]}
         for r in trace_results["runs"] if r["fails"]
      ][:3]
    }

    # ---- C12 final audit
    fsm_payload = {
        "states": states,
        "events": events,
        "terminal_states": terminals,
        "modes": modes,
        "mode_states": mode_states,
        "mode_tags": mode_tags,
        "transitions": trans,
        "state_roles": state_roles,
        "state_tags": best_tags,
        "outputs": outputs_base
    }
    r12 = parse_json_block(ollama(C12(spec, r01, fsm_payload, trace_summary), MODEL_VER, temperature=0.0))
    report["contracts"].append({"id": "C12", "out": r12})

    # ---- finalize suffixing + export
    inputs_i, trans_i, outputs_o, so_o = apply_suffixing(events, trans, outputs_base, so_base)

    # final validation of suffixed outputs matrix shape
    if any(s not in so_o for s in states):
        raise RuntimeError("Missing state outputs after suffixing.")
    for s in states:
        for o in outputs_o:
            if so_o[s].get(o) not in (0, 1):
                raise RuntimeError(f"Invalid output value for {s}:{o}")

    report["final"] = {
        "states": states,
        "events": events,
        "inputs_i": inputs_i,
        "outputs_base": outputs_base,
        "outputs_o": outputs_o,
        "num_transitions": len(trans),
        "audit": r12,
        "trace_failures": trace_results["failures"],
    }

    export_files(fsm_name, states, outputs_o, so_o, trans_i, report)
    dbg("=== PIPELINE OK ===")

# ---------------- REPL / CLI ----------------
@dataclass
class REPL:
    name: str = "test"
    buf: List[str] = field(default_factory=list)

def banner() -> None:
    print("FSM Agent REPL (Ollama) — HW/Protocol/RTL generalized (C01..C12)", flush=True)
    print(f"Model GEN  : {MODEL_GEN}", flush=True)
    print(f"Model VER  : {MODEL_VER}", flush=True)
    print(f"Export dir : {EXPORT_DIR}", flush=True)
    print("Comandi:", flush=True)
    print("  .            => genera + export", flush=True)
    print("  :q           => esci", flush=True)
    print("  :name <n>    => cambia nome FSM", flush=True)
    print("  :show        => mostra buffer", flush=True)
    print("  :clear       => svuota buffer", flush=True)
    print("  :debug on|off=> abilita/disabilita DBG", flush=True)
    print("", flush=True)

def repl() -> int:
    global DEBUG
    st = REPL()
    banner()
    while True:
        try:
            line = input("> ")
        except (EOFError, KeyboardInterrupt):
            print("\n:q", flush=True)
            return 0

        cmd = line.strip()
        if cmd == ":q":
            return 0
        if cmd.startswith(":debug "):
            v = cmd[len(":debug "):].strip().lower()
            DEBUG = (v == "on")
            print(f"DEBUG={DEBUG}", flush=True)
            continue
        if cmd.startswith(":name "):
            st.name = cmd[len(":name "):].strip() or st.name
            print(f"FSM name: {st.name}", flush=True); continue
        if cmd == ":show":
            print("\n--- SPEC BUFFER ---", flush=True)
            print("\n".join(st.buf), flush=True)
            print("--- END ---\n", flush=True)
            continue
        if cmd == ":clear":
            st.buf.clear()
            print("Buffer svuotato.", flush=True)
            continue
        if cmd == ".":
            spec = "\n".join(st.buf).strip()
            if not spec:
                print("Spec vuota.", flush=True)
                continue
            try:
                run_pipeline(spec, st.name)
                print("[OK] Export completato.", flush=True)
            except Exception as e:
                print("[FATAL]", str(e), flush=True)
            continue

        st.buf.append(line)

def main() -> int:
    p = argparse.ArgumentParser(description="HW/Protocol/RTL FSM generator (Ollama) — C01..C12")
    p.add_argument("--name", default="test", help="FSM name (export basename)")
    p.add_argument("--spec", default=None, help="Spec string (if omitted, run REPL)")
    p.add_argument("--spec-file", default=None, help="Path to spec text file")
    p.add_argument("--export-dir", default=None, help="Override export directory")
    p.add_argument("--model-gen", default=None, help="Override generator model")
    p.add_argument("--model-ver", default=None, help="Override verifier model")
    p.add_argument("--ollama-url", default=None, help="Override ollama URL")
    p.add_argument("--debug", action="store_true", help="Enable debug logs")
    args = p.parse_args()

    global EXPORT_DIR, MODEL_GEN, MODEL_VER, OLLAMA_URL, DEBUG
    if args.export_dir:
        EXPORT_DIR = args.export_dir
    if args.model_gen:
        MODEL_GEN = args.model_gen
    if args.model_ver:
        MODEL_VER = args.model_ver
    if args.ollama_url:
        OLLAMA_URL = args.ollama_url
    DEBUG = bool(args.debug)

    try:
        if args.spec is None and args.spec_file is None:
            return repl()
        if args.spec_file:
            with open(args.spec_file, "r", encoding="utf-8") as f:
                spec = f.read()
        else:
            spec = args.spec or ""
        spec = spec.strip()
        if not spec:
            print("[FATAL] Empty spec.", flush=True)
            return 1
        run_pipeline(spec, args.name)
        print("[OK] Export completato.", flush=True)
        return 0
    except Exception as e:
        print("[FATAL] Unhandled:", str(e), flush=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())

