// Auto-generated by flexsoc.backend.design.ip.rtl.
module rv_timer_reg_top
  import rv_timer_reg_pkg::*;
(
 input logic clk_i,
 input logic rst_ni,
 input reg_req_t reg_req_i,
 output reg_rsp_t reg_rsp_o,
 output rv_timer_reg2hw_t reg2hw,
 input rv_timer_hw2reg_t hw2reg,
 input logic devmode_i
);

  rv_timer_reg_core u_reg_core (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .reg_req_i(reg_req_i),
    .reg_rsp_o(reg_rsp_o),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg),
    .devmode_i(devmode_i)
  );

endmodule
