from pathlib import Path

from flexsoc.backend.core import BackendContext
from flexsoc.backend.design.soc.soc import RtlSourceSet, SoCDevice, SoCPlan, SocFlow


def test_rtl_source_set_is_stable_and_deduplicated(tmp_path: Path) -> None:
    output = tmp_path / "rtl.f"
    sources = RtlSourceSet.from_entries(
        ("a.sv", "", "# comment", "b.sv", "a.sv", "+incdir+include")
    )

    assert sources.entries == ("a.sv", "b.sv", "+incdir+include")
    sources.write(output)
    assert output.read_text(encoding="utf-8").splitlines() == [
        "# Auto-generated by FlexSoC native source resolver.",
        "a.sv",
        "b.sv",
        "+incdir+include",
    ]


def test_soc_native_source_manifest_resolves_release_and_generated_rtl(tmp_path: Path) -> None:
    project = tmp_path / "project"
    context = BackendContext(
        project,
        tmp_path / "work",
        {
            "TOP": "test",
            "RUN_TOP": "test",
            "RUN_ID": "dev",
            "HOST": "ibex",
            "FABRIC": "tlul",
        },
    )
    context.paths.ensure()

    release = context.paths.run / "ips" / "uart"
    (release / "rtl" / "deps").mkdir(parents=True)
    (release / "rtl" / "deps" / "pkg.sv").write_text(
        "package pkg; endpackage\n", encoding="utf-8"
    )
    (release / "rtl" / "uart.sv").write_text(
        "module uart; endmodule\n", encoding="utf-8"
    )
    (release / "rtl" / "rtl_common.f").write_text(
        "rtl/deps/pkg.sv\n+incdir+rtl/deps\n",
        encoding="utf-8",
    )
    (release / "rtl" / "rtl_ip.f").write_text(
        "rtl/uart.sv\nrtl/uart.sv\n",
        encoding="utf-8",
    )

    autogen = context.paths.rtl / "autogen"
    autogen.mkdir(parents=True)
    (autogen / "tl_main_pkg.sv").write_text(
        "package tl_main_pkg; endpackage\n", encoding="utf-8"
    )
    (autogen / "xbar_main.sv").write_text(
        "module xbar_main; endmodule\n", encoding="utf-8"
    )
    (context.paths.rtl / "soc.sv").write_text(
        "module soc; endmodule\n", encoding="utf-8"
    )

    flow = SocFlow(context)
    plan = SoCPlan(
        host="ibex",
        fabric="tlul",
        devices=(
            SoCDevice("sram", 0x00100000, 0x00020000, True),
            SoCDevice("uart", 0x80000000, 0x1000, False),
        ),
    )
    output = flow.write_soc_rtl_filelist(plan)
    lines = output.read_text(encoding="utf-8").splitlines()

    assert lines[0] == "# Auto-generated by FlexSoC native source resolver."
    assert "ips/uart/rtl/deps/pkg.sv" in lines
    assert "+incdir+ips/uart/rtl/deps" in lines
    assert lines.count("ips/uart/rtl/uart.sv") == 1
    assert "rtl/autogen/tl_main_pkg.sv" in lines
    assert "rtl/autogen/xbar_main.sv" in lines
    assert lines[-1] == "rtl/soc.sv"


def test_soc_native_source_manifest_rejects_missing_release_entry(tmp_path: Path) -> None:
    project = tmp_path / "project"
    context = BackendContext(
        project,
        tmp_path / "work",
        {
            "TOP": "test",
            "RUN_TOP": "test",
            "RUN_ID": "dev",
            "HOST": "ibex",
            "FABRIC": "tlul",
        },
    )
    context.paths.ensure()

    release = context.paths.run / "ips" / "uart"
    (release / "rtl").mkdir(parents=True)
    (release / "rtl" / "rtl_common.f").write_text(
        "rtl/missing.sv\n", encoding="utf-8"
    )
    (release / "rtl" / "rtl_ip.f").write_text("", encoding="utf-8")

    flow = SocFlow(context)
    plan = SoCPlan(
        host="ibex",
        fabric="tlul",
        devices=(SoCDevice("sram", 0x00100000, 0x00020000, True),),
    )

    try:
        flow.resolve_soc_rtl_sources(plan)
    except FileNotFoundError as exc:
        assert "unresolved staged RTL entry" in str(exc)
    else:
        raise AssertionError("missing release source must be rejected")
