#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def _abs(p: str | Path) -> Path:
    return Path(p).expanduser().resolve()


def _gather_sv_v(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted([p for p in root.rglob("*") if p.suffix in {".sv", ".v"} and p.is_file()])


def _uniq(seq: list[Path]) -> list[Path]:
    out: list[Path] = []
    seen = set()
    for x in seq:
        if x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate rtl_list.f with absolute paths (includes dependencies: pkgs/prim/tlul/prim_opentitan)."
    )
    ap.add_argument("--top", required=True, help="Top name (used for info only)")
    ap.add_argument("--out", required=True, help="Output .f path")
    ap.add_argument("--ips-root", required=True, help="hw/ips root (repo path)")
    ap.add_argument("--rtldir", required=True, help="RTL output directory (workspace-rooted)")
    args = ap.parse_args()

    out = _abs(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    ips_root = _abs(args.ips_root)
    rtldir = _abs(args.rtldir)

    # Dependency roots (add/remove as your project evolves)
    dep_roots = [
        ips_root / "pkgs",
        ips_root / "prim",
        ips_root / "prim_opentitan",
        ips_root / "tlul",
    ]

    # Include dirs: used for `include "foo.sv"` and similar
    incdirs: list[Path] = [rtldir] + [d for d in dep_roots if d.exists()]
    incdirs = _uniq(incdirs)

    # Files to compile: packages first, then everything else
    dep_files: list[Path] = []
    for d in dep_roots:
        dep_files += _gather_sv_v(d)

    rtl_files = _gather_sv_v(rtldir)

    # Packages first (important for slang)
    pkgs = [p for p in dep_files + rtl_files if p.name.endswith("_pkg.sv")]
    others = [p for p in dep_files + rtl_files if not p.name.endswith("_pkg.sv")]

    files = _uniq(pkgs + others)

    # Write filelist
    lines: list[str] = []
    lines.append("# Auto-generated by flow/scripts/gen_filelist.py")
    for d in incdirs:
        lines.append(f"+incdir+{d}")
    for f in files:
        lines.append(str(f))

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
