#!/usr/bin/env python3
r"""
\file help_ip.py
\brief Print the project's HELP banner.
\details
  Minimal script that prints a help message for IP development:
    - configuration and setup,
    - HJSON/doc/reg generation,
    - RTL + lint + sim,
    - synthesis, STA, power, and regressions.

  Coloring is automatic when stdout is a TTY. Set NO_COLOR to disable.
"""

import sys
from common import colorize

# --- internals kept tiny on purpose -----------------------------------------

HELP = """
*************************************************************

****************            HELP             ****************

*************************************************************

##################     IP DEVELOPMENT     ###################

- CONFIG
  • Define the parameters under config.mk
  • To start, set the TOP name

- SETUP
  • Run "make setup" to set up the folder structure

- HJSON
  • Run "make hjson" to initialize the configuration file
    for CSR registers and documentation under data/
  • Update it for your needs

- DOC
  • Run "make doc" to generate the documentation based on
    the configuration file

- REG
  • Run "make reg" to generate CSR registers with a TLUL interface
    based on the configuration file

- RTL SKELETON
  • Run "make rtl_stub" to generate the RTL core and RTL wrapper of the IP

- RTL CODING
  • Write RTL in SystemVerilog under rtl/

- SV2V
  • Run "make sv2v" to generate a single Verilog file
    from all files under rtl/
  • Check for errors

- LINTING
  • Run "make lint" to perform linting
  • Check for errors

- TESTBENCH SETUP
  • Run "make setup_tb" to set up the Verilog testbench
    The Verilog module generated by 'sv2v' will be included
    in the testbench

- COMPILE
  • Run "make compile" to compile the testbench and the top
  • Check for errors

- SIMULATION RUN
  • Run "make sim" to run the Verilog testbench

- SIMULATION VIEW
  • Run "make view" to view the simulation waveforms

- TESTBENCH UPDATE
  • It's time to update the testbench to trigger and
    check what you want

- VIEW PRE-SYN with YOSYS
  • Run "make view_presyn" to view the graph that
    describes the design you wrote

- SYNTHESIS
  • Run "make syn" to check if the design can be
    synthesized correctly

- SDF
  • Run "make sdf" to generate SDF files

- STATIC TIMING ANALYSIS
  • Run "make sta" to perform basic static timing
    analysis with OpenSTA

- PATH VIEW
  • Run "make path view" to generate the path netlist SVG
    files from STA output to inspect them

- POWER ANALYSIS
  • Run "make power" to perform basic static power
    analysis and VCD-based power analysis with OpenSTA

- SYNTHESIS SIMULATION RUN
  • Run "make sim_syn" to run the Verilog testbench

- SYNTHESIS SIMULATION VIEW
  • Run "make view_syn" to view the simulation waveforms

- REGRESSION
  • Run "make regression" to run testbenches under tb/regression

- FUSESOC
  • Run "make fsoc_init" to initialize the .core file for your IP.

- DRIVER
  • Run "make driver TOP={top_ip} MOD_ADD=0x{ip_base_addr_in_the_soc}"
  to generate .h and .c files for the IP

- SAVE IP
  • Run "make ip_save" to save the IP into ips folder

"""


if __name__ == "__main__":
    sys.stdout.write(colorize(HELP))
