#!/usr/bin/env python3
# Copyright 2025 Enea Dimroci
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
from pathlib import Path
from textwrap import dedent


def _auto_repo_root() -> Path:
    # flow/scripts/setup_pnr.py -> repo root is ../../
    return Path(__file__).resolve().parents[2]


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate OpenROAD-flow-scripts config.mk. "
                    "Safe by default: does NOT overwrite existing config.mk."
    )
    p.add_argument("top", help="Top module name (DESIGN_NAME / DESIGN_NICKNAME)")
    p.add_argument("--syn_strategy", default="area", help="Synthesis strategy : none / area / delay")
    p.add_argument("--clk_period", type=int, default=50, help="Clock period in ns")
    p.add_argument("--platform", default="sky130hd", help="Target platform (default: sky130hd)")
    p.add_argument("--filelist", default="rtl/rtl_list.f",
                   help="Path to rtl_list.f (absolute recommended).")
    p.add_argument("--outdir", default="ors", help="Output directory (default: ors)")
    p.add_argument("--repo-root", default=None,
                   help="Repository root path (default: auto-detect from this script location)")
    p.add_argument("--overwrite", action="store_true",
                   help="Overwrite existing config.mk if present")
    args = p.parse_args()

    repo_root = Path(args.repo_root).resolve() if args.repo_root else _auto_repo_root()
    outdir = Path(args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    out = outdir / "config.mk"
    if out.exists() and not args.overwrite:
        # Don't touch it: user may have custom config.mk
        return 0

    filelist = Path(args.filelist)
    # Keep as absolute if user provided absolute; else resolve relative to cwd
    filelist_abs = filelist.resolve()

    # Absolute include dir so ORFS is independent from cwd
    inc_pkgs = (repo_root / "hw" / "ips" / "pkgs").resolve()

    mk = f"""\
    # =========================================
    # OpenROAD-flow-scripts — single-file config.mk
    # Generated by flexsoc setup_pnr.py (cwd-independent)
    # Safe-by-default: will not overwrite unless --overwrite is used.
    # =========================================

    ##### [Repo anchor]
    REPO_ROOT := {repo_root.as_posix()}

    ##### [Design identity]
    export DESIGN_NICKNAME = {args.top}
    export DESIGN_NAME     = {args.top}
    export PLATFORM        = {args.platform}

    ##### [Sources]
    # Filelist (.f) with +incdir+ and files (absolute path)
    FILELIST := {filelist_abs.as_posix()}

    # Global include dirs (absolute, independent from build cwd)
    export VERILOG_INCLUDE_DIRS := {inc_pkgs.as_posix()}

    # Source files: ignore blanks, comments (#) and +incdir+ lines
    export VERILOG_FILES := $(shell awk '!/^\\s*($$|#)/ && $$0 !~ /^\\+incdir\\+/' $(FILELIST))

    ##### [Constraints / Frontend]
    export SYNTH_HDL_FRONTEND = slang
    # SDC is generated next to this config.mk (in outdir)
    export SDC_FILE           = {outdir}/{args.top}.sdc

    ##### [User knobs (override from Make/CLI)]
    STRATEGY ?= {args.syn_strategy}
    TARGET_CLOCK_PS ?= {args.clk_period*1000}

    export CORE_UTILIZATION ?= 50
    export PLACE_DENSITY_LB_ADDON = 0.20
    export TNS_END_PERCENT = 100

    ##### [General reporting / quality-of-life]
    export DETAILED_METRICS := 1
    export REPORT_CLOCK_SKEW := 1
    export YOSYS_FLAGS := -v 3
    export GUI_TIMING := 1

    # -------------------------------------------------
    # Common defaults
    # -------------------------------------------------
    export SETUP_SLACK_MARGIN := 0
    export HOLD_SLACK_MARGIN  := 0

    export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT := 0
    export CELL_PAD_IN_SITES_DETAIL_PLACEMENT := 0

    export DETAILED_ROUTE_END_ITERATION := 64
    export USE_FILL := 0

    export GPL_TIMING_DRIVEN      := 1
    export GPL_ROUTABILITY_DRIVEN := 1

    # -------------------------------------------------
    # Strategy blocks
    # -------------------------------------------------

    ifeq ($(STRATEGY),none)
      # vanilla
    endif

    ifeq ($(STRATEGY),area)
      export ABC_AREA := 1
      export ABC_CLOCK_PERIOD_IN_PS := $(TARGET_CLOCK_PS)
      export PLACE_DENSITY := 0.58
    endif

    ifeq ($(STRATEGY),delay)
      export ABC_AREA := 0
      export ABC_CLOCK_PERIOD_IN_PS := $(TARGET_CLOCK_PS)
      export PLACE_DENSITY := 0.55
    endif
    """

    out.write_text(dedent(mk), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
