// Auto-generated by flexsoc.backend.design.rtl.
module cordic_reg_top
  import cordic_reg_pkg::*;
(
 input logic clk_i,
 input logic rst_ni,
 input tlul_pkg::tl_h2d_t tl_i,
 output tlul_pkg::tl_d2h_t tl_o,
 output cordic_reg2hw_t reg2hw,
 input cordic_hw2reg_t hw2reg,
 input logic devmode_i
);

  logic flexsoc_tlul_re;
  logic flexsoc_tlul_we;
  logic [cordic_reg_pkg::AW-1:0] flexsoc_tlul_addr;
  logic [cordic_reg_pkg::DW-1:0] flexsoc_tlul_wdata;
  logic [cordic_reg_pkg::DBW-1:0] flexsoc_tlul_be;
  cordic_reg_pkg::reg_req_t flexsoc_tlul_reg_req;
  cordic_reg_pkg::reg_rsp_t flexsoc_tlul_reg_rsp;

  assign flexsoc_tlul_reg_req = '{
    valid: flexsoc_tlul_re | flexsoc_tlul_we,
    write: flexsoc_tlul_we,
    addr:  flexsoc_tlul_addr,
    wdata: flexsoc_tlul_wdata,
    wstrb: flexsoc_tlul_be
  };

  tlul_adapter_reg #( 
    .RegAw         (cordic_reg_pkg::AW),
    .RegDw         (cordic_reg_pkg::DW),
    .AccessLatency (0)
  ) u_flexsoc_tlul_to_reg (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_i         (tl_i),
    .tl_o         (tl_o),
    .en_ifetch_i  (prim_mubi_pkg::MuBi4False),
    .intg_error_o (),
    .re_o         (flexsoc_tlul_re),
    .we_o         (flexsoc_tlul_we),
    .addr_o       (flexsoc_tlul_addr),
    .wdata_o      (flexsoc_tlul_wdata),
    .be_o         (flexsoc_tlul_be),
    .busy_i       (~flexsoc_tlul_reg_rsp.ready),
    .rdata_i      (flexsoc_tlul_reg_rsp.rdata),
    .error_i      (flexsoc_tlul_reg_rsp.error)
  );

  cordic_reg_core u_reg_core (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .reg_req_i(flexsoc_tlul_reg_req),
    .reg_rsp_o(flexsoc_tlul_reg_rsp),
    .reg2hw(reg2hw),
    .hw2reg(hw2reg),
    .devmode_i(devmode_i)
  );

endmodule
