// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package gpio_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  // Number of registers for every interface
  parameter int NumRegs = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
      logic        qe;
    } gpio_oe;
    struct packed {
      logic [3:0]  q;
      logic        qe;
    } gpio_o;
  } gpio_reg2hw_direct_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
    } en_input_filter;
    struct packed {
      logic [3:0]  q;
    } en_lvllow;
    struct packed {
      logic [3:0]  q;
    } en_lvlhigh;
    struct packed {
      logic [3:0]  q;
    } en_falling;
    struct packed {
      logic [3:0]  q;
    } en_rising;
  } gpio_reg2hw_intr_ctrl_reg_t;

  typedef struct packed {
    logic [3:0]  d;
    logic        de;
  } gpio_hw2reg_data_in_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } gpio_oe;
    struct packed {
      logic [3:0]  d;
    } gpio_o;
  } gpio_hw2reg_direct_reg_t;

  // Register -> HW type
  typedef struct packed {
    gpio_reg2hw_direct_reg_t direct; // [29:20]
    gpio_reg2hw_intr_ctrl_reg_t intr_ctrl; // [19:0]
  } gpio_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    gpio_hw2reg_data_in_reg_t data_in; // [12:8]
    gpio_hw2reg_direct_reg_t direct; // [7:0]
  } gpio_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] GPIO_DATA_IN_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] GPIO_DIRECT_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] GPIO_INTR_CTRL_OFFSET = 4'h 8;

  // Reset values for hwext registers and their fields
  parameter logic [7:0] GPIO_DIRECT_RESVAL = 8'h 0;

  // Register index
  typedef enum int {
    GPIO_DATA_IN,
    GPIO_DIRECT,
    GPIO_INTR_CTRL
  } gpio_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] GPIO_PERMIT [3] = '{
    4'b 0001, // index[0] GPIO_DATA_IN
    4'b 0001, // index[1] GPIO_DIRECT
    4'b 0111  // index[2] GPIO_INTR_CTRL
  };

  parameter int AW = BlockAw;
  parameter int DW = 32;
  parameter int DBW = DW / 8;

  parameter type reg_req_t = struct packed {
    logic           valid;
    logic           write;
    logic [AW-1:0]  addr;
    logic [DW-1:0]  wdata;
    logic [DBW-1:0] wstrb;
  };

  parameter type reg_rsp_t = struct packed {
    logic [DW-1:0] rdata;
    logic          error;
    logic          ready;
  };


  // FlexSoC external AXI4-Lite transport types.
  typedef struct packed {
    logic [AW-1:0] addr;
    logic [2:0] prot;
  } axi_lite_aw_t;

  typedef struct packed {
    logic [DW-1:0] data;
    logic [DBW-1:0] strb;
  } axi_lite_w_t;

  typedef struct packed { logic [1:0] resp; } axi_lite_b_t;

  typedef struct packed {
    logic [AW-1:0] addr;
    logic [2:0] prot;
  } axi_lite_ar_t;

  typedef struct packed {
    logic [DW-1:0] data;
    logic [1:0] resp;
  } axi_lite_r_t;

  typedef struct packed {
    axi_lite_aw_t aw;
    logic aw_valid;
    axi_lite_w_t w;
    logic w_valid;
    logic b_ready;
    axi_lite_ar_t ar;
    logic ar_valid;
    logic r_ready;
  } axi_lite_req_t;

  typedef struct packed {
    logic aw_ready;
    logic w_ready;
    axi_lite_b_t b;
    logic b_valid;
    logic ar_ready;
    axi_lite_r_t r;
    logic r_valid;
  } axi_lite_rsp_t;

endpackage
