/* Generated by Yosys 0.58 (git sha1 157aabb58, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "rtl/gpio.sv:9.8" *)
module gpio(clk_i, rst_ni, tl_i, tl_o, intr_gpio_o, cio_gpio_i, cio_gpio_o, cio_gpio_en_o);
  (* hdlname = "clk_i" *)
  (* src = "rtl/gpio.sv:15.9" *)
  input clk_i;
  wire clk_i;
  (* hdlname = "rst_ni" *)
  (* src = "rtl/gpio.sv:16.9" *)
  input rst_ni;
  wire rst_ni;
  (* hdlname = "tl_i" *)
  (* src = "rtl/gpio.sv:19.29" *)
  input [108:0] tl_i;
  wire [108:0] tl_i;
  (* hdlname = "tl_o" *)
  (* src = "rtl/gpio.sv:20.29" *)
  output [65:0] tl_o;
  wire [65:0] tl_o;
  (* hdlname = "intr_gpio_o" *)
  (* src = "rtl/gpio.sv:23.22" *)
  output [1:0] intr_gpio_o;
  wire [1:0] intr_gpio_o;
  (* hdlname = "cio_gpio_i" *)
  (* src = "rtl/gpio.sv:26.22" *)
  input [1:0] cio_gpio_i;
  wire [1:0] cio_gpio_i;
  (* hdlname = "cio_gpio_o" *)
  (* src = "rtl/gpio.sv:27.22" *)
  output [1:0] cio_gpio_o;
  wire [1:0] cio_gpio_o;
  (* hdlname = "cio_gpio_en_o" *)
  (* src = "rtl/gpio.sv:28.22" *)
  output [1:0] cio_gpio_en_o;
  wire [1:0] cio_gpio_en_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  (* hdlname = "data_in_d" *)
  (* src = "rtl/gpio.sv:40.15" *)
  wire [1:0] data_in_d;
  (* hdlname = "data_in_q" *)
  (* src = "rtl/gpio.sv:84.15" *)
  wire [1:0] data_in_q;
  (* hdlname = "gen_filter[0] u_filter diff_ctr_d" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:29.36" *)
  wire [1:0] \gen_filter[0].u_filter.diff_ctr_d ;
  (* hdlname = "gen_filter[0] u_filter diff_ctr_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:29.24" *)
  wire [1:0] \gen_filter[0].u_filter.diff_ctr_q ;
  (* hdlname = "gen_filter[0] u_filter enable_i" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:23.24" *)
  wire \gen_filter[0].u_filter.enable_i ;
  (* hdlname = "gen_filter[0] u_filter filter_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:30.9" *)
  wire \gen_filter[0].u_filter.filter_q ;
  (* hdlname = "gen_filter[0] u_filter filter_synced" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:32.9" *)
  wire \gen_filter[0].u_filter.filter_synced ;
  (* hdlname = "gen_filter[0] u_filter gen_async prim_flop_2sync intq" *)
  (* src = "ips/prim_opentitan/prim_flop_2sync.sv:13.21" *)
  wire \gen_filter[0].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "gen_filter[0] u_filter stored_value_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:30.19" *)
  wire \gen_filter[0].u_filter.stored_value_q ;
  (* hdlname = "gen_filter[1] u_filter diff_ctr_d" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:29.36" *)
  wire [1:0] \gen_filter[1].u_filter.diff_ctr_d ;
  (* hdlname = "gen_filter[1] u_filter diff_ctr_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:29.24" *)
  wire [1:0] \gen_filter[1].u_filter.diff_ctr_q ;
  (* hdlname = "gen_filter[1] u_filter enable_i" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:23.24" *)
  wire \gen_filter[1].u_filter.enable_i ;
  (* hdlname = "gen_filter[1] u_filter filter_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:30.9" *)
  wire \gen_filter[1].u_filter.filter_q ;
  (* hdlname = "gen_filter[1] u_filter filter_synced" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:32.9" *)
  wire \gen_filter[1].u_filter.filter_synced ;
  (* hdlname = "gen_filter[1] u_filter gen_async prim_flop_2sync intq" *)
  (* src = "ips/prim_opentitan/prim_flop_2sync.sv:13.21" *)
  wire \gen_filter[1].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "gen_filter[1] u_filter stored_value_q" *)
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:30.19" *)
  wire \gen_filter[1].u_filter.stored_value_q ;
  (* hdlname = "reg2hw" *)
  (* src = "rtl/gpio.sv:33.17" *)
  (* unused_bits = "14 17" *)
  wire [19:0] reg2hw;
  (* hdlname = "u_reg data_in_qs" *)
  (* src = "rtl/gpio_reg_top.sv:94.15" *)
  wire [1:0] \u_reg.data_in_qs ;
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(tl_i[24]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(tl_o[65]),
    .Y(tl_o[0])
  );
  sky130_fd_sc_hd__nand2_1 _147_ (
    .A(tl_o[0]),
    .B(tl_i[108]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(tl_i[107]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(tl_i[106]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand3_1 _151_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _152_ (
    .A(tl_i[60]),
    .B(tl_i[61]),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(tl_i[62]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _154_ (
    .A(tl_i[63]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand3_1 _155_ (
    .A(_050_),
    .B(tl_i[56]),
    .C(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(_053_),
    .B(cio_gpio_o[0]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _157_ (
    .A1(_044_),
    .A2(_053_),
    .B1(_054_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _158_ (
    .A(tl_i[25]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _159_ (
    .A(_053_),
    .B(cio_gpio_o[1]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _160_ (
    .A1(_055_),
    .A2(_053_),
    .B1(_056_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(\gen_filter[0].u_filter.diff_ctr_q [1]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor3_1 _162_ (
    .A(\gen_filter[0].u_filter.filter_synced ),
    .B(\gen_filter[0].u_filter.filter_q ),
    .C(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(\gen_filter[0].u_filter.filter_synced ),
    .B(\gen_filter[0].u_filter.filter_q ),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(\gen_filter[0].u_filter.stored_value_q ),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(_058_),
    .B(_061_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_045_),
    .B(tl_o[62]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o41ai_1 _168_ (
    .A1(tl_i[105]),
    .A2(_047_),
    .A3(tl_i[106]),
    .A4(_045_),
    .B1(_062_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _169_ (
    .A(tl_i[26]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(_053_),
    .B(cio_gpio_en_o[0]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _171_ (
    .A1(_063_),
    .A2(_053_),
    .B1(_064_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _172_ (
    .A(tl_i[27]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_053_),
    .B(cio_gpio_en_o[1]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _174_ (
    .A1(_065_),
    .A2(_053_),
    .B1(_066_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(tl_i[63]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o31ai_1 _176_ (
    .A1(tl_i[62]),
    .A2(tl_i[57]),
    .A3(_067_),
    .B1(tl_i[56]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor3_1 _177_ (
    .A(tl_i[60]),
    .B(tl_i[61]),
    .C(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_045_),
    .B(tl_o[1]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _179_ (
    .A1(_049_),
    .A2(_069_),
    .B1(_070_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(tl_i[62]),
    .B(_067_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a22oi_1 _181_ (
    .A1(_052_),
    .A2(cio_gpio_o[0]),
    .B1(reg2hw[4]),
    .B2(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(tl_i[63]),
    .B(tl_i[62]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(_067_),
    .B(_051_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a22oi_1 _184_ (
    .A1(\u_reg.data_in_qs [0]),
    .A2(_073_),
    .B1(_074_),
    .B2(\gen_filter[0].u_filter.enable_i ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _185_ (
    .A1(_047_),
    .A2(_048_),
    .B1(_045_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(tl_o[16]),
    .B(_046_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a31oi_1 _187_ (
    .A1(_072_),
    .A2(_075_),
    .A3(_076_),
    .B1(_077_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a22oi_1 _188_ (
    .A1(\u_reg.data_in_qs [1]),
    .A2(_073_),
    .B1(_052_),
    .B2(cio_gpio_o[1]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(_074_),
    .B(\gen_filter[1].u_filter.enable_i ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_071_),
    .B(reg2hw[5]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(tl_o[17]),
    .B(_046_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a41oi_1 _192_ (
    .A1(_078_),
    .A2(_076_),
    .A3(_079_),
    .A4(_080_),
    .B1(_081_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a22oi_1 _193_ (
    .A1(_052_),
    .A2(cio_gpio_en_o[0]),
    .B1(_074_),
    .B2(reg2hw[2]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_071_),
    .B(reg2hw[6]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(tl_o[18]),
    .B(_046_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a31oi_1 _196_ (
    .A1(_082_),
    .A2(_076_),
    .A3(_083_),
    .B1(_084_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a22oi_1 _197_ (
    .A1(_052_),
    .A2(cio_gpio_en_o[1]),
    .B1(reg2hw[7]),
    .B2(_071_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(_074_),
    .B(reg2hw[3]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(tl_o[19]),
    .B(_046_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a31oi_1 _200_ (
    .A1(_085_),
    .A2(_076_),
    .A3(_086_),
    .B1(_087_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_071_),
    .B(reg2hw[8]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(tl_o[20]),
    .B(_046_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _203_ (
    .A1(_076_),
    .A2(_088_),
    .B1(_089_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(_071_),
    .B(reg2hw[9]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(tl_o[21]),
    .B(_046_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _206_ (
    .A1(_076_),
    .A2(_090_),
    .B1(_091_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(_071_),
    .B(reg2hw[10]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(tl_o[22]),
    .B(_046_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a21oi_1 _209_ (
    .A1(_076_),
    .A2(_092_),
    .B1(_093_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(_071_),
    .B(reg2hw[11]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(tl_o[23]),
    .B(_046_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _212_ (
    .A1(_076_),
    .A2(_094_),
    .B1(_095_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(_071_),
    .B(reg2hw[12]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _214_ (
    .A(tl_o[24]),
    .B(_046_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _215_ (
    .A1(_076_),
    .A2(_096_),
    .B1(_097_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(_071_),
    .B(reg2hw[13]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(tl_o[25]),
    .B(_046_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(_076_),
    .A2(_098_),
    .B1(_099_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(_045_),
    .B(tl_o[47]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(_049_),
    .B(_100_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(_046_),
    .B(tl_i[92]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(_045_),
    .B(tl_o[49]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_101_),
    .B(_102_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_046_),
    .B(tl_i[93]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(_045_),
    .B(tl_o[50]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(_103_),
    .B(_104_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_046_),
    .B(tl_i[94]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(_045_),
    .B(tl_o[51]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(_105_),
    .B(_106_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_046_),
    .B(tl_i[95]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(_045_),
    .B(tl_o[52]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_107_),
    .B(_108_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_046_),
    .B(tl_i[96]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_045_),
    .B(tl_o[53]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_109_),
    .B(_110_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_046_),
    .B(tl_i[97]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_045_),
    .B(tl_o[54]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_111_),
    .B(_112_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_046_),
    .B(tl_i[98]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(_045_),
    .B(tl_o[55]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(_113_),
    .B(_114_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_046_),
    .B(tl_i[99]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_045_),
    .B(tl_o[56]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_115_),
    .B(_116_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_046_),
    .B(tl_i[100]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_045_),
    .B(tl_o[57]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_117_),
    .B(_118_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_046_),
    .B(tl_i[101]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(_045_),
    .B(tl_o[58]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_119_),
    .B(_120_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _251_ (
    .A1(tl_o[0]),
    .A2(tl_i[0]),
    .B1(_045_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(_050_),
    .B(_071_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(_068_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__mux2_2 _254_ (
    .A0(reg2hw[4]),
    .A1(tl_i[24]),
    .S(_122_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_2 _255_ (
    .A0(reg2hw[5]),
    .A1(tl_i[25]),
    .S(_122_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_2 _256_ (
    .A0(reg2hw[10]),
    .A1(tl_i[30]),
    .S(_122_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_2 _257_ (
    .A0(reg2hw[11]),
    .A1(tl_i[31]),
    .S(_122_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand3_1 _258_ (
    .A(_050_),
    .B(tl_i[56]),
    .C(_074_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_123_),
    .B(\gen_filter[0].u_filter.enable_i ),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _260_ (
    .A1(_044_),
    .A2(_123_),
    .B1(_124_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_123_),
    .B(\gen_filter[1].u_filter.enable_i ),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _262_ (
    .A1(_055_),
    .A2(_123_),
    .B1(_125_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_123_),
    .B(reg2hw[2]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_0 _264_ (
    .A1(_063_),
    .A2(_123_),
    .B1(_126_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_123_),
    .B(reg2hw[3]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(_065_),
    .A2(_123_),
    .B1(_127_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__mux2_2 _267_ (
    .A0(reg2hw[12]),
    .A1(tl_i[32]),
    .S(_122_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _268_ (
    .A0(reg2hw[13]),
    .A1(tl_i[33]),
    .S(_122_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_2 _269_ (
    .A0(reg2hw[8]),
    .A1(tl_i[28]),
    .S(_122_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_2 _270_ (
    .A0(reg2hw[9]),
    .A1(tl_i[29]),
    .S(_122_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(_122_),
    .B(tl_i[26]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _272_ (
    .A1(_068_),
    .A2(_121_),
    .B1(reg2hw[6]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_128_),
    .B(_129_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_122_),
    .B(tl_i[27]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_068_),
    .A2(_121_),
    .B1(reg2hw[7]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(_130_),
    .B(_131_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _277_ (
    .A(\gen_filter[1].u_filter.diff_ctr_q [1]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3_1 _278_ (
    .A(\gen_filter[1].u_filter.filter_synced ),
    .B(\gen_filter[1].u_filter.filter_q ),
    .C(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xor2_1 _279_ (
    .A(\gen_filter[1].u_filter.filter_synced ),
    .B(\gen_filter[1].u_filter.filter_q ),
    .X(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _280_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(\gen_filter[1].u_filter.stored_value_q ),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(_133_),
    .B(_136_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _283_ (
    .A1(\gen_filter[1].u_filter.diff_ctr_q [0]),
    .A2(_132_),
    .B1(_134_),
    .Y(\gen_filter[1].u_filter.diff_ctr_d [0])
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(\gen_filter[1].u_filter.diff_ctr_q [0]),
    .B(\gen_filter[1].u_filter.diff_ctr_q [1]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_137_),
    .B(_134_),
    .Y(\gen_filter[1].u_filter.diff_ctr_d [1])
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(_057_),
    .A2(\gen_filter[0].u_filter.diff_ctr_q [0]),
    .B1(_059_),
    .Y(\gen_filter[0].u_filter.diff_ctr_d [0])
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(\gen_filter[0].u_filter.diff_ctr_q [1]),
    .B(\gen_filter[0].u_filter.diff_ctr_q [0]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(_138_),
    .B(_059_),
    .Y(\gen_filter[0].u_filter.diff_ctr_d [1])
  );
  sky130_fd_sc_hd__mux2_2 _289_ (
    .A0(\gen_filter[0].u_filter.filter_synced ),
    .A1(\gen_filter[0].u_filter.stored_value_q ),
    .S(\gen_filter[0].u_filter.enable_i ),
    .X(data_in_d[0])
  );
  sky130_fd_sc_hd__mux2_2 _290_ (
    .A0(\gen_filter[1].u_filter.filter_synced ),
    .A1(\gen_filter[1].u_filter.stored_value_q ),
    .S(\gen_filter[1].u_filter.enable_i ),
    .X(data_in_d[1])
  );
  sky130_fd_sc_hd__clkinv_1 _291_ (
    .A(data_in_q[0]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(_139_),
    .A2(reg2hw[4]),
    .B1(reg2hw[8]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a211oi_1 _293_ (
    .A1(reg2hw[6]),
    .A2(data_in_q[0]),
    .B1(reg2hw[10]),
    .C1(data_in_d[0]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(data_in_d[0]),
    .A2(_140_),
    .B1(_141_),
    .Y(intr_gpio_o[0])
  );
  sky130_fd_sc_hd__clkinv_1 _295_ (
    .A(data_in_q[1]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _296_ (
    .A1(_142_),
    .A2(reg2hw[5]),
    .B1(reg2hw[9]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a211oi_1 _297_ (
    .A1(reg2hw[7]),
    .A2(data_in_q[1]),
    .B1(reg2hw[11]),
    .C1(data_in_d[1]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(data_in_d[1]),
    .A2(_143_),
    .B1(_144_),
    .Y(intr_gpio_o[1])
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _299_ (
    .CLK(clk_i),
    .D(cio_gpio_i[0]),
    .Q(\gen_filter[0].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _300_ (
    .CLK(clk_i),
    .D(\gen_filter[0].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\gen_filter[0].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sky130_fd_sc_hd__dfrtp_1 _301_ (
    .CLK(clk_i),
    .D(\gen_filter[0].u_filter.filter_synced ),
    .Q(\gen_filter[0].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/gpio.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _302_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(cio_gpio_o[0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/gpio.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _303_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(cio_gpio_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _304_ (
    .CLK(clk_i),
    .D(\gen_filter[0].u_filter.diff_ctr_d [0]),
    .Q(\gen_filter[0].u_filter.diff_ctr_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _305_ (
    .CLK(clk_i),
    .D(\gen_filter[0].u_filter.diff_ctr_d [1]),
    .Q(\gen_filter[0].u_filter.diff_ctr_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _306_ (
    .CLK(clk_i),
    .D(cio_gpio_i[1]),
    .Q(\gen_filter[1].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _307_ (
    .CLK(clk_i),
    .D(\gen_filter[1].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\gen_filter[1].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sky130_fd_sc_hd__dfrtp_1 _308_ (
    .CLK(clk_i),
    .D(\gen_filter[1].u_filter.filter_synced ),
    .Q(\gen_filter[1].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sky130_fd_sc_hd__dfrtp_1 _309_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(\gen_filter[0].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _310_ (
    .CLK(clk_i),
    .D(\gen_filter[1].u_filter.diff_ctr_d [0]),
    .Q(\gen_filter[1].u_filter.diff_ctr_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sky130_fd_sc_hd__dfrtp_1 _311_ (
    .CLK(clk_i),
    .D(\gen_filter[1].u_filter.diff_ctr_d [1]),
    .Q(\gen_filter[1].u_filter.diff_ctr_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _312_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(tl_o[62]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/gpio.sv:76.3" *)
  sky130_fd_sc_hd__dfrtp_1 _313_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(cio_gpio_en_o[0]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/gpio.sv:76.3" *)
  sky130_fd_sc_hd__dfrtp_1 _314_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(cio_gpio_en_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "rtl/gpio.sv:85.3" *)
  sky130_fd_sc_hd__dfxtp_1 _315_ (
    .CLK(clk_i),
    .D(data_in_d[0]),
    .Q(data_in_q[0])
  );
  (* src = "rtl/gpio.sv:85.3" *)
  sky130_fd_sc_hd__dfxtp_1 _316_ (
    .CLK(clk_i),
    .D(data_in_d[1]),
    .Q(data_in_q[1])
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _317_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(tl_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _318_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(tl_o[16]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _319_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(tl_o[17]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _320_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(tl_o[18]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _321_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(tl_o[19]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _322_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(tl_o[20]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _323_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(tl_o[21]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _324_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(tl_o[22]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _325_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(tl_o[23]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _326_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(tl_o[24]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _327_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(tl_o[25]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _328_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(tl_o[47]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _329_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(tl_o[49]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _330_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(tl_o[50]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _331_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(tl_o[51]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _332_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(tl_o[52]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _333_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(tl_o[53]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _334_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(tl_o[54]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _335_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(tl_o[55]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _336_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(tl_o[56]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _337_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(tl_o[57]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _338_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(tl_o[58]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/tlul/tlul_adapter_reg.sv:94.3" *)
  sky130_fd_sc_hd__dfrtp_1 _339_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(tl_o[65]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _340_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(reg2hw[4]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _341_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(reg2hw[5]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _342_ (
    .CLK(clk_i),
    .D(data_in_d[0]),
    .Q(\u_reg.data_in_qs [0]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _343_ (
    .CLK(clk_i),
    .D(data_in_d[1]),
    .Q(\u_reg.data_in_qs [1]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _344_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(reg2hw[10]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _345_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(reg2hw[11]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _346_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(\gen_filter[0].u_filter.enable_i ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _347_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(\gen_filter[1].u_filter.enable_i ),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _348_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(reg2hw[2]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _349_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(reg2hw[3]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _350_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(reg2hw[12]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(reg2hw[13]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(reg2hw[8]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(reg2hw[9]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(reg2hw[6]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _355_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(reg2hw[7]),
    .RESET_B(rst_ni)
  );
  (* src = "ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(\gen_filter[1].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  assign { reg2hw[19:18], reg2hw[16:14], reg2hw[1:0] } = { tl_i[27:24], reg2hw[17], \gen_filter[1].u_filter.enable_i , \gen_filter[0].u_filter.enable_i  };
  assign { tl_o[64:63], tl_o[61:59], tl_o[48], tl_o[46:26], tl_o[15:2] } = { 6'h00, tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], 14'h0000 };
endmodule
