// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtop_cordic_lut_pkg;
class Vtop_cordic_reg_pkg;
class Vtop_prim_alert_pkg;
class Vtop_prim_mubi_pkg;
class Vtop_prim_secded_pkg;
class Vtop_tlul_pkg;
class Vtop_top_pkg;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_top_pkg* __PVT__top_pkg;
    Vtop_prim_secded_pkg* __PVT__prim_secded_pkg;
    Vtop_prim_alert_pkg* __PVT__prim_alert_pkg;
    Vtop_cordic_lut_pkg* __PVT__cordic_lut_pkg;
    Vtop_cordic_reg_pkg* __PVT__cordic_reg_pkg;
    Vtop_prim_mubi_pkg* __PVT__prim_mubi_pkg;
    Vtop_tlul_pkg* __PVT__tlul_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ cordic_tb__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__tl_i_a_valid;
        CData/*2:0*/ cordic_tb__DOT__tl_i_a_opcode;
        CData/*2:0*/ cordic_tb__DOT__tl_i_a_param;
        CData/*1:0*/ cordic_tb__DOT__tl_i_a_size;
        CData/*7:0*/ cordic_tb__DOT__tl_i_a_source;
        CData/*3:0*/ cordic_tb__DOT__tl_i_a_mask;
        CData/*0:0*/ cordic_tb__DOT__tl_i_d_ready;
        CData/*0:0*/ cordic_tb__DOT__tl_o_d_valid;
        CData/*2:0*/ cordic_tb__DOT__tl_o_d_opcode;
        CData/*0:0*/ cordic_tb__DOT__tl_o_d_error;
        CData/*0:0*/ cordic_tb__DOT__tl_o_a_ready;
        CData/*6:0*/ cordic_tb__DOT__cmd_intg_calc;
        CData/*6:0*/ cordic_tb__DOT__data_intg_calc;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__devmode_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_re;
        CData/*5:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_addr;
        CData/*3:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_be;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_error;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__addrmiss;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__wr_err;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_busy;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_start_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_start_wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_mode_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_mode_wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_soft_rst_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_soft_rst_wd;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_rsvd_qs;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_rsvd_wd;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_n_iter_qs;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_n_iter_wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__status_re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__status_busy_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__status_valid_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__status_error_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__x_in_we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__y_in_we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__z_in_we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__x_out_re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__y_out_re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__z_out_re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__cfg_re;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__cfg_data_width_qs;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__cfg_frac_width_qs;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__cfg_max_iter_qs;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__cfg_rsvd_qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__shadow_busy;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__unused_wdata;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__unused_be;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_rsp_intg_gen__DOT__unused_tl;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rst_ni;
        CData/*3:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__en_ifetch_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__intg_error_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__re_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__we_o;
    };
    struct {
        CData/*5:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__addr_o;
        CData/*3:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__be_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__busy_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__error_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__outstanding_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__a_ack;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__d_ack;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__error_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__error;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__err_internal;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__instr_error;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__intg_error;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__addr_align_err;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__malformed_meta_err;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__tl_err;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__reqid_q;
        CData/*1:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__reqsz_q;
        CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rspop_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rd_req;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__wr_req;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__unused_tl;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__err_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__opcode_allowed;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__a_config_allowed;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__op_full;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__op_partial;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__op_get;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_type_err;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__addr_sz_chk;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__fulldata_chk;
        CData/*3:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__mask;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__ds;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__ds;
    };
    struct {
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__ds;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__we;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__de;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__qe;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__q;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__ds;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__we;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__de;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__d;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__we;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__de;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__qe;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__ds;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_data;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__we;
    };
    struct {
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__de;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__d;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__ds;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__ds;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__wd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__ds;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__de;
    };
    struct {
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__we;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__qre;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__we;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__wd;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__qre;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__ds;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__we;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__wd;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__qre;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__ds;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__we;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__wd;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__qre;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__ds;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__re;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__we;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__wd;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__qe;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__qre;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__ds;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__qs;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_start;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_mode;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_soft_rst;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_rsvd;
    };
    struct {
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_n_iter;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_busy;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_valid;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_error;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__cfg_data_width;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__cfg_frac_width;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__cfg_max_iter;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__cfg_rsvd;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__state_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__state_d;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__iter_q;
        CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__iter_d;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__n_iter_q;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__n_iter_d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__mode_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__mode_d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_valid_d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_error_d;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__start_rise;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__start_fall_unused;
        CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__n_iter_eff;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__n_iter_invalid;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__en_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__serial_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__r_edge_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__f_edge_o;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__serial_q;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__clk_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__rst_ni;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__d_i;
        CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__q_o;
        CData/*0:0*/ __Vfunc_mubi4_test_invalid__6__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_invalid__6__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__7__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__7__val;
        CData/*0:0*/ __Vfunc_mubi4_test_false_loose__8__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_false_loose__8__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__11__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__11__val;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__clk_i__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__rst_ni__0;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_rsvd2_qs;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__ctrl_rsvd2_wd;
        SData/*8:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__addr_hit;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wd;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__d;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__q;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__ds;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__qs;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_data;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__wd;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__d;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__q;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__wr_data;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ctrl_rsvd2;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_q;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_d;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_init;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_step;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__unnamedblk1__DOT__z_in_int;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__unnamedblk2__DOT__x_final_visible;
        SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__unnamedblk2__DOT__y_final_visible;
        IData/*31:0*/ cordic_tb__DOT__tl_i_a_address;
        IData/*31:0*/ cordic_tb__DOT__tl_i_a_data;
        IData/*31:0*/ cordic_tb__DOT__tl_o_d_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_wdata;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_rdata;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg_rdata_next;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__status_rsvd_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__x_in_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__x_in_wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__y_in_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__y_in_wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__z_in_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__z_in_wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__x_out_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__y_out_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__z_out_qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__wdata_o;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rdata_i;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rdata;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__rdata_q;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__wd;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__d;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__q;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__ds;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__q;
    };
    struct {
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__wr_data;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__qs;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__wd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__d;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__q;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__ds;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__qs;
        IData/*28:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__status_rsvd;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_in_value;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_in_value;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_in_value;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_out_value;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_out_value;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_out_value;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_q;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_d;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_q;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_d;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_init;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_init;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_shift;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_shift;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_step;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_step;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__x_out_next_32;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__y_out_next_32;
        IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__z_out_next_32;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__unnamedblk1__DOT__x_in_int;
        IData/*18:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__unnamedblk1__DOT__y_in_int;
        IData/*31:0*/ __VactIterCount;
        VlWide<4>/*108:0*/ cordic_tb__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__tl_o;
        VlWide<4>/*108:0*/ cordic_tb__DOT__unnamedblk1__DOT__t;
        VlWide<4>/*108:0*/ cordic_tb__DOT__u_cordic__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__tl_o;
        VlWide<10>/*298:0*/ cordic_tb__DOT__u_cordic__DOT__reg2hw;
        VlWide<5>/*159:0*/ cordic_tb__DOT__u_cordic__DOT__hw2reg;
    };
    struct {
        VlWide<4>/*108:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__tl_o;
        VlWide<10>/*298:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__reg2hw;
        VlWide<5>/*159:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__hw2reg;
        VlWide<4>/*108:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__tl_reg_h2d;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__tl_reg_d2h;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__tl_o_pre;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_rsp_intg_gen__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_rsp_intg_gen__DOT__tl_o;
        VlWide<4>/*108:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__tl_o;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__tl_o_pre;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__tl_i;
        VlWide<3>/*65:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__tl_o;
        VlWide<4>/*108:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__tl_i;
        VlWide<10>/*298:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__reg2hw;
        VlWide<5>/*159:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__hw2reg;
        QData/*42:0*/ __Vfunc_extract_h2d_cmd_intg__1__payload;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__2__Vfuncout;
        QData/*56:0*/ __Vfunc_prim_secded_inv_64_57_enc__2__data_i;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__2__data_o;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__3__Vfuncout;
        QData/*56:0*/ __Vfunc_prim_secded_inv_64_57_enc__3__data_i;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__3__data_o;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlDelayScheduler __VdlySched;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_rsp_intg_gen__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_rsp_intg_gen__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__CmdIntgCheck = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*3:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__MaskOne = 1U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__SwAccess = 0U;
    static constexpr CData/*4:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__SwAccess = 0U;
    static constexpr CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__DATA_W_U8 = 0x10U;
    static constexpr CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__DATA_FRAC_W_U8 = 0x0eU;
    static constexpr CData/*7:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__MAX_ITER_U8 = 0x10U;
    static constexpr CData/*0:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__ResetValue = 0U;
    static constexpr SData/*15:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__AW = 6U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__DBW = 4U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__RegAw = 6U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__RegDw = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__AccessLatency = 0U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__RegBw = 4U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__IW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__SZW = 2U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__IW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__SZW = 2U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__MW = 4U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_reg_if__DOT__u_err__DOT__SubAW = 2U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_start__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_mode__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_soft_rst__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__DW = 5U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd__DOT__wr_en_data_arb__DOT__DW = 5U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_n_iter__DOT__wr_en_data_arb__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__DW = 0x00000010U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_ctrl_rsvd2__DOT__wr_en_data_arb__DOT__DW = 0x00000010U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_busy__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_valid__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_error__DOT__DW = 1U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_status_rsvd__DOT__DW = 0x0000001dU;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_in__DOT__wr_en_data_arb__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_in__DOT__wr_en_data_arb__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_in__DOT__wr_en_data_arb__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_x_out__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_y_out__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_z_out__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_data_width__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_frac_width__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_max_iter__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_reg__DOT__u_cfg_rsvd__DOT__DW = 8U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__DATA_W = 0x00000010U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__DATA_FRAC_W = 0x0000000eU;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ANGLE_W = 0x00000010U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ANGLE_FRAC_W = 0x0000000dU;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__GUARD_W = 3U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__INT_W = 0x00000013U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__MAX_ITER = 0x00000010U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__ITER_W = 5U;
    static constexpr IData/*31:0*/ cordic_tb__DOT__u_cordic__DOT__u_cordic_core__DOT__u_start_edge_detect__DOT__u_sync_1__DOT__Width = 1U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
