"""Register-description scaffold and generated CSR collateral."""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import Any

from flexsoc.backend.core import ensure_dir, safe_write_file


HJSON_TEMPLATE = r"""{{ 
  name:               "{top}",
  human_name:         "{top}",
  one_line_desc:      "Starter FlexSoC IP with control, datapath, and status registers.",
  one_paragraph_desc: '''
    Default development block used by the generated RTL stub and verification scaffolds.
  '''

  cip_id:             "1",
  design_spec:        "",
  dv_doc:             "",
  hw_checklist:       "",
  sw_checklist:       "",

  revisions: [{{
    version:            "1.0.0",
    life_stage:         "L0",
    design_stage:       "D0",
    verification_stage: "V0",
    commit_id:          "",
    notes:              "Generated starter metadata."
  }}]

  clocking: [{{ clock: "clk_i", reset: "rst_ni" }}]
  bus_interfaces: [{{ protocol: "{itf}", direction: "device" }}]
  regwidth: "32"

  registers: [
    {{
      name: "CTRL",
      desc: "Datapath control register.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [
        {{ bits: "0", name: "EN",    desc: "Enable the generated datapath." }},
        {{ bits: "1", name: "START", desc: "Software start pulse placeholder." }},
        {{ bits: "2", name: "CLR",   desc: "Clear the generated pipeline." }}
      ]
    }},

    {{
      name: "MODE",
      desc: "Small mode register used by the generated core.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [
        {{ bits: "1:0", name: "SEL",      desc: "0:add, 1:xor, 2:shift, 3:pass." }},
        {{ bits: "2",   name: "INVERT",   desc: "Reserved starter option." }},
        {{ bits: "3",   name: "SATURATE", desc: "Reserved starter option." }}
      ]
    }},

    {{
      name: "OPERAND_A",
      desc: "Example software operand A.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Operand A value." }}]
    }},

    {{
      name: "OPERAND_B",
      desc: "Example software operand B.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Operand B value." }}]
    }},

    {{
      name: "SCALE",
      desc: "Example shift/scale parameter.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "7:0", name: "VALUE", desc: "Shift amount used in MODE=2." }}]
    }},

    {{
      name: "STATUS",
      desc: "Datapath status generated by hardware.",
      swaccess: "ro",
      hwaccess: "hrw",
      hwext: "true",
      fields: [
        {{ bits: "0", name: "BUSY",  desc: "Pipeline stage 0 is valid." }},
        {{ bits: "1", name: "DONE",  desc: "Pipeline output is valid." }},
        {{ bits: "2", name: "ERROR", desc: "Reserved error flag." }}
      ]
    }},

    {{
      name: "RESULT",
      desc: "Latest generated datapath result.",
      swaccess: "ro",
      hwaccess: "hrw",
      hwext: "true",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Latest data_o sample." }}]
    }}
  ]
}}
"""


def render_hjson(top: str, itf: str) -> str:
    """Render a compact default IP HJSON document."""

    return HJSON_TEMPLATE.format(top=top, itf=itf)


def write_hjson(top: str, itf: str, output: str | Path = ".", *, force: bool = False) -> Path:
    """Write a generated HJSON file and return its path."""

    outdir = Path(output or ".")
    ensure_dir(outdir)
    path = outdir / f"{top}.hjson"
    safe_write_file(path, render_hjson(top, itf), overwrite=force)
    return path

def cfg_hjson(top: str) -> str:
    """Render the cfg-domain HJSON regmap."""

    name = f"{top}_cfg"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "Cfg-domain controls for the generated N-clock IP.",
      one_paragraph_desc: "Global control and cfg-domain status registers for the generated N-clock scaffold.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock cfg regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "CTRL",
          desc: "Global control written from the cfg clock domain.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [
            {{ bits: "0", name: "ENABLE", desc: "Enable RX input and DSP processing." }},
            {{ bits: "1", name: "SOFT_RESET", desc: "Synchronous datapath clear request." }},
            {{ bits: "2", name: "CLK_GATE_EN", desc: "Allow the DSP clock gate to close when idle." }}
          ]
        }},
        {{
          name: "GAIN",
          desc: "Signed Q1.15 gain added by the DSP pipeline. Update while CTRL.ENABLE is low.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "15:0", name: "VALUE", desc: "DSP gain coefficient." }}]
        }},
        {{
          name: "CFG_STATUS",
          desc: "Cfg-domain view of datapath status synchronized back from the DSP domain.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [
            {{ bits: "0", name: "BUSY", desc: "The DSP pipeline currently owns an output sample." }},
            {{ bits: "1", name: "OVERFLOW", desc: "The latest result overflowed or saturated." }}
          ]
        }}
      ]
    }}
    """)


def dsp_hjson(top: str) -> str:
    """Render the dsp-domain HJSON regmap."""

    name = f"{top}_dsp"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "DSP-domain controls and status for the generated N-clock IP.",
      one_paragraph_desc: "Algorithm selection, threshold, result and live DSP status registers for the generated N-clock scaffold.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock dsp regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "DSP_CTRL",
          desc: "DSP-domain algorithm control.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [
            {{ bits: "1:0", name: "OP", desc: "0=MAC plus gain, 1=absolute difference, 2=energy estimate." }},
            {{ bits: "2", name: "SATURATE", desc: "Clamp overflowing results to signed 32-bit limits." }}
          ]
        }},
        {{
          name: "THRESHOLD",
          desc: "Unsigned threshold compared with the DSP result.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "31:0", name: "VALUE", desc: "Result threshold." }}]
        }},
        {{
          name: "RESULT",
          desc: "Latest signed DSP result.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [{{ bits: "31:0", name: "VALUE", desc: "Latest output result." }}]
        }},
        {{
          name: "DSP_STATUS",
          desc: "DSP-domain live status.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [
            {{ bits: "0", name: "VALID", desc: "RESULT contains a valid sample." }},
            {{ bits: "1", name: "ABOVE_THRESHOLD", desc: "RESULT is greater than THRESHOLD." }},
            {{ bits: "2", name: "FIFO_EMPTY", desc: "RX-to-DSP FIFO has no readable payload." }},
            {{ bits: "3", name: "OVERFLOW", desc: "The latest operation overflowed before saturation." }}
          ]
        }}
      ]
    }}
    """)


def generic_hjson(top: str, regmap: str) -> str:
    """Render a small generic HJSON for an extra domain regmap."""

    name = f"{top}_{regmap}"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "Generated {regmap}-domain control/status registers.",
      one_paragraph_desc: "Starter control/status map for a generated N-clock domain.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock domain regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "CTRL",
          desc: "Domain control.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "0", name: "ENABLE", desc: "Enable this domain." }}]
        }},
        {{
          name: "STATUS",
          desc: "Domain status.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [{{ bits: "0", name: "BUSY", desc: "Domain busy." }}]
        }}
      ]
    }}
    """)


def render_nclock_hjson(top: str, regmap: str) -> str:
    """Render one N-clock regmap by short name."""

    if regmap == "cfg":
        return cfg_hjson(top)
    if regmap == "dsp":
        return dsp_hjson(top)
    return generic_hjson(top, regmap)


# RTL generation


def load_hjson(path: str | Path) -> dict[str, Any]:
    """Load one HJSON file with hjson, falling back to a tiny name parser."""

    text = Path(path).read_text(encoding="utf-8")
    try:
        import hjson  # type: ignore

        return hjson.loads(text)
    except ImportError:
        import re

        match = re.search(r"\bname\s*:\s*[\"']?([A-Za-z_][A-Za-z0-9_]*)", text)
        if match:
            return {"name": match.group(1)}
        raise


def render_header_declarations(module_name: str, base_address: str) -> str:
    """Render the C declarations injected into the generated header."""

    upper = module_name.upper()
    return "".join(
        [
            "\n",
            "#include <stdint.h>\n\n",
            f"#define {upper}_BASE {base_address}\n\n",
            f"typedef uintptr_t {module_name}_t;\n",
            f"int {module_name}_init({module_name}_t base);\n",
            f"int {module_name}_in({module_name}_t base);\n",
            f"void {module_name}_out({module_name}_t base, char c);\n",
            f"int {module_name}_putchar(int c);\n",
            f"int {module_name}_puts(const char* str);\n\n",
        ]
    )


def insert_function_declarations(header_path: str | Path, base_address: str, module_name: str) -> Path:
    """Inject the common driver declarations before the C++ guard when present."""

    path = Path(header_path)
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    decls = render_header_declarations(module_name, base_address)
    index = next((i for i, line in enumerate(lines) if line.strip().startswith("#ifdef __cplusplus")), len(lines))
    path.write_text("".join(lines[:index]) + decls + "".join(lines[index:]), encoding="utf-8")
    return path


def render_uart_source(module_name: str) -> str:
    """Render the UART-specialized C driver body."""

    upper = module_name.upper()
    return f'''#include "{module_name}.h"

#define DEV_WRITE(addr, val) (*((volatile uint32_t *)(uintptr_t)(addr)) = (uint32_t)(val))
#define DEV_READ(addr) (*((volatile uint32_t *)(uintptr_t)(addr)))

#ifndef BAUD_RATE
#define BAUD_RATE 115200u
#endif

#ifndef SYSCLK_FREQ
#define SYSCLK_FREQ 50000000u
#endif

#ifndef UART_EOF
#define UART_EOF (-1)
#endif

int {module_name}_init({module_name}_t base) {{
  uint32_t nco = (uint32_t)(((uint64_t)BAUD_RATE << 20) / SYSCLK_FREQ);
  DEV_WRITE(base + UART_CTRL_REG_OFFSET, (nco << 16) | 0x3U);
  return 0;
}}

int {module_name}_in({module_name}_t base) {{
  int res = UART_EOF;
#ifdef UART_STATUS_REG_OFFSET
#ifdef UART_STATUS_RXEMPTY_BIT
  if (!(DEV_READ(base + UART_STATUS_REG_OFFSET) & (1u << UART_STATUS_RXEMPTY_BIT))) {{
    res = (int)DEV_READ(base + UART_RDATA_REG_OFFSET);
  }}
#else
  res = (int)DEV_READ(base + UART_RDATA_REG_OFFSET);
#endif
#else
  res = (int)DEV_READ(base + UART_RDATA_REG_OFFSET);
#endif
  return res;
}}

void {module_name}_out({module_name}_t base, char c) {{
#ifdef UART_STATUS_REG_OFFSET
#ifdef UART_STATUS_TXFULL_BIT
  while (DEV_READ(base + UART_STATUS_REG_OFFSET) & (1u << UART_STATUS_TXFULL_BIT)) {{
  }}
#endif
#endif
  DEV_WRITE(base + UART_WDATA_REG_OFFSET, (uint32_t)(uint8_t)c);
}}

int {module_name}_putchar(int c) {{
  if (c == '\\n') {{
    {module_name}_out(({module_name}_t){upper}_BASE, '\\r');
  }}
  {module_name}_out(({module_name}_t){upper}_BASE, (char)c);
  return c;
}}

int {module_name}_puts(const char* str) {{
  while (*str) {{
    {module_name}_putchar(*str++);
  }}
  return 0;
}}
'''


def render_generic_source(module_name: str) -> str:
    """Render the generic memory-mapped C driver body."""

    upper = module_name.upper()
    return f'''#include "{module_name}.h"

#define DEV_WRITE(addr, val) (*((volatile uint32_t *)(uintptr_t)(addr)) = (uint32_t)(val))
#define DEV_READ(addr) (*((volatile uint32_t *)(uintptr_t)(addr)))

int {module_name}_init({module_name}_t base) {{
#ifdef {upper}_CTRL_REG_OFFSET
  DEV_WRITE(base + {upper}_CTRL_REG_OFFSET, 0x1u);
#else
  DEV_WRITE(base + 0x0u, 0x1u);
#endif
  return 0;
}}

int {module_name}_in({module_name}_t base) {{
#ifdef {upper}_RDATA_REG_OFFSET
  return (int)DEV_READ(base + {upper}_RDATA_REG_OFFSET);
#else
  return (int)DEV_READ(base + 0x0u);
#endif
}}

void {module_name}_out({module_name}_t base, char c) {{
#ifdef {upper}_WDATA_REG_OFFSET
  DEV_WRITE(base + {upper}_WDATA_REG_OFFSET, (uint32_t)(uint8_t)c);
#else
  DEV_WRITE(base + 0x0u, (uint32_t)(uint8_t)c);
#endif
}}

int {module_name}_putchar(int c) {{
  {module_name}_out(({module_name}_t){upper}_BASE, (char)c);
  return c;
}}

int {module_name}_puts(const char* str) {{
  while (*str) {{
    {module_name}_putchar(*str++);
  }}
  return 0;
}}
'''


def write_source(module_name: str, output_dir: str | Path) -> Path:
    """Write the selected C driver body and return the generated path."""

    path = Path(output_dir) / f"{module_name}.c"
    renderer = render_uart_source if module_name == "uart" else render_generic_source
    path.write_text(renderer(module_name), encoding="utf-8")
    return path


def generate_driver(hjson_file: str | Path, output_dir: str | Path, base_address: str) -> tuple[Path, Path]:
    """Generate header declarations and C source for one decoded IP block."""

    module_name = str(load_hjson(hjson_file)["name"])
    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    header = insert_function_declarations(outdir / f"{module_name}.h", base_address, module_name)
    source = write_source(module_name, outdir)
    return header, source


READABLE_SWACCESS = frozenset({"ro", "rc", "rw", "rw1s", "rw1c", "rw0c"})
WRITABLE_SWACCESS = frozenset({"rw", "wo", "r0w1c", "rw1s", "rw1c", "rw0c"})


@dataclass(frozen=True)
class FieldSpec:
    """Normalized field metadata consumed by the Python emitter."""

    name: str
    lsb: int
    msb: int
    swaccess: str
    hwaccess: str
    reset: int | None

    @property
    def mask(self) -> int:
        return ((1 << (self.msb - self.lsb + 1)) - 1) << self.lsb

    @property
    def readable(self) -> bool:
        return self.swaccess in READABLE_SWACCESS

    @property
    def writable(self) -> bool:
        return self.swaccess in WRITABLE_SWACCESS


@dataclass(frozen=True)
class RegisterSpec:
    """Normalized register metadata consumed by the Python emitter."""

    domain: str
    name: str
    offset: int
    reset: int
    reset_mask: int
    fields: tuple[FieldSpec, ...]

    @property
    def path(self) -> str:
        return f"{self.domain}.{self.name}"

    @property
    def readable(self) -> bool:
        return any(field.readable for field in self.fields)

    @property
    def writable(self) -> bool:
        return any(field.writable for field in self.fields)


def _reggen_ip_block() -> Any:
    """Return the bundled reggen ``IpBlock`` class."""

    util_dir = Path(__file__).resolve().parents[3] / "util"
    if util_dir.is_dir() and str(util_dir) not in sys.path:
        sys.path.insert(0, str(util_dir))
    try:
        from reggen.ip_block import IpBlock  # type: ignore
    except ModuleNotFoundError as exc:
        missing = exc.name or "reggen dependency"
        raise SystemExit(
            f"cannot load bundled reggen ({missing!r} missing); run `uv sync` first"
        ) from exc
    return IpBlock


def _source_files(top: str, data_dir: Path) -> list[tuple[str, Path]]:
    """Discover one flat map or any number of named domain maps."""

    named = sorted(data_dir.glob(f"{top}_*.hjson"))
    if named:
        return [(path.stem[len(top) + 1 :], path) for path in named]
    path = data_dir / f"{top}.hjson"
    if path.exists():
        return [("core", path)]
    raise SystemExit(f"no HJSON register maps found for {top} under {data_dir}")


def _field_spec(field: Any) -> FieldSpec:
    reset = field.resval if isinstance(field.resval, int) else None
    return FieldSpec(
        name=str(field.name).upper(),
        lsb=int(field.bits.lsb),
        msb=int(field.bits.msb),
        swaccess=str(field.swaccess.key).lower(),
        hwaccess=str(field.hwaccess.key).lower(),
        reset=reset,
    )


def _collect(top: str, data_dir: Path) -> tuple[list[Path], list[RegisterSpec]]:
    """Load HJSON through reggen and return flattened software-visible CSRs."""

    IpBlock = _reggen_ip_block()
    sources: list[Path] = []
    registers: list[RegisterSpec] = []
    seen_paths: set[str] = set()

    for fallback_domain, source in _source_files(top, data_dir):
        try:
            block = IpBlock.from_path(str(source), [])
        except (RuntimeError, ValueError) as exc:
            raise SystemExit(f"invalid HJSON regmap {source}: {exc}") from exc

        sources.append(source)
        primary_clock = getattr(getattr(block.clocking, "primary", None), "clock", None)
        domain = fallback_domain if source.stem != top else str(primary_clock or fallback_domain)

        for reg_block in block.reg_blocks.values():
            for register in reg_block.flat_regs:
                spec = RegisterSpec(
                    domain=domain,
                    name=str(register.name).upper(),
                    offset=int(register.offset),
                    reset=int(register.resval),
                    reset_mask=int(register.resmask),
                    fields=tuple(_field_spec(field) for field in register.fields),
                )
                if spec.path in seen_paths:
                    raise SystemExit(
                        f"duplicate model register path {spec.path!r} while reading {source}"
                    )
                seen_paths.add(spec.path)
                registers.append(spec)

    if not registers:
        joined = ", ".join(str(path) for path in sources)
        raise SystemExit(f"no registers found in HJSON source(s): {joined}")
    return sources, registers


def _field_expr(field: FieldSpec) -> str:
    return (
        "Field("
        f"name={field.name!r}, lsb={field.lsb}, msb={field.msb}, "
        f"swaccess={field.swaccess!r}, hwaccess={field.hwaccess!r}, "
        f"reset={field.reset!r})"
    )


def _domain_literal(registers: list[RegisterSpec]) -> str:
    by_domain: dict[str, list[RegisterSpec]] = {}
    for register in registers:
        by_domain.setdefault(register.domain, []).append(register)

    rows: list[str] = []
    for domain, domain_registers in by_domain.items():
        rows.extend(
            [
                f"    {domain!r}: RegisterDomain(",
                f"        name={domain!r},",
                "        registers=(",
            ]
        )
        for register in domain_registers:
            rows.extend(
                [
                    "            Register(",
                    f"                domain={register.domain!r},",
                    f"                name={register.name!r},",
                    f"                offset=0x{register.offset:08x},",
                    f"                reset=0x{register.reset:08x},",
                    f"                mask=0x{register.reset_mask:08x},",
                    "                fields=(",
                    *(
                        f"                    {_field_expr(field)},"
                        for field in register.fields
                    ),
                    "                ),",
                    "            ),",
                ]
            )
        rows.extend(["        ),", "    ),"])
    return "\n".join(rows)


def _emit_python(top: str, sources: list[Path], registers: list[RegisterSpec]) -> str:
    """Render the dependency-free ``<top>_regmap.py`` helper."""

    primary_domain = registers[0].domain
    template = dedent(
        '''\
        """Generated model-side CSR map for __TOP__.

        HJSON source(s): __SOURCE_NAMES__.
        Regenerate with ``fx regmap_py --force``. Behavioral code belongs in
        ``__TOP___model.py`` and test scenarios belong in ``__TOP___tests.py``.
        """
        from __future__ import annotations

        from dataclasses import dataclass
        from pathlib import Path
        from typing import Iterable

        TOP = __TOP_REPR__
        PRIMARY_DOMAIN = __PRIMARY_DOMAIN_REPR__


        @dataclass(frozen=True)
        class Field:
            name: str
            lsb: int
            msb: int
            swaccess: str
            hwaccess: str
            reset: int | None = None

            @property
            def width(self) -> int:
                return self.msb - self.lsb + 1

            @property
            def mask(self) -> int:
                return ((1 << self.width) - 1) << self.lsb

            @property
            def readable(self) -> bool:
                return self.swaccess in __READABLE_REPR__

            @property
            def writable(self) -> bool:
                return self.swaccess in __WRITABLE_REPR__

            def encode(self, value: int) -> int:
                if not 0 <= value < (1 << self.width):
                    raise ValueError(
                        f"value {value} does not fit {self.width}-bit field {self.name}"
                    )
                return (value << self.lsb) & self.mask

            def decode(self, register_value: int) -> int:
                return (register_value & self.mask) >> self.lsb


        @dataclass(frozen=True)
        class Register:
            domain: str
            name: str
            offset: int
            reset: int
            mask: int
            fields: tuple[Field, ...]

            @property
            def path(self) -> str:
                return f"{self.domain}.{self.name}"

            @property
            def readable(self) -> bool:
                return any(item.readable for item in self.fields)

            @property
            def writable(self) -> bool:
                return any(item.writable for item in self.fields)

            def field(self, name: str) -> Field:
                key = name.upper()
                for item in self.fields:
                    if item.name == key:
                        return item
                known = ", ".join(item.name for item in self.fields)
                raise KeyError(f"unknown field {self.path}.{name}; known: {known}")

            def __call__(self, **values: int) -> int:
                """Build a register value from its HJSON reset plus field overrides."""

                result = self.reset & 0xFFFF_FFFF
                for name, value in values.items():
                    item = self.field(name)
                    result = (result & ~item.mask) | item.encode(value)
                return result & 0xFFFF_FFFF

            def fields_mask(self, *names: str) -> int:
                """Return the bit mask covering the selected HJSON fields."""

                result = 0
                for name in names:
                    result |= self.field(name).mask
                return result & 0xFFFF_FFFF

            def _value(self, value: int | None, fields: dict[str, int]) -> int:
                if value is not None and fields:
                    raise ValueError(
                        f"pass either a raw value or field values for {self.path}, not both"
                    )
                return self(**fields) if value is None else value & 0xFFFF_FFFF

            def write(
                self,
                value: int | None = None,
                *,
                mask: int | None = None,
                **fields: int,
            ) -> str:
                """Format one ``config.regs`` write row from a raw value or fields."""

                if not self.writable:
                    raise ValueError(f"register {self.path} is not software-writable")
                encoded = self._value(value, fields)
                row = f"{self.path} 0x{encoded:08x}"
                if mask is not None:
                    row += f" 0x{mask & 0xFFFF_FFFF:08x}"
                return row

            def expect(
                self,
                value: int | None = None,
                *,
                mask: int | None = None,
                **fields: int,
            ) -> str:
                """Format one ``config.regs`` check row from a raw value or fields."""

                if not self.readable:
                    raise ValueError(f"register {self.path} is not software-readable")
                encoded = self._value(value, fields)
                if fields and mask is None:
                    mask = self.fields_mask(*fields)
                row = f"expect {self.path} 0x{encoded:08x}"
                if mask is not None:
                    row += f" 0x{mask & 0xFFFF_FFFF:08x}"
                return row

            def vector_write(
                self,
                cycle: int,
                value: int | None = None,
                *,
                mask: int | None = None,
                **fields: int,
            ) -> str:
                """Format one cycle-indexed ``@write`` row from a raw value or fields."""

                if not self.writable:
                    raise ValueError(f"register {self.path} is not software-writable")
                encoded = self._value(value, fields)
                row = f"{cycle} @write {self.path} 0x{encoded:08x}"
                if mask is not None:
                    row += f" 0x{mask & 0xFFFF_FFFF:08x}"
                return row

            def vector_read(
                self,
                cycle: int,
                expected: int | None = None,
                *,
                mask: int | None = None,
                **fields: int,
            ) -> str:
                """Format one cycle-indexed ``@read`` row from a raw value or fields."""

                if not self.readable:
                    raise ValueError(f"register {self.path} is not software-readable")
                encoded = self._value(expected, fields)
                if fields and mask is None:
                    mask = self.fields_mask(*fields)
                row = f"{cycle} @read {self.path} 0x{encoded:08x}"
                if mask is not None:
                    row += f" 0x{mask & 0xFFFF_FFFF:08x}"
                return row


        @dataclass(frozen=True)
        class RegisterDomain:
            name: str
            registers: tuple[Register, ...]

            def reg(self, name: str) -> Register:
                key = name.upper()
                for item in self.registers:
                    if item.name == key:
                        return item
                known = ", ".join(item.name for item in self.registers)
                raise KeyError(f"unknown register {self.name}.{name}; known: {known}")

            def has(self, name: str) -> bool:
                key = name.upper()
                return any(item.name == key for item in self.registers)

            def __getattr__(self, name: str) -> Register:
                try:
                    return self.reg(name)
                except KeyError as exc:
                    raise AttributeError(name) from exc

            @property
            def readable(self) -> tuple[Register, ...]:
                return tuple(item for item in self.registers if item.readable)

            @property
            def writable(self) -> tuple[Register, ...]:
                return tuple(item for item in self.registers if item.writable)

            def __iter__(self):
                return iter(self.registers)


        DOMAINS: dict[str, RegisterDomain] = {
        __DOMAIN_LITERAL__
        }
        PRIMARY = DOMAINS[PRIMARY_DOMAIN]


        def domain(name: str) -> RegisterDomain:
            """Return one generated register domain by its HJSON/clock name."""

            try:
                return DOMAINS[name]
            except KeyError as exc:
                known = ", ".join(DOMAINS)
                raise KeyError(f"unknown {TOP} register domain {name!r}; known: {known}") from exc


        def write_config(path: str | Path, rows: Iterable[str]) -> None:
            """Write one ``config.regs`` file."""

            out = Path(path)
            out.parent.mkdir(parents=True, exist_ok=True)
            registers = [item for group in DOMAINS.values() for item in group]
            lines = [
                "# format: <CLOCK.REG_NAME> <DATA> [MASK] [WAIT_CYCLES] [NOTE]",
                *(f"# map {item.path} 0x{item.offset:08x}" for item in registers),
                *(str(row) for row in rows),
            ]
            out.write_text("\\n".join(lines) + "\\n", encoding="utf-8")
        '''
    )

    replacements = {
        "__TOP__": top,
        "__TOP_REPR__": repr(top),
        "__SOURCE_NAMES__": ", ".join(path.name for path in sources),
        "__PRIMARY_DOMAIN_REPR__": repr(primary_domain),
        "__READABLE_REPR__": repr(tuple(sorted(READABLE_SWACCESS))),
        "__WRITABLE_REPR__": repr(tuple(sorted(WRITABLE_SWACCESS))),
        "__DOMAIN_LITERAL__": _domain_literal(registers),
    }
    for marker, value in replacements.items():
        template = template.replace(marker, value)
    return template


def generate(
    top: str,
    data_dir: Path,
    model_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Generate only ``<top>_regmap.py`` from HJSON."""

    model_dir.mkdir(parents=True, exist_ok=True)
    out_path = model_dir / f"{top}_regmap.py"
    if out_path.exists() and not force:
        return out_path

    sources, registers = _collect(top, data_dir)
    out_path.write_text(_emit_python(top, sources, registers), encoding="utf-8")
    return out_path

class RegsFlow:
    """Generate register source and each derived collateral independently."""

    def __init__(self, project_root: Path | None = None, runner=None):
        from flexsoc.backend.core.execution import ToolRunner

        self.project_root = Path(project_root or Path.cwd()).resolve()
        self.runner = runner or ToolRunner()

    def setup_hjson(
        self,
        top: str,
        interface: str,
        output_dir: Path,
        *,
        force: bool = False,
        clocks=None,
    ) -> Path | tuple[Path, ...]:
        """Create the HJSON source of truth for one IP."""

        if clocks is not None and clocks.multiclock:
            ensure_dir(output_dir)
            paths = tuple(Path(output_dir) / f"{top}_{name}.hjson" for name in ("cfg", "dsp"))
            for path, name in zip(paths, ("cfg", "dsp"), strict=True):
                safe_write_file(path, render_nclock_hjson(top, name), overwrite=force)
            return paths
        return write_hjson(top, interface, output_dir, force=force)

    def _maps(self, top: str, data_dir: Path, regmap: str | None = None) -> tuple[Path, ...]:
        named = sorted(data_dir.glob(f"{top}_*.hjson"))
        paths = named or [data_dir / f"{top}.hjson"]
        if regmap:
            paths = [path for path in paths if path.stem == f"{top}_{regmap}"]
        selected = tuple(path for path in paths if path.is_file())
        if not selected:
            raise FileNotFoundError(f"no HJSON register maps for {top} under {data_dir}")
        return selected

    def _run_regtool(
        self,
        argv: list[str],
        *,
        cwd: Path,
        log: Path,
        on: str = "local",
    ) -> int:
        from flexsoc.backend.core.execution import CommandRequest

        tool = self.project_root / "src" / "util" / "regtool.py"
        request = CommandRequest(
            (sys.executable, str(tool), *argv),
            cwd,
            {},
            log,
        )
        return self.runner.run(request, on=on).returncode

    def generate_rtl(
        self,
        top: str,
        data_dir: Path,
        rtl_dir: Path,
        *,
        regmap: str | None = None,
        on: str = "local",
    ) -> tuple[Path, ...]:
        """Generate CSR RTL for one or all register maps."""

        rtl_dir.mkdir(parents=True, exist_ok=True)
        outputs: list[Path] = []
        for source in self._maps(top, data_dir, regmap):
            log = rtl_dir / f".{source.stem}_regtool.log"
            argv = ["-r", "-t", str(rtl_dir), str(source)]
            if self._run_regtool(argv, cwd=self.project_root, log=log, on=on):
                raise RuntimeError(f"regtool RTL generation failed: {source}")
            outputs.append(source)
        return tuple(outputs)

    def generate_docs(
        self,
        top: str,
        data_dir: Path,
        doc_dir: Path,
        *,
        regmap: str | None = None,
        on: str = "local",
    ) -> tuple[Path, ...]:
        """Generate register and interface documentation."""

        doc_dir.mkdir(parents=True, exist_ok=True)
        outputs: list[Path] = []
        for source in self._maps(top, data_dir, regmap):
            doc = doc_dir / f"{source.stem}.md"
            interfaces = doc_dir / f"{source.stem}_interfaces.md"
            log = doc_dir / f".{source.stem}_regtool.log"
            commands = (
                ["-d", "-o", str(doc), str(source)],
                ["--interfaces", "-o", str(interfaces), str(source)],
            )
            for argv in commands:
                if self._run_regtool(argv, cwd=self.project_root, log=log, on=on):
                    raise RuntimeError(f"regtool documentation failed: {source}")
            outputs.extend((doc, interfaces))
        return tuple(outputs)

    def generate_driver(
        self,
        hjson_file: Path,
        output_dir: Path,
        *,
        base_address: str = "0x0",
    ) -> tuple[Path, Path]:
        """Generate the C register driver from one HJSON map."""

        return generate_driver(hjson_file, output_dir, base_address)

    def generate_regmap_py(
        self,
        top: str,
        data_dir: Path,
        model_dir: Path,
        *,
        force: bool = False,
        refresh_tests: bool = True,
        clocks=None,
    ) -> Path:
        """Generate the Python CSR API and optional machine-owned tests."""

        path = generate(top, data_dir, model_dir, force=force)
        if refresh_tests:
            from .model import write_regmap_tests
            from flexsoc.backend.core import clock_config

            resolved = clocks or clock_config()
            write_regmap_tests(top, model_dir, safe_controls=resolved.multiclock)
        return path

    def flow(
        self,
        top: str,
        interface: str,
        data_dir: Path,
        rtl_dir: Path,
        doc_dir: Path,
        model_dir: Path,
        driver_dir: Path,
        *,
        force: bool = False,
        regmap: str | None = None,
        on: str = "local",
        clocks=None,
    ) -> None:
        """Run the canonical register-collateral flow."""

        self.setup_hjson(top, interface, data_dir, force=force, clocks=clocks)
        self.generate_rtl(top, data_dir, rtl_dir, regmap=regmap, on=on)
        self.generate_docs(top, data_dir, doc_dir, regmap=regmap, on=on)
        self.generate_driver(data_dir / f"{top}.hjson", driver_dir)
        self.generate_regmap_py(top, data_dir, model_dir, force=force, clocks=clocks)

