# =========================================
# OpenROAD-flow-scripts — single-file config.mk
# Generated by flexsoc setup_pnr.py (cwd-independent)
# Safe-by-default: will not overwrite unless --overwrite is used.
# =========================================

##### [Repo anchor]
REPO_ROOT := /home/eneadim/github/flexsoc

##### [Design identity]
export DESIGN_NICKNAME = my_ip
export DESIGN_NAME     = my_ip
export PLATFORM        = sky130hd

##### [Sources]
# Filelist (.f) with +incdir+ and files (absolute path)
FILELIST := /home/eneadim/github/flexsoc/workspace/runs/my_ip/dev1/rtl/rtl_list.f

# Global include dirs (absolute, independent from build cwd)
export VERILOG_INCLUDE_DIRS := /home/eneadim/github/flexsoc/hw/ips/pkgs

# Source files: ignore blanks, comments (#) and +incdir+ lines
export VERILOG_FILES := $(shell awk '!/^\s*($$|#)/ && $$0 !~ /^\+incdir\+/' $(FILELIST))

##### [Constraints / Frontend]
export SYNTH_HDL_FRONTEND = slang
# SDC is generated next to this config.mk (in outdir)
export SDC_FILE           = /home/eneadim/github/flexsoc/workspace/runs/my_ip/dev1/openroad/my_ip.sdc

##### [User knobs (override from Make/CLI)]
STRATEGY ?= area
TARGET_CLOCK_PS ?= 20000

export CORE_UTILIZATION ?= 50
export PLACE_DENSITY_LB_ADDON = 0.20
export TNS_END_PERCENT = 100

##### [General reporting / quality-of-life]
export DETAILED_METRICS := 1
export REPORT_CLOCK_SKEW := 1
export YOSYS_FLAGS := -v 3
export GUI_TIMING := 1

# -------------------------------------------------
# Common defaults
# -------------------------------------------------
export SETUP_SLACK_MARGIN := 0
export HOLD_SLACK_MARGIN  := 0

export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT := 0
export CELL_PAD_IN_SITES_DETAIL_PLACEMENT := 0

export DETAILED_ROUTE_END_ITERATION := 64
export USE_FILL := 0

export GPL_TIMING_DRIVEN      := 1
export GPL_ROUTABILITY_DRIVEN := 1

# -------------------------------------------------
# Strategy blocks
# -------------------------------------------------

ifeq ($(STRATEGY),none)
  # vanilla
endif

ifeq ($(STRATEGY),area)
  export ABC_AREA := 1
  export ABC_CLOCK_PERIOD_IN_PS := $(TARGET_CLOCK_PS)
  export PLACE_DENSITY := 0.58
endif

ifeq ($(STRATEGY),delay)
  export ABC_AREA := 0
  export ABC_CLOCK_PERIOD_IN_PS := $(TARGET_CLOCK_PS)
  export PLACE_DENSITY := 0.55
endif
