"""Behavioral UART model matching the RTL-visible serial framing.

The model contains only UART behavior/timing used by verification. CSR layout
and serialization belong to ``uart_regmap.py``; test scenarios and vector-file
formatting belong to ``uart_tests.py``.
"""

from __future__ import annotations


TOP = "uart"
INPUTS = ("cio_rx_i",)
OUTPUTS = ("cio_tx_o", "cio_tx_en_o")


# uart_core accumulates CTRL.NCO every clk_i cycle and uart_tx/uart_rx divide
# tick_baud_x16 by 16. NCO=0x8000 therefore gives an exact 32-clock bit cell.
NCO = 0x8000
BIT_CYCLES = 32


def parity_bit(byte: int, *, odd: bool) -> int:
    """Return the parity bit generated by uart_core/uart_tx for one byte."""

    xor = (byte & 0xFF).bit_count() & 1
    return xor ^ int(odd)


def uart_frame(
    byte: int,
    *,
    parity: bool = False,
    odd: bool = False,
    bad_parity: bool = False,
) -> list[int]:
    """Return one UART frame: start, eight LSB-first data bits, parity, stop."""

    byte &= 0xFF
    bits = [0]
    bits.extend((byte >> bit) & 1 for bit in range(8))
    if parity:
        bits.append(parity_bit(byte, odd=odd) ^ int(bad_parity))
    bits.append(1)
    return bits
