// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vpwm_ramp_tb.h for the primary calling header

#ifndef VERILATED_VPWM_RAMP_TB___024ROOT_H_
#define VERILATED_VPWM_RAMP_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6;


class Vpwm_ramp_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vpwm_ramp_tb___024root final : public VerilatedModule {
  public:
    // CELLS
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    Vpwm_ramp_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__3__KET____DOT__u_hostfifo;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(prim_fifo_async_simple__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_simple__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_rd_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_rd_ni,0,0);
        VL_IN8(prim_filter__02Eclk_i,0,0);
        VL_IN8(prim_filter__02Erst_ni,0,0);
        VL_IN8(prim_filter_ctr__02Eclk_i,0,0);
        VL_IN8(prim_filter_ctr__02Erst_ni,0,0);
        VL_IN8(prim_subreg__02Eclk_i,0,0);
        VL_IN8(prim_subreg__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_host__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_host__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_reg__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_reg__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_sram__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_sram__02Erst_ni,0,0);
        VL_IN8(tlul_assert_multiple__02Eclk_i,0,0);
        VL_IN8(tlul_assert_multiple__02Erst_ni,0,0);
        VL_IN8(clk_h_i,0,0);
        VL_IN8(rst_h_ni,0,0);
        VL_IN8(clk_d_i,0,0);
        VL_IN8(rst_d_ni,0,0);
        VL_IN8(tlul_socket_1n__02Eclk_i,0,0);
        VL_IN8(tlul_socket_1n__02Erst_ni,0,0);
        VL_IN8(tlul_socket_m1__02Eclk_i,0,0);
        VL_IN8(tlul_socket_m1__02Erst_ni,0,0);
        VL_IN8(multiple_pwm_ramp__02Eclk_i,0,0);
        VL_IN8(multiple_pwm_ramp__02Erst_ni,0,0);
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__effective_rst_n;
        CData/*0:0*/ pwm_ramp_tb__DOT__clk_i;
        CData/*0:0*/ pwm_ramp_tb__DOT__rst_ni;
        VL_IN8(prim_cdc_rand_delay__02Eclk_i,0,0);
        VL_IN8(prim_cdc_rand_delay__02Erst_ni,0,0);
        VL_IN8(prev_data_i,0,0);
        VL_IN8(src_data_i,0,0);
        VL_OUT8(dst_data_o,0,0);
        VL_IN8(re,0,0);
        VL_IN8(prim_subreg_ext__02Ewe,0,0);
        VL_OUT8(prim_subreg_ext__02Eqe,0,0);
        VL_OUT8(qre,0,0);
        VL_IN8(sram2tlul__02Eclk_i,0,0);
        VL_IN8(sram2tlul__02Erst_ni,0,0);
        VL_IN8(mem_req_i,0,0);
        VL_IN8(mem_write_i,0,0);
        VL_OUT8(mem_rvalid_o,0,0);
        VL_OUT8(mem_error_o,1,0);
        VL_IN8(prim_fifo_async_simple__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ewready_o,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_simple__02Erready_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ewready_o,0,0);
        VL_OUT8(wdepth_o,4,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erready_i,0,0);
        VL_OUT8(rdepth_o,4,0);
        VL_OUT8(r_full_o,0,0);
        VL_OUT8(r_notempty_o,0,0);
        VL_OUT8(w_full_o,0,0);
        VL_OUT8(w_sram_req_o,0,0);
    };
    struct {
        VL_IN8(w_sram_gnt_i,0,0);
        VL_OUT8(w_sram_write_o,0,0);
        VL_IN8(w_sram_rvalid_i,0,0);
        VL_IN8(w_sram_rerror_i,1,0);
        VL_OUT8(r_sram_req_o,0,0);
        VL_IN8(r_sram_gnt_i,0,0);
        VL_OUT8(r_sram_write_o,0,0);
        VL_IN8(r_sram_rvalid_i,0,0);
        VL_IN8(r_sram_rerror_i,1,0);
        VL_IN8(prim_filter__02Eenable_i,0,0);
        VL_IN8(prim_filter__02Efilter_i,0,0);
        VL_OUT8(prim_filter__02Efilter_o,0,0);
        VL_IN8(prim_filter_ctr__02Eenable_i,0,0);
        VL_IN8(prim_filter_ctr__02Efilter_i,0,0);
        VL_IN8(thresh_i,1,0);
        VL_OUT8(prim_filter_ctr__02Efilter_o,0,0);
        VL_IN8(prim_subreg__02Ewe,0,0);
        VL_IN8(de,0,0);
        VL_OUT8(prim_subreg__02Eqe,0,0);
        VL_IN8(req_i,0,0);
        VL_OUT8(gnt_o,0,0);
        VL_IN8(we_i,0,0);
        VL_IN8(wdata_intg_i,6,0);
        VL_IN8(be_i,3,0);
        VL_IN8(instr_type_i,3,0);
        VL_OUT8(valid_o,0,0);
        VL_OUT8(rdata_intg_o,6,0);
        VL_OUT8(err_o,0,0);
        VL_OUT8(intg_err_o,0,0);
        VL_IN8(tlul_adapter_reg__02Een_ifetch_i,3,0);
        VL_OUT8(tlul_adapter_reg__02Eintg_error_o,0,0);
        VL_OUT8(re_o,0,0);
        VL_OUT8(tlul_adapter_reg__02Ewe_o,0,0);
        VL_OUT8(tlul_adapter_reg__02Eaddr_o,7,0);
        VL_OUT8(be_o,3,0);
        VL_IN8(busy_i,0,0);
        VL_IN8(error_i,0,0);
        VL_IN8(tlul_adapter_sram__02Een_ifetch_i,3,0);
        VL_OUT8(req_o,0,0);
        VL_OUT8(req_type_o,3,0);
        VL_IN8(gnt_i,0,0);
        VL_OUT8(tlul_adapter_sram__02Ewe_o,0,0);
        VL_OUT8(tlul_adapter_sram__02Eintg_error_o,0,0);
        VL_IN8(rvalid_i,0,0);
        VL_IN8(rerror_i,1,0);
        VL_OUT8(compound_txn_in_progress_o,0,0);
        VL_IN8(readback_en_i,3,0);
        VL_OUT8(readback_error_o,0,0);
        VL_IN8(wr_collision_i,0,0);
        VL_IN8(write_pending_i,0,0);
        VL_IN8(dev_select_i,2,0);
        VL_IN8(multiple_pwm_ramp__02Eenable_i,0,0);
        VL_IN8(step_i,7,0);
        VL_IN8(lvds_0_i,0,0);
        VL_IN8(lvds_1_i,0,0);
        VL_OUT8(pwm_0_o,0,0);
        VL_OUT8(pwm_1_o,0,0);
        VL_OUT8(adc_value_o,7,0);
        VL_OUT8(adc_valid_o,0,0);
        CData/*0:0*/ prim_fifo_async_simple__DOT__wr_en;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_q;
    };
    struct {
        CData/*0:0*/ prim_fifo_async_simple__DOT__not_in_reset_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__dst_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__dst_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__chk_flag;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_cs;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_cs;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_handshake;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_handshake;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__req_sync__DOT__intq;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__ack_sync__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_wptr_gray;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_wptr;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_rptr_gray;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_rptr;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_inc;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_inc;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__stored;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_sram_rptr;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__r_sramrptr_empty;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__store_en;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_wptr_gray__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_rptr_gray__DOT__intq;
        CData/*3:0*/ prim_filter__DOT__stored_vector_q;
        CData/*3:0*/ prim_filter__DOT__stored_vector_d;
        CData/*0:0*/ prim_filter__DOT__stored_value_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_d;
        CData/*0:0*/ prim_filter_ctr__DOT__filter_q;
        CData/*0:0*/ prim_filter_ctr__DOT__stored_value_q;
        CData/*7:0*/ tlul_adapter_host__DOT__tl_source;
        CData/*1:0*/ tlul_adapter_host__DOT__outstanding_reqs_q;
        CData/*1:0*/ tlul_adapter_host__DOT__outstanding_reqs_d;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_d;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_q;
        CData/*0:0*/ tlul_adapter_reg__DOT__outstanding_q;
        CData/*0:0*/ tlul_adapter_reg__DOT__a_ack;
        CData/*0:0*/ tlul_adapter_reg__DOT__error_q;
        CData/*0:0*/ tlul_adapter_reg__DOT__err_internal;
        CData/*0:0*/ tlul_adapter_reg__DOT__instr_error;
        CData/*0:0*/ tlul_adapter_reg__DOT__malformed_meta_err;
        CData/*7:0*/ tlul_adapter_reg__DOT__reqid_q;
        CData/*1:0*/ tlul_adapter_reg__DOT__reqsz_q;
        CData/*2:0*/ tlul_adapter_reg__DOT__rspop_q;
        CData/*0:0*/ tlul_adapter_reg__DOT__rd_req;
        CData/*0:0*/ tlul_adapter_reg__DOT__wr_req;
        CData/*0:0*/ tlul_adapter_reg__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ tlul_adapter_reg__DOT__u_err__DOT__instr_type_err;
        CData/*0:0*/ tlul_adapter_reg__DOT__u_err__DOT__addr_sz_chk;
    };
    struct {
        CData/*0:0*/ tlul_adapter_reg__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ tlul_adapter_reg__DOT__u_err__DOT__fulldata_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__error_det;
        CData/*0:0*/ tlul_adapter_sram__DOT__instr_error;
        CData/*0:0*/ tlul_adapter_sram__DOT__intg_error_q;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_wready;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_rvalid;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_rready;
        CData/*0:0*/ tlul_adapter_sram__DOT__sramreqfifo_wready;
        CData/*0:0*/ tlul_adapter_sram__DOT__sramreqfifo_rready;
        CData/*4:0*/ tlul_adapter_sram__DOT__sramreqfifo_wdata;
        CData/*4:0*/ tlul_adapter_sram__DOT__sramreqfifo_rdata;
        CData/*0:0*/ tlul_adapter_sram__DOT__rspfifo_rvalid;
        CData/*0:0*/ tlul_adapter_sram__DOT__d_valid;
        CData/*0:0*/ tlul_adapter_sram__DOT__d_error;
        CData/*0:0*/ tlul_adapter_sram__DOT__vld_rd_rsp;
        CData/*6:0*/ tlul_adapter_sram__DOT__error_blanking_integ;
        CData/*0:0*/ tlul_adapter_sram__DOT__missed_err_gnt_q;
        CData/*6:0*/ tlul_adapter_sram__DOT__wmask_intg;
        CData/*6:0*/ tlul_adapter_sram__DOT__wdata_intg;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__instr_type_err;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__addr_sz_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__fulldata_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*4:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__storage;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__disable_sva;
    };
    struct {
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__disable_d_error_sva;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__a_mask;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__d_mask;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h2f9dcced__0;
        CData/*2:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h8d3db085__0;
        CData/*1:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h30376d23__0;
        CData/*3:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h6d84055b__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_ha603a01c__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__disable_sva;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__disable_d_error_sva;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__a_mask;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__d_mask;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h2f9dcced__0;
        CData/*2:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h8d3db085__0;
        CData/*1:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h30376d23__0;
        CData/*3:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h6d84055b__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_ha603a01c__0;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__wdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__rdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__full_wclk;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__wdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__rdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__full_wclk;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_socket_1n__DOT__dev_select_outstanding;
        CData/*0:0*/ tlul_socket_1n__DOT__hold_all_requests;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_req;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_rsp;
        CData/*0:0*/ tlul_socket_1n__DOT__hfifo_reqready;
    };
    struct {
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__0__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__1__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__2__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__3__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__reqfifo__rready_i;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__rspfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*2:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_opcode;
        CData/*7:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_source;
        CData/*1:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_size;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_rsp_pending;
        CData/*3:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_instr_type;
        CData/*3:0*/ tlul_socket_m1__DOT__hrequest;
        CData/*3:0*/ tlul_socket_m1__DOT__hgrant;
        CData/*0:0*/ tlul_socket_m1__DOT__arb_ready;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__3__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__2__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__1__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__0__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__full_o;
    };
    struct {
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*1:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__idx_o;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__masked_req;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__ppc_out;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__arb_req;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__mask;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__winner;
        CData/*7:0*/ multiple_pwm_ramp__DOT__adc_value_0;
        CData/*7:0*/ multiple_pwm_ramp__DOT__adc_value_1;
        CData/*0:0*/ multiple_pwm_ramp__DOT__adc_valid_0;
        CData/*0:0*/ multiple_pwm_ramp__DOT__adc_valid_1;
        CData/*0:0*/ multiple_pwm_ramp__DOT__lvds;
        CData/*0:0*/ multiple_pwm_ramp__DOT__lvds_rise;
        CData/*7:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__duty_cycle;
        CData/*7:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__counter;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__clear;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__lvds;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__lvds_rise;
        CData/*1:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__u_prim_deglitch__DOT__count_q;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__u_prim_deglitch__DOT__d_s;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__d_o;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__intq;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_0__DOT__u_prim_edge_detect__DOT__serial_q;
        CData/*7:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__duty_cycle;
        CData/*7:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__counter;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__clear;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__lvds;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__lvds_rise;
        CData/*1:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__u_prim_deglitch__DOT__count_q;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__u_prim_deglitch__DOT__d_s;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__d_o;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__intq;
        CData/*0:0*/ multiple_pwm_ramp__DOT__u_pwm_ramp_1__DOT__u_prim_edge_detect__DOT__serial_q;
        CData/*0:0*/ pwm_ramp_tb__DOT__enable_i;
        CData/*0:0*/ pwm_ramp_tb__DOT__reverse_i;
        CData/*5:0*/ pwm_ramp_tb__DOT__step_i;
        CData/*5:0*/ pwm_ramp_tb__DOT__adc_value_o;
        CData/*0:0*/ pwm_ramp_tb__DOT__adc_valid_o;
        CData/*5:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__duty_cycle;
        CData/*5:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__counter;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__clear;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__lvds;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__lvds_rise;
        CData/*1:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__u_prim_deglitch__DOT__count_q;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__u_prim_deglitch__DOT__d_s;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__d_o;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__u_prim_deglitch__DOT__gen_async__DOT__prim_flop_2sync__DOT__intq;
        CData/*0:0*/ pwm_ramp_tb__DOT__u_pwm_ramp__DOT__u_prim_edge_detect__DOT__serial_q;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__6__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__8__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__8__inp;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__9__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__9__inp;
    };
    struct {
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__15__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__17__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__17__inp;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__18__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__18__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_15E34__31__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_15E34__31__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_B0D6A__33__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_B0D6A__33__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EECFA__36__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EECFA__36__inp;
        CData/*6:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_83AAC__38__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_83AAC__38__inp;
        CData/*1:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_FDEB5__39__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_FDEB5__39__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_15E34__40__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_15E34__40__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_1__44__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_1__44__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_invalid__45__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_invalid__45__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_true_strict__60__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_true_strict__60__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_false_loose__62__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_reg__DOT__prim_mubi_pkg_mubi4_test_false_loose__62__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_reg__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__80__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_reg__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__80__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_invalid__97__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_invalid__97__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__112__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__112__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_false_loose__114__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_false_loose__114__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__116__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__116__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__120__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__120__val;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__122__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__122__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__123__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__123__inp;
        CData/*6:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_83AAC__128__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_83AAC__128__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_1__129__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_1__129__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_EECFA__130__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_EECFA__130__inp;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__131__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__131__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__132__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__132__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_B0D6A__133__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_B0D6A__133__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__136__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__136__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__159__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__159__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__160__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__160__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__162__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__162__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__163__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__163__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__168__Vfuncout;
    };
    struct {
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__168__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__169__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__169__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__171__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__171__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__172__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__172__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__177__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__177__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__178__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__178__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__180__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__180__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__181__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__181__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__194__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__194__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__195__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__195__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__197__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__197__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__198__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__198__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__200__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__200__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__201__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__201__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__203__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__203__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__204__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__204__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__205__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__207__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__217__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__217__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__218__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__218__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__220__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__220__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__221__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__221__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__223__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__223__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__224__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__224__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__226__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__226__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__227__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__227__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__228__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__230__Vfuncout;
        CData/*4:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_5__236__Vfuncout;
        CData/*4:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_5__236__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_EECFA__237__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_EECFA__237__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_FE1F6__238__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_FE1F6__238__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__239__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__239__cmd_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__240__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__240__cmd_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_83AAC__248__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_83AAC__248__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_data_intg__249__Vfuncout;
    };
    struct {
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_data_intg__249__data_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__250__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__250__data_intg;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__264__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__264__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__265__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__265__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__267__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__267__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__268__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__268__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__273__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__273__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__274__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__274__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__276__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__276__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__277__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__277__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__prim_mubi_pkg_mubi4_test_true_strict__279__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__prim_mubi_pkg_mubi4_test_true_strict__279__val;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__281__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__281__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__282__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__282__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__283__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__283__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__284__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__284__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__286__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__286__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__289__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__289__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__290__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__290__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__291__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__291__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__292__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__292__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__294__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__294__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__297__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__297__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__298__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__298__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__299__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__299__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__300__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__300__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__302__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__302__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__305__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__305__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__306__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__306__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__307__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__307__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__308__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__308__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__310__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__310__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__313__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__313__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__314__Vfuncout;
    };
    struct {
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__314__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__315__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__315__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__316__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__316__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__318__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__318__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__321__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__321__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__322__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__322__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__323__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__323__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__324__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__324__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__325__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__325__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__328__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__328__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__329__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__329__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__330__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__330__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__331__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__331__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__332__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__332__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__335__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__335__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__336__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__336__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__337__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__337__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__338__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__338__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__339__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__339__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__342__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__342__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__343__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__343__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__344__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__344__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__345__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__345__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__346__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__346__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__353__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__353__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__354__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__354__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__356__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__356__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__357__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__357__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__362__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__362__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__363__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__363__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__365__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__365__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__366__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__366__inp;
        CData/*0:0*/ __VstlFirstIteration;
    };
    struct {
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__effective_rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_subreg__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_subreg__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_reg__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_reg__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_assert_multiple__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_assert_multiple__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_h_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_h_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_d_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_d_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__multiple_pwm_ramp__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__multiple_pwm_ramp__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pwm_ramp_tb__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pwm_ramp_tb__DOT__rst_ni__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(mem_addr_i,11,0);
        VL_IN16(prim_fifo_async_simple__02Ewdata_i,15,0);
        VL_OUT16(prim_fifo_async_simple__02Erdata_o,15,0);
        VL_OUT16(w_sram_addr_o,15,0);
        VL_OUT16(r_sram_addr_o,15,0);
        VL_OUT16(tlul_adapter_sram__02Eaddr_o,11,0);
        SData/*15:0*/ prim_fifo_async_simple__DOT__data_q;
        SData/*8:0*/ tlul_socket_1n__DOT__num_req_outstanding;
        SData/*13:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_11E70__126__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_11E70__126__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__327__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__327__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__334__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__334__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__341__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__341__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__348__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__348__inp;
        VL_IN(prim_subreg_ext__02Ewd,31,0);
        VL_IN(prim_subreg_ext__02Ed,31,0);
        VL_OUT(prim_subreg_ext__02Eq,31,0);
        VL_OUT(prim_subreg_ext__02Eds,31,0);
        VL_OUT(prim_subreg_ext__02Eqs,31,0);
        VL_OUTW(sram2tlul__02Etl_o,108,0,4);
        VL_INW(sram2tlul__02Etl_i,65,0,3);
        VL_IN(mem_wdata_i,31,0);
        VL_OUT(mem_rdata_o,31,0);
    };
    struct {
        VL_IN(prim_fifo_async_sram_adapter__02Ewdata_i,31,0);
        VL_OUT(prim_fifo_async_sram_adapter__02Erdata_o,31,0);
        VL_OUT(w_sram_wdata_o,31,0);
        VL_OUT(w_sram_wmask_o,31,0);
        VL_IN(w_sram_rdata_i,31,0);
        VL_OUT(r_sram_wdata_o,31,0);
        VL_OUT(r_sram_wmask_o,31,0);
        VL_IN(r_sram_rdata_i,31,0);
        VL_IN(prim_subreg__02Ewd,31,0);
        VL_IN(prim_subreg__02Ed,31,0);
        VL_OUT(prim_subreg__02Eq,31,0);
        VL_OUT(prim_subreg__02Eds,31,0);
        VL_OUT(prim_subreg__02Eqs,31,0);
        VL_IN(addr_i,31,0);
        VL_IN(tlul_adapter_host__02Ewdata_i,31,0);
        VL_OUT(tlul_adapter_host__02Erdata_o,31,0);
        VL_OUTW(tlul_adapter_host__02Etl_o,108,0,4);
        VL_INW(tlul_adapter_host__02Etl_i,65,0,3);
        VL_INW(tlul_adapter_reg__02Etl_i,108,0,4);
        VL_OUTW(tlul_adapter_reg__02Etl_o,65,0,3);
        VL_OUT(tlul_adapter_reg__02Ewdata_o,31,0);
        VL_IN(tlul_adapter_reg__02Erdata_i,31,0);
        VL_INW(tlul_adapter_sram__02Etl_i,108,0,4);
        VL_OUTW(tlul_adapter_sram__02Etl_o,65,0,3);
        VL_OUT(tlul_adapter_sram__02Ewdata_o,31,0);
        VL_OUT(wmask_o,31,0);
        VL_IN(tlul_adapter_sram__02Erdata_i,31,0);
        VL_INW(h2d,217,0,7);
        VL_INW(d2h,131,0,5);
        VL_INW(tlul_fifo_async__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_fifo_async__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_fifo_async__02Etl_d_o,108,0,4);
        VL_INW(tlul_fifo_async__02Etl_d_i,65,0,3);
        VL_INW(tlul_socket_1n__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_socket_1n__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_socket_1n__02Etl_d_o,435,0,14);
        VL_INW(tlul_socket_1n__02Etl_d_i,263,0,9);
        VL_INW(tlul_socket_m1__02Etl_h_i,435,0,14);
        VL_OUTW(tlul_socket_m1__02Etl_h_o,263,0,9);
        VL_OUTW(tlul_socket_m1__02Etl_d_o,108,0,4);
        VL_INW(tlul_socket_m1__02Etl_d_i,65,0,3);
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_q;
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_d;
        IData/*31:0*/ prim_subreg__DOT__wr_data;
        VlWide<4>/*108:0*/ tlul_adapter_host__DOT__tl_out;
        IData/*31:0*/ tlul_adapter_reg__DOT__rdata_q;
        VlWide<3>/*65:0*/ tlul_adapter_reg__DOT__tl_o_pre;
        VlWide<3>/*65:0*/ tlul_adapter_sram__DOT__tl_o_int;
        IData/*16:0*/ tlul_adapter_sram__DOT__reqfifo_wdata;
        IData/*16:0*/ tlul_adapter_sram__DOT__reqfifo_rdata;
        IData/*31:0*/ tlul_adapter_sram__DOT__error_blanking_data;
        IData/*31:0*/ tlul_adapter_sram__DOT__wmask_int;
        IData/*31:0*/ tlul_adapter_sram__DOT__wdata_int;
        IData/*31:0*/ tlul_adapter_sram__DOT__sv2v_autoblock_1__DOT__i;
        IData/*31:0*/ tlul_adapter_sram__DOT__gen_rmask__DOT__rmask;
        IData/*16:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<80>/*2559:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__pend_req;
        VlWide<80>/*2559:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__pend_req;
        VlWide<4>/*108:0*/ tlul_socket_1n__DOT__tl_t_o;
        IData/*22:0*/ tlul_socket_1n__DOT__blanked_auser;
        VlWide<3>/*65:0*/ tlul_socket_1n__DOT__tl_t_p;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rdata_o;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__reqfifo__wdata_i;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__rspfifo__wdata_i;
    };
    struct {
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*65:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__tl_h_o_int;
        VlWide<14>/*435:0*/ tlul_socket_m1__DOT__hreq_fifo_o;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__dreq_fifo_i;
        VlWide<3>/*65:0*/ tlul_socket_m1__DOT__drsp_fifo_o;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__arb_data;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__0__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__1__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__2__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__3__KET____DOT__hreq_fifo_i;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rdata_o;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellinp__rspfifo__wdata_i;
        VlWide<4>/*107:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        IData/*31:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__sv2v_autoblock_3__DOT__i;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_D591E__32__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_D591E__32__inp;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_9783B__34__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_9783B__34__inp;
        IData/*22:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EDEFC__35__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EDEFC__35__inp;
        IData/*31:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_9783B__42__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_reg__DOT__sv2v_cast_9783B__42__inp;
        IData/*31:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_9783B__125__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_9783B__125__inp;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__239__tl;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__240__tl;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__241__tl;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__285__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__285__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__287__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__287__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__288__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__288__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__293__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__293__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__295__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__295__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__296__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__296__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__301__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__301__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__303__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__303__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__304__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__304__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__309__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__309__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__311__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__311__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__312__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__312__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__317__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__317__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__319__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__319__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__320__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__320__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__326__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__326__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__333__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__333__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__340__Vfuncout;
    };
    struct {
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__340__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__347__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__347__inp;
        IData/*31:0*/ __VactIterCount;
        QData/*39:0*/ tlul_adapter_sram__DOT__rspfifo_wdata;
        QData/*39:0*/ tlul_adapter_sram__DOT__rspfifo_rdata;
        QData/*38:0*/ tlul_adapter_sram__DOT____Vcellout__u_tlul_data_integ_enc_instr__data_intg_o;
        QData/*38:0*/ tlul_adapter_sram__DOT____Vcellout__u_tlul_data_integ_enc_data__data_intg_o;
        QData/*39:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__storage;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__a_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__d_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__a_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__d_data;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__240__cmd;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__241__Vfuncout;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__241__payload;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__242__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__242__data_i;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__242__data_o;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__243__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__243__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__244__Vfuncout;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__244__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__245__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__245__data_i;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__245__data_o;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__246__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__246__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__247__Vfuncout;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__247__inp;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__250__enc_data;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_39_32_enc__251__Vfuncout;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_39_32_enc__251__data_o;
        VlUnpacked<VlWide<4>/*106:0*/, 4> tlul_fifo_async__DOT__reqfifo__DOT__storage;
        VlUnpacked<QData/*63:0*/, 4> tlul_fifo_async__DOT__rspfifo__DOT__storage;
        VlUnpacked<VlWide<4>/*108:0*/, 5> tlul_socket_1n__DOT__tl_u_o;
        VlUnpacked<VlWide<3>/*65:0*/, 5> tlul_socket_1n__DOT__tl_u_i;
        VlUnpacked<VlWide<3>/*65:0*/, 4> tlul_socket_m1__DOT__hrsp_fifo_i;
        VlUnpacked<CData/*0:0*/, 30> __Vm_traceActivity;
    };
    double pwm_ramp_tb__DOT__analog_input;
    double pwm_ramp_tb__DOT__u_rc_filter__DOT__y_prev;
    VlDelayScheduler __VdlySched;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<37> __VactTriggered;
    VlTriggerVec<37> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vpwm_ramp_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vpwm_ramp_tb___024root(Vpwm_ramp_tb__Syms* symsp, const char* v__name);
    ~Vpwm_ramp_tb___024root();
    VL_UNCOPYABLE(Vpwm_ramp_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
