// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "prim_assert.sv"

module gpio_reg_top
  import gpio_reg_pkg::* ;
(
  input logic clk_i,
  input logic rst_ni,
  // From TLUL
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output gpio_reg_pkg::gpio_reg2hw_t reg2hw, // Write
  input  gpio_reg_pkg::gpio_hw2reg_t hw2reg, // Read

  // Devmode
  input logic devmode_i // If 1, explicit error return for unmapped register access
);

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(0),
    .EnableDataIntgGen(0)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;


  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [1:0] data_in_qs;
  logic direct_re;
  logic direct_we;
  logic [1:0] direct_gpio_o_qs;
  logic [1:0] direct_gpio_o_wd;
  logic [1:0] direct_gpio_oe_qs;
  logic [1:0] direct_gpio_oe_wd;
  logic intr_ctrl_we;
  logic [1:0] intr_ctrl_en_rising_qs;
  logic [1:0] intr_ctrl_en_rising_wd;
  logic [1:0] intr_ctrl_en_falling_qs;
  logic [1:0] intr_ctrl_en_falling_wd;
  logic [1:0] intr_ctrl_en_lvlhigh_qs;
  logic [1:0] intr_ctrl_en_lvlhigh_wd;
  logic [1:0] intr_ctrl_en_lvllow_qs;
  logic [1:0] intr_ctrl_en_lvllow_wd;
  logic [1:0] intr_ctrl_en_input_filter_qs;
  logic [1:0] intr_ctrl_en_input_filter_wd;
  logic ctrl_en_input_filter_we;
  logic [3:0] ctrl_en_input_filter_qs;
  logic [3:0] ctrl_en_input_filter_wd;

  // Register instances
  // R[data_in]: V(False)
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_data_in (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.data_in.de),
    .d      (hw2reg.data_in.d),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (data_in_qs)
  );


  // R[direct]: V(True)
  logic direct_qe;
  logic [1:0] direct_flds_we;
  assign direct_qe = &direct_flds_we;
  //   F[gpio_o]: 1:0
  prim_subreg_ext #(
    .DW    (2)
  ) u_direct_gpio_o (
    .re     (direct_re),
    .we     (direct_we),
    .wd     (direct_gpio_o_wd),
    .d      (hw2reg.direct.gpio_o.d),
    .qre    (),
    .qe     (direct_flds_we[0]),
    .q      (reg2hw.direct.gpio_o.q),
    .ds     (),
    .qs     (direct_gpio_o_qs)
  );
  assign reg2hw.direct.gpio_o.qe = direct_qe;

  //   F[gpio_oe]: 3:2
  prim_subreg_ext #(
    .DW    (2)
  ) u_direct_gpio_oe (
    .re     (direct_re),
    .we     (direct_we),
    .wd     (direct_gpio_oe_wd),
    .d      (hw2reg.direct.gpio_oe.d),
    .qre    (),
    .qe     (direct_flds_we[1]),
    .q      (reg2hw.direct.gpio_oe.q),
    .ds     (),
    .qs     (direct_gpio_oe_qs)
  );
  assign reg2hw.direct.gpio_oe.qe = direct_qe;


  // R[intr_ctrl]: V(False)
  //   F[en_rising]: 1:0
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_intr_ctrl_en_rising (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_ctrl_we),
    .wd     (intr_ctrl_en_rising_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_ctrl.en_rising.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_ctrl_en_rising_qs)
  );

  //   F[en_falling]: 3:2
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_intr_ctrl_en_falling (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_ctrl_we),
    .wd     (intr_ctrl_en_falling_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_ctrl.en_falling.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_ctrl_en_falling_qs)
  );

  //   F[en_lvlhigh]: 5:4
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_intr_ctrl_en_lvlhigh (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_ctrl_we),
    .wd     (intr_ctrl_en_lvlhigh_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_ctrl.en_lvlhigh.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_ctrl_en_lvlhigh_qs)
  );

  //   F[en_lvllow]: 7:6
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_intr_ctrl_en_lvllow (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_ctrl_we),
    .wd     (intr_ctrl_en_lvllow_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_ctrl.en_lvllow.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_ctrl_en_lvllow_qs)
  );

  //   F[en_input_filter]: 9:8
  prim_subreg #(
    .DW      (2),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (2'h0),
    .Mubi    (1'b0)
  ) u_intr_ctrl_en_input_filter (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_ctrl_we),
    .wd     (intr_ctrl_en_input_filter_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_ctrl.en_input_filter.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_ctrl_en_input_filter_qs)
  );


  // R[ctrl_en_input_filter]: V(False)
  prim_subreg #(
    .DW      (4),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (4'h0),
    .Mubi    (1'b0)
  ) u_ctrl_en_input_filter (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_en_input_filter_we),
    .wd     (ctrl_en_input_filter_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_en_input_filter.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_en_input_filter_qs)
  );



  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == GPIO_DATA_IN_OFFSET);
    addr_hit[1] = (reg_addr == GPIO_DIRECT_OFFSET);
    addr_hit[2] = (reg_addr == GPIO_INTR_CTRL_OFFSET);
    addr_hit[3] = (reg_addr == GPIO_CTRL_EN_INPUT_FILTER_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(GPIO_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(GPIO_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(GPIO_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(GPIO_PERMIT[3] & ~reg_be)))));
  end

  // Generate write-enables
  assign direct_re = addr_hit[1] & reg_re & !reg_error;
  assign direct_we = addr_hit[1] & reg_we & !reg_error;

  assign direct_gpio_o_wd = reg_wdata[1:0];

  assign direct_gpio_oe_wd = reg_wdata[3:2];
  assign intr_ctrl_we = addr_hit[2] & reg_we & !reg_error;

  assign intr_ctrl_en_rising_wd = reg_wdata[1:0];

  assign intr_ctrl_en_falling_wd = reg_wdata[3:2];

  assign intr_ctrl_en_lvlhigh_wd = reg_wdata[5:4];

  assign intr_ctrl_en_lvllow_wd = reg_wdata[7:6];

  assign intr_ctrl_en_input_filter_wd = reg_wdata[9:8];
  assign ctrl_en_input_filter_we = addr_hit[3] & reg_we & !reg_error;

  assign ctrl_en_input_filter_wd = reg_wdata[3:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[1:0] = data_in_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[1:0] = direct_gpio_o_qs;
        reg_rdata_next[3:2] = direct_gpio_oe_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[1:0] = intr_ctrl_en_rising_qs;
        reg_rdata_next[3:2] = intr_ctrl_en_falling_qs;
        reg_rdata_next[5:4] = intr_ctrl_en_lvlhigh_qs;
        reg_rdata_next[7:6] = intr_ctrl_en_lvllow_qs;
        reg_rdata_next[9:8] = intr_ctrl_en_input_filter_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[3:0] = ctrl_en_input_filter_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule


