"""SoC composition, TL-UL fabric generation, and software scaffold flow."""

from __future__ import annotations
import shlex

import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ...core import BackendContext, CommandRequest, ToolRunner
from ..ip.rtl import RtlFlow

SUPPORTED_HOSTS = {"ibex", "uart"}
SUPPORTED_FABRICS = {"tlul"}
HOST_IPS = {"ibex", "ibex_top_tracing"}
KNOWN_BASES = {
    "uart": 0x80000000,
    "uart_master": 0x80000000,
    "gpio": 0x80040000,
    "rv_timer": 0x80060000,
    "spi_host": 0x80080000,
}
SRAM_BASE = 0x00100000
SRAM_SIZE = 128 * 1024
IBEX_RESET_VECTOR_OFFSET = 0x80
SOC_STACK_SIZE = 0x1000
SOC_TEST_STATUS_SIZE = 4
SOC_BOOT_PASS_MAGIC = 0x46534F43
SOC_UART_PASS_MAGIC = 0x55415254
SOC_UART_TEST_BYTE = 0x55
SOC_UART_BAUD_NCO = 0x8000
SOC_UART_BIT_CYCLES = 32


@dataclass(frozen=True, slots=True)
class SoCDevice:
    """One memory-mapped endpoint in the resolved SoC plan."""

    name: str
    base: int
    size: int = 0x1000
    builtin: bool = False

    @property
    def base_hex(self) -> str:
        return f"0x{self.base:08X}"

    @property
    def size_hex(self) -> str:
        return f"0x{self.size:08X}"

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "base": self.base_hex,
            "size": self.size_hex,
            "builtin": self.builtin,
        }


@dataclass(frozen=True, slots=True)
class SoCPlan:
    """Single source of truth for one resolved SoC composition."""

    host: str
    fabric: str
    devices: tuple[SoCDevice, ...]

    @property
    def external_devices(self) -> tuple[SoCDevice, ...]:
        return tuple(device for device in self.devices if not device.builtin)

    def device(self, name: str) -> SoCDevice:
        matches = tuple(device for device in self.devices if device.name == name)
        if len(matches) != 1:
            raise ValueError(f"expected exactly one SoC device named {name!r}, found {len(matches)}")
        return matches[0]

    @property
    def ibex_boot_addr(self) -> int:
        if self.host != "ibex":
            raise ValueError(f"host {self.host!r} has no Ibex boot address")
        return self.device("sram").base

    @property
    def reset_pc(self) -> int:
        if self.host != "ibex":
            raise ValueError(f"host {self.host!r} has no CPU reset PC")
        return self.ibex_boot_addr + IBEX_RESET_VECTOR_OFFSET

    def to_dict(self) -> dict[str, object]:
        return {
            "schema": 1,
            "host": self.host,
            "fabric": self.fabric,
            "devices": [device.to_dict() for device in self.devices],
        }


@dataclass(frozen=True, slots=True)
class RtlSourceSet:
    """Deterministic native FlexSoC RTL source manifest."""

    entries: tuple[str, ...]

    @classmethod
    def from_entries(cls, entries: list[str] | tuple[str, ...]) -> "RtlSourceSet":
        ordered: list[str] = []
        seen: set[str] = set()
        for raw in entries:
            entry = str(raw).strip()
            if not entry or entry.startswith("#") or entry in seen:
                continue
            seen.add(entry)
            ordered.append(entry)
        return cls(tuple(ordered))

    def write(self, path: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        body = "\n".join(self.entries)
        path.write_text(
            "# Auto-generated by FlexSoC native source resolver.\n"
            + body
            + ("\n" if body else ""),
            encoding="utf-8",
        )
        return path

@dataclass(slots=True)
class TlulFabric:
    """Generate the concrete TL-UL fabric with the vendored OpenTitan tlgen."""

    project_root: Path
    runner: ToolRunner

    @staticmethod
    def host_name(host: str) -> str:
        return "uart_host" if host == "uart" else "ibex"

    @staticmethod
    def host_node(name: str) -> dict[str, Any]:
        return {
            "name": name,
            "type": "host",
            "clock": "clk_i",
            "reset": "rst_ni",
            "xbar": False,
            "pipeline": False,
        }

    @staticmethod
    def device_node(device: SoCDevice) -> dict[str, Any]:
        return {
            "name": device.name,
            "type": "device",
            "clock": "clk_i",
            "reset": "rst_ni",
            "xbar": False,
            "addr_range": [{"base_addr": device.base_hex, "size_byte": device.size_hex}],
        }

    def payload(self, plan: SoCPlan) -> dict[str, Any]:
        host = self.host_name(plan.host)
        return {
            "name": "main",
            "type": "xbar",
            "clock": "clk_i",
            "clock_connections": {"clk_i": "main"},
            "reset": "rst_ni",
            "reset_connections": {"rst_ni": "main"},
            "nodes": [self.host_node(host), *(self.device_node(device) for device in plan.devices)],
            "connections": {host: [device.name for device in plan.devices]},
        }

    def generate(self, plan: SoCPlan, run_dir: Path, log: Path, *, on: str = "local") -> object:
        config = run_dir / "soc" / "xbar.hjson"
        SocFlow.write_json(config, self.payload(plan))
        outputs = (
            run_dir / "rtl" / "autogen" / "tl_main_pkg.sv",
            run_dir / "rtl" / "autogen" / "xbar_main.sv",
        )
        argv = (
            sys.executable,
            str(self.project_root / "src" / "util" / "tlgen.py"),
            "-t", str(config),
            "-o", str(run_dir),
        )
        return self.runner.run(
            CommandRequest(argv, self.project_root, {}, log, (config,), outputs), on=on
        )


@dataclass(slots=True)
class SoCDv:
    """Generate SoC-owned functional DV from the shared FlexSoC testbench model."""

    context: BackendContext

    @property
    def paths(self):
        return self.context.paths

    def generate(self, plan: SoCPlan) -> tuple[Path, ...]:
        """Generate the canonical SystemVerilog TB and SoC-owned M0 tests."""

        from flexsoc.backend.core import templates
        from flexsoc.backend.dv.tb.sv import SystemVerilogTestbench, TestbenchConfig

        period = max(1, int(float(self.context.values.get("CLK_PERIOD", "10"))))
        test = str(self.context.values.get("TEST_NAME", "smoke")).strip() or "smoke"
        config = TestbenchConfig(
            top="soc", rtldir=self.paths.rtl, simdir=self.paths.sim,
            syndir=self.paths.syn, prims=(), clk_period_ns=period,
            compiler="verilator", interface=plan.fabric,
            output=self.paths.tb / "sv",
        )
        if test in {"boot_smoke", "uart_smoke"}:
            if plan.host != "ibex":
                raise ValueError(f"{test} requires the ibex SoC host")
            if test == "uart_smoke":
                plan.device("uart")
            layout = SoCTestMemoryLayout.from_plan(plan)
            sram = layout.sram
            status_addr = layout.status_addr
            status_word = layout.status_word
            status_width = layout.status_word_width
            pass_magic = SOC_UART_PASS_MAGIC if test == "uart_smoke" else SOC_BOOT_PASS_MAGIC
            evidence_tag = "UARTFW" if test == "uart_smoke" else "BOOT"
            vmem = self.paths.tests / test / "sw" / "build" / "main.vmem"
            config = TestbenchConfig(
                top=config.top,
                rtldir=config.rtldir,
                simdir=config.simdir,
                syndir=config.syndir,
                prims=config.prims,
                clk_period_ns=config.clk_period_ns,
                compiler=config.compiler,
                interface=config.interface,
                io_delay_pct=config.io_delay_pct,
                vsv=config.vsv,
                output=config.output,
                devices=config.devices,
                force=config.force,
                dut_parameters=(("SramInitFile", f'"{vmem.as_posix()}"'),),
                extra_declarations=(
                    "  logic soc_boot_pass_seen = 1'b0;\n"
                    "  integer soc_boot_cycle = 0;\n"
                    "  integer soc_boot_pass_cycle = -1;"
                ),
                extra_statements=(
                    "  always_ff @(posedge clk_i) begin\n"
                    "    if (!rst_ni) begin\n"
                    "      soc_boot_cycle <= 0;\n"
                    "    end else begin\n"
                    "      soc_boot_cycle <= soc_boot_cycle + 1;\n"
                    "    end\n"
                    "    if (u_dut.sram_data_req && u_dut.sram_data_we &&\n"
                    f"        u_dut.sram_data_addr == {status_width}'h{status_word:X} &&\n"
                    f"        u_dut.sram_data_wdata == 32'h{pass_magic:08X} &&\n"
                    "        &u_dut.sram_data_wmask && !soc_boot_pass_seen) begin\n"
                    "      soc_boot_pass_seen <= 1'b1;\n"
                    "      soc_boot_pass_cycle <= soc_boot_cycle;\n"
                    f'      $display("[TB][{evidence_tag}] status=0x{status_addr:08X} expected=0x{pass_magic:08X} observed=0x%08X cycle=%0d", u_dut.sram_data_wdata, soc_boot_cycle);\n'
                    "    end\n"
                    "  end"
                ),
                post_checks=(
                    "for (integer soc_fw_wait = 0; soc_fw_wait < 1024 && !soc_boot_pass_seen; soc_fw_wait++) begin",
                    "  @(posedge clk_i);",
                    "end",
                    "if (!soc_boot_pass_seen) begin",
                    f'  $display("[TB][{evidence_tag}] FAIL status=0x{status_addr:08X} expected=0x{pass_magic:08X}");',
                    "  errors++;",
                    "end else begin",
                    f'  $display("[TB][{evidence_tag}] PASS entry=0x{plan.ibex_boot_addr:08X} reset_pc=0x{plan.reset_pc:08X} status=0x{status_addr:08X} magic=0x{pass_magic:08X} cycle=%0d", soc_boot_pass_cycle);',
                    "end",
                ),
            )
            if test == "uart_smoke":
                config = TestbenchConfig(
                    **{field: getattr(config, field) for field in TestbenchConfig.__dataclass_fields__
                       if field not in {"extra_declarations", "extra_statements", "post_checks"}},
                    extra_declarations=config.extra_declarations + (
                        "\n  logic uart_frame_seen = 1'b0;\n"
                        "  logic [7:0] uart_frame_byte = '0;"
                    ),
                    extra_statements=config.extra_statements + (
                        "\n  initial begin\n"
                        "    forever begin\n"
                        "      @(negedge tx_o);\n"
                        "      if (rst_ni && !uart_frame_seen) begin\n"
                        f"        repeat ({SOC_UART_BIT_CYCLES + SOC_UART_BIT_CYCLES // 2}) @(posedge clk_i);\n"
                        "        for (int i = 0; i < 8; i++) begin\n"
                        "          uart_frame_byte[i] = tx_o;\n"
                        f"          repeat ({SOC_UART_BIT_CYCLES}) @(posedge clk_i);\n"
                        "        end\n"
                        "        if (tx_o !== 1'b1) begin\n"
                        "          $display(\"[TB][UART] FAIL stop_bit=%b\", tx_o);\n"
                        "          errors++;\n"
                        "        end else if (uart_frame_byte !== 8'h55) begin\n"
                        "          $display(\"[TB][UART] FAIL expected=0x55 observed=0x%02x\", uart_frame_byte);\n"
                        "          errors++;\n"
                        "        end else begin\n"
                        "          uart_frame_seen = 1'b1;\n"
                        "          $display(\"[TB][UART] PASS byte=0x%02x\", uart_frame_byte);\n"
                        "        end\n"
                        "      end\n"
                        "    end\n"
                        "  end"
                    ),
                    post_checks=config.post_checks + (
                        "if (!uart_frame_seen) begin",
                        '  $display("[TB][UART] FAIL no valid TX frame observed");',
                        "  errors++;",
                        "end",
                    ),
                )

        generated = SystemVerilogTestbench().setup(config, clocks=self.context.clocks)
        created: list[Path] = list(generated)
        catalogue = ("smoke", "boot_smoke", "uart_smoke") if plan.host == "ibex" and any(d.name == "uart" for d in plan.external_devices) else (("smoke", "boot_smoke") if plan.host == "ibex" else ("smoke",))
        sram = plan.device("sram") if plan.host == "ibex" else SoCDevice("sram", SRAM_BASE, SRAM_SIZE, True)
        for test_name in catalogue:
            test_dir = self.paths.tests / test_name
            test_dir.mkdir(parents=True, exist_ok=True)
            for name in ("config.regs", "data_in.vec", "data_out.vec"):
                templates.write(
                    f"design/soc/dv/{test_name}/{name}.j2", test_dir / name, force=True,
                    sram_base=f"0x{sram.base:08X}",
                    sram_size=f"0x{sram.size:08X}",
                )
                created.append(test_dir / name)
        return tuple(created)


@dataclass(frozen=True, slots=True)
class SoCTestMemoryLayout:
    """Canonical CPU-test view of the SoC SRAM."""

    sram: SoCDevice

    def __post_init__(self) -> None:
        reserved = SOC_TEST_STATUS_SIZE + SOC_STACK_SIZE
        if self.sram.size <= reserved:
            raise ValueError("SoC SRAM is too small for test status plus software stack")
        if self.sram.base % 4 or self.sram.size % 4:
            raise ValueError("SoC SRAM base and size must be word aligned")
        if SOC_TEST_STATUS_SIZE != 4:
            raise ValueError("SoC test status must be one 32-bit word")

    @classmethod
    def from_plan(cls, plan: SoCPlan) -> "SoCTestMemoryLayout":
        return cls(plan.device("sram"))

    @property
    def ram_size(self) -> int:
        return self.sram.size - SOC_TEST_STATUS_SIZE - SOC_STACK_SIZE

    @property
    def status_addr(self) -> int:
        return self.sram.base + self.ram_size

    @property
    def stack_addr(self) -> int:
        return self.status_addr + SOC_TEST_STATUS_SIZE

    @property
    def status_word(self) -> int:
        return (self.status_addr - self.sram.base) // 4

    @property
    def status_word_width(self) -> int:
        words = self.sram.size // 4
        return max(1, (words - 1).bit_length())

@dataclass(slots=True)
class SoCSoftware:
    """Own SoC test-software sources, build products, and simulator memory images."""

    context: BackendContext
    runner: ToolRunner

    @property
    def paths(self):
        return self.context.paths

    @staticmethod
    def render_memory_map(plan: SoCPlan) -> str:
        """Render the software-visible SoC address map from the resolved plan."""

        lines = [
            "#ifndef FLEXSOC_SOC_MEMORY_MAP_H",
            "#define FLEXSOC_SOC_MEMORY_MAP_H",
            "",
            "#include <stdint.h>",
            "",
        ]
        for device in plan.devices:
            macro = re.sub(r"[^A-Za-z0-9]+", "_", device.name).upper().strip("_")
            lines.append(f"#define SOC_{macro}_BASE_ADDR UINT32_C(0x{device.base:08X})")
            lines.append(f"#define SOC_{macro}_SIZE UINT32_C(0x{device.size:08X})")
            lines.append("")
        lines.append("#endif")
        return "\n".join(lines) + "\n"

    def generate_memory_map(self, plan: SoCPlan) -> Path:
        """Materialize the canonical software projection of SoCPlan."""

        output = self.paths.sw / "include" / "soc_memory_map.h"
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(self.render_memory_map(plan), encoding="utf-8")
        return output

    def staged_driver(self, name: str) -> tuple[Path, Path]:
        """Return one immutable staged IP driver header/source pair."""

        driver_dir = self.paths.run / "ips" / name / "sw" / "drivers"
        header = driver_dir / f"{name}.h"
        source = driver_dir / f"{name}.c"
        missing = [path for path in (header, source) if not path.is_file()]
        if missing:
            raise FileNotFoundError(
                f"staged {name} driver is incomplete: " + ", ".join(str(path) for path in missing)
            )
        return header, source

    @staticmethod
    def _run_relative(path: Path, run: Path, origin: Path) -> str:
        """Return a stable run-relative path from one generated software directory."""

        target_parts = path.resolve().relative_to(run.resolve()).parts
        origin_parts = origin.resolve().relative_to(run.resolve()).parts
        return (Path(*([".."] * len(origin_parts))) / Path(*target_parts)).as_posix()

    def generate_boot_smoke(self, plan: SoCPlan) -> tuple[Path, ...]:
        """Materialize source-first boot software for the M0 CPU execution test."""

        from flexsoc.backend.core.render.templates import templates

        layout = SoCTestMemoryLayout.from_plan(plan)
        sram = layout.sram
        reserved = SOC_STACK_SIZE + SOC_TEST_STATUS_SIZE
        if sram.size <= reserved:
            raise ValueError("SoC SRAM is too small for boot test status plus software stack")
        status_origin = layout.status_addr
        stack_origin = layout.stack_addr
        sw = self.paths.tests / "boot_smoke" / "sw"
        sw.mkdir(parents=True, exist_ok=True)
        templates.write("design/soc/boot.S.j2", sw / "boot.S", force=True)
        templates.write(
            "design/soc/link.ld.j2", sw / "link.ld", force=True,
            ram_origin=f"0x{sram.base:08X}",
            ram_length=f"0x{layout.ram_size:X}",
            test_status_origin=f"0x{status_origin:08X}",
            test_status_length=f"0x{SOC_TEST_STATUS_SIZE:X}",
            stack_origin=f"0x{stack_origin:08X}",
            stack_length=f"0x{SOC_STACK_SIZE:X}",
        )
        templates.write(
            "design/soc/dv/boot_smoke/main.c.j2", sw / "main.c", force=True,
            pass_magic=f"0x{SOC_BOOT_PASS_MAGIC:08X}u",
        )
        (sw / "Makefile").write_text(
            SocFlow.render_makefile([]), encoding="utf-8"
        )
        return tuple(sw / name for name in ("boot.S", "link.ld", "main.c", "Makefile"))

    @staticmethod
    def binary_to_vmem(binary: Path, output: Path) -> Path:
        """Convert one little-endian RV32 flat binary into 32-bit readmemh words."""

        payload = binary.read_bytes()
        if len(payload) % 4:
            payload += b"\x00" * (4 - len(payload) % 4)
        words = [
            f"{int.from_bytes(payload[offset:offset + 4], 'little'):08x}"
            for offset in range(0, len(payload), 4)
        ]
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text("\n".join(words) + ("\n" if words else ""), encoding="utf-8")
        return output

    def build_boot_smoke(self, plan: SoCPlan, *, on: str = "local") -> object:
        """Compile the M0 C test and derive the VMEM consumed by the RTL SRAM."""

        sources = self.generate_boot_smoke(plan)
        sw = self.paths.tests / "boot_smoke" / "sw"
        elf = sw / "build" / "main.elf"
        binary = sw / "build" / "main.bin"
        vmem = sw / "build" / "main.vmem"
        result = self.runner.run(
            CommandRequest(
                ("make", "--no-print-directory", "-C", str(sw), "clean", "all"),
                self.context.project_root,
                {},
                self.paths.logs / "soc" / "sw-boot_smoke.log",
                inputs=sources,
                outputs=(elf, binary),
            ),
            on=on,
        )
        if getattr(result, "returncode", 0):
            return result
        if not binary.is_file():
            raise FileNotFoundError(f"boot_smoke binary was not produced: {binary}")
        self.binary_to_vmem(binary, vmem)
        return result

    def generate_uart_smoke(self, plan: SoCPlan) -> tuple[Path, ...]:
        """Generate M1 firmware using only the staged UART driver and SoC memory map."""

        from flexsoc.backend.core.render.templates import templates

        plan.device("uart")
        layout = SoCTestMemoryLayout.from_plan(plan)
        sram = layout.sram
        reserved = SOC_STACK_SIZE + SOC_TEST_STATUS_SIZE
        if sram.size <= reserved:
            raise ValueError("SoC SRAM is too small for UART test status plus software stack")

        status_origin = layout.status_addr
        stack_origin = layout.stack_addr
        sw = self.paths.tests / "uart_smoke" / "sw"
        sw.mkdir(parents=True, exist_ok=True)

        memory_map = self.generate_memory_map(plan)
        driver_header, driver_source = self.staged_driver("uart")

        templates.write("design/soc/boot.S.j2", sw / "boot.S", force=True)
        templates.write(
            "design/soc/link.ld.j2", sw / "link.ld", force=True,
            ram_origin=f"0x{sram.base:08X}",
            ram_length=f"0x{layout.ram_size:X}",
            test_status_origin=f"0x{status_origin:08X}",
            test_status_length=f"0x{SOC_TEST_STATUS_SIZE:X}",
            stack_origin=f"0x{stack_origin:08X}",
            stack_length=f"0x{SOC_STACK_SIZE:X}",
        )
        templates.write(
            "design/soc/dv/uart_smoke/main.c.j2", sw / "main.c", force=True,
            pass_magic=f"0x{SOC_UART_PASS_MAGIC:08X}u",
            test_byte=f"0x{SOC_UART_TEST_BYTE:02X}",
        )

        period_ns = float(self.context.values.get("CLK_PERIOD", "10"))
        if period_ns <= 0:
            raise ValueError("CLK_PERIOD must be positive")
        sysclk_hz = int(round(1_000_000_000.0 / period_ns))
        baud_rate = max(1, (sysclk_hz * SOC_UART_BAUD_NCO) >> 20)

        templates.write(
            "design/soc/dv/uart_smoke/Makefile.j2", sw / "Makefile", force=True,
            soc_include=self._run_relative(memory_map.parent, self.paths.run, sw),
            uart_driver_dir=self._run_relative(driver_source.parent, self.paths.run, sw),
            sysclk_hz=sysclk_hz,
            baud_rate=baud_rate,
        )
        return (
            sw / "boot.S", sw / "link.ld", sw / "main.c", sw / "Makefile",
            memory_map, driver_header, driver_source,
        )

    def build_uart_smoke(self, plan: SoCPlan, *, on: str = "local") -> object:
        """Compile M1 firmware against the immutable staged UART driver."""

        sources = self.generate_uart_smoke(plan)
        sw = self.paths.tests / "uart_smoke" / "sw"
        elf = sw / "build" / "main.elf"
        binary = sw / "build" / "main.bin"
        vmem = sw / "build" / "main.vmem"
        result = self.runner.run(
            CommandRequest(
                ("make", "--no-print-directory", "-C", str(sw), "clean", "all"),
                self.context.project_root,
                {},
                self.paths.logs / "soc" / "sw-uart_smoke.log",
                inputs=sources,
                outputs=(elf, binary),
            ),
            on=on,
        )
        if getattr(result, "returncode", 0):
            return result
        if not binary.is_file():
            raise FileNotFoundError(f"uart_smoke binary was not produced: {binary}")
        self.binary_to_vmem(binary, vmem)
        return result

class SocFlow:
    """Resolve and generate one SoC composition for the current backend context."""

    def __init__(self, context: BackendContext, runner: ToolRunner | None = None):
        self.context = context
        self.runner = runner or ToolRunner(project_root=context.project_root)
        self.fabric = TlulFabric(context.project_root, self.runner)
        self.dv = SoCDv(context)
        self.software = SoCSoftware(context, self.runner)

    @property
    def paths(self):
        return self.context.paths

    @property
    def values(self):
        return self.context.values

    def run_target(self, target, *, on: str = "local"):
        """Execute the single public SoC target."""

        if target.action != "soc":
            raise ValueError(f"unsupported SoC action: {target.action!r}")
        action = str(self.values.get("SOC_ACTION", "generate")).strip().lower()
        if action == "show":
            return self.show()
        if action == "build":
            return self.build(on=on)
        if action == "simulate":
            return self.simulate(on=on)
        if action == "view":
            return self.view(on=on)
        if action != "generate":
            raise ValueError(
                f"unsupported SoC option {action!r}; expected generate, build, simulate, view, or show"
            )
        return self.generate(on=on)

    def prepare_run(self) -> tuple[Path, ...]:
        """Create canonical SoC run directories and merge staged IP RTL filelists."""

        run = self.paths.run
        for path in (
            run / "ips", self.paths.rtl, self.paths.logs, self.paths.doc,
            self.paths.tb, self.paths.sim, self.paths.tests, self.paths.model, run / "soc",
        ):
            path.mkdir(parents=True, exist_ok=True)
        ips = self.loaded_ip_dirs()
        (run / "ips" / "loaded_ips.txt").write_text(
            "".join(f"{ip.name}\n" for ip in ips), encoding="utf-8"
        )
        sources = self.merged_rtl_sources(ips) if ips else ()
        (run / "rtl" / "rtl_ip.f").write_text(
            "\n".join(sources) + ("\n" if sources else ""), encoding="utf-8"
        )
        (run / "rtl" / "rtl_list.f").unlink(missing_ok=True)
        return ips

    def loaded_ip_dirs(self) -> tuple[Path, ...]:
        ips = self.paths.run / "ips"
        if not ips.is_dir():
            return ()
        return tuple(sorted(path for path in ips.iterdir() if path.is_dir()))

    def resolve_plan(self) -> SoCPlan:
        """Resolve host infrastructure plus explicitly staged reusable IPs."""

        host = self.normalize_host(str(self.values.get("HOST", "ibex")))
        fabric = self.normalize_fabric(str(self.values.get("FABRIC", "tlul")))
        loaded = tuple(path.name for path in self.loaded_ip_dirs())

        devices = list(self.builtin_devices(host))
        used_names = {device.name for device in devices}
        used_bases = {device.base for device in devices}
        next_base = 0x800A0000

        for name in loaded:
            if name in HOST_IPS or name in used_names:
                continue
            base = KNOWN_BASES.get(name)
            if base is None:
                while next_base in used_bases:
                    next_base += 0x00020000
                base = next_base
                next_base += 0x00020000
            if base in used_bases:
                raise ValueError(f"duplicate SoC base address 0x{base:08X} for {name}")
            devices.append(SoCDevice(name, base))
            used_names.add(name)
            used_bases.add(base)

        return SoCPlan(host, fabric, tuple(devices))

    @staticmethod
    def normalize_host(host: str) -> str:
        host = host.strip().lower()
        if host not in SUPPORTED_HOSTS:
            raise ValueError(f"unsupported SoC host {host!r}; expected one of: {', '.join(sorted(SUPPORTED_HOSTS))}")
        return host

    @staticmethod
    def normalize_fabric(fabric: str) -> str:
        fabric = fabric.strip().lower()
        if fabric not in SUPPORTED_FABRICS:
            raise ValueError("unsupported SoC fabric {!r}; currently supported: tlul".format(fabric))
        return fabric

    @staticmethod
    def builtin_devices(host: str) -> tuple[SoCDevice, ...]:
        """Return only infrastructure intrinsically required by a host."""

        if host == "ibex":
            return (SoCDevice("sram", SRAM_BASE, SRAM_SIZE, True),)
        if host == "uart":
            return ()
        raise ValueError(f"unsupported SoC host {host!r}")

    def write_plan(self, plan: SoCPlan) -> Path:
        return self.write_json(self.paths.run / "soc" / "plan.json", plan.to_dict())

    def show(self, *, as_json: bool = False) -> int:
        """Print the stored plan, or the currently resolved plan when not generated yet."""

        payload = self.resolve_plan().to_dict()
        print(json.dumps(payload, indent=None if as_json else 2, sort_keys=True))
        return 0

    def generate(self, *, on: str = "local") -> object:
        """Generate the complete hardware composition for the current SoC plan."""

        self.prepare_run()
        plan = self.resolve_plan()
        self.write_plan(plan)
        result = self.fabric.generate(plan, self.paths.run, self.paths.logs / "soc" / "tlgen.log", on=on)
        if getattr(result, "returncode", 0):
            return result
        self.generate_top(plan)
        self.write_soc_rtl_filelist(plan)
        self.write_native_rtl_filelist(plan, on=on)
        return self.paths.run / "soc" / "plan.json"

    def vendor_roots(self) -> tuple[Path, Path]:
        """Return the pinned vendor roots required by the current M0 SoC."""

        roots = (
            self.context.project_root / "vendor" / "lowrisc_ibex",
            self.context.project_root / "vendor" / "lowrisc_ip",
        )
        missing = tuple(path for path in roots if not path.is_dir())
        if missing:
            names = ", ".join(path.name for path in missing)
            raise FileNotFoundError(
                f"missing vendored SoC dependencies: {names}; fetch the pinned vendor inputs first"
            )
        return roots


    def native_rtl_inputs(self) -> tuple[Path, ...]:
        """Return concrete RTL source inputs referenced by the native rtl.f."""

        filelist = self.paths.rtl / "rtl.f"
        if not filelist.is_file():
            raise FileNotFoundError(f"missing native SoC RTL filelist: {filelist}")

        inputs: list[Path] = [filelist]
        for raw in filelist.read_text(encoding="utf-8").splitlines():
            entry = raw.strip()
            if not entry or entry.startswith("+"):
                continue
            path = Path(entry)
            resolved = path if path.is_absolute() else (self.paths.run / path).resolve()
            if not resolved.is_file():
                raise FileNotFoundError(f"native rtl.f references missing source: {resolved}")
            inputs.append(resolved)

        return tuple(dict.fromkeys(inputs))

    def native_verilator_lint(self, *, on: str = "local") -> object:
        """Elaborate/lint the generated SoC directly from the native rtl.f."""

        filelist = self.paths.rtl / "rtl.f"
        argv = (
            str(self.values.get("VERILATOR", "verilator")),
            "--lint-only",
            "--sv",
            "--timing",
            "-Wall",
            "-Wno-fatal",
            "-f",
            str(filelist),
            "--top-module",
            "soc",
        )
        return self.runner.run(
            CommandRequest(
                argv,
                self.paths.run,
                {},
                self.paths.logs / "soc" / "build.log",
                inputs=self.native_rtl_inputs(),
            ),
            on=on,
        )

    def native_verilator_simulator(self, *, on: str = "local") -> tuple[object, Path]:
        """Build the generated SoC functional testbench directly with Verilator."""

        filelist = self.paths.rtl / "rtl.f"
        sv_dir = self.paths.tb / "sv"
        source = sv_dir / "soc_tb.sv"
        if not source.is_file():
            raise FileNotFoundError(f"generated SoC testbench not found: {source}")

        build_dir = self.paths.sim / "verilator"
        shutil.rmtree(build_dir, ignore_errors=True)
        build_dir.parent.mkdir(parents=True, exist_ok=True)
        simulator = build_dir / "Vsoc_tb"

        tb_inputs = tuple(sorted(path for path in sv_dir.rglob("*") if path.is_file()))
        inputs = tuple(dict.fromkeys((*self.native_rtl_inputs(), *tb_inputs)))

        argv = (
            str(self.values.get("VERILATOR", "verilator")),
            "-Wall",
            "-Wno-fatal",
            "--binary",
            "--timing",
            "--Mdir",
            str(build_dir),
            "--trace-fst",
            "--trace-structs",
            f"-I{sv_dir}",
            f"-I{self.paths.rtl}",
            "-f",
            str(filelist),
            str(source),
            "--top-module",
            "soc_tb",
        )
        result = self.runner.run(
            CommandRequest(
                argv,
                self.paths.run,
                {},
                self.paths.logs / "soc" / "sim-build.log",
                inputs=inputs,
                outputs=(simulator,),
            ),
            on=on,
        )
        return result, simulator
    def build(self, *, on: str = "local") -> object:
        """Generate and lint/elaborate the SoC through native Verilator."""

        generated = self.generate(on=on)
        if getattr(generated, "returncode", 0):
            return generated
        return self.native_verilator_lint(on=on)

    def simulate(self, *, on: str = "local") -> object:
        """Build selected CPU software, then build and run the native SoC simulator."""

        generated = self.generate(on=on)
        if getattr(generated, "returncode", 0):
            return generated

        plan = self.resolve_plan()
        test = str(self.values.get("TEST_NAME", "smoke")).strip() or "smoke"
        runtime_inputs: tuple[Path, ...] = ()

        software_builder = {
            "boot_smoke": self.software.build_boot_smoke,
            "uart_smoke": self.software.build_uart_smoke,
        }.get(test)
        if software_builder is not None:
            software = software_builder(plan, on=on)
            if getattr(software, "returncode", 0):
                return software
            sw_build = self.paths.tests / test / "sw" / "build"
            elf = sw_build / "main.elf"
            vmem = sw_build / "main.vmem"
            missing = [path for path in (elf, vmem) if not path.is_file()]
            if missing:
                raise FileNotFoundError(
                    f"{test} software build is incomplete: "
                    + ", ".join(str(path) for path in missing)
                )
            runtime_inputs = (elf, vmem)

        built, simulator = self.native_verilator_simulator(on=on)
        if getattr(built, "returncode", 0):
            return built

        from ...dv.func.functional import FunctionalFlow

        return FunctionalFlow(self.runner).run_systemverilog(
            top="soc",
            test_root=self.paths.tests,
            tb_dir=self.paths.tb,
            sim_dir=self.paths.sim,
            test_name=test,
            compiler="verilator",
            seed=int(self.values.get("SEED", "1")),
            executable=simulator,
            extra_inputs=runtime_inputs,
            wave_file=self.paths.sim / f"soc_tb_{test}.fst",
            log=self.paths.logs / "soc" / "sim.log",
            on=on,
        )

    def view(self, *, on: str = "local") -> object:
        """Open the waveform produced by the selected canonical SoC test."""

        from ...core.flow.session import WorkspaceFlow

        test = str(self.values.get("TEST_NAME", "smoke")).strip() or "smoke"
        wave = WorkspaceFlow._select_waveform(self.paths.sim, "soc", test)
        viewer = str(self.values.get("WAVE_VIEWER", "surfer"))
        env = WorkspaceFlow._viewer_environment(
            viewer, str(self.values.get("SURFER_BACKEND", "auto"))
        )
        print(f"[wave] test={test} {wave}", flush=True)
        return self.runner.run(
            CommandRequest(
                (viewer, str(wave)), wave.parent, env,
                self.paths.logs / "viewer" / "view.log", inputs=(wave,),
            ),
            on=on,
        )

    @staticmethod
    def write_json(path: Path, payload: dict[str, Any]) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        return path.resolve()

    @staticmethod
    def read_filelists(ip_dir: Path) -> tuple[str, ...]:
        files = (ip_dir / "rtl" / "rtl_common.f", ip_dir / "rtl" / "rtl_ip.f")
        missing = [path for path in files if not path.is_file()]
        if missing:
            raise FileNotFoundError("missing canonical IP filelist(s): " + ", ".join(map(str, missing)))
        return tuple(
            line
            for flist in files
            for raw in flist.read_text(encoding="utf-8").splitlines()
            if (line := raw.strip()) and not line.startswith("#")
        )

    @staticmethod
    def merged_rtl_sources(ips: tuple[Path, ...]) -> tuple[str, ...]:
        merged: list[str] = []
        seen: set[str] = set()
        for ip in ips:
            for source in SocFlow.read_filelists(ip):
                if source not in seen:
                    seen.add(source)
                    merged.append(source)
        return tuple(merged)


    @staticmethod
    def _resolve_native_flist_entry(
        entry: str,
        *,
        release_root: Path,
        project_root: Path,
        run_root: Path,
    ) -> str:
        """Resolve one staged-release file-list entry without filesystem scanning."""

        directive = ""
        value = entry
        if entry.startswith("+incdir+"):
            directive = "+incdir+"
            value = entry[len(directive):]

        source = Path(value)
        if source.is_absolute():
            resolved = source
        else:
            candidates = (
                release_root / source,
                project_root / source,
                run_root / source,
            )
            resolved = next((candidate for candidate in candidates if candidate.exists()), None)
            if resolved is None:
                raise FileNotFoundError(
                    f"unresolved staged RTL entry {entry!r} from {release_root}"
                )

        resolved = resolved.resolve()
        try:
            rendered = resolved.relative_to(run_root.resolve()).as_posix()
        except ValueError:
            rendered = resolved.as_posix()
        return directive + rendered

    def resolve_soc_rtl_sources(self, plan: SoCPlan) -> RtlSourceSet:
        """Resolve FlexSoC-owned SoC RTL sources from explicit release contracts."""

        del plan
        entries: list[str] = []

        for release_root in self.loaded_ip_dirs():
            for entry in self.read_filelists(release_root):
                normalized = entry.replace("\\", "/")
                if (
                    "rtl/deps/flexsoc/prim_opentitan/" in normalized
                    or "rtl/deps/flexsoc/pkgs/" in normalized
                ):
                    continue
                entries.append(
                    self._resolve_native_flist_entry(
                        entry,
                        release_root=release_root,
                        project_root=self.context.project_root,
                        run_root=self.paths.run,
                    )
                )

        generated = (
            self.paths.rtl / "autogen" / "tl_main_pkg.sv",
            self.paths.rtl / "autogen" / "xbar_main.sv",
            self.paths.rtl / "soc.sv",
        )
        for source in generated:
            if not source.is_file():
                raise FileNotFoundError(
                    f"missing generated SoC RTL source required by native resolver: {source}"
                )
            entries.append(source.resolve().relative_to(self.paths.run.resolve()).as_posix())

        return RtlSourceSet.from_entries(entries)

    def write_soc_rtl_filelist(self, plan: SoCPlan) -> Path:
        """Write the native SoC-owned source manifest."""

        return self.resolve_soc_rtl_sources(plan).write(self.paths.rtl / "rtl_soc.f")



    def materialize_native_primitives(self) -> Path:
        """Build one native primitive library, preferring FlexSoC-owned RTL.

        FlexSoC's frozen prim_opentitan sources win. Missing abstract primitives
        are filled from the pinned lowRISC generic implementations.
        """

        flexsoc_root = self.context.project_root / "hw" / "ips" / "prim_opentitan"
        lowrisc_root = (
            self.context.project_root
            / "vendor"
            / "lowrisc_ip"
            / "ip"
            / "prim_generic"
            / "rtl"
        )
        if not flexsoc_root.is_dir():
            raise FileNotFoundError(
                f"missing FlexSoC primitive library required by native SoC flow: {flexsoc_root}"
            )
        if not lowrisc_root.is_dir():
            raise FileNotFoundError(
                f"missing lowRISC generic primitive fallback required by native SoC flow: {lowrisc_root}"
            )

        shutil.rmtree(self.paths.rtl / "prim_generic", ignore_errors=True)
        output_root = self.paths.rtl / "prim_native"
        shutil.rmtree(output_root, ignore_errors=True)
        output_root.mkdir(parents=True, exist_ok=True)

        count = 0
        for source in sorted(flexsoc_root.glob("prim_*.sv")):
            target = output_root / source.name
            target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
            count += 1

        for source in sorted(lowrisc_root.glob("prim_generic_*.sv")):
            target_name = source.name.replace("prim_generic_", "prim_", 1)
            target = output_root / target_name
            if target.exists():
                continue
            text = source.read_text(encoding="utf-8").replace("prim_generic_", "prim_")
            target.write_text(text, encoding="utf-8")
            count += 1

        if count == 0:
            raise FileNotFoundError("native primitive library resolved no RTL sources")
        return output_root

    def materialize_native_packages(self) -> Path:
        """Materialize the canonical FlexSoC-owned package/include library."""

        source_root = self.context.project_root / "hw" / "ips" / "pkgs"
        if not source_root.is_dir():
            raise FileNotFoundError(
                f"missing FlexSoC package library required by native SoC flow: {source_root}"
            )

        output_root = self.paths.rtl / "pkgs_native"
        shutil.rmtree(output_root, ignore_errors=True)
        output_root.mkdir(parents=True, exist_ok=True)

        count = 0
        for source in sorted(source_root.iterdir()):
            if not source.is_file() or source.suffix not in {".sv", ".svh"}:
                continue
            target = output_root / source.name
            target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
            count += 1

        top_pkg = output_root / "top_pkg.sv"
        if not top_pkg.is_file():
            raise FileNotFoundError(
                f"FlexSoC native package library is missing required top_pkg.sv: {top_pkg}"
            )
        if count == 0:
            raise FileNotFoundError("native package library resolved no sources")
        return output_root
    def write_native_rtl_filelist(self, plan: SoCPlan, *, on: str = "local") -> Path:
        """Generate the complete tool-ready SoC RTL closure with Slang."""

        from types import SimpleNamespace

        top_file = self.paths.rtl / "soc.sv"
        ownership_file = self.paths.rtl / "rtl_soc.f"
        if not top_file.is_file():
            raise FileNotFoundError(f"missing generated SoC top: {top_file}")
        if not ownership_file.is_file():
            raise FileNotFoundError(f"missing native SoC ownership manifest: {ownership_file}")

        primitive_root = self.materialize_native_primitives()
        package_root = self.materialize_native_packages()

        lowrisc = self.context.project_root / "vendor" / "lowrisc_ip"
        if not lowrisc.is_dir():
            raise FileNotFoundError(
                f"missing pinned lowRISC IP vendor tree required by SoC RTL closure: {lowrisc}"
            )

        search_roots: list[Path] = [primitive_root, package_root]

        for relative in (
            Path("ip/prim/rtl"),
            Path("ip/tlul/rtl"),
            Path("ip/lc_ctrl/rtl"),
        ):
            candidate = lowrisc / relative
            if candidate.is_dir():
                search_roots.append(candidate)

        if plan.host == "ibex":
            ibex_rtl = self.context.project_root / "vendor" / "lowrisc_ibex" / "rtl"
            if not ibex_rtl.is_dir():
                raise FileNotFoundError(
                    f"missing pinned Ibex RTL root required by SoC RTL closure: {ibex_rtl}"
                )
            search_roots.insert(2, ibex_rtl)

        seed_files: list[Path] = []
        include_dirs: list[Path] = [package_root]
        for raw in ownership_file.read_text(encoding="utf-8").splitlines():
            entry = raw.strip()
            if not entry or entry.startswith("#"):
                continue
            if entry.startswith("+incdir+"):
                for item in entry[len("+incdir+"):].split("+"):
                    if not item:
                        continue
                    path = Path(item)
                    include_dirs.append(
                        path if path.is_absolute() else (self.paths.run / path).resolve()
                    )
                continue

            path = Path(entry)
            source = path if path.is_absolute() else (self.paths.run / path).resolve()
            if not source.is_file():
                raise FileNotFoundError(f"missing rtl_soc.f seed source: {source}")
            if source != top_file.resolve():
                seed_files.append(source)

        top_pkg = package_root / "top_pkg.sv"
        package_files = [top_pkg]
        package_files.extend(
            source
            for source in sorted(package_root.glob("*_pkg.sv"))
            if source != top_pkg
        )

        discovery_args: list[str] = []
        if plan.host == "ibex":
            discovery_args.extend(("-DSYNTHESIS", "-DRVFI"))
        for directory in dict.fromkeys(include_dirs):
            discovery_args.extend(("-I", str(directory)))
        discovery_args.extend(str(source) for source in package_files)
        discovery_args.extend(str(source) for source in seed_files)

        output = self.paths.rtl / "rtl.f"
        RtlFlow.run_flist(
            SimpleNamespace(
                root=self.paths.run,
                search_root=search_roots,
                top_file=top_file,
                top="soc",
                extra_args=shlex.join(discovery_args),
                slang=str(self.values.get("SLANG", "slang")),
                output=output,
                common_out=None,
                ip_out=None,
                common_root=[],
                synthesis=False,
            ),
            runner=self.runner,
            on=on,
        )

        if not output.is_file() or not output.read_text(encoding="utf-8").strip():
            raise RuntimeError(f"Slang did not produce a usable SoC RTL filelist: {output}")

        raw_lines = [
            line
            for line in output.read_text(encoding="utf-8").splitlines()
            if line.strip() != "+define+SYNTHESIS"
        ]

        # Preserve directives first, then force canonical FlexSoC packages before
        # dependent RTL such as tlul_pkg.sv. Remaining Slang closure order follows.
        directives = [line for line in raw_lines if line.startswith("+")]
        package_entries = []
        for source in package_files:
            resolved = source.resolve()
            try:
                rendered = resolved.relative_to(self.paths.run.resolve()).as_posix()
            except ValueError:
                rendered = resolved.as_posix()
            package_entries.append(rendered)

        package_set = set(package_entries)
        body = [
            line
            for line in raw_lines
            if not line.startswith("+") and line not in package_set
        ]

        ordered: list[str] = []
        seen: set[str] = set()
        for line in (*directives, *package_entries, *body):
            if not line or line in seen:
                continue
            seen.add(line)
            ordered.append(line)

        output.write_text("\n".join(ordered) + "\n", encoding="utf-8")
        return output

    def find_sv_file(self, module_name: str) -> Path | None:
        """Resolve a loaded device only from its frozen staged release."""

        rtl = self.paths.run / "ips" / module_name / "rtl"
        if not rtl.is_dir():
            return None
        exact = rtl / f"{module_name}.sv"
        if exact.is_file():
            return exact
        matches = sorted(rtl.rglob(f"{module_name}.sv"))
        return matches[0] if len(matches) == 1 else None

    @staticmethod
    def parse_ports(sv_file: Path) -> list[tuple[str, str | None, str]]:
        content = sv_file.read_text(encoding="utf-8")
        content = re.sub(r"//.*?$|/\*.*?\*/", "", content, flags=re.DOTALL | re.MULTILINE)
        content = re.sub(r"\s+", " ", content)
        match = re.search(r"\bmodule\b.*?\((?P<plist>.*?)\)\s*;", content)
        if not match:
            return []
        ports = []
        for declaration in (part.strip() for part in match.group("plist").split(",")):
            parsed = re.match(r"^\s*(input|output)\b\s+(.*)$", declaration)
            if not parsed:
                continue
            direction, rest = parsed.group(1), parsed.group(2).strip()
            name_match = re.search(r"([A-Za-z_]\w*)\s*$", rest)
            if not name_match:
                continue
            ports.append((direction, rest[:name_match.start(1)].strip() or None, name_match.group(1)))
        return ports

    @staticmethod
    def collect_soc_ports(modules_ports: dict[str, list[tuple[str, str | None, str]]]) -> dict[str, str]:
        all_ports: dict[str, str] = {}
        for ports in modules_ports.values():
            for direction, dtype, name in ports:
                all_ports.setdefault(name, direction + " " + (dtype or ""))
        return all_ports

    @staticmethod
    def add_host_ports(host: str, all_ports: dict[str, str]) -> dict[str, str]:
        if host == "uart":
            all_ports.setdefault("cio_rx_i", "input logic")
            all_ports.setdefault("cio_tx_o", "output logic")
            all_ports.setdefault("cio_tx_en_o", "output logic")
        return all_ports

    @staticmethod
    def generate_port_decls(all_ports: dict[str, str]) -> list[str]:
        ports = [
            (name, direction)
            for name, direction in all_ports.items()
            if "tl_" not in name and name not in {"clk_i", "rst_ni"} and "intr" not in name
        ]
        return [
            f"  {direction} {name}{',' if index + 1 < len(ports) else ''}"
            for index, (name, direction) in enumerate(ports)
        ]

    @staticmethod
    def generate_module_inst(module: str, ports: list[tuple[str, str | None, str]]) -> str:
        from flexsoc.backend.core.render.templates import templates
        connections = [".clk_i", ".rst_ni", f".tl_i(tl_{module}_h2d)", f".tl_o(tl_{module}_d2h)"]
        connections.extend(
            f".{name}"
            for _direction, _dtype, name in ports
            if name not in {"tl_i", "tl_o", "clk_i", "rst_ni"}
            and not any(token in name for token in ("intr", "alert_rx", "alert_tx"))
        )
        connections.extend(
            f".{name}()"
            for _direction, _dtype, name in ports
            if any(token in name for token in ("intr", "alert_rx", "alert_tx"))
        )
        return templates.render("design/soc/module_instance.sv.j2", module=module, connections=connections)

    @staticmethod
    def defaults(plan: SoCPlan) -> str:
        from flexsoc.backend.core.render.templates import templates

        values: dict[str, object] = {}
        if plan.host == "ibex":
            layout = SoCTestMemoryLayout.from_plan(plan)
            sram = layout.sram
            values.update(
                mem_size=sram.size,
                boot_addr=f"32'h{plan.ibex_boot_addr:08X}",
            )
        return templates.render(f"design/soc/defaults_{plan.host}.sv.j2", **values)

    @staticmethod
    def render_xbar_connections(plan: SoCPlan) -> str:
        from flexsoc.backend.core.render.templates import templates
        connections: list[str] = []
        if plan.host == "ibex":
            connections.extend((
                ".tl_ibex_i (tl_ibex_h2d)", ".tl_ibex_o (tl_ibex_d2h)",
                ".tl_sram_o (tl_sram_h2d)", ".tl_sram_i (tl_sram_d2h)",
            ))
        elif plan.host == "uart":
            connections.extend((
                ".tl_uart_host_i (tl_uart_host_h2d)", ".tl_uart_host_o (tl_uart_host_d2h)",
            ))
        for device in plan.external_devices:
            connections.extend((
                f".tl_{device.name}_o (tl_{device.name}_h2d)",
                f".tl_{device.name}_i (tl_{device.name}_d2h)",
            ))
        return templates.render("design/soc/xbar.sv.j2", connections=connections)

    def module_ports(self, plan: SoCPlan) -> dict[str, list[tuple[str, str | None, str]]]:
        parsed = {}
        for device in plan.external_devices:
            source = self.find_sv_file(device.name)
            if source is None:
                raise FileNotFoundError(
                    f"loaded SoC device {device.name!r} has no unique rtl/{device.name}.sv"
                )
            parsed[device.name] = self.parse_ports(source)
        return parsed

    def render_soc_sv(self, plan: SoCPlan, modules_ports: dict[str, list[tuple[str, str | None, str]]]) -> str:
        from flexsoc.backend.core.render.templates import templates
        all_ports = self.add_host_ports(plan.host, self.collect_soc_ports(modules_ports))
        port_declarations = "\n".join(self.generate_port_decls(all_ports))
        tl_signals = "\n".join(
            line
            for module in modules_ports
            for line in (
                f"  tlul_pkg::tl_h2d_t tl_{module}_h2d;",
                f"  tlul_pkg::tl_d2h_t tl_{module}_d2h;",
            )
        )
        if tl_signals:
            tl_signals += "\n"
        instances = "\n".join(
            self.generate_module_inst(module, ports) for module, ports in modules_ports.items()
        )
        return templates.render(
            "design/soc/soc.sv.j2",
            port_declarations=port_declarations,
            defaults=self.defaults(plan),
            tl_signals=tl_signals,
            xbar=self.render_xbar_connections(plan),
            module_instances=instances,
        )

    @staticmethod
    def write_soc_core(path: Path, plan: SoCPlan) -> Path:
        from flexsoc.backend.core.render.templates import templates
        return templates.write(
            "design/soc/soc.core.j2", path, force=True,
            host=plan.host, modules=[device.name for device in plan.external_devices],
            merge_key="<<: *default_target",
        )

    def generate_top(self, plan: SoCPlan) -> Path:
        modules_ports = self.module_ports(plan)
        all_ports = self.add_host_ports(plan.host, self.collect_soc_ports(modules_ports))
        output = self.paths.rtl / "soc.sv"
        output.write_text(self.render_soc_sv(plan, modules_ports), encoding="utf-8")
        self.dv.generate(plan)
        self.software.generate_memory_map(plan)
        if plan.host == "ibex":
            self.software.generate_boot_smoke(plan)
            if any(device.name == "uart" for device in plan.external_devices):
                self.software.generate_uart_smoke(plan)
        self.write_soc_core(self.paths.run / "soc.core", plan)
        return output

    @staticmethod
    def copy_driver_files(ips_dir: Path, sw_dir: Path) -> list[str]:
        if not ips_dir.exists():
            return []
        modules: list[str] = []
        for ip_dir in sorted((path for path in ips_dir.iterdir() if path.is_dir()), key=lambda path: path.name):
            driver_dir = ip_dir / "sw" / "drivers"
            files = sorted(driver_dir.glob("*.h")) + sorted(driver_dir.glob("*.c"))
            if not files:
                continue
            for source in files:
                shutil.copy2(source, sw_dir / source.name)
            modules.append(ip_dir.name)
        return modules

    @staticmethod
    def render_main_c(modules: list[str], host: str) -> str:
        from flexsoc.backend.core.render.templates import templates
        return templates.render("design/soc/main.c.j2", modules=modules, uses_uart=host == "uart" and "uart" in modules)

    @staticmethod
    def render_makefile(modules: list[str]) -> str:
        from flexsoc.backend.core.render.templates import templates
        objects = " ".join(f"$(BUILD_DIR)/{module}.o" for module in ("main", *modules))
        return templates.render("design/soc/Makefile.j2", obj_list=f"{objects} $(BUILD_DIR)/boot.o")

    def generate_software(self, plan: SoCPlan) -> tuple[Path, list[str]]:
        """Generate the reusable SoC software scaffold from the resolved memory map."""

        from flexsoc.backend.core.render.templates import templates
        sw = self.paths.sw
        sw.mkdir(parents=True, exist_ok=True)
        modules = self.copy_driver_files(self.paths.run / "ips", sw)
        templates.write("design/soc/boot.S.j2", sw / "boot.S", force=True)
        layout = SoCTestMemoryLayout.from_plan(plan)
        sram = layout.sram
        if sram.size <= SOC_STACK_SIZE + SOC_TEST_STATUS_SIZE:
            raise ValueError("SoC SRAM is too small for the reserved software stack and test status")
        reserved = SOC_STACK_SIZE + SOC_TEST_STATUS_SIZE
        status_origin = layout.status_addr
        stack_origin = layout.stack_addr
        templates.write(
            "design/soc/link.ld.j2", sw / "link.ld", force=True,
            ram_origin=f"0x{sram.base:08X}", ram_length=f"0x{layout.ram_size:X}",
            test_status_origin=f"0x{status_origin:08X}",
            test_status_length=f"0x{SOC_TEST_STATUS_SIZE:X}",
            stack_origin=f"0x{stack_origin:08X}", stack_length=f"0x{SOC_STACK_SIZE:X}",
        )
        (sw / "main.c").write_text(self.render_main_c(modules, plan.host), encoding="utf-8")
        (sw / "Makefile").write_text(self.render_makefile(modules), encoding="utf-8")
        return sw, modules
