/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/c++ 13.3.0) */

(* top =  1  *)
(* src = "../../rtl/gpio.sv:2.8" *)
module gpio(clk_i, rst_ni, cio_gpio_i, cio_gpio_o, cio_gpio_en_o, intr_gpio_o, tl_i, tl_o);
  (* hdlname = "clk_i" *)
  input clk_i;
  wire clk_i;
  (* hdlname = "rst_ni" *)
  input rst_ni;
  wire rst_ni;
  (* hdlname = "cio_gpio_i" *)
  input [3:0] cio_gpio_i;
  wire [3:0] cio_gpio_i;
  (* hdlname = "cio_gpio_o" *)
  output [3:0] cio_gpio_o;
  wire [3:0] cio_gpio_o;
  (* hdlname = "cio_gpio_en_o" *)
  output [3:0] cio_gpio_en_o;
  wire [3:0] cio_gpio_en_o;
  (* hdlname = "intr_gpio_o" *)
  output [3:0] intr_gpio_o;
  wire [3:0] intr_gpio_o;
  (* hdlname = "tl_i" *)
  input [108:0] tl_i;
  wire [108:0] tl_i;
  (* hdlname = "tl_o" *)
  output [65:0] tl_o;
  wire [65:0] tl_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[0] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[10] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[11] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[12] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[1] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[2] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[3] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[4] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[5] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[6] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[7] ;
  (* hdlname = "hw2reg" *)
  wire \hw2reg[9] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[0] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[10] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[11] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[12] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[13] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[14] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[15] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[16] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[17] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[18] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[19] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[1] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[2] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[3] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[4] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[5] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[6] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[7] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[8] ;
  (* hdlname = "reg2hw" *)
  wire \reg2hw[9] ;
  (* hdlname = "u_gpio_core data_in_q" *)
  wire \u_gpio_core.data_in_q[0] ;
  (* hdlname = "u_gpio_core data_in_q" *)
  wire \u_gpio_core.data_in_q[1] ;
  (* hdlname = "u_gpio_core data_in_q" *)
  wire \u_gpio_core.data_in_q[2] ;
  (* hdlname = "u_gpio_core data_in_q" *)
  wire \u_gpio_core.data_in_q[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter filter_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.filter_q ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter filter_synced" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.filter_synced ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter gen_async prim_flop_2sync intq" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "u_gpio_core gen_input_filter[0] u_filter stored_value_q" *)
  wire \u_gpio_core.gen_input_filter[0].u_filter.stored_value_q ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter filter_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.filter_q ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter filter_synced" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.filter_synced ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter gen_async prim_flop_2sync intq" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "u_gpio_core gen_input_filter[1] u_filter stored_value_q" *)
  wire \u_gpio_core.gen_input_filter[1].u_filter.stored_value_q ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter filter_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.filter_q ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter filter_synced" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.filter_synced ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter gen_async prim_flop_2sync intq" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "u_gpio_core gen_input_filter[2] u_filter stored_value_q" *)
  wire \u_gpio_core.gen_input_filter[2].u_filter.stored_value_q ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_d" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[1] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[2] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter diff_ctr_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[3] ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter filter_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.filter_q ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter filter_synced" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.filter_synced ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter gen_async prim_flop_2sync intq" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.gen_async.prim_flop_2sync.intq ;
  (* hdlname = "u_gpio_core gen_input_filter[3] u_filter stored_value_q" *)
  wire \u_gpio_core.gen_input_filter[3].u_filter.stored_value_q ;
  (* hdlname = "u_gpio_core intr_gpio_o" *)
  wire \u_gpio_core.intr_gpio_o[0] ;
  (* hdlname = "u_gpio_core intr_gpio_o" *)
  wire \u_gpio_core.intr_gpio_o[1] ;
  (* hdlname = "u_gpio_core intr_gpio_o" *)
  wire \u_gpio_core.intr_gpio_o[2] ;
  (* hdlname = "u_gpio_core intr_gpio_o" *)
  wire \u_gpio_core.intr_gpio_o[3] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[0] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[16] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[17] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[18] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[19] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[1] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[20] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[21] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[22] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[23] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[24] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[25] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[26] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[27] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[28] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[29] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[30] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[31] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[32] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[33] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[34] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[35] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[36] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[49] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[50] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[51] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[52] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[53] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[54] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[55] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[56] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[57] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[58] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[62] ;
  (* hdlname = "u_gpio_reg tl_o" *)
  wire \u_gpio_reg.tl_o[65] ;
  sg13g2_mux2_1 _259_ (
    .A0(\u_gpio_core.gen_input_filter[2].u_filter.filter_synced ),
    .A1(\u_gpio_core.gen_input_filter[2].u_filter.stored_value_q ),
    .S(\reg2hw[18] ),
    .X(\hw2reg[11] )
  );
  sg13g2_inv_1 _260_ (
    .A(\u_gpio_core.data_in_q[2] ),
    .Y(_066_)
  );
  sg13g2_a21oi_1 _261_ (
    .A1(_066_),
    .A2(\reg2hw[2] ),
    .B1(\reg2hw[10] ),
    .Y(_067_)
  );
  sg13g2_inv_1 _262_ (
    .A(\reg2hw[6] ),
    .Y(_068_)
  );
  sg13g2_nor2_1 _263_ (
    .A(_066_),
    .B(_068_),
    .Y(_069_)
  );
  sg13g2_nor3_1 _264_ (
    .A(\reg2hw[14] ),
    .B(_069_),
    .C(\hw2reg[11] ),
    .Y(_070_)
  );
  sg13g2_a21oi_1 _265_ (
    .A1(\hw2reg[11] ),
    .A2(_067_),
    .B1(_070_),
    .Y(\u_gpio_core.intr_gpio_o[2] )
  );
  sg13g2_mux2_1 _266_ (
    .A0(\u_gpio_core.gen_input_filter[1].u_filter.filter_synced ),
    .A1(\u_gpio_core.gen_input_filter[1].u_filter.stored_value_q ),
    .S(\reg2hw[17] ),
    .X(\hw2reg[10] )
  );
  sg13g2_inv_1 _267_ (
    .A(\u_gpio_core.data_in_q[1] ),
    .Y(_071_)
  );
  sg13g2_a21oi_1 _268_ (
    .A1(_071_),
    .A2(\reg2hw[1] ),
    .B1(\reg2hw[9] ),
    .Y(_072_)
  );
  sg13g2_inv_1 _269_ (
    .A(\reg2hw[5] ),
    .Y(_073_)
  );
  sg13g2_nor2_1 _270_ (
    .A(_073_),
    .B(_071_),
    .Y(_074_)
  );
  sg13g2_nor3_1 _271_ (
    .A(\reg2hw[13] ),
    .B(_074_),
    .C(\hw2reg[10] ),
    .Y(_075_)
  );
  sg13g2_a21oi_1 _272_ (
    .A1(\hw2reg[10] ),
    .A2(_072_),
    .B1(_075_),
    .Y(\u_gpio_core.intr_gpio_o[1] )
  );
  sg13g2_mux2_1 _273_ (
    .A0(\u_gpio_core.gen_input_filter[0].u_filter.filter_synced ),
    .A1(\u_gpio_core.gen_input_filter[0].u_filter.stored_value_q ),
    .S(\reg2hw[16] ),
    .X(\hw2reg[9] )
  );
  sg13g2_inv_1 _274_ (
    .A(\u_gpio_core.data_in_q[0] ),
    .Y(_076_)
  );
  sg13g2_a21oi_1 _275_ (
    .A1(_076_),
    .A2(\reg2hw[0] ),
    .B1(\reg2hw[8] ),
    .Y(_077_)
  );
  sg13g2_inv_1 _276_ (
    .A(\reg2hw[4] ),
    .Y(_078_)
  );
  sg13g2_nor2_1 _277_ (
    .A(_078_),
    .B(_076_),
    .Y(_079_)
  );
  sg13g2_nor3_1 _278_ (
    .A(\reg2hw[12] ),
    .B(_079_),
    .C(\hw2reg[9] ),
    .Y(_080_)
  );
  sg13g2_a21oi_1 _279_ (
    .A1(\hw2reg[9] ),
    .A2(_077_),
    .B1(_080_),
    .Y(\u_gpio_core.intr_gpio_o[0] )
  );
  sg13g2_inv_1 _280_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[2] ),
    .Y(_081_)
  );
  sg13g2_inv_1 _281_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[1] ),
    .Y(_082_)
  );
  sg13g2_inv_1 _282_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ),
    .Y(_083_)
  );
  sg13g2_nor2_1 _283_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  sg13g2_inv_1 _284_ (
    .A(_084_),
    .Y(_085_)
  );
  sg13g2_nor2_1 _285_ (
    .A(_081_),
    .B(_085_),
    .Y(_086_)
  );
  sg13g2_inv_1 _286_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[3] ),
    .Y(_087_)
  );
  sg13g2_xnor2_1 _287_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.filter_synced ),
    .B(\u_gpio_core.gen_input_filter[3].u_filter.filter_q ),
    .Y(_088_)
  );
  sg13g2_o21ai_1 _288_ (
    .A1(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[2] ),
    .A2(_084_),
    .B1(_088_),
    .Y(_089_)
  );
  sg13g2_a21oi_1 _289_ (
    .A1(_086_),
    .A2(_087_),
    .B1(_089_),
    .Y(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[2] )
  );
  sg13g2_nand2_1 _290_ (
    .A(_086_),
    .B(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[3] ),
    .Y(_090_)
  );
  sg13g2_xnor2_1 _291_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[1] ),
    .B(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ),
    .Y(_091_)
  );
  sg13g2_inv_1 _292_ (
    .A(_088_),
    .Y(_092_)
  );
  sg13g2_a21oi_1 _293_ (
    .A1(_090_),
    .A2(_091_),
    .B1(_092_),
    .Y(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[1] )
  );
  sg13g2_a21oi_1 _294_ (
    .A1(_090_),
    .A2(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ),
    .B1(_092_),
    .Y(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[0] )
  );
  sg13g2_inv_1 _295_ (
    .A(_086_),
    .Y(_093_)
  );
  sg13g2_a21oi_1 _296_ (
    .A1(_093_),
    .A2(_087_),
    .B1(_092_),
    .Y(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[3] )
  );
  sg13g2_inv_1 _297_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[3] ),
    .Y(_094_)
  );
  sg13g2_inv_1 _298_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[2] ),
    .Y(_095_)
  );
  sg13g2_inv_1 _299_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[0] ),
    .Y(_096_)
  );
  sg13g2_inv_1 _300_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[1] ),
    .Y(_097_)
  );
  sg13g2_nor2_1 _301_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  sg13g2_inv_1 _302_ (
    .A(_098_),
    .Y(_099_)
  );
  sg13g2_nor2_1 _303_ (
    .A(_095_),
    .B(_099_),
    .Y(_100_)
  );
  sg13g2_xnor2_1 _304_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.filter_synced ),
    .B(\u_gpio_core.gen_input_filter[2].u_filter.filter_q ),
    .Y(_101_)
  );
  sg13g2_inv_1 _305_ (
    .A(_101_),
    .Y(_102_)
  );
  sg13g2_a21oi_1 _306_ (
    .A1(_095_),
    .A2(_099_),
    .B1(_102_),
    .Y(_103_)
  );
  sg13g2_inv_1 _307_ (
    .A(_103_),
    .Y(_104_)
  );
  sg13g2_a21oi_1 _308_ (
    .A1(_094_),
    .A2(_100_),
    .B1(_104_),
    .Y(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[2] )
  );
  sg13g2_nand2_1 _309_ (
    .A(_100_),
    .B(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[3] ),
    .Y(_105_)
  );
  sg13g2_xnor2_1 _310_ (
    .A(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[0] ),
    .B(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[1] ),
    .Y(_106_)
  );
  sg13g2_a21oi_1 _311_ (
    .A1(_105_),
    .A2(_106_),
    .B1(_102_),
    .Y(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[1] )
  );
  sg13g2_a21oi_1 _312_ (
    .A1(_105_),
    .A2(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[0] ),
    .B1(_102_),
    .Y(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[0] )
  );
  sg13g2_inv_1 _313_ (
    .A(_100_),
    .Y(_107_)
  );
  sg13g2_a21oi_1 _314_ (
    .A1(_107_),
    .A2(_094_),
    .B1(_102_),
    .Y(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[3] )
  );
  sg13g2_inv_1 _315_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[2] ),
    .Y(_108_)
  );
  sg13g2_inv_1 _316_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[1] ),
    .Y(_109_)
  );
  sg13g2_inv_1 _317_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ),
    .Y(_110_)
  );
  sg13g2_nor2_1 _318_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  sg13g2_inv_1 _319_ (
    .A(_111_),
    .Y(_112_)
  );
  sg13g2_nor2_1 _320_ (
    .A(_108_),
    .B(_112_),
    .Y(_113_)
  );
  sg13g2_inv_1 _321_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[3] ),
    .Y(_114_)
  );
  sg13g2_xnor2_1 _322_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.filter_synced ),
    .B(\u_gpio_core.gen_input_filter[1].u_filter.filter_q ),
    .Y(_115_)
  );
  sg13g2_o21ai_1 _323_ (
    .A1(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[2] ),
    .A2(_111_),
    .B1(_115_),
    .Y(_116_)
  );
  sg13g2_a21oi_1 _324_ (
    .A1(_113_),
    .A2(_114_),
    .B1(_116_),
    .Y(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[2] )
  );
  sg13g2_nand2_1 _325_ (
    .A(_113_),
    .B(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[3] ),
    .Y(_117_)
  );
  sg13g2_xnor2_1 _326_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[1] ),
    .B(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ),
    .Y(_118_)
  );
  sg13g2_inv_1 _327_ (
    .A(_115_),
    .Y(_119_)
  );
  sg13g2_a21oi_1 _328_ (
    .A1(_117_),
    .A2(_118_),
    .B1(_119_),
    .Y(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[1] )
  );
  sg13g2_a21oi_1 _329_ (
    .A1(_117_),
    .A2(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ),
    .B1(_119_),
    .Y(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[0] )
  );
  sg13g2_inv_1 _330_ (
    .A(_113_),
    .Y(_120_)
  );
  sg13g2_a21oi_1 _331_ (
    .A1(_120_),
    .A2(_114_),
    .B1(_119_),
    .Y(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[3] )
  );
  sg13g2_inv_1 _332_ (
    .A(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ),
    .Y(_121_)
  );
  sg13g2_inv_1 _333_ (
    .A(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[1] ),
    .Y(_122_)
  );
  sg13g2_nor2_1 _334_ (
    .A(_121_),
    .B(_122_),
    .Y(_123_)
  );
  sg13g2_nand2_1 _335_ (
    .A(_123_),
    .B(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[2] ),
    .Y(_124_)
  );
  sg13g2_inv_1 _336_ (
    .A(_124_),
    .Y(_125_)
  );
  sg13g2_inv_1 _337_ (
    .A(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[3] ),
    .Y(_126_)
  );
  sg13g2_xnor2_1 _338_ (
    .A(\u_gpio_core.gen_input_filter[0].u_filter.filter_synced ),
    .B(\u_gpio_core.gen_input_filter[0].u_filter.filter_q ),
    .Y(_127_)
  );
  sg13g2_o21ai_1 _339_ (
    .A1(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[2] ),
    .A2(_123_),
    .B1(_127_),
    .Y(_128_)
  );
  sg13g2_a21oi_1 _340_ (
    .A1(_125_),
    .A2(_126_),
    .B1(_128_),
    .Y(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[2] )
  );
  sg13g2_nand2_1 _341_ (
    .A(_125_),
    .B(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[3] ),
    .Y(_129_)
  );
  sg13g2_xnor2_1 _342_ (
    .A(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ),
    .B(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[1] ),
    .Y(_130_)
  );
  sg13g2_inv_1 _343_ (
    .A(_127_),
    .Y(_131_)
  );
  sg13g2_a21oi_1 _344_ (
    .A1(_129_),
    .A2(_130_),
    .B1(_131_),
    .Y(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[1] )
  );
  sg13g2_a21oi_1 _345_ (
    .A1(_129_),
    .A2(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ),
    .B1(_131_),
    .Y(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[0] )
  );
  sg13g2_a21oi_1 _346_ (
    .A1(_124_),
    .A2(_126_),
    .B1(_131_),
    .Y(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[3] )
  );
  sg13g2_inv_2 _347_ (
    .A(\u_gpio_reg.tl_o[65] ),
    .Y(\u_gpio_reg.tl_o[0] )
  );
  sg13g2_nand2_2 _348_ (
    .A(\u_gpio_reg.tl_o[0] ),
    .B(tl_i[108]),
    .Y(_132_)
  );
  sg13g2_inv_1 _349_ (
    .A(tl_i[107]),
    .Y(_133_)
  );
  sg13g2_nand2b_1 _350_ (
    .A_N(tl_i[106]),
    .B(_133_),
    .Y(_134_)
  );
  sg13g2_nor2_2 _351_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  sg13g2_nor2_1 _352_ (
    .A(tl_i[60]),
    .B(tl_i[61]),
    .Y(_136_)
  );
  sg13g2_nand2_2 _353_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  sg13g2_inv_2 _354_ (
    .A(tl_i[63]),
    .Y(_138_)
  );
  sg13g2_nor2_2 _355_ (
    .A(tl_i[62]),
    .B(_138_),
    .Y(_139_)
  );
  sg13g2_buf_8 _356_ (
    .A(_139_),
    .X(_140_)
  );
  sg13g2_nand2_1 _357_ (
    .A(tl_i[57]),
    .B(tl_i[58]),
    .Y(_141_)
  );
  sg13g2_inv_1 _358_ (
    .A(tl_i[56]),
    .Y(_142_)
  );
  sg13g2_a21oi_1 _359_ (
    .A1(_140_),
    .A2(_141_),
    .B1(_142_),
    .Y(_143_)
  );
  sg13g2_nand2_1 _360_ (
    .A(tl_i[62]),
    .B(tl_i[63]),
    .Y(_144_)
  );
  sg13g2_o21ai_1 _361_ (
    .A1(_143_),
    .A2(_137_),
    .B1(_144_),
    .Y(_145_)
  );
  sg13g2_nor2_1 _362_ (
    .A(_137_),
    .B(_145_),
    .Y(_146_)
  );
  sg13g2_nand2_1 _363_ (
    .A(_146_),
    .B(_140_),
    .Y(_147_)
  );
  sg13g2_buf_8 _364_ (
    .A(_147_),
    .X(_148_)
  );
  sg13g2_mux2_1 _365_ (
    .A0(tl_i[34]),
    .A1(\reg2hw[10] ),
    .S(_148_),
    .X(_000_)
  );
  sg13g2_mux2_1 _366_ (
    .A0(tl_i[33]),
    .A1(\reg2hw[9] ),
    .S(_148_),
    .X(_001_)
  );
  sg13g2_mux2_1 _367_ (
    .A0(tl_i[32]),
    .A1(\reg2hw[8] ),
    .S(_148_),
    .X(_002_)
  );
  sg13g2_buf_2 _368_ (
    .A(_132_),
    .X(_149_)
  );
  sg13g2_mux2_1 _369_ (
    .A0(tl_i[98]),
    .A1(\u_gpio_reg.tl_o[55] ),
    .S(_149_),
    .X(_003_)
  );
  sg13g2_mux2_1 _370_ (
    .A0(tl_i[97]),
    .A1(\u_gpio_reg.tl_o[54] ),
    .S(_149_),
    .X(_004_)
  );
  sg13g2_mux2_1 _371_ (
    .A0(tl_i[96]),
    .A1(\u_gpio_reg.tl_o[53] ),
    .S(_149_),
    .X(_005_)
  );
  sg13g2_mux2_1 _372_ (
    .A0(tl_i[95]),
    .A1(\u_gpio_reg.tl_o[52] ),
    .S(_149_),
    .X(_006_)
  );
  sg13g2_mux2_1 _373_ (
    .A0(tl_i[94]),
    .A1(\u_gpio_reg.tl_o[51] ),
    .S(_149_),
    .X(_007_)
  );
  sg13g2_mux2_1 _374_ (
    .A0(tl_i[93]),
    .A1(\u_gpio_reg.tl_o[50] ),
    .S(_149_),
    .X(_008_)
  );
  sg13g2_mux2_1 _375_ (
    .A0(tl_i[92]),
    .A1(\u_gpio_reg.tl_o[49] ),
    .S(_149_),
    .X(_009_)
  );
  sg13g2_mux2_1 _376_ (
    .A0(tl_i[100]),
    .A1(\u_gpio_reg.tl_o[57] ),
    .S(_149_),
    .X(_010_)
  );
  sg13g2_inv_1 _377_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .Y(_150_)
  );
  sg13g2_inv_1 _378_ (
    .A(_132_),
    .Y(_151_)
  );
  sg13g2_nor3_1 _379_ (
    .A(tl_i[105]),
    .B(tl_i[106]),
    .C(_133_),
    .Y(_152_)
  );
  sg13g2_nand2_1 _380_ (
    .A(_151_),
    .B(_152_),
    .Y(_153_)
  );
  sg13g2_nand2_1 _381_ (
    .A(_137_),
    .B(_153_),
    .Y(_154_)
  );
  sg13g2_and2_1 _382_ (
    .A(_145_),
    .B(_154_),
    .X(_155_)
  );
  sg13g2_nor2_1 _383_ (
    .A(_132_),
    .B(_155_),
    .Y(_156_)
  );
  sg13g2_and3_1 _384_ (
    .A(_156_),
    .B(_134_),
    .C(_144_),
    .X(_157_)
  );
  sg13g2_buf_4 _385_ (
    .A(_157_),
    .X(_158_)
  );
  sg13g2_a21oi_1 _386_ (
    .A1(_150_),
    .A2(_149_),
    .B1(_158_),
    .Y(_011_)
  );
  sg13g2_inv_1 _387_ (
    .A(\u_gpio_reg.tl_o[35] ),
    .Y(_159_)
  );
  sg13g2_nand2_1 _388_ (
    .A(_140_),
    .B(\reg2hw[19] ),
    .Y(_160_)
  );
  sg13g2_a22oi_1 _389_ (
    .A1(_159_),
    .A2(_149_),
    .B1(_160_),
    .B2(_158_),
    .Y(_012_)
  );
  sg13g2_inv_1 _390_ (
    .A(\u_gpio_reg.tl_o[34] ),
    .Y(_161_)
  );
  sg13g2_nand2_1 _391_ (
    .A(_140_),
    .B(\reg2hw[18] ),
    .Y(_162_)
  );
  sg13g2_a22oi_1 _392_ (
    .A1(_161_),
    .A2(_149_),
    .B1(_162_),
    .B2(_158_),
    .Y(_013_)
  );
  sg13g2_inv_1 _393_ (
    .A(\u_gpio_reg.tl_o[33] ),
    .Y(_163_)
  );
  sg13g2_nand2_1 _394_ (
    .A(_140_),
    .B(\reg2hw[17] ),
    .Y(_164_)
  );
  sg13g2_a22oi_1 _395_ (
    .A1(_163_),
    .A2(_149_),
    .B1(_164_),
    .B2(_158_),
    .Y(_014_)
  );
  sg13g2_inv_1 _396_ (
    .A(\u_gpio_reg.tl_o[32] ),
    .Y(_165_)
  );
  sg13g2_nand2_1 _397_ (
    .A(_140_),
    .B(\reg2hw[16] ),
    .Y(_166_)
  );
  sg13g2_a22oi_1 _398_ (
    .A1(_165_),
    .A2(_149_),
    .B1(_166_),
    .B2(_158_),
    .Y(_015_)
  );
  sg13g2_inv_1 _399_ (
    .A(\u_gpio_reg.tl_o[31] ),
    .Y(_167_)
  );
  sg13g2_nand2_1 _400_ (
    .A(_140_),
    .B(\reg2hw[15] ),
    .Y(_168_)
  );
  sg13g2_a22oi_1 _401_ (
    .A1(_167_),
    .A2(_149_),
    .B1(_168_),
    .B2(_158_),
    .Y(_016_)
  );
  sg13g2_inv_1 _402_ (
    .A(\u_gpio_reg.tl_o[30] ),
    .Y(_169_)
  );
  sg13g2_nand2_1 _403_ (
    .A(_140_),
    .B(\reg2hw[14] ),
    .Y(_170_)
  );
  sg13g2_a22oi_1 _404_ (
    .A1(_169_),
    .A2(_149_),
    .B1(_170_),
    .B2(_158_),
    .Y(_017_)
  );
  sg13g2_inv_1 _405_ (
    .A(\u_gpio_reg.tl_o[29] ),
    .Y(_171_)
  );
  sg13g2_nand2_1 _406_ (
    .A(_140_),
    .B(\reg2hw[13] ),
    .Y(_172_)
  );
  sg13g2_a22oi_1 _407_ (
    .A1(_171_),
    .A2(_149_),
    .B1(_172_),
    .B2(_158_),
    .Y(_018_)
  );
  sg13g2_inv_1 _408_ (
    .A(\u_gpio_reg.tl_o[28] ),
    .Y(_173_)
  );
  sg13g2_nand2_1 _409_ (
    .A(_140_),
    .B(\reg2hw[12] ),
    .Y(_174_)
  );
  sg13g2_a22oi_1 _410_ (
    .A1(_173_),
    .A2(_149_),
    .B1(_174_),
    .B2(_158_),
    .Y(_019_)
  );
  sg13g2_inv_1 _411_ (
    .A(\u_gpio_reg.tl_o[27] ),
    .Y(_175_)
  );
  sg13g2_nand2_1 _412_ (
    .A(_140_),
    .B(\reg2hw[11] ),
    .Y(_176_)
  );
  sg13g2_a22oi_1 _413_ (
    .A1(_175_),
    .A2(_149_),
    .B1(_176_),
    .B2(_158_),
    .Y(_020_)
  );
  sg13g2_inv_1 _414_ (
    .A(\u_gpio_reg.tl_o[26] ),
    .Y(_177_)
  );
  sg13g2_nand2_1 _415_ (
    .A(_140_),
    .B(\reg2hw[10] ),
    .Y(_178_)
  );
  sg13g2_a22oi_1 _416_ (
    .A1(_177_),
    .A2(_149_),
    .B1(_178_),
    .B2(_158_),
    .Y(_021_)
  );
  sg13g2_inv_1 _417_ (
    .A(\u_gpio_reg.tl_o[25] ),
    .Y(_179_)
  );
  sg13g2_nand2_1 _418_ (
    .A(_140_),
    .B(\reg2hw[9] ),
    .Y(_180_)
  );
  sg13g2_a22oi_1 _419_ (
    .A1(_179_),
    .A2(_149_),
    .B1(_180_),
    .B2(_158_),
    .Y(_022_)
  );
  sg13g2_inv_1 _420_ (
    .A(\u_gpio_reg.tl_o[24] ),
    .Y(_181_)
  );
  sg13g2_nand2_1 _421_ (
    .A(_140_),
    .B(\reg2hw[8] ),
    .Y(_182_)
  );
  sg13g2_a22oi_1 _422_ (
    .A1(_181_),
    .A2(_149_),
    .B1(_182_),
    .B2(_158_),
    .Y(_023_)
  );
  sg13g2_inv_1 _423_ (
    .A(\u_gpio_reg.tl_o[23] ),
    .Y(_183_)
  );
  sg13g2_inv_1 _424_ (
    .A(tl_i[62]),
    .Y(_184_)
  );
  sg13g2_inv_1 _425_ (
    .A(\reg2hw[7] ),
    .Y(_185_)
  );
  sg13g2_nand2_1 _426_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  sg13g2_a22oi_1 _427_ (
    .A1(tl_i[62]),
    .A2(\hw2reg[3] ),
    .B1(tl_i[63]),
    .B2(_186_),
    .Y(_187_)
  );
  sg13g2_and2_1 _428_ (
    .A(_156_),
    .B(_134_),
    .X(_188_)
  );
  sg13g2_buf_2 _429_ (
    .A(_188_),
    .X(_189_)
  );
  sg13g2_a22oi_1 _430_ (
    .A1(_183_),
    .A2(_149_),
    .B1(_187_),
    .B2(_189_),
    .Y(_024_)
  );
  sg13g2_inv_1 _431_ (
    .A(\u_gpio_reg.tl_o[22] ),
    .Y(_190_)
  );
  sg13g2_nand2_1 _432_ (
    .A(_068_),
    .B(_184_),
    .Y(_191_)
  );
  sg13g2_a22oi_1 _433_ (
    .A1(tl_i[62]),
    .A2(\hw2reg[2] ),
    .B1(tl_i[63]),
    .B2(_191_),
    .Y(_192_)
  );
  sg13g2_a22oi_1 _434_ (
    .A1(_190_),
    .A2(_149_),
    .B1(_192_),
    .B2(_189_),
    .Y(_025_)
  );
  sg13g2_inv_1 _435_ (
    .A(\u_gpio_reg.tl_o[21] ),
    .Y(_193_)
  );
  sg13g2_nand2_1 _436_ (
    .A(_073_),
    .B(_184_),
    .Y(_194_)
  );
  sg13g2_a22oi_1 _437_ (
    .A1(tl_i[62]),
    .A2(\hw2reg[1] ),
    .B1(tl_i[63]),
    .B2(_194_),
    .Y(_195_)
  );
  sg13g2_a22oi_1 _438_ (
    .A1(_193_),
    .A2(_149_),
    .B1(_195_),
    .B2(_189_),
    .Y(_026_)
  );
  sg13g2_inv_1 _439_ (
    .A(\u_gpio_reg.tl_o[20] ),
    .Y(_196_)
  );
  sg13g2_nand2_1 _440_ (
    .A(_078_),
    .B(_184_),
    .Y(_197_)
  );
  sg13g2_a22oi_1 _441_ (
    .A1(\hw2reg[0] ),
    .A2(tl_i[62]),
    .B1(tl_i[63]),
    .B2(_197_),
    .Y(_198_)
  );
  sg13g2_a22oi_1 _442_ (
    .A1(_196_),
    .A2(_149_),
    .B1(_198_),
    .B2(_189_),
    .Y(_027_)
  );
  sg13g2_inv_1 _443_ (
    .A(\u_gpio_reg.tl_o[19] ),
    .Y(_199_)
  );
  sg13g2_inv_1 _444_ (
    .A(\u_gpio_core.data_in_q[3] ),
    .Y(_200_)
  );
  sg13g2_o21ai_1 _445_ (
    .A1(tl_i[63]),
    .A2(_200_),
    .B1(_184_),
    .Y(_201_)
  );
  sg13g2_nor2_1 _446_ (
    .A(tl_i[63]),
    .B(_184_),
    .Y(_202_)
  );
  sg13g2_inv_1 _447_ (
    .A(\hw2reg[7] ),
    .Y(_203_)
  );
  sg13g2_nand2_1 _448_ (
    .A(_202_),
    .B(_203_),
    .Y(_204_)
  );
  sg13g2_a22oi_1 _449_ (
    .A1(\reg2hw[3] ),
    .A2(_140_),
    .B1(_201_),
    .B2(_204_),
    .Y(_205_)
  );
  sg13g2_a22oi_1 _450_ (
    .A1(_199_),
    .A2(_149_),
    .B1(_205_),
    .B2(_189_),
    .Y(_028_)
  );
  sg13g2_inv_1 _451_ (
    .A(\u_gpio_reg.tl_o[18] ),
    .Y(_206_)
  );
  sg13g2_o21ai_1 _452_ (
    .A1(tl_i[62]),
    .A2(_066_),
    .B1(_138_),
    .Y(_207_)
  );
  sg13g2_nand2b_1 _453_ (
    .A_N(\reg2hw[2] ),
    .B(_140_),
    .Y(_208_)
  );
  sg13g2_a22oi_1 _454_ (
    .A1(\hw2reg[6] ),
    .A2(_202_),
    .B1(_207_),
    .B2(_208_),
    .Y(_209_)
  );
  sg13g2_a22oi_1 _455_ (
    .A1(_206_),
    .A2(_149_),
    .B1(_209_),
    .B2(_189_),
    .Y(_029_)
  );
  sg13g2_inv_1 _456_ (
    .A(\u_gpio_reg.tl_o[17] ),
    .Y(_210_)
  );
  sg13g2_inv_1 _457_ (
    .A(_140_),
    .Y(_211_)
  );
  sg13g2_a21oi_1 _458_ (
    .A1(\hw2reg[5] ),
    .A2(tl_i[62]),
    .B1(tl_i[63]),
    .Y(_212_)
  );
  sg13g2_o21ai_1 _459_ (
    .A1(_071_),
    .A2(tl_i[62]),
    .B1(_212_),
    .Y(_213_)
  );
  sg13g2_o21ai_1 _460_ (
    .A1(\reg2hw[1] ),
    .A2(_211_),
    .B1(_213_),
    .Y(_214_)
  );
  sg13g2_a22oi_1 _461_ (
    .A1(_210_),
    .A2(_149_),
    .B1(_214_),
    .B2(_189_),
    .Y(_030_)
  );
  sg13g2_inv_1 _462_ (
    .A(\u_gpio_reg.tl_o[16] ),
    .Y(_215_)
  );
  sg13g2_o21ai_1 _463_ (
    .A1(tl_i[62]),
    .A2(_076_),
    .B1(_138_),
    .Y(_216_)
  );
  sg13g2_nand2b_1 _464_ (
    .A_N(\reg2hw[0] ),
    .B(_140_),
    .Y(_217_)
  );
  sg13g2_a22oi_1 _465_ (
    .A1(\hw2reg[4] ),
    .A2(_202_),
    .B1(_216_),
    .B2(_217_),
    .Y(_218_)
  );
  sg13g2_a22oi_1 _466_ (
    .A1(_215_),
    .A2(_149_),
    .B1(_218_),
    .B2(_189_),
    .Y(_031_)
  );
  sg13g2_inv_1 _467_ (
    .A(tl_i[26]),
    .Y(_219_)
  );
  sg13g2_nor4_1 _468_ (
    .A(_184_),
    .B(tl_i[63]),
    .C(_137_),
    .D(_145_),
    .Y(_220_)
  );
  sg13g2_buf_2 _469_ (
    .A(_220_),
    .X(_221_)
  );
  sg13g2_nor2_1 _470_ (
    .A(\hw2reg[6] ),
    .B(_221_),
    .Y(_222_)
  );
  sg13g2_a21oi_1 _471_ (
    .A1(_219_),
    .A2(_221_),
    .B1(_222_),
    .Y(_032_)
  );
  sg13g2_inv_1 _472_ (
    .A(tl_i[25]),
    .Y(_223_)
  );
  sg13g2_nor2_1 _473_ (
    .A(\hw2reg[5] ),
    .B(_221_),
    .Y(_224_)
  );
  sg13g2_a21oi_1 _474_ (
    .A1(_223_),
    .A2(_221_),
    .B1(_224_),
    .Y(_033_)
  );
  sg13g2_inv_1 _475_ (
    .A(tl_i[24]),
    .Y(_225_)
  );
  sg13g2_nor2_1 _476_ (
    .A(\hw2reg[4] ),
    .B(_221_),
    .Y(_226_)
  );
  sg13g2_a21oi_1 _477_ (
    .A1(_225_),
    .A2(_221_),
    .B1(_226_),
    .Y(_034_)
  );
  sg13g2_inv_1 _478_ (
    .A(tl_i[30]),
    .Y(_227_)
  );
  sg13g2_nor2_1 _479_ (
    .A(\hw2reg[2] ),
    .B(_221_),
    .Y(_228_)
  );
  sg13g2_a21oi_1 _480_ (
    .A1(_227_),
    .A2(_221_),
    .B1(_228_),
    .Y(_035_)
  );
  sg13g2_inv_1 _481_ (
    .A(tl_i[29]),
    .Y(_229_)
  );
  sg13g2_nor2_1 _482_ (
    .A(\hw2reg[1] ),
    .B(_221_),
    .Y(_230_)
  );
  sg13g2_a21oi_1 _483_ (
    .A1(_229_),
    .A2(_221_),
    .B1(_230_),
    .Y(_036_)
  );
  sg13g2_inv_1 _484_ (
    .A(tl_i[28]),
    .Y(_231_)
  );
  sg13g2_nor2_1 _485_ (
    .A(\hw2reg[0] ),
    .B(_221_),
    .Y(_232_)
  );
  sg13g2_a21oi_1 _486_ (
    .A1(_231_),
    .A2(_221_),
    .B1(_232_),
    .Y(_037_)
  );
  sg13g2_mux2_1 _487_ (
    .A0(tl_i[38]),
    .A1(\reg2hw[14] ),
    .S(_148_),
    .X(_038_)
  );
  sg13g2_mux2_1 _488_ (
    .A0(tl_i[37]),
    .A1(\reg2hw[13] ),
    .S(_148_),
    .X(_039_)
  );
  sg13g2_mux2_1 _489_ (
    .A0(tl_i[36]),
    .A1(\reg2hw[12] ),
    .S(_148_),
    .X(_040_)
  );
  sg13g2_nand2_1 _490_ (
    .A(_148_),
    .B(\reg2hw[6] ),
    .Y(_233_)
  );
  sg13g2_o21ai_1 _491_ (
    .A1(_227_),
    .A2(_148_),
    .B1(_233_),
    .Y(_041_)
  );
  sg13g2_nand2_1 _492_ (
    .A(_148_),
    .B(\reg2hw[5] ),
    .Y(_234_)
  );
  sg13g2_o21ai_1 _493_ (
    .A1(_229_),
    .A2(_148_),
    .B1(_234_),
    .Y(_042_)
  );
  sg13g2_nand2_1 _494_ (
    .A(_148_),
    .B(\reg2hw[4] ),
    .Y(_235_)
  );
  sg13g2_o21ai_1 _495_ (
    .A1(_231_),
    .A2(_148_),
    .B1(_235_),
    .Y(_043_)
  );
  sg13g2_mux2_1 _496_ (
    .A0(tl_i[42]),
    .A1(\reg2hw[18] ),
    .S(_148_),
    .X(_044_)
  );
  sg13g2_mux2_1 _497_ (
    .A0(tl_i[41]),
    .A1(\reg2hw[17] ),
    .S(_148_),
    .X(_045_)
  );
  sg13g2_mux2_1 _498_ (
    .A0(tl_i[40]),
    .A1(\reg2hw[16] ),
    .S(_148_),
    .X(_046_)
  );
  sg13g2_nand2_1 _499_ (
    .A(_148_),
    .B(\reg2hw[2] ),
    .Y(_236_)
  );
  sg13g2_o21ai_1 _500_ (
    .A1(_219_),
    .A2(_148_),
    .B1(_236_),
    .Y(_047_)
  );
  sg13g2_nand2_1 _501_ (
    .A(_148_),
    .B(\reg2hw[1] ),
    .Y(_237_)
  );
  sg13g2_o21ai_1 _502_ (
    .A1(_223_),
    .A2(_148_),
    .B1(_237_),
    .Y(_048_)
  );
  sg13g2_nand2_1 _503_ (
    .A(_148_),
    .B(\reg2hw[0] ),
    .Y(_238_)
  );
  sg13g2_o21ai_1 _504_ (
    .A1(_225_),
    .A2(_148_),
    .B1(_238_),
    .Y(_049_)
  );
  sg13g2_inv_1 _505_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.stored_value_q ),
    .Y(_239_)
  );
  sg13g2_o21ai_1 _506_ (
    .A1(_082_),
    .A2(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ),
    .B1(_090_),
    .Y(_240_)
  );
  sg13g2_nand3_1 _507_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[3] ),
    .B(_240_),
    .C(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[2] ),
    .Y(_241_)
  );
  sg13g2_nor2_1 _508_ (
    .A(\u_gpio_core.gen_input_filter[3].u_filter.filter_synced ),
    .B(_241_),
    .Y(_242_)
  );
  sg13g2_a21oi_1 _509_ (
    .A1(_239_),
    .A2(_241_),
    .B1(_242_),
    .Y(_050_)
  );
  sg13g2_o21ai_1 _510_ (
    .A1(_109_),
    .A2(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ),
    .B1(_117_),
    .Y(_243_)
  );
  sg13g2_nand3_1 _511_ (
    .A(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[3] ),
    .B(_243_),
    .C(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[2] ),
    .Y(_244_)
  );
  sg13g2_mux2_1 _512_ (
    .A0(\u_gpio_core.gen_input_filter[1].u_filter.filter_synced ),
    .A1(\u_gpio_core.gen_input_filter[1].u_filter.stored_value_q ),
    .S(_244_),
    .X(_051_)
  );
  sg13g2_mux2_1 _513_ (
    .A0(tl_i[43]),
    .A1(\reg2hw[19] ),
    .S(_148_),
    .X(_052_)
  );
  sg13g2_nor2_1 _514_ (
    .A(\reg2hw[19] ),
    .B(\u_gpio_core.gen_input_filter[3].u_filter.filter_synced ),
    .Y(_245_)
  );
  sg13g2_a21oi_1 _515_ (
    .A1(\reg2hw[19] ),
    .A2(_239_),
    .B1(_245_),
    .Y(\hw2reg[12] )
  );
  sg13g2_a21oi_1 _516_ (
    .A1(_200_),
    .A2(\reg2hw[3] ),
    .B1(\reg2hw[11] ),
    .Y(_246_)
  );
  sg13g2_nor2_1 _517_ (
    .A(_200_),
    .B(_185_),
    .Y(_247_)
  );
  sg13g2_nor3_1 _518_ (
    .A(\reg2hw[15] ),
    .B(_247_),
    .C(\hw2reg[12] ),
    .Y(_248_)
  );
  sg13g2_a21oi_1 _519_ (
    .A1(\hw2reg[12] ),
    .A2(_246_),
    .B1(_248_),
    .Y(\u_gpio_core.intr_gpio_o[3] )
  );
  sg13g2_nor2_1 _520_ (
    .A(tl_i[31]),
    .B(_148_),
    .Y(_249_)
  );
  sg13g2_a21oi_1 _521_ (
    .A1(_185_),
    .A2(_148_),
    .B1(_249_),
    .Y(_053_)
  );
  sg13g2_mux2_1 _522_ (
    .A0(tl_i[27]),
    .A1(\reg2hw[3] ),
    .S(_148_),
    .X(_054_)
  );
  sg13g2_a22oi_1 _523_ (
    .A1(_096_),
    .A2(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[1] ),
    .B1(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[3] ),
    .B2(_100_),
    .Y(_250_)
  );
  sg13g2_nor3_1 _524_ (
    .A(_094_),
    .B(_104_),
    .C(_250_),
    .Y(_251_)
  );
  sg13g2_mux2_1 _525_ (
    .A0(\u_gpio_core.gen_input_filter[2].u_filter.stored_value_q ),
    .A1(\u_gpio_core.gen_input_filter[2].u_filter.filter_synced ),
    .S(_251_),
    .X(_055_)
  );
  sg13g2_mux2_1 _526_ (
    .A0(tl_i[39]),
    .A1(\reg2hw[15] ),
    .S(_148_),
    .X(_056_)
  );
  sg13g2_mux2_1 _527_ (
    .A0(\hw2reg[3] ),
    .A1(tl_i[31]),
    .S(_221_),
    .X(_057_)
  );
  sg13g2_o21ai_1 _528_ (
    .A1(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ),
    .A2(_122_),
    .B1(_129_),
    .Y(_252_)
  );
  sg13g2_nand3b_1 _529_ (
    .A_N(_128_),
    .B(_252_),
    .C(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[3] ),
    .Y(_253_)
  );
  sg13g2_mux2_1 _530_ (
    .A0(\u_gpio_core.gen_input_filter[0].u_filter.filter_synced ),
    .A1(\u_gpio_core.gen_input_filter[0].u_filter.stored_value_q ),
    .S(_253_),
    .X(_058_)
  );
  sg13g2_nand2_1 _531_ (
    .A(_221_),
    .B(tl_i[27]),
    .Y(_254_)
  );
  sg13g2_o21ai_1 _532_ (
    .A1(_203_),
    .A2(_221_),
    .B1(_254_),
    .Y(_059_)
  );
  sg13g2_nor2_1 _533_ (
    .A(\u_gpio_reg.tl_o[1] ),
    .B(_151_),
    .Y(_255_)
  );
  sg13g2_nand2b_1 _534_ (
    .A_N(_136_),
    .B(_135_),
    .Y(_256_)
  );
  sg13g2_o21ai_1 _535_ (
    .A1(_255_),
    .A2(_156_),
    .B1(_256_),
    .Y(_060_)
  );
  sg13g2_mux2_1 _536_ (
    .A0(tl_i[101]),
    .A1(\u_gpio_reg.tl_o[58] ),
    .S(_149_),
    .X(_061_)
  );
  sg13g2_mux2_1 _537_ (
    .A0(tl_i[99]),
    .A1(\u_gpio_reg.tl_o[56] ),
    .S(_149_),
    .X(_062_)
  );
  sg13g2_inv_1 _538_ (
    .A(\u_gpio_reg.tl_o[62] ),
    .Y(_257_)
  );
  sg13g2_o21ai_1 _539_ (
    .A1(_257_),
    .A2(_151_),
    .B1(_153_),
    .Y(_063_)
  );
  sg13g2_o21ai_1 _540_ (
    .A1(\u_gpio_reg.tl_o[0] ),
    .A2(tl_i[0]),
    .B1(_149_),
    .Y(_064_)
  );
  sg13g2_mux2_1 _541_ (
    .A0(tl_i[35]),
    .A1(\reg2hw[11] ),
    .S(_148_),
    .X(_065_)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _542_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(\u_gpio_reg.tl_o[62] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _543_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(\reg2hw[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _544_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(\reg2hw[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _545_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(\reg2hw[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _546_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(\reg2hw[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sg13g2_dfrbpq_1 _547_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sg13g2_dfrbpq_1 _548_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _549_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(\reg2hw[16] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _550_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(\reg2hw[17] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _551_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(\reg2hw[18] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _552_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(\reg2hw[19] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _553_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(\reg2hw[4] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _554_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(\reg2hw[5] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _555_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(\reg2hw[6] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _556_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(\reg2hw[7] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sg13g2_dfrbpq_1 _557_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _558_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(\reg2hw[12] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _559_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(\reg2hw[13] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _560_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(\reg2hw[14] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _561_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\reg2hw[15] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:63.3" *)
  sg13g2_dfrbpq_1 _562_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(\hw2reg[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:63.3" *)
  sg13g2_dfrbpq_1 _563_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(\hw2reg[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:63.3" *)
  sg13g2_dfrbpq_1 _564_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(\hw2reg[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:63.3" *)
  sg13g2_dfrbpq_1 _565_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(\hw2reg[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:57.3" *)
  sg13g2_dfrbpq_1 _566_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.stored_value_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:55.3" *)
  sg13g2_dfrbpq_1 _567_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(\hw2reg[4] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:55.3" *)
  sg13g2_dfrbpq_1 _568_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(\hw2reg[5] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:55.3" *)
  sg13g2_dfrbpq_1 _569_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(\hw2reg[6] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../rtl/gpio_core.sv:55.3" *)
  sg13g2_dfrbpq_1 _570_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(\hw2reg[7] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _571_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(\u_gpio_reg.tl_o[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _572_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(\u_gpio_reg.tl_o[16] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _573_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(\u_gpio_reg.tl_o[17] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _574_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(\u_gpio_reg.tl_o[18] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _575_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(\u_gpio_reg.tl_o[19] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _576_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(\u_gpio_reg.tl_o[20] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _577_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(\u_gpio_reg.tl_o[21] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _578_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(\u_gpio_reg.tl_o[22] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _579_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(\u_gpio_reg.tl_o[23] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _580_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(\u_gpio_reg.tl_o[24] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _581_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(\u_gpio_reg.tl_o[25] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _582_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(\u_gpio_reg.tl_o[26] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _583_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(\u_gpio_reg.tl_o[27] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _584_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(\u_gpio_reg.tl_o[28] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _585_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(\u_gpio_reg.tl_o[29] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _586_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(\u_gpio_reg.tl_o[30] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _587_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(\u_gpio_reg.tl_o[31] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _588_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(\u_gpio_reg.tl_o[32] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _589_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(\u_gpio_reg.tl_o[33] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _590_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(\u_gpio_reg.tl_o[34] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _591_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(\u_gpio_reg.tl_o[35] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sg13g2_dfrbpq_1 _592_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(\u_gpio_reg.tl_o[36] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _593_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(\u_gpio_reg.tl_o[57] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _594_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(\u_gpio_reg.tl_o[58] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _595_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(\u_gpio_reg.tl_o[49] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _596_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(\u_gpio_reg.tl_o[50] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _597_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(\u_gpio_reg.tl_o[51] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _598_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(\u_gpio_reg.tl_o[52] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _599_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(\u_gpio_reg.tl_o[53] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _600_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(\u_gpio_reg.tl_o[54] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _601_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(\u_gpio_reg.tl_o[55] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sg13g2_dfrbpq_1 _602_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(\u_gpio_reg.tl_o[56] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/tlul/tlul_adapter_reg.sv:94.3" *)
  sg13g2_dfrbpq_1 _603_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(\u_gpio_reg.tl_o[65] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _604_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(\reg2hw[8] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _605_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(\reg2hw[9] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _606_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(\reg2hw[10] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _607_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(\reg2hw[11] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _608_ (
    .CLK(clk_i),
    .D(\hw2reg[9] ),
    .Q(\u_gpio_core.data_in_q[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _609_ (
    .CLK(clk_i),
    .D(\hw2reg[10] ),
    .Q(\u_gpio_core.data_in_q[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _610_ (
    .CLK(clk_i),
    .D(\hw2reg[11] ),
    .Q(\u_gpio_core.data_in_q[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sg13g2_dfrbpq_1 _611_ (
    .CLK(clk_i),
    .D(\hw2reg[12] ),
    .Q(\u_gpio_core.data_in_q[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _612_ (
    .CLK(clk_i),
    .D(cio_gpio_i[0]),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _613_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sg13g2_dfrbpq_1 _614_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.filter_synced ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _615_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[0] ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _616_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[1] ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _617_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[2] ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _618_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_d[3] ),
    .Q(\u_gpio_core.gen_input_filter[0].u_filter.diff_ctr_q[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _619_ (
    .CLK(clk_i),
    .D(cio_gpio_i[1]),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _620_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sg13g2_dfrbpq_1 _621_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.filter_synced ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _622_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[0] ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _623_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[1] ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _624_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[2] ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _625_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_d[3] ),
    .Q(\u_gpio_core.gen_input_filter[1].u_filter.diff_ctr_q[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _626_ (
    .CLK(clk_i),
    .D(cio_gpio_i[2]),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _627_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sg13g2_dfrbpq_1 _628_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.filter_synced ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _629_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[0] ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _630_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[1] ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _631_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[2] ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _632_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_d[3] ),
    .Q(\u_gpio_core.gen_input_filter[2].u_filter.diff_ctr_q[3] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _633_ (
    .CLK(clk_i),
    .D(cio_gpio_i[3]),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.gen_async.prim_flop_2sync.intq ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sg13g2_dfrbpq_1 _634_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.gen_async.prim_flop_2sync.intq ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.filter_synced ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:49.3" *)
  sg13g2_dfrbpq_1 _635_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.filter_synced ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.filter_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _636_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[0] ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[0] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _637_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[1] ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[1] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _638_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[2] ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[2] ),
    .RESET_B(rst_ni)
  );
  (* src = "../../../../../../../home/eneadim/github/flexsoc/hw/ips/prim_opentitan/prim_filter_ctr.sv:65.3" *)
  sg13g2_dfrbpq_1 _639_ (
    .CLK(clk_i),
    .D(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_d[3] ),
    .Q(\u_gpio_core.gen_input_filter[3].u_filter.diff_ctr_q[3] ),
    .RESET_B(rst_ni)
  );
  sg13g2_tielo _640_ (
    .L_LO(_258_)
  );
  sg13g2_buf_1 _641_ (
    .A(\u_gpio_reg.tl_o[0] ),
    .X(tl_o[0])
  );
  sg13g2_buf_1 _642_ (
    .A(\u_gpio_reg.tl_o[1] ),
    .X(tl_o[1])
  );
  sg13g2_buf_1 _643_ (
    .A(_258_),
    .X(tl_o[2])
  );
  sg13g2_buf_1 _644_ (
    .A(_258_),
    .X(tl_o[3])
  );
  sg13g2_buf_1 _645_ (
    .A(_258_),
    .X(tl_o[4])
  );
  sg13g2_buf_1 _646_ (
    .A(_258_),
    .X(tl_o[5])
  );
  sg13g2_buf_1 _647_ (
    .A(_258_),
    .X(tl_o[6])
  );
  sg13g2_buf_1 _648_ (
    .A(_258_),
    .X(tl_o[7])
  );
  sg13g2_buf_1 _649_ (
    .A(_258_),
    .X(tl_o[8])
  );
  sg13g2_buf_1 _650_ (
    .A(_258_),
    .X(tl_o[9])
  );
  sg13g2_buf_1 _651_ (
    .A(_258_),
    .X(tl_o[10])
  );
  sg13g2_buf_1 _652_ (
    .A(_258_),
    .X(tl_o[11])
  );
  sg13g2_buf_1 _653_ (
    .A(_258_),
    .X(tl_o[12])
  );
  sg13g2_buf_1 _654_ (
    .A(_258_),
    .X(tl_o[13])
  );
  sg13g2_buf_1 _655_ (
    .A(_258_),
    .X(tl_o[14])
  );
  sg13g2_buf_1 _656_ (
    .A(_258_),
    .X(tl_o[15])
  );
  sg13g2_buf_1 _657_ (
    .A(\u_gpio_reg.tl_o[16] ),
    .X(tl_o[16])
  );
  sg13g2_buf_1 _658_ (
    .A(\u_gpio_reg.tl_o[17] ),
    .X(tl_o[17])
  );
  sg13g2_buf_1 _659_ (
    .A(\u_gpio_reg.tl_o[18] ),
    .X(tl_o[18])
  );
  sg13g2_buf_1 _660_ (
    .A(\u_gpio_reg.tl_o[19] ),
    .X(tl_o[19])
  );
  sg13g2_buf_1 _661_ (
    .A(\u_gpio_reg.tl_o[20] ),
    .X(tl_o[20])
  );
  sg13g2_buf_1 _662_ (
    .A(\u_gpio_reg.tl_o[21] ),
    .X(tl_o[21])
  );
  sg13g2_buf_1 _663_ (
    .A(\u_gpio_reg.tl_o[22] ),
    .X(tl_o[22])
  );
  sg13g2_buf_1 _664_ (
    .A(\u_gpio_reg.tl_o[23] ),
    .X(tl_o[23])
  );
  sg13g2_buf_1 _665_ (
    .A(\u_gpio_reg.tl_o[24] ),
    .X(tl_o[24])
  );
  sg13g2_buf_1 _666_ (
    .A(\u_gpio_reg.tl_o[25] ),
    .X(tl_o[25])
  );
  sg13g2_buf_1 _667_ (
    .A(\u_gpio_reg.tl_o[26] ),
    .X(tl_o[26])
  );
  sg13g2_buf_1 _668_ (
    .A(\u_gpio_reg.tl_o[27] ),
    .X(tl_o[27])
  );
  sg13g2_buf_1 _669_ (
    .A(\u_gpio_reg.tl_o[28] ),
    .X(tl_o[28])
  );
  sg13g2_buf_1 _670_ (
    .A(\u_gpio_reg.tl_o[29] ),
    .X(tl_o[29])
  );
  sg13g2_buf_1 _671_ (
    .A(\u_gpio_reg.tl_o[30] ),
    .X(tl_o[30])
  );
  sg13g2_buf_1 _672_ (
    .A(\u_gpio_reg.tl_o[31] ),
    .X(tl_o[31])
  );
  sg13g2_buf_1 _673_ (
    .A(\u_gpio_reg.tl_o[32] ),
    .X(tl_o[32])
  );
  sg13g2_buf_1 _674_ (
    .A(\u_gpio_reg.tl_o[33] ),
    .X(tl_o[33])
  );
  sg13g2_buf_1 _675_ (
    .A(\u_gpio_reg.tl_o[34] ),
    .X(tl_o[34])
  );
  sg13g2_buf_1 _676_ (
    .A(\u_gpio_reg.tl_o[35] ),
    .X(tl_o[35])
  );
  sg13g2_buf_1 _677_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[36])
  );
  sg13g2_buf_1 _678_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[37])
  );
  sg13g2_buf_1 _679_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[38])
  );
  sg13g2_buf_1 _680_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[39])
  );
  sg13g2_buf_1 _681_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[40])
  );
  sg13g2_buf_1 _682_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[41])
  );
  sg13g2_buf_1 _683_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[42])
  );
  sg13g2_buf_1 _684_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[43])
  );
  sg13g2_buf_1 _685_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[44])
  );
  sg13g2_buf_1 _686_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[45])
  );
  sg13g2_buf_1 _687_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[46])
  );
  sg13g2_buf_1 _688_ (
    .A(\u_gpio_reg.tl_o[36] ),
    .X(tl_o[47])
  );
  sg13g2_buf_1 _689_ (
    .A(_258_),
    .X(tl_o[48])
  );
  sg13g2_buf_1 _690_ (
    .A(\u_gpio_reg.tl_o[49] ),
    .X(tl_o[49])
  );
  sg13g2_buf_1 _691_ (
    .A(\u_gpio_reg.tl_o[50] ),
    .X(tl_o[50])
  );
  sg13g2_buf_1 _692_ (
    .A(\u_gpio_reg.tl_o[51] ),
    .X(tl_o[51])
  );
  sg13g2_buf_1 _693_ (
    .A(\u_gpio_reg.tl_o[52] ),
    .X(tl_o[52])
  );
  sg13g2_buf_1 _694_ (
    .A(\u_gpio_reg.tl_o[53] ),
    .X(tl_o[53])
  );
  sg13g2_buf_1 _695_ (
    .A(\u_gpio_reg.tl_o[54] ),
    .X(tl_o[54])
  );
  sg13g2_buf_1 _696_ (
    .A(\u_gpio_reg.tl_o[55] ),
    .X(tl_o[55])
  );
  sg13g2_buf_1 _697_ (
    .A(\u_gpio_reg.tl_o[56] ),
    .X(tl_o[56])
  );
  sg13g2_buf_1 _698_ (
    .A(\u_gpio_reg.tl_o[57] ),
    .X(tl_o[57])
  );
  sg13g2_buf_1 _699_ (
    .A(\u_gpio_reg.tl_o[58] ),
    .X(tl_o[58])
  );
  sg13g2_buf_1 _700_ (
    .A(_258_),
    .X(tl_o[59])
  );
  sg13g2_buf_1 _701_ (
    .A(_258_),
    .X(tl_o[60])
  );
  sg13g2_buf_1 _702_ (
    .A(_258_),
    .X(tl_o[61])
  );
  sg13g2_buf_1 _703_ (
    .A(\u_gpio_reg.tl_o[62] ),
    .X(tl_o[62])
  );
  sg13g2_buf_1 _704_ (
    .A(_258_),
    .X(tl_o[63])
  );
  sg13g2_buf_1 _705_ (
    .A(_258_),
    .X(tl_o[64])
  );
  sg13g2_buf_1 _706_ (
    .A(\u_gpio_reg.tl_o[65] ),
    .X(tl_o[65])
  );
  sg13g2_buf_1 _707_ (
    .A(\u_gpio_core.intr_gpio_o[0] ),
    .X(intr_gpio_o[0])
  );
  sg13g2_buf_1 _708_ (
    .A(\u_gpio_core.intr_gpio_o[1] ),
    .X(intr_gpio_o[1])
  );
  sg13g2_buf_1 _709_ (
    .A(\u_gpio_core.intr_gpio_o[2] ),
    .X(intr_gpio_o[2])
  );
  sg13g2_buf_1 _710_ (
    .A(\u_gpio_core.intr_gpio_o[3] ),
    .X(intr_gpio_o[3])
  );
  sg13g2_buf_1 _711_ (
    .A(\hw2reg[0] ),
    .X(cio_gpio_en_o[0])
  );
  sg13g2_buf_1 _712_ (
    .A(\hw2reg[1] ),
    .X(cio_gpio_en_o[1])
  );
  sg13g2_buf_1 _713_ (
    .A(\hw2reg[2] ),
    .X(cio_gpio_en_o[2])
  );
  sg13g2_buf_1 _714_ (
    .A(\hw2reg[3] ),
    .X(cio_gpio_en_o[3])
  );
  sg13g2_buf_1 _715_ (
    .A(\hw2reg[4] ),
    .X(cio_gpio_o[0])
  );
  sg13g2_buf_1 _716_ (
    .A(\hw2reg[5] ),
    .X(cio_gpio_o[1])
  );
  sg13g2_buf_1 _717_ (
    .A(\hw2reg[6] ),
    .X(cio_gpio_o[2])
  );
  sg13g2_buf_1 _718_ (
    .A(\hw2reg[7] ),
    .X(cio_gpio_o[3])
  );
endmodule
