# ruff: noqa
#!/usr/bin/env python3
from __future__ import annotations

"""
Generate rtl_list.f with:
- absolute paths
- canonical package order
- ordered IP dependencies
- include dirs needed by the flow

This script intentionally delegates ordering logic to common.py.
"""

import argparse
from pathlib import Path

from .common import build_ordered_sources


def _abs(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _uniq(seq: list[Path]) -> list[Path]:
    out: list[Path] = []
    seen: set[Path] = set()
    for item in seq:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate rtl_list.f with canonical source ordering.")
    ap.add_argument("--top", required=True, help="Top module name")
    ap.add_argument("--out", required=True, help="Output filelist path")
    ap.add_argument("--ips-root", required=True, help="hw/ips root")
    ap.add_argument("--rtldir", required=True, help="RTL output directory")
    args = ap.parse_args()

    top = str(args.top)
    out = _abs(args.out)
    ips_root = _abs(args.ips_root)
    rtldir = _abs(args.rtldir)

    out.parent.mkdir(parents=True, exist_ok=True)

    incdirs = _uniq(
        [
            rtldir,
            ips_root / "pkgs",
            ips_root / "prim",
            ips_root / "prim_opentitan",
            ips_root / "tlul",
        ]
    )
    incdirs = [d for d in incdirs if d.exists()]

    files = build_ordered_sources(top=top, rtl_root=rtldir, ips_root=ips_root)

    lines: list[str] = []
    lines.append("# Auto-generated by flexsoc.tools.gen_filelist")
    for incdir in incdirs:
        lines.append(f"+incdir+{incdir}")
    for path in files:
        lines.append(path.as_posix())

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
