// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pwm_reg_pkg;

  // Param list
  parameter int NOutputs = 1;

  // Address widths within the block
  parameter int BlockAw = 4;
  parameter int AW = BlockAw;
  parameter int DW = 32;
  parameter int DBW = DW/8;                    // Byte Width

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } cntr_en;
    struct packed {
      logic [3:0]  q;
      logic        qe;
    } dc_resn;
    struct packed {
      logic [26:0] q;
      logic        qe;
    } clk_div;
  } pwm_reg2hw_cfg_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } pwm_reg2hw_pwm_en_mreg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
      logic        qe;
    } duty_cycle;
    struct packed {
      logic [15:0] q;
      logic        qe;
    } phase_delay;
  } pwm_reg2hw_pwm_param_mreg_t;

  // Register -> HW type
  typedef struct packed {
    pwm_reg2hw_cfg_reg_t cfg; // [70:36]
    pwm_reg2hw_pwm_en_mreg_t [0:0] pwm_en; // [35:34]
    pwm_reg2hw_pwm_param_mreg_t [0:0] pwm_param; // [33:0]
  } pwm_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PWM_CFG_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] PWM_PWM_EN_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] PWM_PWM_PARAM_OFFSET = 4'h 8;

  // Register index
  typedef enum int {
    PWM_CFG,
    PWM_PWM_EN,
    PWM_PWM_PARAM
  } pwm_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PWM_PERMIT [3] = '{
    4'b 1111, // index[0] PWM_CFG
    4'b 0001, // index[1] PWM_PWM_EN
    4'b 1111  // index[2] PWM_PWM_PARAM
  };

  parameter type reg_req_t = struct packed {
    logic           valid;
    logic           write;
    logic [AW-1:0]  addr;
    logic [DW-1:0]  wdata;
    logic [DBW-1:0] wstrb;
  };

  parameter type reg_rsp_t = struct packed {
    logic [DW-1:0]  rdata;
    logic           error;
    logic           ready;
  };

endpackage
