// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module uart_reg_core (
  input clk_i,
  input rst_ni,
  input  uart_reg_pkg::reg_req_t reg_req_i,
  output uart_reg_pkg::reg_rsp_t reg_rsp_o,
  // To HW
  output uart_reg_pkg::uart_reg2hw_t reg2hw, // Write
  input  uart_reg_pkg::uart_hw2reg_t hw2reg, // Read

  input logic devmode_i,

  // Integrity check errors
  output logic intg_err_o
);

  import uart_reg_pkg::* ;

  localparam int AW = 5;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;



  // incoming payload check
  logic intg_err;
  assign intg_err = 1'b0;

  // also check for spurious write enables
  logic reg_we_err;
  logic [5:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(6)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  assign reg_we = reg_req_i.valid & reg_req_i.write & ~reg_busy;
  assign reg_re = reg_req_i.valid & ~reg_req_i.write & ~reg_busy;
  assign reg_addr = reg_req_i.addr[AW-1:0];
  assign reg_wdata = reg_req_i.wdata;
  assign reg_be = reg_req_i.wstrb;
  assign reg_rsp_o.rdata = reg_rdata;
  assign reg_rsp_o.error = reg_error;
  assign reg_rsp_o.ready = ~reg_busy;

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_we;
  logic ctrl_tx_qs;
  logic ctrl_tx_wd;
  logic ctrl_rx_qs;
  logic ctrl_rx_wd;
  logic ctrl_nf_qs;
  logic ctrl_nf_wd;
  logic ctrl_slpbk_qs;
  logic ctrl_slpbk_wd;
  logic ctrl_llpbk_qs;
  logic ctrl_llpbk_wd;
  logic ctrl_parity_en_qs;
  logic ctrl_parity_en_wd;
  logic ctrl_parity_odd_qs;
  logic ctrl_parity_odd_wd;
  logic [15:0] ctrl_nco_qs;
  logic [15:0] ctrl_nco_wd;
  logic status_re;
  logic status_txfull_qs;
  logic status_rxfull_qs;
  logic status_txempty_qs;
  logic status_txidle_qs;
  logic status_rxidle_qs;
  logic status_rxempty_qs;
  logic rdata_re;
  logic [7:0] rdata_qs;
  logic wdata_we;
  logic [7:0] wdata_wd;
  logic fifo_ctrl_we;
  logic fifo_ctrl_rxrst_wd;
  logic fifo_ctrl_txrst_wd;
  logic fifo_status_re;
  logic [7:0] fifo_status_txlvl_qs;
  logic [7:0] fifo_status_rxlvl_qs;

  // Register instances
  // R[ctrl]: V(False)
  //   F[tx]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_tx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_tx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.tx.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_tx_qs)
  );

  //   F[rx]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_rx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_rx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.rx.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_rx_qs)
  );

  //   F[nf]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_nf (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_nf_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.nf.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_nf_qs)
  );

  //   F[slpbk]: 4:4
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_slpbk (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_slpbk_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.slpbk.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_slpbk_qs)
  );

  //   F[llpbk]: 5:5
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_llpbk (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_llpbk_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.llpbk.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_llpbk_qs)
  );

  //   F[parity_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_parity_en (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_parity_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.parity_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_parity_en_qs)
  );

  //   F[parity_odd]: 7:7
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_parity_odd (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_parity_odd_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.parity_odd.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_parity_odd_qs)
  );

  //   F[nco]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h4b7f),
    .Mubi    (1'b0)
  ) u_ctrl_nco (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_nco_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.nco.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_nco_qs)
  );


  // R[status]: V(True)
  //   F[txfull]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_txfull (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.txfull.d),
    .qre    (reg2hw.status.txfull.re),
    .qe     (),
    .q      (reg2hw.status.txfull.q),
    .ds     (),
    .qs     (status_txfull_qs)
  );

  //   F[rxfull]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rxfull (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rxfull.d),
    .qre    (reg2hw.status.rxfull.re),
    .qe     (),
    .q      (reg2hw.status.rxfull.q),
    .ds     (),
    .qs     (status_rxfull_qs)
  );

  //   F[txempty]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_txempty (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.txempty.d),
    .qre    (reg2hw.status.txempty.re),
    .qe     (),
    .q      (reg2hw.status.txempty.q),
    .ds     (),
    .qs     (status_txempty_qs)
  );

  //   F[txidle]: 3:3
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_txidle (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.txidle.d),
    .qre    (reg2hw.status.txidle.re),
    .qe     (),
    .q      (reg2hw.status.txidle.q),
    .ds     (),
    .qs     (status_txidle_qs)
  );

  //   F[rxidle]: 4:4
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rxidle (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rxidle.d),
    .qre    (reg2hw.status.rxidle.re),
    .qe     (),
    .q      (reg2hw.status.rxidle.q),
    .ds     (),
    .qs     (status_rxidle_qs)
  );

  //   F[rxempty]: 5:5
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rxempty (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rxempty.d),
    .qre    (reg2hw.status.rxempty.re),
    .qe     (),
    .q      (reg2hw.status.rxempty.q),
    .ds     (),
    .qs     (status_rxempty_qs)
  );


  // R[rdata]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_rdata (
    .re     (rdata_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.rdata.d),
    .qre    (reg2hw.rdata.re),
    .qe     (),
    .q      (reg2hw.rdata.q),
    .ds     (),
    .qs     (rdata_qs)
  );


  // R[wdata]: V(False)
  logic wdata_qe;
  logic [0:0] wdata_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_wdata0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&wdata_flds_we),
    .q_o(wdata_qe)
  );
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_wdata (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (wdata_we),
    .wd     (wdata_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (wdata_flds_we[0]),
    .q      (reg2hw.wdata.q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.wdata.qe = wdata_qe;


  // R[fifo_ctrl]: V(False)
  logic fifo_ctrl_qe;
  logic [1:0] fifo_ctrl_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_fifo_ctrl0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&fifo_ctrl_flds_we),
    .q_o(fifo_ctrl_qe)
  );
  //   F[rxrst]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_fifo_ctrl_rxrst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (fifo_ctrl_we),
    .wd     (fifo_ctrl_rxrst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (fifo_ctrl_flds_we[0]),
    .q      (reg2hw.fifo_ctrl.rxrst.q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.fifo_ctrl.rxrst.qe = fifo_ctrl_qe;

  //   F[txrst]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_fifo_ctrl_txrst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (fifo_ctrl_we),
    .wd     (fifo_ctrl_txrst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (fifo_ctrl_flds_we[1]),
    .q      (reg2hw.fifo_ctrl.txrst.q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.fifo_ctrl.txrst.qe = fifo_ctrl_qe;


  // R[fifo_status]: V(True)
  //   F[txlvl]: 7:0
  prim_subreg_ext #(
    .DW    (8)
  ) u_fifo_status_txlvl (
    .re     (fifo_status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.fifo_status.txlvl.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (fifo_status_txlvl_qs)
  );

  //   F[rxlvl]: 23:16
  prim_subreg_ext #(
    .DW    (8)
  ) u_fifo_status_rxlvl (
    .re     (fifo_status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.fifo_status.rxlvl.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (fifo_status_rxlvl_qs)
  );



  logic [5:0] addr_hit;
  always_comb begin
    addr_hit[0] = (reg_addr == UART_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == UART_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == UART_RDATA_OFFSET);
    addr_hit[3] = (reg_addr == UART_WDATA_OFFSET);
    addr_hit[4] = (reg_addr == UART_FIFO_CTRL_OFFSET);
    addr_hit[5] = (reg_addr == UART_FIFO_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(UART_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(UART_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(UART_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(UART_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(UART_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(UART_PERMIT[5] & ~reg_be)))));
  end

  // Generate write-enables
  assign ctrl_we = addr_hit[0] & reg_we & !reg_error;

  assign ctrl_tx_wd = reg_wdata[0];

  assign ctrl_rx_wd = reg_wdata[1];

  assign ctrl_nf_wd = reg_wdata[2];

  assign ctrl_slpbk_wd = reg_wdata[4];

  assign ctrl_llpbk_wd = reg_wdata[5];

  assign ctrl_parity_en_wd = reg_wdata[6];

  assign ctrl_parity_odd_wd = reg_wdata[7];

  assign ctrl_nco_wd = reg_wdata[31:16];
  assign status_re = addr_hit[1] & reg_re & !reg_error;
  assign rdata_re = addr_hit[2] & reg_re & !reg_error;
  assign wdata_we = addr_hit[3] & reg_we & !reg_error;

  assign wdata_wd = reg_wdata[7:0];
  assign fifo_ctrl_we = addr_hit[4] & reg_we & !reg_error;

  assign fifo_ctrl_rxrst_wd = reg_wdata[0];

  assign fifo_ctrl_txrst_wd = reg_wdata[1];
  assign fifo_status_re = addr_hit[5] & reg_re & !reg_error;

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = ctrl_we;
    reg_we_check[1] = 1'b0;
    reg_we_check[2] = 1'b0;
    reg_we_check[3] = wdata_we;
    reg_we_check[4] = fifo_ctrl_we;
    reg_we_check[5] = 1'b0;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_tx_qs;
        reg_rdata_next[1] = ctrl_rx_qs;
        reg_rdata_next[2] = ctrl_nf_qs;
        reg_rdata_next[4] = ctrl_slpbk_qs;
        reg_rdata_next[5] = ctrl_llpbk_qs;
        reg_rdata_next[6] = ctrl_parity_en_qs;
        reg_rdata_next[7] = ctrl_parity_odd_qs;
        reg_rdata_next[31:16] = ctrl_nco_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_txfull_qs;
        reg_rdata_next[1] = status_rxfull_qs;
        reg_rdata_next[2] = status_txempty_qs;
        reg_rdata_next[3] = status_txidle_qs;
        reg_rdata_next[4] = status_rxidle_qs;
        reg_rdata_next[5] = status_rxempty_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = rdata_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
      end

      addr_hit[5]: begin
        reg_rdata_next[7:0] = fifo_status_txlvl_qs;
        reg_rdata_next[23:16] = fifo_status_rxlvl_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

endmodule
