from __future__ import annotations

import argparse
from pathlib import Path


ALIASES = {
    "uart-master": "uart",
    "uart_master": "uart",
}


def canon(name: str) -> str:
    return ALIASES.get(name, name)


def add_unique(out: list[str], seen: set[str], value: str) -> None:
    v = value.strip()
    if not v or v in seen:
        return
    seen.add(v)
    out.append(v)


def add_file(out: list[str], seen: set[str], path: Path) -> None:
    if path.exists():
        add_unique(out, seen, str(path.resolve()))


def common_files(repo_root: Path) -> list[Path]:
    inc_pkgs = repo_root / "hw/ips/pkgs"
    inc_prim = repo_root / "hw/ips/prim"
    inc_prim_ot = repo_root / "hw/ips/prim_opentitan"
    inc_tlul = repo_root / "hw/ips/tlul"

    package_files = [
        inc_pkgs / "top_pkg.sv",
        inc_prim / "prim_reg_pkg.sv",
        inc_pkgs / "prim_mubi_pkg.sv",
        inc_pkgs / "prim_secded_pkg.sv",
        inc_pkgs / "prim_subreg_pkg.sv",
        inc_pkgs / "prim_util_pkg.sv",
        inc_pkgs / "tlul_pkg.sv",
        inc_pkgs / "prim_assert.sv",
        inc_pkgs / "prim_count_pkg.sv",
        inc_pkgs / "prim_flop_macros.sv",
        inc_pkgs / "prim_alert_pkg.sv",
    ]

    prim_files = sorted(p for p in inc_prim.glob("*.sv") if p.name != "prim_reg_pkg.sv")
    prim_ot_files = sorted(p for p in inc_prim_ot.glob("*.sv"))
    tlul_files = sorted(p for p in inc_tlul.glob("*.sv"))

    return package_files + prim_files + prim_ot_files + tlul_files


def write_ip_flist(top: str, out: Path, rtldir: Path, repo_root: Path) -> None:
    inc_pkgs = repo_root / "hw/ips/pkgs"
    inc_prim = repo_root / "hw/ips/prim"
    inc_prim_ot = repo_root / "hw/ips/prim_opentitan"
    inc_tlul = repo_root / "hw/ips/tlul"

    local_sv = sorted(rtldir.glob("*.sv"))

    pkg_files: list[Path] = []
    other_modules: list[Path] = []
    core_file: Path | None = None
    top_file: Path | None = None

    for f in local_sv:
        name = f.name
        if name == f"{top}_core.sv":
            core_file = f
        elif name == f"{top}.sv":
            top_file = f
        elif "pkg" in name:
            pkg_files.append(f)
        else:
            other_modules.append(f)

    lines: list[str] = []
    seen: set[str] = set()

    add_unique(lines, seen, "# Auto-generated by flexsoc.tools.gen_filelist")
    add_unique(lines, seen, f"+incdir+{rtldir}")
    add_unique(lines, seen, f"+incdir+{inc_pkgs}")
    add_unique(lines, seen, f"+incdir+{inc_prim}")
    add_unique(lines, seen, f"+incdir+{inc_prim_ot}")
    add_unique(lines, seen, f"+incdir+{inc_tlul}")

    for f in common_files(repo_root):
        add_file(lines, seen, f)

    for f in sorted(pkg_files):
        add_file(lines, seen, f)

    for f in sorted(other_modules):
        add_file(lines, seen, f)

    if core_file is not None:
        add_file(lines, seen, core_file)

    if top_file is not None:
        add_file(lines, seen, top_file)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def remap_soc_line(line: str, ip_rtl_dir: Path) -> str | None:
    s = line.strip()
    if not s or s.startswith("#") or s.startswith("+incdir+"):
        return None

    p = Path(s)

    if p.is_absolute():
        # shared/common hw files stay absolute
        if "/hw/ips/" in p.as_posix():
            return str(p.resolve())
        # IP-local generated files are remapped into the loaded IP bundle rtl dir
        return str((ip_rtl_dir / p.name).resolve())

    return str((ip_rtl_dir / p.name).resolve())


def write_soc_flist(top: str, out: Path, run_dir: Path) -> None:
    rtl_dir = run_dir / "rtl"
    ips_dir = run_dir / "ips"

    lines: list[str] = []
    seen: set[str] = set()

    add_unique(lines, seen, "# Auto-generated by flexsoc.tools.gen_filelist --soc")

    if ips_dir.exists():
        for ip_dir in sorted(p for p in ips_dir.iterdir() if p.is_dir()):
            ip_rtl_dir = ip_dir / "rtl"
            ip_flist = ip_rtl_dir / "rtl_list.f"

            if ip_flist.exists():
                for raw in ip_flist.read_text(encoding="utf-8").splitlines():
                    mapped = remap_soc_line(raw, ip_rtl_dir)
                    if mapped is not None:
                        add_unique(lines, seen, mapped)
            else:
                name = canon(ip_dir.name)
                for f in sorted(ip_rtl_dir.glob("*.sv")):
                    add_file(lines, seen, f)
                for f in sorted(ip_rtl_dir.glob("*.v")):
                    add_file(lines, seen, f)
                add_file(lines, seen, ip_rtl_dir / f"{name}_reg_pkg.sv")
                add_file(lines, seen, ip_rtl_dir / f"{name}_reg_top.sv")
                add_file(lines, seen, ip_rtl_dir / f"{name}_core.sv")
                add_file(lines, seen, ip_rtl_dir / f"{name}.sv")

    add_file(lines, seen, rtl_dir / "tl_main_pkg.sv")
    add_file(lines, seen, rtl_dir / "xbar_main.sv")
    add_file(lines, seen, rtl_dir / f"{top}.sv")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ips-root", required=False)
    ap.add_argument("--rtldir", required=False)
    ap.add_argument("--workspace", required=False)
    ap.add_argument("--run-top", required=False)
    ap.add_argument("--run-id", required=False)
    ap.add_argument("--soc", action="store_true")
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[3]
    out = Path(args.out).expanduser().resolve()

    if args.soc:
        if not args.workspace or not args.run_top or not args.run_id:
            raise SystemExit("ERROR: --soc requires --workspace --run-top --run-id")
        run_dir = Path(args.workspace).expanduser().resolve() / "runs" / args.run_top / args.run_id
        write_soc_flist(args.top, out, run_dir)
    else:
        if not args.rtldir:
            raise SystemExit("ERROR: IP mode requires --rtldir")
        rtldir = Path(args.rtldir).expanduser().resolve()
        write_ip_flist(args.top, out, rtldir, repo_root)

    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
