"""Generate starter HJSON metadata for a FlexSoC IP block."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from textwrap import dedent

from flexsoc.clocking import clock_config

try:
    from .common import colorize, ensure_dir, safe_write_file
except Exception:  # pragma: no cover - keeps direct script execution import-safe.
    def colorize(text: str) -> str:
        """Return text unchanged when package helpers are unavailable."""

        return text

    def ensure_dir(path: str | Path) -> None:
        """Create a directory for direct script execution."""

        Path(path).mkdir(parents=True, exist_ok=True)

    def safe_write_file(path: str | Path, content: str, *, overwrite: bool = False) -> None:
        """Write a file while preserving the existing no-overwrite default."""

        target = Path(path)
        if target.exists() and not overwrite:
            raise FileExistsError(target)
        target.write_text(content, encoding="utf-8")


HJSON_TEMPLATE = r"""{{ 
  name:               "{top}",
  human_name:         "{top}",
  one_line_desc:      "Starter FlexSoC IP with control, datapath, and status registers.",
  one_paragraph_desc: '''
    Default development block used by the generated RTL stub and verification scaffolds.
  '''

  cip_id:             "1",
  design_spec:        "",
  dv_doc:             "",
  hw_checklist:       "",
  sw_checklist:       "",

  revisions: [{{
    version:            "1.0.0",
    life_stage:         "L0",
    design_stage:       "D0",
    verification_stage: "V0",
    commit_id:          "",
    notes:              "Generated starter metadata."
  }}]

  clocking: [{{ clock: "clk_i", reset: "rst_ni" }}]
  bus_interfaces: [{{ protocol: "{itf}", direction: "device" }}]
  regwidth: "32"

  registers: [
    {{
      name: "CTRL",
      desc: "Datapath control register.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [
        {{ bits: "0", name: "EN",    desc: "Enable the generated datapath." }},
        {{ bits: "1", name: "START", desc: "Software start pulse placeholder." }},
        {{ bits: "2", name: "CLR",   desc: "Clear the generated pipeline." }}
      ]
    }},

    {{
      name: "MODE",
      desc: "Small mode register used by the generated core.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [
        {{ bits: "1:0", name: "SEL",      desc: "0:add, 1:xor, 2:shift, 3:pass." }},
        {{ bits: "2",   name: "INVERT",   desc: "Reserved starter option." }},
        {{ bits: "3",   name: "SATURATE", desc: "Reserved starter option." }}
      ]
    }},

    {{
      name: "OPERAND_A",
      desc: "Example software operand A.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Operand A value." }}]
    }},

    {{
      name: "OPERAND_B",
      desc: "Example software operand B.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Operand B value." }}]
    }},

    {{
      name: "SCALE",
      desc: "Example shift/scale parameter.",
      swaccess: "rw",
      hwaccess: "hro",
      fields: [{{ bits: "7:0", name: "VALUE", desc: "Shift amount used in MODE=2." }}]
    }},

    {{
      name: "STATUS",
      desc: "Datapath status generated by hardware.",
      swaccess: "ro",
      hwaccess: "hrw",
      hwext: "true",
      fields: [
        {{ bits: "0", name: "BUSY",  desc: "Pipeline stage 0 is valid." }},
        {{ bits: "1", name: "DONE",  desc: "Pipeline output is valid." }},
        {{ bits: "2", name: "ERROR", desc: "Reserved error flag." }}
      ]
    }},

    {{
      name: "RESULT",
      desc: "Latest generated datapath result.",
      swaccess: "ro",
      hwaccess: "hrw",
      hwext: "true",
      fields: [{{ bits: "31:0", name: "VALUE", desc: "Latest data_o sample." }}]
    }}
  ]
}}
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments for HJSON template generation."""

    parser = argparse.ArgumentParser(
        prog="hjson_gen",
        description="Generate a starter <TOP>.hjson template for an IP.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--top", required=True, help="Top module name.")
    parser.add_argument("--interface", dest="itf", required=True, help="Bus interface, for example tlul.")
    parser.add_argument("--output-dir", dest="output", default=".", help="Output directory.")
    parser.add_argument("-f", "--force", action="store_true", help="Overwrite an existing <TOP>.hjson file.")
    return parser.parse_args(argv)


def render_hjson(top: str, itf: str) -> str:
    """Render a compact default IP HJSON document."""

    return HJSON_TEMPLATE.format(top=top, itf=itf)


def write_hjson(top: str, itf: str, output: str | Path = ".", *, force: bool = False) -> Path:
    """Write a generated HJSON file and return its path."""

    outdir = Path(output or ".")
    ensure_dir(outdir)
    path = outdir / f"{top}.hjson"
    safe_write_file(path, render_hjson(top, itf), overwrite=force)
    return path

def cfg_hjson(top: str) -> str:
    """Render the cfg-domain HJSON regmap."""

    name = f"{top}_cfg"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "Cfg-domain controls for the generated N-clock IP.",
      one_paragraph_desc: "Global control and cfg-domain status registers for the generated N-clock scaffold.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock cfg regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "CTRL",
          desc: "Global control written from the cfg clock domain.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [
            {{ bits: "0", name: "ENABLE", desc: "Enable RX input and DSP processing." }},
            {{ bits: "1", name: "SOFT_RESET", desc: "Synchronous datapath clear request." }},
            {{ bits: "2", name: "CLK_GATE_EN", desc: "Allow the DSP clock gate to close when idle." }}
          ]
        }},
        {{
          name: "GAIN",
          desc: "Signed Q1.15 gain added by the DSP pipeline. Update while CTRL.ENABLE is low.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "15:0", name: "VALUE", desc: "DSP gain coefficient." }}]
        }},
        {{
          name: "CFG_STATUS",
          desc: "Cfg-domain view of datapath status synchronized back from the DSP domain.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [
            {{ bits: "0", name: "BUSY", desc: "The DSP pipeline currently owns an output sample." }},
            {{ bits: "1", name: "OVERFLOW", desc: "The latest result overflowed or saturated." }}
          ]
        }}
      ]
    }}
    """)


def dsp_hjson(top: str) -> str:
    """Render the dsp-domain HJSON regmap."""

    name = f"{top}_dsp"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "DSP-domain controls and status for the generated N-clock IP.",
      one_paragraph_desc: "Algorithm selection, threshold, result and live DSP status registers for the generated N-clock scaffold.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock dsp regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "DSP_CTRL",
          desc: "DSP-domain algorithm control.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [
            {{ bits: "1:0", name: "OP", desc: "0=MAC plus gain, 1=absolute difference, 2=energy estimate." }},
            {{ bits: "2", name: "SATURATE", desc: "Clamp overflowing results to signed 32-bit limits." }}
          ]
        }},
        {{
          name: "THRESHOLD",
          desc: "Unsigned threshold compared with the DSP result.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "31:0", name: "VALUE", desc: "Result threshold." }}]
        }},
        {{
          name: "RESULT",
          desc: "Latest signed DSP result.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [{{ bits: "31:0", name: "VALUE", desc: "Latest output result." }}]
        }},
        {{
          name: "DSP_STATUS",
          desc: "DSP-domain live status.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [
            {{ bits: "0", name: "VALID", desc: "RESULT contains a valid sample." }},
            {{ bits: "1", name: "ABOVE_THRESHOLD", desc: "RESULT is greater than THRESHOLD." }},
            {{ bits: "2", name: "FIFO_EMPTY", desc: "RX-to-DSP FIFO has no readable payload." }},
            {{ bits: "3", name: "OVERFLOW", desc: "The latest operation overflowed before saturation." }}
          ]
        }}
      ]
    }}
    """)


def generic_hjson(top: str, regmap: str) -> str:
    """Render a small generic HJSON for an extra domain regmap."""

    name = f"{top}_{regmap}"
    return dedent(f"""\
    {{
      name:               "{name}",
      human_name:         "{name}",
      one_line_desc:      "Generated {regmap}-domain control/status registers.",
      one_paragraph_desc: "Starter control/status map for a generated N-clock domain.",
      cip_id:             "1",
      design_spec:        "",
      dv_doc:             "",
      hw_checklist:       "",
      sw_checklist:       "",
      revisions: [{{
        version:            "1.0.0",
        life_stage:         "L0",
        design_stage:       "D0",
        verification_stage: "V0",
        commit_id:          "",
        notes:              "Generated N-clock domain regmap."
      }}],
      clocking: [{{ clock: "clk_i", reset: "rst_ni" }}],
      bus_interfaces: [{{ protocol: "tlul", direction: "device" }}],
      regwidth: "32",
      registers: [
        {{
          name: "CTRL",
          desc: "Domain control.",
          swaccess: "rw",
          hwaccess: "hro",
          fields: [{{ bits: "0", name: "ENABLE", desc: "Enable this domain." }}]
        }},
        {{
          name: "STATUS",
          desc: "Domain status.",
          swaccess: "ro",
          hwaccess: "hrw",
          hwext: "true",
          fields: [{{ bits: "0", name: "BUSY", desc: "Domain busy." }}]
        }}
      ]
    }}
    """)


def render_nclock_hjson(top: str, regmap: str) -> str:
    """Render one N-clock regmap by short name."""

    if regmap == "cfg":
        return cfg_hjson(top)
    if regmap == "dsp":
        return dsp_hjson(top)
    return generic_hjson(top, regmap)


# ---------------------------------------------------------------------------
# RTL generation
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """Run the HJSON generator command line entrypoint."""

    try:
        args = parse_args(argv)
        top, itf = args.top.strip(), args.itf.strip()
        if not top or not itf:
            print(colorize("Error: --top and --itf must be non-empty."), file=sys.stderr)
            return 2
        clocks = clock_config()
        if clocks.multiclock:
            output = Path(args.output)
            ensure_dir(output)
            for regmap in ("cfg", "dsp"):
                path = output / f"{top}_{regmap}.hjson"
                safe_write_file(path, render_nclock_hjson(top, regmap), overwrite=args.force)
        else:
            write_hjson(top, itf, args.output, force=args.force)
        return 0
    except FileExistsError as err:
        print(colorize(f"Refusing to overwrite existing file: {err} (use --force)"), file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print(colorize("Aborted by user."), file=sys.stderr)
        return 130
    except Exception as err:
        print(colorize(f"Error: {err!s}"), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
