"""Regenerate the top wrapper from an edited <top>_core.sv module."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from .common import colorize, safe_write_file


@dataclass(frozen=True, slots=True)
class Port:
    """One parsed SystemVerilog port."""

    direction: str
    svtype: str
    name: str


def _strip_comments(text: str) -> str:
    """Remove line and block comments from SystemVerilog text."""

    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return "\n".join(line.split("//", 1)[0] for line in text.splitlines())


def _port_list(text: str) -> str:
    """Return the first module port list."""

    match = re.search(r"module\s+\w+\s*(?:import\s+[^;]+;\s*)?\((.*?)\);", _strip_comments(text), re.S)
    if not match:
        raise ValueError("could not parse core module header")
    return match.group(1)


def parse_ports(core_path: str | Path) -> list[Port]:
    """Parse direction, type, and name from a compact module header."""

    ports: list[Port] = []
    for raw in _port_list(Path(core_path).read_text(encoding="utf-8")).splitlines():
        line = raw.strip().rstrip(",")
        if not line.startswith(("input", "output")):
            continue
        tokens = line.split()
        direction, name = tokens[0], tokens[-1]
        ports.append(Port(direction, " ".join(tokens[1:-1]), name))
    return ports


def _bus_ports(itf: str) -> list[Port]:
    """Return register-bus wrapper ports for the selected interface."""

    if itf == "tlul":
        return [Port("input", "tlul_pkg::tl_h2d_t", "tl_i"), Port("output", "tlul_pkg::tl_d2h_t", "tl_o")]
    return [Port("input", "reg_req_t", "reg_req_i"), Port("output", "reg_rsp_t", "reg_rsp_o")]


def _bus_pins(itf: str) -> list[str]:
    """Return register-top bus pin connections."""

    return [".tl_i(tl_i)", ".tl_o(tl_o)"] if itf == "tlul" else [".reg_req_i(reg_req_i)", ".reg_rsp_o(reg_rsp_o)"]


def _external_core_ports(ports: list[Port]) -> list[Port]:
    """Return core ports that must stay visible at the wrapper boundary."""

    hidden = {"reg2hw", "hw2reg"}
    return [port for port in ports if port.name not in hidden]


def _format_port(port: Port) -> str:
    """Render one module port declaration."""

    return f"  {port.direction:<6} {port.svtype} {port.name}".replace("  ", " ").rstrip()


def _instance(name: str, module: str, pins: list[str]) -> list[str]:
    """Render a compact SystemVerilog instance."""

    lines = [f"  {module} u_{name} ("]
    lines.extend(f"    {pin}{',' if i + 1 < len(pins) else ''}" for i, pin in enumerate(pins))
    lines.append("  );")
    return lines


def render_top_from_core(top: str, core_path: str | Path, itf: str = "tlul") -> str:
    """Render <top>.sv from <top>_core.sv ports and the register interface."""

    itf = "reg_iface" if itf == "reg" else itf.strip().lower()
    if itf not in {"tlul", "reg_iface"}:
        raise ValueError("--interface must be tlul, reg_iface, or reg")
    ports = parse_ports(core_path)
    top_ports = _external_core_ports(ports) + _bus_ports(itf)
    reg_pins = [".clk_i(clk_i)", ".rst_ni(rst_ni)", *_bus_pins(itf), ".reg2hw(reg2hw)", ".hw2reg(hw2reg)", ".devmode_i(1'b1)"]
    core_pins = [f".{port.name}({port.name})" for port in ports]
    lines = [
        "// Auto-generated by flexsoc.backend.top_from_core.",
        f"module {top}",
        f"  import {top}_reg_pkg::*;",
        "(",
        *[line + ("," if i + 1 < len(top_ports) else "") for i, line in enumerate(_format_port(p) for p in top_ports)],
        ");",
        "",
        f"  {top}_reg2hw_t reg2hw;",
        f"  {top}_hw2reg_t hw2reg;",
        "",
        *_instance(f"{top}_reg", f"{top}_reg_top", reg_pins),
        "",
        *_instance(f"{top}_core", f"{top}_core", core_pins),
        "",
        "endmodule",
    ]
    return "\n".join(lines) + "\n"


def write_top_from_core(top: str, rtl_dir: str | Path, itf: str, *, force: bool = False) -> Path:
    """Write <top>.sv next to <top>_core.sv."""

    rtl = Path(rtl_dir)
    core = rtl / f"{top}_core.sv"
    out = rtl / f"{top}.sv"
    if not core.exists():
        raise FileNotFoundError(core)
    safe_write_file(out, render_top_from_core(top, core, itf), overwrite=force)
    return out


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description="Regenerate <TOP>.sv from <TOP>_core.sv.")
    parser.add_argument("--top", required=True)
    parser.add_argument("--rtl-dir", default=".")
    parser.add_argument("--interface", default="tlul", choices=["tlul", "reg_iface", "reg"])
    parser.add_argument("-f", "--force", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the wrapper generator."""

    try:
        args = parse_args(argv)
        write_top_from_core(args.top, args.rtl_dir, args.interface, force=args.force)
        return 0
    except Exception as err:
        print(colorize(f"Error: {err}"), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
