"""Regenerate the top wrapper from an edited <top>_core.sv module."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from flexsoc.clocking import ClockConfig, ClockDomain, clock_config

from .common import colorize, safe_write_file


@dataclass(frozen=True, slots=True)
class Port:
    """One parsed SystemVerilog port."""

    direction: str
    svtype: str
    name: str


def _strip_comments(text: str) -> str:
    """Remove line and block comments from SystemVerilog text."""

    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return "\n".join(line.split("//", 1)[0] for line in text.splitlines())


def _port_list(text: str) -> str:
    """Return the first module port list."""

    match = re.search(r"module\s+\w+\s*(?:import\s+[^;]+;\s*)*\((.*?)\);", _strip_comments(text), re.S)
    if not match:
        raise ValueError("could not parse core module header")
    return match.group(1)


def parse_ports(core_path: str | Path) -> list[Port]:
    """Parse direction, type, and name from a compact module header."""

    ports: list[Port] = []
    for raw in _port_list(Path(core_path).read_text(encoding="utf-8")).splitlines():
        line = raw.strip().rstrip(",")
        if not line.startswith(("input", "output")):
            continue
        tokens = line.split()
        direction, name = tokens[0], tokens[-1]
        ports.append(Port(direction, " ".join(tokens[1:-1]), name))
    return ports


def _bus_ports(itf: str) -> list[Port]:
    """Return register-bus wrapper ports for the selected interface."""

    if itf == "tlul":
        return [Port("input", "tlul_pkg::tl_h2d_t", "tl_i"), Port("output", "tlul_pkg::tl_d2h_t", "tl_o")]
    return [Port("input", "reg_req_t", "reg_req_i"), Port("output", "reg_rsp_t", "reg_rsp_o")]


def _bus_pins(itf: str) -> list[str]:
    """Return register-top bus pin connections."""

    return [".tl_i(tl_i)", ".tl_o(tl_o)"] if itf == "tlul" else [".reg_req_i(reg_req_i)", ".reg_rsp_o(reg_rsp_o)"]


def _external_core_ports(ports: list[Port]) -> list[Port]:
    """Return core ports that must stay visible at the wrapper boundary."""

    hidden = {"reg2hw", "hw2reg"}
    return [port for port in ports if port.name not in hidden]


def _format_port(port: Port) -> str:
    """Render one module port declaration."""

    return f"  {port.direction:<6} {port.svtype} {port.name}".replace("  ", " ").rstrip()


def _instance(name: str, module: str, pins: list[str]) -> list[str]:
    """Render a compact SystemVerilog instance."""

    lines = [f"  {module} u_{name} ("]
    lines.extend(f"    {pin}{',' if i + 1 < len(pins) else ''}" for i, pin in enumerate(pins))
    lines.append("  );")
    return lines


def render_top_from_core(top: str, core_path: str | Path, itf: str = "tlul") -> str:
    """Render <top>.sv from <top>_core.sv ports and the register interface."""

    itf = "reg_iface" if itf == "reg" else itf.strip().lower()
    if itf not in {"tlul", "reg_iface"}:
        raise ValueError("--interface must be tlul, reg_iface, or reg")
    ports = parse_ports(core_path)
    top_ports = _external_core_ports(ports) + _bus_ports(itf)
    reg_pins = [".clk_i(clk_i)", ".rst_ni(rst_ni)", *_bus_pins(itf), ".reg2hw(reg2hw)", ".hw2reg(hw2reg)", ".devmode_i(1'b1)"]
    core_pins = [f".{port.name}({port.name})" for port in ports]
    lines = [
        "// Auto-generated by flexsoc.backend.top_from_core.",
        f"module {top}",
        f"  import {top}_reg_pkg::*;",
        "(",
        *[line + ("," if i + 1 < len(top_ports) else "") for i, line in enumerate(_format_port(p) for p in top_ports)],
        ");",
        "",
        f"  {top}_reg2hw_t reg2hw;",
        f"  {top}_hw2reg_t hw2reg;",
        "",
        *_instance(f"{top}_reg", f"{top}_reg_top", reg_pins),
        "",
        *_instance(f"{top}_core", f"{top}_core", core_pins),
        "",
        "endmodule",
    ]
    return "\n".join(lines) + "\n"


_REG_PORT_RE = re.compile(r"^(?P<name>[A-Za-z_][A-Za-z0-9_]*)_(?P<kind>reg2hw_i|hw2reg_o)$")


@dataclass(frozen=True, slots=True)
class RegisterWindow:
    """One discovered regtool interface and its clock domain."""

    name: str
    domain: ClockDomain

    @property
    def reset_ni(self) -> str:
        return self.domain.reset if self.domain.reset_polarity == "low" else f"~{self.domain.reset}"


def _register_windows(ports: list[Port], clocks: ClockConfig) -> tuple[RegisterWindow, ...]:
    """Bind paired register ports to same-named clock domains."""

    kinds: dict[str, set[str]] = {}
    for port in ports:
        match = _REG_PORT_RE.match(port.name)
        if match:
            kinds.setdefault(match["name"], set()).add(match["kind"])
    domains, port_names = {item.name: item for item in clocks.domains}, {port.name for port in ports}
    windows: list[RegisterWindow] = []
    for name, found in kinds.items():
        missing = {"reg2hw_i", "hw2reg_o"} - found
        if missing:
            raise ValueError(f"register window {name!r} is missing core port(s): {', '.join(sorted(missing))}")
        domain = domains.get(name)
        if domain is None:
            raise ValueError(f"register window {name!r} requires a matching CLOCK_DOMAINS entry")
        absent = [signal for signal in (domain.signal, domain.reset) if signal not in port_names]
        if absent:
            raise ValueError(f"register window {name!r} clock/reset port(s) missing from core: {', '.join(absent)}")
        windows.append(RegisterWindow(name, domain))
    return tuple(windows)


def render_nclock_top(top: str, core_path: str | Path, clocks: ClockConfig) -> str:
    """Render a clock-count-neutral wrapper around one editable core."""

    core = Path(core_path)
    core = core / f"{top}_core.sv" if core.is_dir() else core
    ports = parse_ports(core)
    windows = _register_windows(ports, clocks)
    hidden = {f"{window.name}_{kind}" for window in windows for kind in ("reg2hw_i", "hw2reg_o")}
    exposed = [port for port in ports if port.name not in hidden]
    declarations = [_format_port(port) for port in exposed]
    declarations += [item for window in windows for item in (
        f"  input  tlul_pkg::tl_h2d_t        {window.name}_tl_i",
        f"  output tlul_pkg::tl_d2h_t        {window.name}_tl_o",
    )]
    devmode = "devmode_i" if any(port.name == "devmode_i" for port in exposed) else "1'b1"
    lines = [
        "// Auto-generated N-clock wrapper. Edit the core, then rerun fx top_from_core.",
        f"module {top}",
        *(f"  import {top}_{window.name}_reg_pkg::*;" for window in windows),
        "(",
        *[line + ("," if i + 1 < len(declarations) else "") for i, line in enumerate(declarations)],
        ");", "",
    ]
    for window in windows:
        name, domain = window.name, window.domain
        lines += [
            f"  {top}_{name}_reg2hw_t {name}_reg2hw;",
            f"  {top}_{name}_hw2reg_t {name}_hw2reg;", "",
            f"  {top}_{name}_reg_top u_{name}_reg_top (",
            f"    .clk_i     ({domain.signal}),",
            f"    .rst_ni    ({window.reset_ni}),",
            f"    .tl_i      ({name}_tl_i),",
            f"    .tl_o      ({name}_tl_o),",
            f"    .reg2hw    ({name}_reg2hw),",
            f"    .hw2reg    ({name}_hw2reg),",
            f"    .devmode_i ({devmode})",
            "  );", "",
        ]
    pins = []
    for port in ports:
        match = _REG_PORT_RE.match(port.name)
        signal = f"{match['name']}_{match['kind'][:-2]}" if match else port.name
        pins.append(f"    .{port.name:<22}({signal})")
    lines += [f"  {top}_core u_core (", ",\n".join(pins), "  );", "", "endmodule", ""]
    return "\n".join(lines)


def write_top_from_core(top: str, rtl_dir: str | Path, itf: str, *, force: bool = False, clocks: ClockConfig | None = None) -> Path:
    """Write <top>.sv next to <top>_core.sv."""

    rtl = Path(rtl_dir)
    core = rtl / f"{top}_core.sv"
    out = rtl / f"{top}.sv"
    if not core.exists():
        raise FileNotFoundError(core)
    cfg = clocks or clock_config()
    text = render_nclock_top(top, core, cfg) if cfg.multiclock else render_top_from_core(top, core, itf)
    safe_write_file(out, text, overwrite=force)
    return out


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description="Regenerate <TOP>.sv from <TOP>_core.sv.")
    parser.add_argument("--top", required=True)
    parser.add_argument("--rtl-dir", default=".")
    parser.add_argument("--interface", default="tlul", choices=["tlul", "reg_iface", "reg"])
    parser.add_argument("-f", "--force", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the wrapper generator."""

    try:
        args = parse_args(argv)
        write_top_from_core(args.top, args.rtl_dir, args.interface, force=args.force)
        return 0
    except Exception as err:
        print(colorize(f"Error: {err}"), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
