// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
#include "verilated_covergroup.h"
#include "verilated_timing.h"
class Vtop_prim_mubi_pkg;
class Vtop_prim_secded_pkg;
class Vtop_rv_timer_reg_pkg;
class Vtop_tlul_pkg;
class Vtop_top_pkg;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_top_pkg* __PVT__top_pkg;
    Vtop_prim_secded_pkg* __PVT__prim_secded_pkg;
    Vtop_rv_timer_reg_pkg* __PVT__rv_timer_reg_pkg;
    Vtop_prim_mubi_pkg* __PVT__prim_mubi_pkg;
    Vtop_tlul_pkg* __PVT__tlul_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__rst_ni;
        CData/*1:0*/ rv_timer_tb__DOT__gpio_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT__intr_timer_expired_hart0_timer0_o;
        CData/*0:0*/ rv_timer_tb__DOT__tl_i_a_valid;
        CData/*2:0*/ rv_timer_tb__DOT__tl_i_a_opcode;
        CData/*2:0*/ rv_timer_tb__DOT__tl_i_a_param;
        CData/*1:0*/ rv_timer_tb__DOT__tl_i_a_size;
        CData/*7:0*/ rv_timer_tb__DOT__tl_i_a_source;
        CData/*3:0*/ rv_timer_tb__DOT__tl_i_a_mask;
        CData/*0:0*/ rv_timer_tb__DOT__tl_i_d_ready;
        CData/*0:0*/ rv_timer_tb__DOT__tl_o_d_valid;
        CData/*2:0*/ rv_timer_tb__DOT__tl_o_d_opcode;
        CData/*0:0*/ rv_timer_tb__DOT__tl_o_d_error;
        CData/*0:0*/ rv_timer_tb__DOT__tl_o_a_ready;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__rst_ni;
        CData/*1:0*/ rv_timer_tb__DOT____Vtogcov__gpio_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__intr_timer_expired_hart0_timer0_o;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_valid;
        CData/*2:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_opcode;
        CData/*2:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_param;
        CData/*1:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_size;
        CData/*7:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_source;
        CData/*3:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_mask;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_d_ready;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__tl_o_d_valid;
        CData/*2:0*/ rv_timer_tb__DOT____Vtogcov__tl_o_d_opcode;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__tl_o_d_error;
        CData/*0:0*/ rv_timer_tb__DOT____Vtogcov__tl_o_a_ready;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__rst_ni;
        CData/*1:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gpio_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_expired_hart0_timer0_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__active;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__tick;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_set;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_test_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_test_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_state_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_state_de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_timer_state_d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__intr_out;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__sel_gpio_intr_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__sel_gpio_intr_1;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__rst_ni;
        CData/*1:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__gpio_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_expired_hart0_timer0_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__active;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__tick;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_set;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_test_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_test_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_state_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_state_de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_timer_state_d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__intr_out;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__sel_gpio_intr_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__sel_gpio_intr_1;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__clk_i;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__devmode_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_re;
        CData/*4:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_addr;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_be;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__addrmiss;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__wr_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_busy;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_active_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_active_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_gpio_intr_0_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_gpio_intr_0_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_gpio_intr_1_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__ctrl_gpio_intr_1_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_enable0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_enable0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_enable0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_state0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_state0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_state0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_test0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_test0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__cfg0_we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__cfg0_step_qs;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__cfg0_step_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__timer_v0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__compare_v0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_test0_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__intr_test0_flds_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__compare_v0_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__compare_v0_flds_we;
        CData/*6:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__addr_hit;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__shadow_busy;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__unused_wdata;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__unused_be;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__devmode_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_re;
        CData/*4:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_addr;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_be;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__addrmiss;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__wr_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_busy;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_active_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_active_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_gpio_intr_0_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_gpio_intr_0_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_gpio_intr_1_0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__ctrl_gpio_intr_1_0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_enable0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_enable0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_enable0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_state0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_state0_qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_state0_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_test0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_test0_wd;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__cfg0_we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__cfg0_step_qs;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__cfg0_step_wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__timer_v0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__compare_v0_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_test0_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__intr_test0_flds_we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__compare_v0_qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__compare_v0_flds_we;
        CData/*6:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__addr_hit;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__unused_wdata;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__unused_be;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_data;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____VlemCond_0;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rst_ni;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__en_ifetch_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__intg_error_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__re_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__we_o;
        CData/*4:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__addr_o;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__be_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__busy_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__error_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__outstanding_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__a_ack;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__d_ack;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__error_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__err_internal;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__instr_error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__intg_error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__addr_align_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__malformed_meta_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__tl_err;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__reqid_q;
        CData/*1:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__reqsz_q;
        CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rspop_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rd_req;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__wr_req;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rst_ni;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__en_ifetch_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__re_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__we_o;
        CData/*4:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__addr_o;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__be_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__error_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__outstanding_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__a_ack;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__d_ack;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__error_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__err_internal;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__instr_error;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__addr_align_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__malformed_meta_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__tl_err;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__reqid_q;
        CData/*1:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__reqsz_q;
        CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rspop_q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rd_req;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__wr_req;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__unused_tl;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT____Vtogcov__unused_tl;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____VlemCond_1;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__err_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__opcode_allowed;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__a_config_allowed;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__op_full;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__op_partial;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__op_get;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_type_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__addr_sz_chk;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__fulldata_chk;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__mask;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__err_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__opcode_allowed;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__a_config_allowed;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__op_full;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__op_partial;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__op_get;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__instr_wr_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__instr_type_err;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__addr_sz_chk;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__mask_chk;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__fulldata_chk;
        CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__mask;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__we;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__de;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__qe;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__q;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__ds;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__wd;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__qe;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__q;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__ds;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__wr_en;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT____Vtogcov__wr_data;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__de;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__d;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____VlemCond_0;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__de;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_en;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__unused_tl;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT____Vtogcov__unused_tl;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__d_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__q_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT____Vtogcov__d_i;
    };
    struct {
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT____Vtogcov__q_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__re;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__d;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__qre;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__ds;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__qs;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT____Vtogcov__we;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT____Vtogcov__wd;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT____Vtogcov__qe;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT____Vtogcov__q;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__active;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__step;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__tick;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__intr;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__active;
        CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__step;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__tick;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__intr;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__event_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__reg2hw_intr_enable_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__reg2hw_intr_test_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__reg2hw_intr_test_qe_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__reg2hw_intr_state_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__hw2reg_intr_state_de_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__hw2reg_intr_state_d_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__intr_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__status;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__clk_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__rst_ni;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__event_intr_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__reg2hw_intr_enable_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__reg2hw_intr_test_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__reg2hw_intr_test_qe_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__reg2hw_intr_state_q_i;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__hw2reg_intr_state_de_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__hw2reg_intr_state_d_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__intr_o;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__status;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT____Vtogcov__g_intr_eventnew_event;
        CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__g_intr_event__DOT__new_event;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__rst_ni__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__rst_ni__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__cfg0_prescale_qs;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__cfg0_prescale_wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__cfg0_prescale_qs;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__cfg0_prescale_wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____VlemCond_0;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__d;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__ds;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__qs;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_data;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__d;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__ds;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__qs;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT____Vtogcov__wr_data;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____VlemCond_0;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__d;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__wr_data;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__prescaler;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__tick_count;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__prescaler;
        SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__tick_count;
        IData/*31:0*/ rv_timer_tb__DOT____VlemExpr_1;
        IData/*31:0*/ rv_timer_tb__DOT__tl_i_a_address;
        IData/*31:0*/ rv_timer_tb__DOT__tl_i_a_data;
        IData/*31:0*/ rv_timer_tb__DOT__tl_o_d_data;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__tl_o;
        IData/*31:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_address;
        IData/*31:0*/ rv_timer_tb__DOT____Vtogcov__tl_i_a_data;
        IData/*31:0*/ rv_timer_tb__DOT____Vtogcov__tl_o_d_data;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT____Vtogcov__tl_o;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_wdata;
    };
    struct {
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_rdata;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg_rdata_next;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__timer_v0_qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__timer_v0_wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__compare_v0_qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__compare_v0_wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_wdata;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_rdata;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg_rdata_next;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__timer_v0_qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__timer_v0_wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__compare_v0_qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__compare_v0_wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____VlemCond_1;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__wdata_o;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rdata_i;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rdata;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__rdata_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__wdata_o;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rdata_i;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rdata;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__rdata_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____VlemCond_0;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__ds;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__ds;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT____Vtogcov__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____VlemCond_0;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__ds;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__ds;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__qs;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT____Vtogcov__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____VlemCond_0;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__wd;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wd;
    };
    struct {
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__wr_data;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT____Vtogcov__gen_wunused_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__gen_w__DOT__unused_q;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__mtime_d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__mtime;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__mtime_d;
        IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__mtime;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__tl_o;
        VlWide<3>/*91:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__reg2hw;
        QData/*34:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__hw2reg;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__tl_o;
        VlWide<3>/*91:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__reg2hw;
        QData/*34:0*/ rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__hw2reg;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__tl_o;
        VlWide<3>/*91:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__reg2hw;
        QData/*34:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__hw2reg;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__tl_reg_h2d;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__tl_reg_d2h;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__tl_o_pre;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__tl_o;
        VlWide<3>/*91:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__reg2hw;
        QData/*34:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__hw2reg;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__tl_reg_h2d;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__tl_reg_d2h;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT____Vtogcov__tl_o_pre;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__tl_o;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__tl_o_pre;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__tl_o;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT____Vtogcov__tl_o_pre;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__tl_o;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT____Vtogcov__tl_o;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__tl_i;
        VlWide<4>/*108:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__tl_o;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT____Vtogcov__tl_i;
        VlWide<3>/*65:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT____Vtogcov__tl_o;
        VlUnpacked<SData/*11:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__prescaler;
        VlUnpacked<CData/*7:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__step;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__mtime_d;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__mtime;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 1>, 1> rv_timer_tb__DOT__u_rv_timer__DOT__mtimecmp;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 1>, 1> rv_timer_tb__DOT__u_rv_timer__DOT__mtimecmp_update;
        VlUnpacked<CData/*0:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__input_capture_active_d;
        VlUnpacked<CData/*0:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__input_capture_active_q;
        VlUnpacked<SData/*11:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__prescaler;
        VlUnpacked<CData/*7:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__step;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__mtime_d;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__mtime;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 1>, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__mtimecmp;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 1>, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__mtimecmp_update;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__input_capture_active_d;
        VlUnpacked<CData/*0:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vtogcov__input_capture_active_q;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT____Vcellinp__gen_harts__BRA__0__KET____DOT__u_core__mtimecmp;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__mtimecmp;
        VlUnpacked<IData/*31:0*/, 1> rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT____Vtogcov__mtimecmp;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    std::string rv_timer_tb__DOT__wave_path;
    VlDelayScheduler __VdlySched;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;
    uint32_t __Vcoverage[7491]{};

    // PARAMETERS
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__FLEXSOC_TL_PUT_FULL = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__FLEXSOC_TL_PUT_PARTIAL = 1U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__FLEXSOC_TL_GET = 4U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__CmdIntgCheck = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_rsp_intg_gen__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*3:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__MaskOne = 1U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__SwAccess = 0U;
    static constexpr CData/*7:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__RESVAL = 1U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__SwAccess = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__SwAccess = 3U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__RESVAL = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__Mubi = 0U;
    static constexpr CData/*2:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__SwAccess = 3U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__Mubi = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__EnableRspIntgGen = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__EnableDataIntgGen = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__ResetValue = 0U;
    static constexpr CData/*0:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__FlopOutput = 1U;
    static constexpr SData/*11:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__AW = 5U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__DBW = 4U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_enable0__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_1_0__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_gpio_intr_0_0__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_ctrl_active_0__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__RegAw = 5U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__RegDw = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__AccessLatency = 0U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__RegBw = 4U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__IW = 8U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__SZW = 2U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__IW = 8U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__SZW = 2U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__MW = 4U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__SubAW = 2U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__RESVAL = 0xffffffffU;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v0__DOT__wr_en_data_arb__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__RESVAL = 0U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_timer_v0__DOT__wr_en_data_arb__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__DW = 8U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_step__DOT__wr_en_data_arb__DOT__DW = 8U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__DW = 0x0000000cU;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_cfg0_prescale__DOT__wr_en_data_arb__DOT__DW = 0x0000000cU;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_state0__DOT__wr_en_data_arb__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_compare_v00_qe__DOT__Width = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__u_reg__DOT__u_intr_test0__DOT__DW = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_core__DOT__N = 1U;
    static constexpr IData/*31:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__Width = 1U;
    static constexpr QData/*39:0*/ rv_timer_tb__DOT__u_rv_timer__DOT__gen_harts__BRA__0__KET____DOT__u_intr_hw__DOT__IntrT = 0x0000004576656e74ULL;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, bool localCounter, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp,
        const char* fsmVarp, const char* fsmFromp, const char* fsmTop, const char* fsmTagp);
    void __vlCoverToggleInsert(int begin, int end, bool ranged, uint32_t* countp, bool enable, bool localCounter, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp);
};


#endif  // guard
