#!/usr/bin/env python3
"""
CORDIC plotting and analysis utilities.

This module is intended to complement the CORDIC reference model by providing
high-quality visual inspection of:
- sine/cosine estimation quality in rotation mode
- magnitude/angle estimation quality in vectoring mode
- absolute error trends over the input domain
- error histograms for quick regression inspection

The plots generated by this script are particularly useful during:
- early algorithm bring-up
- RTL vs model alignment
- fixed-point format selection
- iteration count tradeoff studies
- regression result review

This file deliberately imports the golden model from cordic_model.py so that
all numerical behavior remains centralized in the same reference implementation.
"""

from __future__ import annotations

import argparse
import math
import os
from dataclasses import dataclass

import matplotlib.pyplot as plt
import numpy as np

from cordic_model import (
    PI,
    CordicConfig,
    FixedFormat,
    atan2_mag_fixed,
    atan2_math_reference,
    fixed_to_float,
    normalize_angle_pm_pi,
    sincos_fixed,
    sincos_math_reference,
)


# =============================================================================
# Dataclasses used to keep plotting data organized
# =============================================================================

@dataclass
class RotationSweepData:
    """
    Container for rotation-mode sweep results.

    Attributes
    ----------
    angles:
        Input angles in radians.
    cos_ref:
        Reference cosine values from Python math library.
    sin_ref:
        Reference sine values from Python math library.
    cos_dut:
        CORDIC fixed-point cosine converted back to float.
    sin_dut:
        CORDIC fixed-point sine converted back to float.
    cos_err:
        Absolute cosine error.
    sin_err:
        Absolute sine error.
    """
    angles: np.ndarray
    cos_ref: np.ndarray
    sin_ref: np.ndarray
    cos_dut: np.ndarray
    sin_dut: np.ndarray
    cos_err: np.ndarray
    sin_err: np.ndarray


@dataclass
class VectoringSweepData:
    """
    Container for vectoring-mode sweep results.

    Attributes
    ----------
    angles:
        Sweep angle used to generate the Cartesian input points.
    x:
        Generated x Cartesian coordinates.
    y:
        Generated y Cartesian coordinates.
    mag_ref:
        Reference magnitude values.
    ang_ref:
        Reference atan2 values.
    mag_dut:
        CORDIC magnitude estimate.
    ang_dut:
        CORDIC angle estimate.
    mag_err:
        Absolute magnitude error.
    ang_err:
        Absolute wrapped angular error.
    """
    angles: np.ndarray
    x: np.ndarray
    y: np.ndarray
    mag_ref: np.ndarray
    ang_ref: np.ndarray
    mag_dut: np.ndarray
    ang_dut: np.ndarray
    mag_err: np.ndarray
    ang_err: np.ndarray


# =============================================================================
# Utility helpers
# =============================================================================

def ensure_dir(path: str) -> None:
    """
    Create the target directory if it does not already exist.
    """
    os.makedirs(path, exist_ok=True)


def save_figure(output_dir: str, filename: str) -> None:
    """
    Save the current matplotlib figure using a consistent configuration.

    Parameters
    ----------
    output_dir:
        Directory where the figure will be written.
    filename:
        Output PNG filename.
    """
    ensure_dir(output_dir)
    full_path = os.path.join(output_dir, filename)
    plt.tight_layout()
    plt.savefig(full_path, dpi=180, bbox_inches="tight")
    print(f"Saved plot: {full_path}")


def print_error_summary(name: str, values: np.ndarray) -> None:
    """
    Print a compact numerical summary of an error array.

    Parameters
    ----------
    name:
        Human-readable metric name.
    values:
        NumPy array of error values.
    """
    print(
        f"{name:<24} "
        f"min={np.min(values):.6e}  "
        f"mean={np.mean(values):.6e}  "
        f"max={np.max(values):.6e}  "
        f"std={np.std(values):.6e}"
    )


# =============================================================================
# Data generation for plotting
# =============================================================================

def build_rotation_sweep(cfg: CordicConfig, num_points: int = 2001) -> RotationSweepData:
    """
    Sweep the full angle interval [-pi, pi] and compare CORDIC vs reference.

    This is the most useful plot set for evaluating:
    - trigonometric approximation quality
    - angle-domain regions with larger error
    - impact of fixed-point quantization
    - impact of iteration count

    Parameters
    ----------
    cfg:
        CORDIC configuration.
    num_points:
        Number of sample points across the angle domain.

    Returns
    -------
    RotationSweepData
        Structured sweep results.
    """
    angles = np.linspace(-PI, PI, num_points)

    cos_ref = np.zeros_like(angles)
    sin_ref = np.zeros_like(angles)
    cos_dut = np.zeros_like(angles)
    sin_dut = np.zeros_like(angles)

    for idx, angle in enumerate(angles):
        # Reference values from the Python math library.
        c_ref, s_ref = sincos_math_reference(angle)
        cos_ref[idx] = c_ref
        sin_ref[idx] = s_ref

        # Fixed-point CORDIC output converted back to float.
        dut = sincos_fixed(angle, cfg)
        cos_dut[idx] = fixed_to_float(dut.x, cfg.data_format)
        sin_dut[idx] = fixed_to_float(dut.y, cfg.data_format)

    cos_err = np.abs(cos_ref - cos_dut)
    sin_err = np.abs(sin_ref - sin_dut)

    return RotationSweepData(
        angles=angles,
        cos_ref=cos_ref,
        sin_ref=sin_ref,
        cos_dut=cos_dut,
        sin_dut=sin_dut,
        cos_err=cos_err,
        sin_err=sin_err,
    )


def build_vectoring_sweep(
    cfg: CordicConfig,
    radius: float = 0.8,
    num_points: int = 2001,
) -> VectoringSweepData:
    """
    Sweep a circle in Cartesian space and compare vectoring-mode outputs.

    The sweep creates points:
        x = r * cos(theta)
        y = r * sin(theta)

    This is a clean and very informative way to evaluate:
    - angle estimation error across quadrants
    - magnitude estimation consistency
    - corner behavior around axes
    - phase discontinuity handling around +/- pi

    Parameters
    ----------
    cfg:
        CORDIC configuration.
    radius:
        Radius of the swept circle. It should stay well inside the supported
        fixed-point dynamic range to avoid intermediate overflow.
    num_points:
        Number of points along the circle.

    Returns
    -------
    VectoringSweepData
        Structured sweep results.
    """
    angles = np.linspace(-PI, PI, num_points)

    x = radius * np.cos(angles)
    y = radius * np.sin(angles)

    mag_ref = np.zeros_like(angles)
    ang_ref = np.zeros_like(angles)
    mag_dut = np.zeros_like(angles)
    ang_dut = np.zeros_like(angles)

    for idx, (x_val, y_val) in enumerate(zip(x, y)):
        # Exact mathematical reference.
        mag_r, ang_r = atan2_math_reference(float(x_val), float(y_val))
        mag_ref[idx] = mag_r
        ang_ref[idx] = ang_r

        # Fixed-point CORDIC estimate converted back to float.
        dut = atan2_mag_fixed(float(x_val), float(y_val), cfg)
        mag_dut[idx] = dut.x
        ang_dut[idx] = dut.z

    mag_err = np.abs(mag_ref - mag_dut)

    # Angle error must be wrapped because phase is periodic.
    ang_err = np.array(
        [abs(normalize_angle_pm_pi(ref - dut)) for ref, dut in zip(ang_ref, ang_dut)]
    )

    return VectoringSweepData(
        angles=angles,
        x=x,
        y=y,
        mag_ref=mag_ref,
        ang_ref=ang_ref,
        mag_dut=mag_dut,
        ang_dut=ang_dut,
        mag_err=mag_err,
        ang_err=ang_err,
    )


# =============================================================================
# Plotting functions for rotation mode
# =============================================================================

def plot_rotation_waveforms(data: RotationSweepData, output_dir: str) -> None:
    """
    Plot reference and CORDIC cosine on the same figure, then reference and
    CORDIC sine on another figure.

    Separate figures are used intentionally so each plot remains readable and
    publication-friendly.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.cos_ref, label="cos reference")
    plt.plot(data.angles, data.cos_dut, label="cos cordic")
    plt.xlabel("Angle [rad]")
    plt.ylabel("Cosine")
    plt.title("CORDIC rotation mode - cosine")
    plt.grid(True, alpha=0.3)
    plt.legend()
    save_figure(output_dir, "rotation_cosine.png")
    plt.close()

    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.sin_ref, label="sin reference")
    plt.plot(data.angles, data.sin_dut, label="sin cordic")
    plt.xlabel("Angle [rad]")
    plt.ylabel("Sine")
    plt.title("CORDIC rotation mode - sine")
    plt.grid(True, alpha=0.3)
    plt.legend()
    save_figure(output_dir, "rotation_sine.png")
    plt.close()


def plot_rotation_errors(data: RotationSweepData, output_dir: str) -> None:
    """
    Plot absolute cosine and sine error versus angle.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.cos_err)
    plt.xlabel("Angle [rad]")
    plt.ylabel("Absolute error")
    plt.title("CORDIC rotation mode - absolute cosine error")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "rotation_cosine_error.png")
    plt.close()

    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.sin_err)
    plt.xlabel("Angle [rad]")
    plt.ylabel("Absolute error")
    plt.title("CORDIC rotation mode - absolute sine error")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "rotation_sine_error.png")
    plt.close()


def plot_rotation_histograms(data: RotationSweepData, output_dir: str, bins: int = 80) -> None:
    """
    Plot histograms of cosine and sine absolute error.

    Histograms are useful to understand whether the implementation shows:
    - a narrow and well-controlled error distribution
    - long tails
    - outliers near specific regions of the input domain
    """
    plt.figure(figsize=(8, 5))
    plt.hist(data.cos_err, bins=bins)
    plt.xlabel("Absolute error")
    plt.ylabel("Count")
    plt.title("CORDIC rotation mode - cosine error histogram")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "rotation_cosine_error_hist.png")
    plt.close()

    plt.figure(figsize=(8, 5))
    plt.hist(data.sin_err, bins=bins)
    plt.xlabel("Absolute error")
    plt.ylabel("Count")
    plt.title("CORDIC rotation mode - sine error histogram")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "rotation_sine_error_hist.png")
    plt.close()


# =============================================================================
# Plotting functions for vectoring mode
# =============================================================================

def plot_vectoring_waveforms(data: VectoringSweepData, output_dir: str) -> None:
    """
    Plot magnitude and angle reference vs CORDIC estimate.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.mag_ref, label="magnitude reference")
    plt.plot(data.angles, data.mag_dut, label="magnitude cordic")
    plt.xlabel("Sweep angle [rad]")
    plt.ylabel("Magnitude")
    plt.title("CORDIC vectoring mode - magnitude estimate")
    plt.grid(True, alpha=0.3)
    plt.legend()
    save_figure(output_dir, "vectoring_magnitude.png")
    plt.close()

    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.ang_ref, label="angle reference")
    plt.plot(data.angles, data.ang_dut, label="angle cordic")
    plt.xlabel("Sweep angle [rad]")
    plt.ylabel("Angle [rad]")
    plt.title("CORDIC vectoring mode - angle estimate")
    plt.grid(True, alpha=0.3)
    plt.legend()
    save_figure(output_dir, "vectoring_angle.png")
    plt.close()


def plot_vectoring_errors(data: VectoringSweepData, output_dir: str) -> None:
    """
    Plot absolute magnitude error and absolute wrapped angle error.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.mag_err)
    plt.xlabel("Sweep angle [rad]")
    plt.ylabel("Absolute error")
    plt.title("CORDIC vectoring mode - magnitude absolute error")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "vectoring_magnitude_error.png")
    plt.close()

    plt.figure(figsize=(10, 5))
    plt.plot(data.angles, data.ang_err)
    plt.xlabel("Sweep angle [rad]")
    plt.ylabel("Absolute wrapped angle error [rad]")
    plt.title("CORDIC vectoring mode - angle absolute error")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "vectoring_angle_error.png")
    plt.close()


def plot_vectoring_histograms(data: VectoringSweepData, output_dir: str, bins: int = 80) -> None:
    """
    Plot error histograms for vectoring mode.
    """
    plt.figure(figsize=(8, 5))
    plt.hist(data.mag_err, bins=bins)
    plt.xlabel("Absolute error")
    plt.ylabel("Count")
    plt.title("CORDIC vectoring mode - magnitude error histogram")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "vectoring_magnitude_error_hist.png")
    plt.close()

    plt.figure(figsize=(8, 5))
    plt.hist(data.ang_err, bins=bins)
    plt.xlabel("Absolute wrapped angle error [rad]")
    plt.ylabel("Count")
    plt.title("CORDIC vectoring mode - angle error histogram")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "vectoring_angle_error_hist.png")
    plt.close()


def plot_vectoring_xy_path(data: VectoringSweepData, output_dir: str) -> None:
    """
    Plot the Cartesian points used during the vectoring sweep.

    This plot is not an error plot; it serves as a visual reminder of the input
    domain being exercised. It is useful in reports and design reviews.
    """
    plt.figure(figsize=(6, 6))
    plt.plot(data.x, data.y)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Vectoring sweep input domain")
    plt.axis("equal")
    plt.grid(True, alpha=0.3)
    save_figure(output_dir, "vectoring_input_circle.png")
    plt.close()


# =============================================================================
# Top-level runners
# =============================================================================

def run_rotation_plots(cfg: CordicConfig, output_dir: str, num_points: int) -> None:
    """
    Generate all rotation-mode plots and print an error summary.
    """
    print("Generating rotation-mode plots...")
    data = build_rotation_sweep(cfg, num_points=num_points)

    print_error_summary("Rotation cosine error", data.cos_err)
    print_error_summary("Rotation sine error", data.sin_err)

    plot_rotation_waveforms(data, output_dir)
    plot_rotation_errors(data, output_dir)
    plot_rotation_histograms(data, output_dir)


def run_vectoring_plots(cfg: CordicConfig, output_dir: str, num_points: int, radius: float) -> None:
    """
    Generate all vectoring-mode plots and print an error summary.
    """
    print("Generating vectoring-mode plots...")
    data = build_vectoring_sweep(cfg, radius=radius, num_points=num_points)

    print_error_summary("Vectoring magnitude error", data.mag_err)
    print_error_summary("Vectoring angle error", data.ang_err)

    plot_vectoring_xy_path(data, output_dir)
    plot_vectoring_waveforms(data, output_dir)
    plot_vectoring_errors(data, output_dir)
    plot_vectoring_histograms(data, output_dir)


# =============================================================================
# CLI
# =============================================================================

def build_argparser() -> argparse.ArgumentParser:
    """
    Build the command-line parser.

    The interface is kept intentionally simple so that the script can be used:
    - manually during development
    - from Makefiles
    - inside CI or regression scripts
    """
    parser = argparse.ArgumentParser(description="CORDIC plotting utilities")

    parser.add_argument("--width", type=int, default=16, help="Data path width")
    parser.add_argument("--frac", type=int, default=14, help="Data path fractional bits")
    parser.add_argument("--angle-width", type=int, default=16, help="Angle path width")
    parser.add_argument("--angle-frac", type=int, default=13, help="Angle path fractional bits")
    parser.add_argument("--iterations", type=int, default=16, help="Number of CORDIC iterations")
    parser.add_argument("--guard-bits", type=int, default=3, help="Internal x/y guard bits")
    parser.add_argument(
        "--wrap-output",
        action="store_true",
        help="Wrap x/y outputs instead of saturating them",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        default="workspace/runs/cordic/dev/report/plots",
        help="Directory where PNG plots will be saved",
    )

    parser.add_argument(
        "--num-points",
        type=int,
        default=2001,
        help="Number of sweep points for each analysis",
    )

    parser.add_argument(
        "--radius",
        type=float,
        default=0.8,
        help="Radius used for vectoring circular sweep",
    )

    parser.add_argument(
        "--rotation-only",
        action="store_true",
        help="Generate only rotation-mode plots",
    )

    parser.add_argument(
        "--vectoring-only",
        action="store_true",
        help="Generate only vectoring-mode plots",
    )

    return parser


def main() -> None:
    """
    Main CLI entry point.
    """
    args = build_argparser().parse_args()

    cfg = CordicConfig(
        data_format=FixedFormat(width=args.width, frac=args.frac, signed=True),
        angle_format=FixedFormat(width=args.angle_width, frac=args.angle_frac, signed=True),
        iterations=args.iterations,
        compensate_gain=True,
        internal_guard_bits=args.guard_bits,
        saturate_output=not args.wrap_output,
    )

    print("CORDIC plotting configuration")
    print("-----------------------------")
    print(f"Data width      : {cfg.data_format.width}")
    print(f"Data frac       : {cfg.data_format.frac}")
    print(f"Angle width     : {cfg.angle_format.width}")
    print(f"Angle frac      : {cfg.angle_format.frac}")
    print(f"Iterations      : {cfg.iterations}")
    print(f"Output dir      : {args.output_dir}")
    print(f"Sweep points    : {args.num_points}")
    print(f"Vector radius   : {args.radius}")
    print()

    if not args.vectoring_only:
        run_rotation_plots(cfg, args.output_dir, args.num_points)

    if not args.rotation_only:
        run_vectoring_plots(cfg, args.output_dir, args.num_points, args.radius)


if __name__ == "__main__":
    main()
