// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop_pkg.h for the primary calling header

#ifndef VERILATED_VTOP_PKG___024ROOT_H_
#define VERILATED_VTOP_PKG___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_pkg_tlul_fifo_sync__RCz9_RDz9;


class Vtop_pkg__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_pkg___024root final {
  public:
    // CELLS
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    Vtop_pkg_tlul_fifo_sync__RCz9_RDz9* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__3__KET____DOT__u_hostfifo;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(prim_clk_div__02Eclk_i,0,0);
        VL_IN8(prim_clk_div__02Erst_ni,0,0);
        VL_IN8(prim_lifo__02Eclk_i,0,0);
        VL_IN8(prim_lifo__02Erst_ni,0,0);
        VL_IN8(prim_ram__02Eclk_i,0,0);
        VL_IN8(prim_rom__02Eclk_i,0,0);
        VL_IN8(prim_shreg__02Eclk_i,0,0);
        VL_IN8(prim_cdc_rand_delay__02Eclk_i,0,0);
        VL_IN8(prim_cdc_rand_delay__02Erst_ni,0,0);
        VL_IN8(prim_intr_hw__02Eclk_i,0,0);
        VL_IN8(prim_intr_hw__02Erst_ni,0,0);
        VL_IN8(src_clk_i,0,0);
        VL_IN8(src_rst_ni,0,0);
        VL_IN8(dst_clk_i,0,0);
        VL_IN8(dst_rst_ni,0,0);
        VL_IN8(prim_counter__02Eclk_i,0,0);
        VL_IN8(prim_counter__02Erst_ni,0,0);
        VL_IN8(prim_deglitch__02Eclk_i,0,0);
        VL_IN8(prim_deglitch__02Erst_ni,0,0);
        VL_IN8(prim_edge_detect__02Eclk_i,0,0);
        VL_IN8(prim_edge_detect__02Erst_ni,0,0);
        VL_IN8(rd_clk_i,0,0);
        VL_IN8(wr_clk_i,0,0);
        VL_IN8(prim_fifo__02Erst_ni,0,0);
        VL_IN8(prim_reg__02Eclk_i,0,0);
        VL_IN8(prim_reg__02Erst_ni,0,0);
        VL_IN8(rrarbiter__02Eclk_i,0,0);
        VL_IN8(rrarbiter__02Erst_ni,0,0);
        VL_IN8(prim_fifo_async_simple__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_simple__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_rd_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_rd_ni,0,0);
        VL_IN8(prim_filter__02Eclk_i,0,0);
        VL_IN8(prim_filter__02Erst_ni,0,0);
        VL_IN8(prim_filter_ctr__02Eclk_i,0,0);
        VL_IN8(prim_filter_ctr__02Erst_ni,0,0);
        VL_IN8(clk_src_i,0,0);
        VL_IN8(rst_src_ni,0,0);
        VL_IN8(clk_dst_i,0,0);
        VL_IN8(rst_dst_ni,0,0);
        VL_IN8(prim_alert_sender__02Eclk_i,0,0);
        VL_IN8(prim_alert_sender__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_host__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_host__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_sram__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_sram__02Erst_ni,0,0);
        VL_IN8(clk_h_i,0,0);
        VL_IN8(rst_h_ni,0,0);
        VL_IN8(clk_d_i,0,0);
        VL_IN8(rst_d_ni,0,0);
        VL_IN8(tlul_socket_1n__02Eclk_i,0,0);
        VL_IN8(tlul_socket_1n__02Erst_ni,0,0);
        VL_IN8(tlul_socket_m1__02Eclk_i,0,0);
        VL_IN8(tlul_socket_m1__02Erst_ni,0,0);
        VL_IN8(my_ip__02Eclk_i,0,0);
        VL_IN8(my_ip__02Erst_ni,0,0);
        VL_IN8(testmode_i,0,0);
        VL_IN8(prim_clk_div__02Een_i,0,0);
        VL_OUT8(prim_clk_div__02Eclk_o,0,0);
        VL_IN8(prim_clk_gate__02Eclk_i,0,0);
    };
    struct {
        VL_IN8(prim_clk_gate__02Een_i,0,0);
        VL_IN8(test_en_i,0,0);
        VL_OUT8(prim_clk_gate__02Eclk_o,0,0);
        VL_IN8(A,0,-2);
        VL_OUT8(Z,0,-2);
        VL_IN8(prim_lifo__02Ewdata_i,7,0);
        VL_IN8(prim_lifo__02Ewvalid_i,0,0);
        VL_OUT8(prim_lifo__02Ewready_o,0,0);
        VL_OUT8(prim_lifo__02Erdata_o,7,0);
        VL_OUT8(prim_lifo__02Ervalid_o,0,0);
        VL_IN8(prim_lifo__02Erready_i,0,0);
        VL_OUT8(lifo_full_o,0,0);
        VL_OUT8(lifo_empty_o,0,0);
        VL_IN8(prim_ram__02Erst_ni,0,0);
        VL_IN8(prim_ram__02Een_i,0,0);
        VL_IN8(prim_ram__02Ewe_i,0,0);
        VL_IN8(prim_rom__02Erst_ni,0,0);
        VL_IN8(prim_shreg__02Erst_ni,0,0);
        VL_IN8(prim_shreg__02Een_i,0,0);
        VL_IN8(prim_shreg__02Eserial_i,0,0);
        VL_OUT8(pdata_o,7,0);
        VL_OUT8(serial_o,0,0);
        VL_IN8(prev_data_i,0,0);
        VL_IN8(prim_cdc_rand_delay__02Esrc_data_i,0,0);
        VL_OUT8(prim_cdc_rand_delay__02Edst_data_o,0,0);
        VL_IN8(event_intr_i,0,0);
        VL_IN8(reg2hw_intr_enable_q_i,0,0);
        VL_IN8(reg2hw_intr_test_q_i,0,0);
        VL_IN8(reg2hw_intr_test_qe_i,0,0);
        VL_IN8(reg2hw_intr_state_q_i,0,0);
        VL_OUT8(hw2reg_intr_state_de_o,0,0);
        VL_OUT8(hw2reg_intr_state_d_o,0,0);
        VL_OUT8(intr_o,0,0);
        VL_IN8(cdc_2phase__02Esrc_data_i,0,0);
        VL_IN8(src_valid_i,0,0);
        VL_OUT8(src_ready_o,0,0);
        VL_OUT8(cdc_2phase__02Edst_data_o,0,0);
        VL_OUT8(dst_valid_o,0,0);
        VL_IN8(dst_ready_i,0,0);
        VL_IN8(prim_counter__02Een_i,0,0);
        VL_IN8(clr_i,0,0);
        VL_IN8(up_down_i,0,0);
        VL_IN8(step_i,3,0);
        VL_IN8(tc_val_i,3,0);
        VL_OUT8(val_o,3,0);
        VL_OUT8(tc_o,0,0);
        VL_IN8(prim_deglitch__02Een_i,0,0);
        VL_IN8(d_i,0,0);
        VL_OUT8(q_o,0,0);
        VL_IN8(prim_edge_detect__02Een_i,0,0);
        VL_IN8(prim_edge_detect__02Eserial_i,0,0);
        VL_OUT8(r_edge_o,0,0);
        VL_OUT8(f_edge_o,0,0);
        VL_IN8(prim_fifo__02Ewdata_i,7,0);
        VL_IN8(prim_fifo__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo__02Ewready_o,0,0);
        VL_OUT8(prim_fifo__02Erdata_o,7,0);
        VL_OUT8(prim_fifo__02Ervalid_o,0,0);
        VL_IN8(prim_fifo__02Erready_i,0,0);
        VL_OUT8(fifo_full,0,0);
        VL_OUT8(fifo_empty,0,0);
        VL_IN8(we,0,0);
        VL_IN8(de,0,0);
        VL_OUT8(qe,0,0);
    };
    struct {
        VL_IN8(flush_i,0,0);
        VL_IN8(rrarbiter__02Een_i,0,0);
        VL_OUT8(vld_o,0,0);
        VL_OUT8(idx_o,3,0);
        VL_IN8(prim_fifo_async_simple__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ewready_o,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_simple__02Erready_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ewready_o,0,0);
        VL_OUT8(wdepth_o,4,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erready_i,0,0);
        VL_OUT8(rdepth_o,4,0);
        VL_OUT8(r_full_o,0,0);
        VL_OUT8(r_notempty_o,0,0);
        VL_OUT8(w_full_o,0,0);
        VL_OUT8(w_sram_req_o,0,0);
        VL_IN8(w_sram_gnt_i,0,0);
        VL_OUT8(w_sram_write_o,0,0);
        VL_IN8(w_sram_rvalid_i,0,0);
        VL_IN8(w_sram_rerror_i,1,0);
        VL_OUT8(r_sram_req_o,0,0);
        VL_IN8(r_sram_gnt_i,0,0);
        VL_OUT8(r_sram_write_o,0,0);
        VL_IN8(r_sram_rvalid_i,0,0);
        VL_IN8(r_sram_rerror_i,1,0);
        VL_IN8(prim_filter__02Eenable_i,0,0);
        VL_IN8(prim_filter__02Efilter_i,0,0);
        VL_OUT8(prim_filter__02Efilter_o,0,0);
        VL_IN8(prim_filter_ctr__02Eenable_i,0,0);
        VL_IN8(prim_filter_ctr__02Efilter_i,0,0);
        VL_IN8(thresh_i,1,0);
        VL_OUT8(prim_filter_ctr__02Efilter_o,0,0);
        VL_IN8(src_regwen_i,0,0);
        VL_IN8(src_we_i,0,0);
        VL_IN8(src_re_i,0,0);
        VL_OUT8(src_busy_o,0,0);
        VL_IN8(dst_update_i,0,0);
        VL_OUT8(dst_we_o,0,0);
        VL_OUT8(dst_re_o,0,0);
        VL_OUT8(dst_regwen_o,0,0);
        VL_IN8(prim_reg_we_check__02Eclk_i,0,0);
        VL_IN8(prim_reg_we_check__02Erst_ni,0,0);
        VL_IN8(prim_reg_we_check__02Een_i,0,0);
        VL_OUT8(prim_reg_we_check__02Eerr_o,0,0);
        VL_IN8(alert_test_i,0,0);
        VL_IN8(alert_req_i,0,0);
        VL_OUT8(alert_ack_o,0,0);
        VL_OUT8(alert_state_o,0,0);
        VL_IN8(alert_rx_i,3,0);
        VL_OUT8(alert_tx_o,1,0);
        VL_IN8(sram2tlul__02Eclk_i,0,0);
        VL_IN8(sram2tlul__02Erst_ni,0,0);
        VL_IN8(mem_req_i,0,0);
        VL_IN8(mem_write_i,0,0);
        VL_OUT8(mem_rvalid_o,0,0);
        VL_OUT8(mem_error_o,1,0);
        VL_IN8(tlul_adapter_host__02Ereq_i,0,0);
        VL_OUT8(gnt_o,0,0);
        VL_IN8(tlul_adapter_host__02Ewe_i,0,0);
        VL_IN8(wdata_intg_i,6,0);
        VL_IN8(be_i,3,0);
        VL_IN8(instr_type_i,3,0);
    };
    struct {
        VL_OUT8(valid_o,0,0);
        VL_OUT8(rdata_intg_o,6,0);
        VL_OUT8(tlul_adapter_host__02Eerr_o,0,0);
        VL_OUT8(intg_err_o,0,0);
        VL_IN8(en_ifetch_i,3,0);
        VL_OUT8(req_o,0,0);
        VL_OUT8(req_type_o,3,0);
        VL_IN8(gnt_i,0,0);
        VL_OUT8(we_o,0,0);
        VL_OUT8(intg_error_o,0,0);
        VL_IN8(rvalid_i,0,0);
        VL_IN8(rerror_i,1,0);
        VL_OUT8(compound_txn_in_progress_o,0,0);
        VL_IN8(readback_en_i,3,0);
        VL_OUT8(readback_error_o,0,0);
        VL_IN8(wr_collision_i,0,0);
        VL_IN8(write_pending_i,0,0);
        VL_IN8(tlul_assert_multiple__02Eclk_i,0,0);
        VL_IN8(tlul_assert_multiple__02Erst_ni,0,0);
        VL_IN8(dev_select_i,2,0);
        VL_IN8(port_i,0,0);
        VL_OUT8(port_o,0,0);
        CData/*3:0*/ prim_clk_div__DOT__counter_q;
        CData/*0:0*/ prim_clk_div__DOT__clk_q;
        CData/*0:0*/ prim_clk_gate__DOT__en_latch;
        CData/*7:0*/ prim_lifo__DOT____Vlvbound_hd0f2e51d__0;
        CData/*3:0*/ prim_lifo__DOT__pointer;
        CData/*0:0*/ prim_lifo__DOT__wr_en;
        CData/*0:0*/ prim_lifo__DOT__rd_en;
        CData/*7:0*/ prim_shreg__DOT__shift_reg;
        CData/*0:0*/ prim_cdc_rand_delay__DOT__dst_internal;
        CData/*0:0*/ cdc_2phase__DOT__i_src__DOT__req_src_q;
        CData/*0:0*/ cdc_2phase__DOT__i_src__DOT__ack_src_q;
        CData/*0:0*/ cdc_2phase__DOT__i_src__DOT__ack_q;
        CData/*0:0*/ cdc_2phase__DOT__i_src__DOT__data_src_q;
        CData/*0:0*/ cdc_2phase__DOT__i_dst__DOT__req_dst_q;
        CData/*0:0*/ cdc_2phase__DOT__i_dst__DOT__req_q0;
        CData/*0:0*/ cdc_2phase__DOT__i_dst__DOT__req_q1;
        CData/*0:0*/ cdc_2phase__DOT__i_dst__DOT__ack_dst_q;
        CData/*0:0*/ cdc_2phase__DOT__i_dst__DOT__data_dst_q;
        CData/*4:0*/ prim_counter__DOT__count_q;
        CData/*4:0*/ prim_counter__DOT__count_d;
        CData/*2:0*/ prim_deglitch__DOT__count_q;
        CData/*0:0*/ prim_edge_detect__DOT__serial_q;
        CData/*7:0*/ prim_fifo__DOT____Vlvbound_h2c7b1089__0;
        CData/*3:0*/ prim_fifo__DOT__rd_gray_pointer;
        CData/*3:0*/ prim_fifo__DOT__rd_binary_pointer;
        CData/*3:0*/ prim_fifo__DOT__rd_binary_pointer_next;
        CData/*3:0*/ prim_fifo__DOT__wr_gray_pointer;
        CData/*3:0*/ prim_fifo__DOT__wr_binary_pointer;
        CData/*3:0*/ prim_fifo__DOT__wr_binary_pointer_next;
        CData/*0:0*/ prim_fifo__DOT__rdptr_eq_next_wrptr;
        CData/*3:0*/ rrarbiter__DOT__arb_sel_q;
        CData/*3:0*/ rrarbiter__DOT__arb_sel_lock_q;
        CData/*0:0*/ rrarbiter__DOT__lock_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__wr_en;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__not_in_reset_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__dst_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_cs;
    };
    struct {
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_cs;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__req_sync__DOT__intq;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__ack_sync__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_wptr_gray;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_rptr_gray;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_inc;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_inc;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__stored;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_sram_rptr;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__store_en;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT____VdfgRegularize_h1c658b81_0_1;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_wptr_gray__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_rptr_gray__DOT__intq;
        CData/*3:0*/ prim_filter__DOT__stored_vector_q;
        CData/*3:0*/ prim_filter__DOT__stored_vector_d;
        CData/*0:0*/ prim_filter__DOT__stored_value_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_d;
        CData/*0:0*/ prim_filter_ctr__DOT__filter_q;
        CData/*0:0*/ prim_filter_ctr__DOT__stored_value_q;
        CData/*0:0*/ prim_reg_cdc__DOT__src_ack;
        CData/*0:0*/ prim_reg_cdc__DOT__src_busy_q;
        CData/*2:0*/ prim_reg_cdc__DOT__txn_bits_q;
        CData/*0:0*/ prim_reg_cdc__DOT__src_req;
        CData/*0:0*/ prim_reg_cdc__DOT__dst_to_src;
        CData/*0:0*/ prim_reg_cdc__DOT__dst_req_from_src;
        CData/*0:0*/ prim_reg_cdc__DOT__u_src_to_dst_req__DOT__src_level;
        CData/*0:0*/ prim_reg_cdc__DOT__u_src_to_dst_req__DOT__dst_level;
        CData/*0:0*/ prim_reg_cdc__DOT__u_src_to_dst_req__DOT__dst_level_q;
        CData/*0:0*/ prim_reg_cdc__DOT__u_src_to_dst_req__DOT__prim_flop_2sync__DOT__intq;
        CData/*0:0*/ prim_reg_cdc__DOT__u_arb__DOT__gen_passthru__DOT__u_dst_to_src_ack__DOT__src_level;
        CData/*0:0*/ prim_reg_cdc__DOT__u_arb__DOT__gen_passthru__DOT__u_dst_to_src_ack__DOT__dst_level;
        CData/*0:0*/ prim_reg_cdc__DOT__u_arb__DOT__gen_passthru__DOT__u_dst_to_src_ack__DOT__dst_level_q;
        CData/*0:0*/ prim_reg_cdc__DOT__u_arb__DOT__gen_passthru__DOT__u_dst_to_src_ack__DOT__prim_flop_2sync__DOT__intq;
        CData/*0:0*/ prim_alert_sender__DOT__ping_sigint;
        CData/*0:0*/ prim_alert_sender__DOT__ack_sigint;
        CData/*2:0*/ prim_alert_sender__DOT__state_d;
        CData/*2:0*/ prim_alert_sender__DOT__state_q;
        CData/*0:0*/ prim_alert_sender__DOT__alert_pd;
        CData/*0:0*/ prim_alert_sender__DOT__alert_nd;
        CData/*0:0*/ prim_alert_sender__DOT__alert_set_q;
        CData/*0:0*/ prim_alert_sender__DOT__alert_clr;
        CData/*0:0*/ prim_alert_sender__DOT__alert_test_set_q;
        CData/*0:0*/ prim_alert_sender__DOT__ping_set_q;
        CData/*0:0*/ prim_alert_sender__DOT__ping_clr;
        CData/*0:0*/ prim_alert_sender__DOT__alert_req_trigger;
        CData/*0:0*/ prim_alert_sender__DOT__alert_test_trigger;
        CData/*0:0*/ prim_alert_sender__DOT__ping_trigger;
        CData/*1:0*/ prim_alert_sender__DOT____Vcellout__u_prim_flop_alert__q_o;
        CData/*1:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_d;
        CData/*1:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_q;
    };
    struct {
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pq;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nq;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pd;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nd;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_d;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_q;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_p__DOT__intq;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_n__DOT__intq;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__level_d;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__level_q;
        CData/*1:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_d;
        CData/*1:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_q;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_pd;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_nd;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_d;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_q;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_p__DOT__intq;
        CData/*0:0*/ prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_n__DOT__intq;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_d;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_q;
        CData/*0:0*/ tlul_adapter_sram__DOT__error_det;
        CData/*0:0*/ tlul_adapter_sram__DOT__intg_error_q;
        CData/*0:0*/ tlul_adapter_sram__DOT__missed_err_gnt_q;
        CData/*4:0*/ tlul_adapter_sram__DOT____Vcellout__u_sramreqfifo__rdata_o;
        CData/*0:0*/ tlul_adapter_sram__DOT____VdfgRegularize_hb17975a6_0_0;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__wready_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__rvalid_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__wready_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*4:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__storage;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__wvalid_i;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__rvalid_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_fifo_async__DOT____Vcellout__reqfifo__wready_o;
        CData/*0:0*/ tlul_fifo_async__DOT____Vcellout__rspfifo__wready_o;
    };
    struct {
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_socket_1n__DOT__dev_select_outstanding;
        CData/*0:0*/ tlul_socket_1n__DOT__hold_all_requests;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_req;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_rsp;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__0__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__1__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__2__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__3__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
    };
    struct {
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*2:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_opcode;
        CData/*7:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_source;
        CData/*1:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_size;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_rsp_pending;
        CData/*3:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_instr_type;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__reqfifo__wready_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__req_i;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gnt_o;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__ppc_out;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__mask;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__winner;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__reg_error;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT____Vcellout__u_ctrl_en__q;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT____Vcellout__u_ctrl_rst__q;
        CData/*3:0*/ my_ip__DOT__u_my_ip_reg__DOT__addr_hit;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__outstanding_q;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__a_ack;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__d_ack;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__error_q;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__err_internal;
        CData/*7:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__reqid_q;
        CData/*1:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__reqsz_q;
        CData/*2:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__rspop_q;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__rd_req;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__wr_req;
        CData/*0:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_ctrl_en__DOT__wr_en;
        CData/*0:0*/ my_ip__DOT__u_my_ip_core__DOT__status_full;
        CData/*0:0*/ my_ip__DOT__u_my_ip_core__DOT__status_empty;
        CData/*7:0*/ my_ip__DOT__u_my_ip_core__DOT__rdata;
        CData/*0:0*/ my_ip__DOT__u_my_ip_core__DOT__u_sync_name__DOT__intq;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__1__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__3__Vfuncout;
        CData/*0:0*/ __Vfunc_mubi4_test_invalid__4__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_invalid__4__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__5__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__5__val;
        CData/*0:0*/ __Vfunc_mubi4_test_false_loose__6__Vfuncout;
    };
    struct {
        CData/*3:0*/ __Vfunc_mubi4_test_false_loose__6__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__7__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__7__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__8__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__8__val;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__10__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__11__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__14__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__15__Vfuncout;
        CData/*6:0*/ __Vfunc_get_bad_cmd_intg__18__Vfuncout;
        CData/*6:0*/ __Vfunc_get_bad_cmd_intg__18__cmd_intg;
        CData/*6:0*/ __Vfunc_get_cmd_intg__19__Vfuncout;
        CData/*6:0*/ __Vfunc_get_cmd_intg__19__cmd_intg;
        CData/*6:0*/ __Vfunc_get_bad_data_intg__23__Vfuncout;
        CData/*6:0*/ __Vfunc_get_bad_data_intg__23__data_intg;
        CData/*6:0*/ __Vfunc_get_data_intg__24__Vfuncout;
        CData/*6:0*/ __Vfunc_get_data_intg__24__data_intg;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__26__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__26__val;
        CData/*0:0*/ __Vdly__cdc_2phase__DOT__i_src__DOT__req_src_q;
        CData/*0:0*/ __Vdly__prim_reg_cdc__DOT__u_src_to_dst_req__DOT__src_level;
        CData/*7:0*/ __VdlyVal__prim_fifo__DOT__fifo_stored__v0;
        CData/*3:0*/ __VdlyDim0__prim_fifo__DOT__fifo_stored__v0;
        CData/*0:0*/ __VdlySet__prim_fifo__DOT__fifo_stored__v0;
        CData/*0:0*/ __VdlySet__prim_fifo__DOT__fifo_stored__v1;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_clk_div__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_clk_div__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_lifo__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_lifo__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_ram__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_rom__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_shreg__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_cdc_rand_delay__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_cdc_rand_delay__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_intr_hw__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_intr_hw__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__src_clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__src_rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dst_clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dst_rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_counter__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_counter__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_deglitch__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_deglitch__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_edge_detect__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_edge_detect__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__wr_clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rd_clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_reg__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_reg__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rrarbiter__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rrarbiter__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Eclk_i__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_src_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_src_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_dst_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_dst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_alert_sender__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_alert_sender__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_h_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_h_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_d_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_d_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__my_ip__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__my_ip__02Erst_ni__0;
        VL_IN16(prim_ram__02Eaddr_i,15,0);
        VL_IN16(prim_rom__02Eaddr_i,15,0);
        VL_IN16(rrarbiter__02Ereq_i,12,0);
        VL_OUT16(ack_o,12,0);
        VL_IN16(prim_fifo_async_simple__02Ewdata_i,15,0);
        VL_OUT16(prim_fifo_async_simple__02Erdata_o,15,0);
        VL_OUT16(w_sram_addr_o,15,0);
        VL_OUT16(r_sram_addr_o,15,0);
        VL_IN16(mem_addr_i,11,0);
        VL_OUT16(addr_o,11,0);
        SData/*12:0*/ rrarbiter__DOT__mask;
        SData/*15:0*/ prim_fifo_async_simple__DOT__data_q;
        SData/*8:0*/ tlul_socket_1n__DOT__num_req_outstanding;
        SData/*15:0*/ my_ip__DOT__u_my_ip_reg__DOT____Vcellout__u_ctrl_setting__q;
        VL_IN(prim_ram__02Ewdata_i,31,0);
        VL_OUT(prim_ram__02Erdata_o,31,0);
        VL_OUT(prim_rom__02Erdata_o,31,0);
        VL_IN(wd,31,0);
        VL_OUT(ds,31,0);
        VL_OUT(qs,31,0);
        VL_IN(d,31,0);
        VL_OUT(q,31,0);
        VL_IN(prim_fifo_async_sram_adapter__02Ewdata_i,31,0);
        VL_OUT(prim_fifo_async_sram_adapter__02Erdata_o,31,0);
        VL_OUT(w_sram_wdata_o,31,0);
        VL_OUT(w_sram_wmask_o,31,0);
        VL_IN(w_sram_rdata_i,31,0);
        VL_OUT(r_sram_wdata_o,31,0);
        VL_OUT(r_sram_wmask_o,31,0);
        VL_IN(r_sram_rdata_i,31,0);
        VL_IN(src_wd_i,31,0);
        VL_OUT(src_qs_o,31,0);
        VL_IN(dst_ds_i,31,0);
        VL_IN(dst_qs_i,31,0);
        VL_OUT(dst_wd_o,31,0);
        VL_IN(oh_i,31,0);
        VL_IN(mem_wdata_i,31,0);
        VL_OUT(mem_rdata_o,31,0);
        VL_IN(tlul_adapter_host__02Eaddr_i,31,0);
        VL_IN(tlul_adapter_host__02Ewdata_i,31,0);
        VL_OUT(tlul_adapter_host__02Erdata_o,31,0);
    };
    struct {
        VL_OUT(wdata_o,31,0);
        VL_OUT(wmask_o,31,0);
        VL_IN(rdata_i,31,0);
        IData/*31:0*/ prim_reg__DOT__wr_data;
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_q;
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_d;
        IData/*31:0*/ prim_reg_cdc__DOT__src_q;
        IData/*31:0*/ tlul_adapter_sram__DOT__error_blanking_data;
        IData/*16:0*/ tlul_adapter_sram__DOT____Vcellout__u_reqfifo__rdata_o;
        IData/*16:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__storage;
        IData/*22:0*/ tlul_socket_1n__DOT__blanked_auser;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rdata_o;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__reqfifo__wdata_i;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__rspfifo__wdata_i;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT____Vcellout__gen_arb_ppc__DOT__u_reqarb__data_o;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rdata_o;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellinp__rspfifo__wdata_i;
        VlWide<4>/*107:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        IData/*31:0*/ my_ip__DOT__u_my_ip_reg__DOT__reg_rdata_next;
        IData/*31:0*/ my_ip__DOT__u_my_ip_reg__DOT__u_reg_if__DOT__rdata_q;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        IData/*31:0*/ __VactIterCount;
        VL_OUTW(sram2tlul__02Etl_o,108,0,4);
        VL_INW(sram2tlul__02Etl_i,65,0,3);
        VL_OUTW(tlul_adapter_host__02Etl_o,108,0,4);
        VL_INW(tlul_adapter_host__02Etl_i,65,0,3);
        VL_INW(tlul_adapter_sram__02Etl_i,108,0,4);
        VL_OUTW(tlul_adapter_sram__02Etl_o,65,0,3);
        VL_INW(tlul_fifo_async__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_fifo_async__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_fifo_async__02Etl_d_o,108,0,4);
        VL_INW(tlul_fifo_async__02Etl_d_i,65,0,3);
        VL_INW(tlul_socket_1n__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_socket_1n__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_socket_m1__02Etl_d_o,108,0,4);
        VL_INW(tlul_socket_m1__02Etl_d_i,65,0,3);
        VL_INW(my_ip__02Etl_i,108,0,4);
        VL_OUTW(my_ip__02Etl_o,65,0,3);
        QData/*39:0*/ tlul_adapter_sram__DOT____Vcellinp__u_rspfifo__wdata_i;
        QData/*39:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<4>/*108:0*/ tlul_socket_1n__DOT____Vcellinp__gen_err_resp__DOT__err_resp__tl_h_i;
        VlWide<3>/*65:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__tl_h_o_int;
        QData/*62:0*/ tlul_socket_m1__DOT____VdfgRegularize_ha7c0ca08_0_4;
        VlWide<4>/*108:0*/ __Vfunc_get_bad_cmd_intg__18__tl;
        VlWide<4>/*108:0*/ __Vfunc_get_cmd_intg__19__tl;
        QData/*42:0*/ __Vfunc_get_cmd_intg__19__cmd;
        QData/*42:0*/ __Vfunc_extract_h2d_cmd_intg__20__Vfuncout;
        VlWide<4>/*108:0*/ __Vfunc_extract_h2d_cmd_intg__20__tl;
        QData/*42:0*/ __Vfunc_extract_h2d_cmd_intg__20__payload;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__21__Vfuncout;
        QData/*56:0*/ __Vfunc_prim_secded_inv_64_57_enc__21__data_i;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__21__data_o;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__22__Vfuncout;
        QData/*56:0*/ __Vfunc_prim_secded_inv_64_57_enc__22__data_i;
        QData/*63:0*/ __Vfunc_prim_secded_inv_64_57_enc__22__data_o;
        QData/*38:0*/ __Vfunc_get_data_intg__24__enc_data;
        QData/*38:0*/ __Vfunc_prim_secded_inv_39_32_enc__25__Vfuncout;
        QData/*38:0*/ __Vfunc_prim_secded_inv_39_32_enc__25__data_o;
        VL_INW(h2d[2],108,0,4);
        VL_INW(d2h[2],65,0,3);
        VL_OUTW(tlul_socket_1n__02Etl_d_o[4],108,0,4);
    };
    struct {
        VL_INW(tlul_socket_1n__02Etl_d_i[4],65,0,3);
        VL_INW(tlul_socket_m1__02Etl_h_i[4],108,0,4);
        VL_OUTW(tlul_socket_m1__02Etl_h_o[4],65,0,3);
        VlUnpacked<CData/*7:0*/, 12> prim_lifo__DOT__lifo_stored;
        VlUnpacked<IData/*31:0*/, 65536> prim_ram__DOT__mem;
        VlUnpacked<IData/*31:0*/, 65536> prim_rom__DOT__rom;
        VlUnpacked<CData/*7:0*/, 12> prim_fifo__DOT__fifo_stored;
        VlUnpacked<CData/*3:0*/, 2> prim_fifo__DOT__rd_gray_pointer_sync;
        VlUnpacked<CData/*3:0*/, 2> prim_fifo__DOT__wr_gray_pointer_sync;
        VlUnpacked<SData/*12:0*/, 13> rrarbiter__DOT__mask_lut;
        VlUnpacked<VlWide<4>/*106:0*/, 4> tlul_fifo_async__DOT__reqfifo__DOT__storage;
        VlUnpacked<QData/*63:0*/, 4> tlul_fifo_async__DOT__rspfifo__DOT__storage;
        VlUnpacked<VlWide<3>/*65:0*/, 5> tlul_socket_1n__DOT__tl_u_i;
        VlUnpacked<VlWide<4>/*108:0*/, 4> tlul_socket_m1__DOT__hreq_fifo_o;
        VlUnpacked<VlWide<4>/*108:0*/, 4> tlul_socket_m1__DOT____Vcellinp__gen_arb_ppc__DOT__u_reqarb__data_i;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop_pkg__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop_pkg___024root(Vtop_pkg__Syms* symsp, const char* namep);
    ~Vtop_pkg___024root();
    VL_UNCOPYABLE(Vtop_pkg___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
