// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vspi_host_tb.h for the primary calling header

#include "Vspi_host_tb__pch.h"
#include "Vspi_host_tb_spi_host_tb.h"

VL_ATTR_COLD void Vspi_host_tb_spi_host_tb___ctor_var_reset(Vspi_host_tb_spi_host_tb* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vspi_host_tb_spi_host_tb___ctor_var_reset\n"); );
    Vspi_host_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__PVT__clk_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rst_ni = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(109, vlSelf->__PVT__tl_i);
    vlSelf->__PVT__spi_sdio_i = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(66, vlSelf->__PVT__tl_o);
    vlSelf->__PVT__spi_sclk_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__read_data = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__reg_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__reg_re = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__reg_error = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__reg_rdata_next = VL_RAND_RESET_I(32);
    vlSelf->u_spi_host__DOT__u_spi_host_reg__DOT____Vcellout__u_ctrl_en__q = VL_RAND_RESET_I(1);
    vlSelf->u_spi_host__DOT__u_spi_host_reg__DOT____Vcellout__u_ctrl_txrst__q = VL_RAND_RESET_I(1);
    vlSelf->u_spi_host__DOT__u_spi_host_reg__DOT____Vcellout__u_ctrl_rxrst__q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__wdata_qe = VL_RAND_RESET_I(1);
    vlSelf->u_spi_host__DOT__u_spi_host_reg__DOT____Vcellout__u_wdata__q = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__addr_hit = VL_RAND_RESET_I(4);
    vlSelf->u_spi_host__DOT__u_spi_host_reg__DOT____VdfgRegularize_h533b1fce_2_6 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__outstanding_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__a_ack = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__rdata_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__error_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__err_internal = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__instr_error = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__malformed_meta_err = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__reqid_q = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__reqsz_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__rspop_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__rd_req = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__wr_req = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(66, vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__tl_o_pre);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_wr_err = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_type_err = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__addr_sz_chk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__mask_chk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__fulldata_chk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_ctrl_en__DOT__wr_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_reg__DOT__u_wdata__DOT__wr_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__current_state = VL_RAND_RESET_I(2);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__next_state = VL_RAND_RESET_I(2);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__current_byte_q = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__current_byte_d = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__cs_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__cs_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sdio_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sdio_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sdioz_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sdioz_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sclk_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__byte_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__byte_cnt_d = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__bit_cnt_q = VL_RAND_RESET_I(4);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__bit_cnt_d = VL_RAND_RESET_I(4);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_rready_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_rready_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__rx_fifo_wvalid_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__rx_fifo_wvalid_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__r_wn_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__r_wn_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__rx_fifo_depth = VL_RAND_RESET_I(2);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_depth = VL_RAND_RESET_I(2);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__sclk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_rdata = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__rx_fifo_rvalid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__rx_fifo_wready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_rvalid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__tx_fifo_wready = VL_RAND_RESET_I(1);
    vlSelf->u_spi_host__DOT__u_spi_host_core__DOT____Vcellinp__u_clk_div2__d_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__full_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__fifo_empty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__under_rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__storage = VL_RAND_RESET_I(24);
    vlSelf->u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT____Vlvbound_hda94dff7__0 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__full_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__fifo_empty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__under_rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__storage = VL_RAND_RESET_I(24);
    vlSelf->u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT____Vlvbound_hda94dff7__0 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_FDEB5__5__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_FDEB5__5__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_15E34__6__Vfuncout = VL_RAND_RESET_I(8);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_15E34__6__inp = VL_RAND_RESET_I(8);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_9783B__8__Vfuncout = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_9783B__8__inp = VL_RAND_RESET_I(32);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_1__10__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__sv2v_cast_1__10__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__prim_mubi_pkg_mubi4_test_invalid__11__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__prim_mubi_pkg_mubi4_test_invalid__11__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__prim_mubi_pkg_mubi4_test_true_strict__26__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__prim_mubi_pkg_mubi4_test_true_strict__26__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__46__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_reg__DOT__u_reg_if__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__46__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__67__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__67__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__68__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__68__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__70__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__70__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__71__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__71__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__76__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__76__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__77__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__77__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__79__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__79__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__80__Vfuncout = VL_RAND_RESET_I(2);
    vlSelf->__Vfunc_u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__80__inp = VL_RAND_RESET_I(2);
    vlSelf->__Vdly__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_txfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(3);
    vlSelf->__Vdly__u_spi_host__DOT__u_spi_host_core__DOT__u_spi_rxfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(3);
}
