// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vspi_host_tb.h for the primary calling header

#include "Vspi_host_tb__pch.h"
#include "Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6.h"

VL_ATTR_COLD void Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6___ctor_var_reset(Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+        Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6___ctor_var_reset\n"); );
    Vspi_host_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clk_i = VL_RAND_RESET_I(1);
    vlSelf->rst_ni = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(109, vlSelf->tl_h_i);
    VL_RAND_RESET_W(66, vlSelf->tl_h_o);
    VL_RAND_RESET_W(109, vlSelf->tl_d_o);
    VL_RAND_RESET_W(66, vlSelf->tl_d_i);
    vlSelf->spare_req_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__spare_req_o = VL_RAND_RESET_I(1);
    vlSelf->spare_rsp_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__spare_rsp_o = VL_RAND_RESET_I(1);
    vlSelf->__Vcellout__reqfifo__rvalid_o = VL_RAND_RESET_I(1);
    vlSelf->__Vcellout__reqfifo__wready_o = VL_RAND_RESET_I(1);
    vlSelf->__Vcellout__rspfifo__rvalid_o = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(65, vlSelf->__Vcellinp__rspfifo__wdata_i);
    vlSelf->__Vcellout__rspfifo__wready_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__full_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__depth_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__empty = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(108, vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__storage);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__full_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__depth_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__empty = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(65, vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__storage);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_msb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__4__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__4__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__5__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__5__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__7__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__7__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__8__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__8__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__13__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__13__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__14__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__14__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__16__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__16__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__17__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__17__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__22__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__22__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__23__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__23__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__25__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__25__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__26__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__26__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__31__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__31__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__32__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__32__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__34__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__34__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__35__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__35__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__40__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__40__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__41__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__41__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__43__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__43__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__44__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__44__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__49__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__49__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__50__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__50__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__52__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__52__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__53__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__53__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__58__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__58__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__59__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__59__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__61__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__61__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__62__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__62__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__67__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__67__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__68__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__68__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__70__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__70__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__71__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__71__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__76__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__76__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__77__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__77__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__79__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__79__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__80__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__80__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__85__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__85__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__86__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__86__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__88__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__88__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__89__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__89__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__94__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__94__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__95__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__95__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__97__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__97__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__98__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__98__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__103__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__103__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__104__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__104__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__106__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__106__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__107__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__107__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__112__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__112__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__113__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__113__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__115__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__115__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__116__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__116__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__121__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__121__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__122__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__122__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__124__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__124__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__125__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__125__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__130__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__130__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__131__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__131__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__133__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__133__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__134__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__134__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__139__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__139__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__140__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__140__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__142__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__142__inp = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__143__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__143__inp = VL_RAND_RESET_I(1);
}
