// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vspi_host_tb.h for the primary calling header

#ifndef VERILATED_VSPI_HOST_TB___024ROOT_H_
#define VERILATED_VSPI_HOST_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vspi_host_tb___024unit;
class Vspi_host_tb___024unit__03a__03atlul_utils__Vclpkg;
class Vspi_host_tb_spi_host_reg_pkg;
class Vspi_host_tb_spi_host_tb;
class Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6;


class Vspi_host_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vspi_host_tb___024root final : public VerilatedModule {
  public:
    // CELLS
    Vspi_host_tb_spi_host_tb* spi_host_tb;
    Vspi_host_tb___024unit* __PVT____024unit;
    Vspi_host_tb_spi_host_reg_pkg* __PVT__spi_host_reg_pkg;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__0__KET____DOT__fifo_d;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__1__KET____DOT__fifo_d;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__2__KET____DOT__fifo_d;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_1n__DOT__gen_dfifo__BRA__3__KET____DOT__fifo_d;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__0__KET____DOT__u_hostfifo;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__1__KET____DOT__u_hostfifo;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__2__KET____DOT__u_hostfifo;
    Vspi_host_tb_tlul_fifo_sync__RCz6_RDz6* __PVT__tlul_socket_m1__DOT__gen_host_fifo__BRA__3__KET____DOT__u_hostfifo;
    Vspi_host_tb___024unit__03a__03atlul_utils__Vclpkg* __024unit__03a__03atlul_utils__Vclpkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(prim_fifo_async_simple__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_simple__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_simple__02Erst_rd_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_wr_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_wr_ni,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Eclk_rd_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erst_rd_ni,0,0);
        VL_IN8(prim_filter__02Eclk_i,0,0);
        VL_IN8(prim_filter__02Erst_ni,0,0);
        VL_IN8(prim_filter_ctr__02Eclk_i,0,0);
        VL_IN8(prim_filter_ctr__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_host__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_host__02Erst_ni,0,0);
        VL_IN8(tlul_adapter_sram__02Eclk_i,0,0);
        VL_IN8(tlul_adapter_sram__02Erst_ni,0,0);
        VL_IN8(tlul_assert_multiple__02Eclk_i,0,0);
        VL_IN8(tlul_assert_multiple__02Erst_ni,0,0);
        VL_IN8(clk_h_i,0,0);
        VL_IN8(rst_h_ni,0,0);
        VL_IN8(clk_d_i,0,0);
        VL_IN8(rst_d_ni,0,0);
        VL_IN8(tlul_socket_1n__02Eclk_i,0,0);
        VL_IN8(tlul_socket_1n__02Erst_ni,0,0);
        VL_IN8(tlul_socket_m1__02Eclk_i,0,0);
        VL_IN8(tlul_socket_m1__02Erst_ni,0,0);
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__effective_rst_n;
        VL_IN8(prim_cdc_rand_delay__02Eclk_i,0,0);
        VL_IN8(prim_cdc_rand_delay__02Erst_ni,0,0);
        VL_IN8(prev_data_i,0,0);
        VL_IN8(src_data_i,0,0);
        VL_OUT8(dst_data_o,0,0);
        VL_IN8(sram2tlul__02Eclk_i,0,0);
        VL_IN8(sram2tlul__02Erst_ni,0,0);
        VL_IN8(mem_req_i,0,0);
        VL_IN8(mem_write_i,0,0);
        VL_OUT8(mem_rvalid_o,0,0);
        VL_OUT8(mem_error_o,1,0);
        VL_IN8(prim_fifo_async_simple__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ewready_o,0,0);
        VL_OUT8(prim_fifo_async_simple__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_simple__02Erready_i,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Ewvalid_i,0,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ewready_o,0,0);
        VL_OUT8(wdepth_o,4,0);
        VL_OUT8(prim_fifo_async_sram_adapter__02Ervalid_o,0,0);
        VL_IN8(prim_fifo_async_sram_adapter__02Erready_i,0,0);
        VL_OUT8(rdepth_o,4,0);
        VL_OUT8(r_full_o,0,0);
        VL_OUT8(r_notempty_o,0,0);
        VL_OUT8(w_full_o,0,0);
        VL_OUT8(w_sram_req_o,0,0);
        VL_IN8(w_sram_gnt_i,0,0);
        VL_OUT8(w_sram_write_o,0,0);
        VL_IN8(w_sram_rvalid_i,0,0);
        VL_IN8(w_sram_rerror_i,1,0);
        VL_OUT8(r_sram_req_o,0,0);
        VL_IN8(r_sram_gnt_i,0,0);
        VL_OUT8(r_sram_write_o,0,0);
        VL_IN8(r_sram_rvalid_i,0,0);
        VL_IN8(r_sram_rerror_i,1,0);
        VL_IN8(prim_filter__02Eenable_i,0,0);
        VL_IN8(prim_filter__02Efilter_i,0,0);
        VL_OUT8(prim_filter__02Efilter_o,0,0);
    };
    struct {
        VL_IN8(prim_filter_ctr__02Eenable_i,0,0);
        VL_IN8(prim_filter_ctr__02Efilter_i,0,0);
        VL_IN8(thresh_i,1,0);
        VL_OUT8(prim_filter_ctr__02Efilter_o,0,0);
        VL_IN8(req_i,0,0);
        VL_OUT8(gnt_o,0,0);
        VL_IN8(we_i,0,0);
        VL_IN8(wdata_intg_i,6,0);
        VL_IN8(be_i,3,0);
        VL_IN8(instr_type_i,3,0);
        VL_OUT8(valid_o,0,0);
        VL_OUT8(rdata_intg_o,6,0);
        VL_OUT8(err_o,0,0);
        VL_OUT8(intg_err_o,0,0);
        VL_IN8(en_ifetch_i,3,0);
        VL_OUT8(req_o,0,0);
        VL_OUT8(req_type_o,3,0);
        VL_IN8(gnt_i,0,0);
        VL_OUT8(we_o,0,0);
        VL_OUT8(intg_error_o,0,0);
        VL_IN8(rvalid_i,0,0);
        VL_IN8(rerror_i,1,0);
        VL_OUT8(compound_txn_in_progress_o,0,0);
        VL_IN8(readback_en_i,3,0);
        VL_OUT8(readback_error_o,0,0);
        VL_IN8(wr_collision_i,0,0);
        VL_IN8(write_pending_i,0,0);
        VL_IN8(dev_select_i,2,0);
        CData/*0:0*/ prim_fifo_async_simple__DOT__wr_en;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__pending_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__not_in_reset_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__dst_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__dst_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__chk_flag;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_cs;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_ns;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_cs;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_ack;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_d;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_q;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_req;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_handshake;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_handshake;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__req_sync__DOT__intq;
        CData/*0:0*/ prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__ack_sync__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_wptr_gray;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_wptr;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_d;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_gray_q;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_rptr_gray;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__w_rptr;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__w_wptr_inc;
    };
    struct {
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__r_rptr_inc;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__stored;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__r_sram_rptr;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__r_sramrptr_empty;
        CData/*0:0*/ prim_fifo_async_sram_adapter__DOT__store_en;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_wptr_gray__DOT__intq;
        CData/*4:0*/ prim_fifo_async_sram_adapter__DOT__u_sync_rptr_gray__DOT__intq;
        CData/*3:0*/ prim_filter__DOT__stored_vector_q;
        CData/*3:0*/ prim_filter__DOT__stored_vector_d;
        CData/*0:0*/ prim_filter__DOT__stored_value_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_q;
        CData/*1:0*/ prim_filter_ctr__DOT__diff_ctr_d;
        CData/*0:0*/ prim_filter_ctr__DOT__filter_q;
        CData/*0:0*/ prim_filter_ctr__DOT__stored_value_q;
        CData/*7:0*/ tlul_adapter_host__DOT__tl_source;
        CData/*1:0*/ tlul_adapter_host__DOT__outstanding_reqs_q;
        CData/*1:0*/ tlul_adapter_host__DOT__outstanding_reqs_d;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_d;
        CData/*0:0*/ tlul_adapter_host__DOT__g_multiple_reqs__DOT__source_q;
        CData/*0:0*/ tlul_adapter_sram__DOT__error_det;
        CData/*0:0*/ tlul_adapter_sram__DOT__instr_error;
        CData/*0:0*/ tlul_adapter_sram__DOT__intg_error_q;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_wready;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_rvalid;
        CData/*0:0*/ tlul_adapter_sram__DOT__reqfifo_rready;
        CData/*0:0*/ tlul_adapter_sram__DOT__sramreqfifo_wready;
        CData/*0:0*/ tlul_adapter_sram__DOT__sramreqfifo_rready;
        CData/*4:0*/ tlul_adapter_sram__DOT__sramreqfifo_wdata;
        CData/*4:0*/ tlul_adapter_sram__DOT__sramreqfifo_rdata;
        CData/*0:0*/ tlul_adapter_sram__DOT__rspfifo_rvalid;
        CData/*0:0*/ tlul_adapter_sram__DOT__d_valid;
        CData/*0:0*/ tlul_adapter_sram__DOT__d_error;
        CData/*0:0*/ tlul_adapter_sram__DOT__vld_rd_rsp;
        CData/*6:0*/ tlul_adapter_sram__DOT__error_blanking_integ;
        CData/*0:0*/ tlul_adapter_sram__DOT__missed_err_gnt_q;
        CData/*6:0*/ tlul_adapter_sram__DOT__wmask_intg;
        CData/*6:0*/ tlul_adapter_sram__DOT__wdata_intg;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__instr_type_err;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__addr_sz_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_err__DOT__fulldata_chk;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*4:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__storage;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
    };
    struct {
        CData/*1:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__full_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__disable_sva;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__disable_d_error_sva;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__a_mask;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__d_mask;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h2f9dcced__0;
        CData/*2:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h8d3db085__0;
        CData/*1:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h30376d23__0;
        CData/*3:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_h6d84055b__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT____Vlvbound_ha603a01c__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__disable_sva;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__disable_d_error_sva;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__a_mask;
        CData/*7:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__d_mask;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h2f9dcced__0;
        CData/*2:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h8d3db085__0;
        CData/*1:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h30376d23__0;
        CData/*3:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_h6d84055b__0;
        CData/*0:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT____Vlvbound_ha603a01c__0;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__wdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__rdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__full_wclk;
        CData/*0:0*/ tlul_fifo_async__DOT__reqfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__reqfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__wdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__rdepth_o;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_combi;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_sync;
    };
    struct {
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_sync;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_sync_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_wptr_gray_d;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_q;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_rptr_gray_d;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__full_wclk;
        CData/*0:0*/ tlul_fifo_async__DOT__rspfifo__DOT__empty_rclk;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_wptr__DOT__intq;
        CData/*2:0*/ tlul_fifo_async__DOT__rspfifo__DOT__sync_rptr__DOT__intq;
        CData/*2:0*/ tlul_socket_1n__DOT__dev_select_outstanding;
        CData/*0:0*/ tlul_socket_1n__DOT__hold_all_requests;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_req;
        CData/*0:0*/ tlul_socket_1n__DOT__accept_t_rsp;
        CData/*0:0*/ tlul_socket_1n__DOT__hfifo_reqready;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__0__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__1__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__2__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_u_o__BRA__3__KET____DOT__dev_select;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__reqfifo__rready_i;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__rspfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*2:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_opcode;
        CData/*7:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_source;
        CData/*1:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_size;
        CData/*0:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_rsp_pending;
        CData/*3:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__err_instr_type;
        CData/*3:0*/ tlul_socket_m1__DOT__hrequest;
        CData/*3:0*/ tlul_socket_m1__DOT__hgrant;
        CData/*0:0*/ tlul_socket_m1__DOT__arb_ready;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__3__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__2__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__1__KET__;
        CData/*0:0*/ tlul_socket_m1__DOT__hfifo_rspvalid__BRA__0__KET__;
    };
    struct {
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__reqfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rvalid_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__wready_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__full_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__depth_o;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_wptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_incr_rptr;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__fifo_empty;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__under_rst;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__empty;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set_cnt;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_cnt_q;
        CData/*1:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set_cnt;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__wptr_wrap_set;
        CData/*0:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__rptr_wrap_set;
        CData/*1:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__idx_o;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__masked_req;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__ppc_out;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__arb_req;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__mask;
        CData/*3:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__winner;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__6__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__8__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__8__inp;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__9__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__9__inp;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__gray2dec__15__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__17__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__17__inp;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__18__Vfuncout;
        CData/*4:0*/ __Vfunc_prim_fifo_async_sram_adapter__DOT__sv2v_cast_2DA09__18__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_15E34__31__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_15E34__31__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_B0D6A__33__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_B0D6A__33__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EECFA__36__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EECFA__36__inp;
        CData/*6:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_83AAC__38__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_83AAC__38__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_invalid__39__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_invalid__39__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__54__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__54__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_false_loose__56__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_false_loose__56__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__58__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__58__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__62__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__prim_mubi_pkg_mubi4_test_true_strict__62__val;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__64__Vfuncout;
    };
    struct {
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__64__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__65__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__65__inp;
        CData/*6:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_83AAC__70__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_83AAC__70__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_1__71__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_1__71__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_EECFA__72__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_EECFA__72__inp;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__73__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_FDEB5__73__inp;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__74__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_15E34__74__inp;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_B0D6A__75__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_B0D6A__75__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__78__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_adapter_sram__DOT__u_err__DOT__prim_mubi_pkg_mubi4_test_true_strict__78__val;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__101__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__101__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__102__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__102__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__104__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__104__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__105__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__105__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__110__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__110__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__111__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__111__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__113__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__113__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__114__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_sramreqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__114__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__119__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__119__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__120__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__120__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__122__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__122__inp;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__123__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__123__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__136__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__136__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__137__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__137__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__139__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__139__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__140__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__140__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__142__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__142__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__143__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__143__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__145__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__145__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__146__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__sv2v_cast_2DA09__146__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__147__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__reqfifo__DOT__g_full_gray_conversion__DOT__gray2dec__149__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__159__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__159__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__160__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__160__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__162__Vfuncout;
    };
    struct {
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__162__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__163__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__163__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__165__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__165__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__166__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__166__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__168__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__168__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__169__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__sv2v_cast_2DA09__169__inp;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__170__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_fifo_async__DOT__rspfifo__DOT__g_full_gray_conversion__DOT__gray2dec__172__Vfuncout;
        CData/*4:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_5__178__Vfuncout;
        CData/*4:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_5__178__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_EECFA__179__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_EECFA__179__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_FE1F6__180__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_FE1F6__180__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__181__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__181__cmd_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__182__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__182__cmd_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_83AAC__190__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_83AAC__190__inp;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_data_intg__191__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_data_intg__191__data_intg;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__192__Vfuncout;
        CData/*6:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__192__data_intg;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__206__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__206__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__207__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__207__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__209__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__209__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__210__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__210__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__215__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__215__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__216__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__216__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__218__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__218__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__219__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__219__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__prim_mubi_pkg_mubi4_test_true_strict__221__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__prim_mubi_pkg_mubi4_test_true_strict__221__val;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__223__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__223__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__224__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__224__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__225__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__225__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__226__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__226__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__228__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__228__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__231__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__231__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__232__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__232__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__233__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__233__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__234__Vfuncout;
    };
    struct {
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__234__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__236__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__236__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__239__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__239__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__240__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__240__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__241__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__241__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__242__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__242__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__244__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__244__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__247__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__247__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__248__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__248__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__249__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__249__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__250__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__250__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__252__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__252__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__255__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__255__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__256__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__256__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__257__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__257__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__258__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__258__inp;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__260__Vfuncout;
        CData/*3:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_B0D6A__260__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__263__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__263__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__264__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__264__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__265__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__265__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__266__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__266__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__267__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__267__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__270__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__270__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__271__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__271__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__272__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__272__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__273__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__273__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__274__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__274__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__277__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__277__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__278__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__278__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__279__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__279__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__280__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__280__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__281__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__281__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__284__Vfuncout;
    };
    struct {
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__284__inp;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__285__Vfuncout;
        CData/*2:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_3__285__inp;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__286__Vfuncout;
        CData/*1:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_FDEB5__286__inp;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__287__Vfuncout;
        CData/*7:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_15E34__287__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__288__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_17D81__288__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__295__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__295__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__296__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__296__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__298__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__298__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__299__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__299__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__304__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__304__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__305__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__305__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__307__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__307__inp;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__308__Vfuncout;
        CData/*0:0*/ __Vfunc_tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__u_fifo_cnt__DOT__sv2v_cast_2DA09__308__inp;
        CData/*0:0*/ __VvifTrigger_h100a9299__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_simple__DOT__u_prim_sync_reqack__DOT__effective_rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_wr_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_wr_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Eclk_rd_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_fifo_async_sram_adapter__02Erst_rd_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__prim_filter_ctr__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_host__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_adapter_sram__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_assert_multiple__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_assert_multiple__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_h_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_h_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_d_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_d_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_1n__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Eclk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tlul_socket_m1__02Erst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__spi_host_tb____PVT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__spi_host_tb____PVT__rst_ni__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(mem_addr_i,11,0);
        VL_IN16(prim_fifo_async_simple__02Ewdata_i,15,0);
        VL_OUT16(prim_fifo_async_simple__02Erdata_o,15,0);
        VL_OUT16(w_sram_addr_o,15,0);
        VL_OUT16(r_sram_addr_o,15,0);
        VL_OUT16(addr_o,11,0);
    };
    struct {
        SData/*15:0*/ prim_fifo_async_simple__DOT__data_q;
        SData/*8:0*/ tlul_socket_1n__DOT__num_req_outstanding;
        SData/*13:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_11E70__68__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_11E70__68__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__269__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__269__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__276__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__276__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__283__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__283__inp;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__290__Vfuncout;
        SData/*13:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_11E70__290__inp;
        VL_OUTW(sram2tlul__02Etl_o,108,0,4);
        VL_INW(sram2tlul__02Etl_i,65,0,3);
        VL_IN(mem_wdata_i,31,0);
        VL_OUT(mem_rdata_o,31,0);
        VL_IN(prim_fifo_async_sram_adapter__02Ewdata_i,31,0);
        VL_OUT(prim_fifo_async_sram_adapter__02Erdata_o,31,0);
        VL_OUT(w_sram_wdata_o,31,0);
        VL_OUT(w_sram_wmask_o,31,0);
        VL_IN(w_sram_rdata_i,31,0);
        VL_OUT(r_sram_wdata_o,31,0);
        VL_OUT(r_sram_wmask_o,31,0);
        VL_IN(r_sram_rdata_i,31,0);
        VL_IN(addr_i,31,0);
        VL_IN(tlul_adapter_host__02Ewdata_i,31,0);
        VL_OUT(tlul_adapter_host__02Erdata_o,31,0);
        VL_OUTW(tlul_adapter_host__02Etl_o,108,0,4);
        VL_INW(tlul_adapter_host__02Etl_i,65,0,3);
        VL_INW(tlul_adapter_sram__02Etl_i,108,0,4);
        VL_OUTW(tlul_adapter_sram__02Etl_o,65,0,3);
        VL_OUT(wdata_o,31,0);
        VL_OUT(wmask_o,31,0);
        VL_IN(rdata_i,31,0);
        VL_INW(h2d,217,0,7);
        VL_INW(d2h,131,0,5);
        VL_INW(tlul_fifo_async__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_fifo_async__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_fifo_async__02Etl_d_o,108,0,4);
        VL_INW(tlul_fifo_async__02Etl_d_i,65,0,3);
        VL_INW(tlul_socket_1n__02Etl_h_i,108,0,4);
        VL_OUTW(tlul_socket_1n__02Etl_h_o,65,0,3);
        VL_OUTW(tlul_socket_1n__02Etl_d_o,435,0,14);
        VL_INW(tlul_socket_1n__02Etl_d_i,263,0,9);
        VL_INW(tlul_socket_m1__02Etl_h_i,435,0,14);
        VL_OUTW(tlul_socket_m1__02Etl_h_o,263,0,9);
        VL_OUTW(tlul_socket_m1__02Etl_d_o,108,0,4);
        VL_INW(tlul_socket_m1__02Etl_d_i,65,0,3);
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_q;
        IData/*31:0*/ prim_fifo_async_sram_adapter__DOT__rdata_d;
        VlWide<4>/*108:0*/ tlul_adapter_host__DOT__tl_out;
        VlWide<3>/*65:0*/ tlul_adapter_sram__DOT__tl_o_int;
        IData/*16:0*/ tlul_adapter_sram__DOT__reqfifo_wdata;
        IData/*16:0*/ tlul_adapter_sram__DOT__reqfifo_rdata;
        IData/*31:0*/ tlul_adapter_sram__DOT__error_blanking_data;
        IData/*31:0*/ tlul_adapter_sram__DOT__wmask_int;
        IData/*31:0*/ tlul_adapter_sram__DOT__wdata_int;
        IData/*31:0*/ tlul_adapter_sram__DOT__sv2v_autoblock_1__DOT__i;
        IData/*31:0*/ tlul_adapter_sram__DOT__gen_rmask__DOT__rmask;
        IData/*16:0*/ tlul_adapter_sram__DOT__u_reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<80>/*2559:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__pend_req;
        VlWide<80>/*2559:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__pend_req;
        VlWide<4>/*108:0*/ tlul_socket_1n__DOT__tl_t_o;
        IData/*22:0*/ tlul_socket_1n__DOT__blanked_auser;
    };
    struct {
        VlWide<3>/*65:0*/ tlul_socket_1n__DOT__tl_t_p;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellout__reqfifo__rdata_o;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__reqfifo__wdata_i;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT____Vcellinp__rspfifo__wdata_i;
        VlWide<4>/*109:0*/ tlul_socket_1n__DOT__fifo_h__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_1n__DOT__fifo_h__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*65:0*/ tlul_socket_1n__DOT__gen_err_resp__DOT__err_resp__DOT__tl_h_o_int;
        VlWide<14>/*435:0*/ tlul_socket_m1__DOT__hreq_fifo_o;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__dreq_fifo_i;
        VlWide<3>/*65:0*/ tlul_socket_m1__DOT__drsp_fifo_o;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__arb_data;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__0__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__1__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__2__KET____DOT__hreq_fifo_i;
        VlWide<4>/*108:0*/ tlul_socket_m1__DOT__gen_host_fifo__BRA__3__KET____DOT__hreq_fifo_i;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellout__rspfifo__rdata_o;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT____Vcellinp__rspfifo__wdata_i;
        VlWide<4>/*107:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__reqfifo__DOT__gen_normal_fifo__DOT__storage;
        VlWide<3>/*64:0*/ tlul_socket_m1__DOT__u_devicefifo__DOT__rspfifo__DOT__gen_normal_fifo__DOT__storage;
        IData/*31:0*/ tlul_socket_m1__DOT__gen_arb_ppc__DOT__u_reqarb__DOT__gen_normal_case__DOT__sv2v_autoblock_3__DOT__i;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_D591E__32__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_D591E__32__inp;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_9783B__34__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_9783B__34__inp;
        IData/*22:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EDEFC__35__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_adapter_host__DOT__sv2v_cast_EDEFC__35__inp;
        IData/*31:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_9783B__67__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_adapter_sram__DOT__sv2v_cast_9783B__67__inp;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_bad_cmd_intg__181__tl;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__182__tl;
        VlWide<4>/*108:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__183__tl;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__227__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__227__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__229__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__229__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__230__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__230__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__235__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__235__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__237__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__237__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__238__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__238__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__243__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__243__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__245__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__245__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__246__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__246__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__251__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__251__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__253__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__253__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__254__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__254__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__259__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_D591E__259__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__261__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__261__inp;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__262__Vfuncout;
        IData/*22:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_EDEFC__262__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__268__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__268__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__275__Vfuncout;
    };
    struct {
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__275__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__282__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__282__inp;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__289__Vfuncout;
        IData/*31:0*/ __Vfunc_tlul_socket_m1__DOT__sv2v_cast_9783B__289__inp;
        IData/*31:0*/ __VactIterCount;
        QData/*39:0*/ tlul_adapter_sram__DOT__rspfifo_wdata;
        QData/*39:0*/ tlul_adapter_sram__DOT__rspfifo_rdata;
        QData/*38:0*/ tlul_adapter_sram__DOT____Vcellout__u_tlul_data_integ_enc_instr__data_intg_o;
        QData/*38:0*/ tlul_adapter_sram__DOT____Vcellout__u_tlul_data_integ_enc_data__data_intg_o;
        QData/*39:0*/ tlul_adapter_sram__DOT__u_rspfifo__DOT__gen_normal_fifo__DOT__storage;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__a_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__0__KET____DOT__tlul_assert__DOT__d_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__a_data;
        QData/*63:0*/ tlul_assert_multiple__DOT__gen_assert__BRA__1__KET____DOT__tlul_assert__DOT__d_data;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_cmd_intg__182__cmd;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__183__Vfuncout;
        QData/*42:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_extract_h2d_cmd_intg__183__payload;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__184__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__184__data_i;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__184__data_o;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__185__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__185__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__186__Vfuncout;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__186__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__187__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__187__data_i;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_64_57_enc__187__data_o;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__188__Vfuncout;
        QData/*56:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_57__188__inp;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__189__Vfuncout;
        QData/*63:0*/ __Vfunc_tlul_socket_1n__DOT__sv2v_cast_64__189__inp;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__tlul_pkg_get_data_intg__192__enc_data;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_39_32_enc__193__Vfuncout;
        QData/*38:0*/ __Vfunc_tlul_socket_1n__DOT__prim_secded_pkg_prim_secded_inv_39_32_enc__193__data_o;
        VlUnpacked<VlWide<4>/*106:0*/, 4> tlul_fifo_async__DOT__reqfifo__DOT__storage;
        VlUnpacked<QData/*63:0*/, 4> tlul_fifo_async__DOT__rspfifo__DOT__storage;
        VlUnpacked<VlWide<4>/*108:0*/, 5> tlul_socket_1n__DOT__tl_u_o;
        VlUnpacked<VlWide<3>/*65:0*/, 5> tlul_socket_1n__DOT__tl_u_i;
        VlUnpacked<VlWide<3>/*65:0*/, 4> tlul_socket_m1__DOT__hrsp_fifo_i;
        VlUnpacked<CData/*0:0*/, 32> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlDynamicTriggerScheduler __VdynSched;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VicoTriggered;
    VlTriggerVec<33> __VactTriggered;
    VlTriggerVec<33> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vspi_host_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vspi_host_tb___024root(Vspi_host_tb__Syms* symsp, const char* v__name);
    ~Vspi_host_tb___024root();
    VL_UNCOPYABLE(Vspi_host_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
