"""Behavioral model for the FlexSoC UART master IP.

The model owns protocol semantics only. CSR layout belongs to
``uart_master_regmap.py`` and vector formatting/test selection belongs to
``uart_master_tests.py``.
"""

from __future__ import annotations

from dataclasses import dataclass


TOP = "uart_master"
INPUTS = ("gnt_i", "valid_i", "rdata_i", "err_i", "cio_rx_i")
OUTPUTS = (
    "req_o",
    "addr_o",
    "we_o",
    "wdata_o",
    "be_o",
    "cio_tx_o",
    "cio_tx_en_o",
)

NCO = 0x8000
BIT_CYCLES = 32

SOF_REQ = 0xA5
SOF_RESP = 0x5A
PROTO_VER = 0x01
OP_READ = 0
OP_WRITE = 1


def parity_bit(byte: int, *, odd: bool) -> int:
    """Return the UART parity bit generated by the RTL."""

    xor = (byte & 0xFF).bit_count() & 1
    return xor ^ int(odd)


def uart_frame(
    byte: int,
    *,
    parity: bool = False,
    odd: bool = False,
    bad_parity: bool = False,
) -> list[int]:
    """Return one UART frame: start, eight LSB-first data bits, parity, stop."""

    byte &= 0xFF
    bits = [0]
    bits.extend((byte >> bit) & 1 for bit in range(8))
    if parity:
        bits.append(parity_bit(byte, odd=odd) ^ int(bad_parity))
    bits.append(1)
    return bits


@dataclass(frozen=True)
class HostRequest:
    """One command received from the external UART and launched to the SoC."""

    address: int
    write: bool = False
    data: int = 0
    byte_enable: int = 0xF

    @property
    def opcode(self) -> int:
        return OP_WRITE if self.write else OP_READ

    @property
    def aligned_address(self) -> int:
        return self.address & 0xFFFF_FFFC

    def encode(self) -> list[int]:
        """Encode the byte stream consumed by ``uart_host_bridge``.

        The RTL shift register consumes address and write data least-significant
        byte first. This follows the implemented behavior rather than the stale
        ``MSB-first`` comment in the legacy source.
        """

        payload = [SOF_REQ, self.opcode, self.byte_enable & 0xFF]
        payload.extend((self.address & 0xFFFF_FFFF).to_bytes(4, "little"))
        if self.write:
            payload.extend((self.data & 0xFFFF_FFFF).to_bytes(4, "little"))
        return payload

    def bus_outputs(self) -> dict[str, int]:
        """Return the stable host-bus outputs produced for this command."""

        return {
            "addr_o": self.aligned_address,
            "we_o": int(self.write),
            "wdata_o": self.data & 0xFFFF_FFFF if self.write else 0,
            "be_o": (self.byte_enable & 0xF) if self.write else 0xF,
        }


@dataclass(frozen=True)
class HostResponse:
    """One UART response generated after a read transaction."""

    data: int
    error: bool = False
    opcode: int = OP_READ

    def encode(self) -> list[int]:
        """Encode the bridge response stream; read data is transmitted MSB-first."""

        return [
            SOF_RESP,
            PROTO_VER,
            self.opcode & 0xFF,
            int(self.error),
            *((self.data & 0xFFFF_FFFF).to_bytes(4, "big")),
        ]
