/* Generated by Yosys 0.58 (git sha1 157aabb58, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:1.8" *)
module spi_host(clk_i, rst_ni, tl_i, tl_o, spi_cs_o, spi_sclk_o, spi_sdioz_o, spi_sdio_i, spi_sdio_o);
  (* hdlname = "clk_i" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:7.19" *)
  input clk_i;
  wire clk_i;
  (* hdlname = "rst_ni" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:8.19" *)
  input rst_ni;
  wire rst_ni;
  (* hdlname = "tl_i" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:11.29" *)
  input [108:0] tl_i;
  wire [108:0] tl_i;
  (* hdlname = "tl_o" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:12.29" *)
  output [65:0] tl_o;
  wire [65:0] tl_o;
  (* hdlname = "spi_cs_o" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:15.16" *)
  output spi_cs_o;
  wire spi_cs_o;
  (* hdlname = "spi_sclk_o" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:16.16" *)
  output spi_sclk_o;
  wire spi_sclk_o;
  (* hdlname = "spi_sdioz_o" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:17.16" *)
  output spi_sdioz_o;
  wire spi_sdioz_o;
  (* hdlname = "spi_sdio_i" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:18.16" *)
  input spi_sdio_i;
  wire spi_sdio_i;
  (* hdlname = "spi_sdio_o" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:19.16" *)
  output spi_sdio_o;
  wire spi_sdio_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  (* hdlname = "reg2hw" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host.sv:22.21" *)
  (* unused_bits = "9" *)
  wire [28:0] reg2hw;
  (* hdlname = "u_spi_host_core bit_cnt_q" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:39.15" *)
  wire [3:0] \u_spi_host_core.bit_cnt_q ;
  (* hdlname = "u_spi_host_core byte_cnt_q" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:38.15" *)
  wire [2:0] \u_spi_host_core.byte_cnt_q ;
  (* hdlname = "u_spi_host_core current_byte_q" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:33.15" *)
  wire [7:0] \u_spi_host_core.current_byte_q ;
  (* hdlname = "u_spi_host_core current_state" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:26.11" *)
  wire [1:0] \u_spi_host_core.current_state ;
  (* hdlname = "u_spi_host_core r_wn_q" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:43.23" *)
  wire \u_spi_host_core.r_wn_q ;
  (* hdlname = "u_spi_host_core rx_fifo_wvalid" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:51.15" *)
  wire \u_spi_host_core.rx_fifo_wvalid ;
  (* hdlname = "u_spi_host_core rx_fifo_wvalid_d" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:41.33" *)
  wire \u_spi_host_core.rx_fifo_wvalid_d ;
  (* hdlname = "u_spi_host_core sclk" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:47.23" *)
  wire \u_spi_host_core.sclk ;
  (* hdlname = "u_spi_host_core sdioz_d" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:36.24" *)
  wire \u_spi_host_core.sdioz_d ;
  (* hdlname = "u_spi_host_core tx_fifo_rready" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:52.15" *)
  wire \u_spi_host_core.tx_fifo_rready ;
  (* hdlname = "u_spi_host_core tx_fifo_rready_d" *)
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:40.33" *)
  wire \u_spi_host_core.tx_fifo_rready_d ;
  (* hdlname = "u_spi_host_core u_clk_div2 d_i" *)
  (* src = "../hw/ips/prim_opentitan/prim_flop.sv:13.28" *)
  wire \u_spi_host_core.u_clk_div2.d_i ;
  (* hdlname = "u_spi_host_core u_sclk_driver d_i" *)
  (* src = "../hw/ips/prim_opentitan/prim_flop.sv:13.28" *)
  wire \u_spi_host_core.u_sclk_driver.d_i ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo fifo_rptr" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:63.33" *)
  wire [1:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo fifo_wptr" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:63.22" *)
  wire [1:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo storage" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:105.34" *)
  wire [23:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo u_fifo_cnt rptr_wrap_cnt_q" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:38.24" *)
  wire [2:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo u_fifo_cnt wptr_wrap_cnt_q" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:37.24" *)
  wire [2:0] \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q ;
  (* hdlname = "u_spi_host_core u_spi_rxfifo gen_normal_fifo under_rst" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:67.11" *)
  wire \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ;
  (* hdlname = "u_spi_host_core u_spi_txfifo gen_normal_fifo fifo_rptr" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:63.33" *)
  wire [1:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr ;
  (* hdlname = "u_spi_host_core u_spi_txfifo gen_normal_fifo fifo_wptr" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:63.22" *)
  wire [1:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr ;
  (* hdlname = "u_spi_host_core u_spi_txfifo gen_normal_fifo storage" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:105.34" *)
  wire [23:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage ;
  (* hdlname = "u_spi_host_core u_spi_txfifo gen_normal_fifo u_fifo_cnt rptr_wrap_cnt_q" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:38.24" *)
  wire [2:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q ;
  (* hdlname = "u_spi_host_core u_spi_txfifo gen_normal_fifo u_fifo_cnt wptr_wrap_cnt_q" *)
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:37.24" *)
  wire [2:0] \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q ;
  (* hdlname = "u_spi_host_reg u_wdata qe" *)
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:28.25" *)
  wire \u_spi_host_reg.u_wdata.qe ;
  sky130_fd_sc_hd__nor3b_1 _377_ (
    .A(tl_i[60]),
    .B(tl_i[61]),
    .C_N(tl_i[56]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(tl_o[65]),
    .Y(tl_o[0])
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(tl_o[0]),
    .B(tl_i[108]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(tl_i[106]),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _382_ (
    .A(tl_i[107]),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(_072_),
    .B(tl_o[1]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _385_ (
    .A1(_071_),
    .A2(_076_),
    .B1(_077_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(tl_i[62]),
    .B(tl_i[63]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_072_),
    .B(_075_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(reg2hw[26]),
    .A2(_078_),
    .B1(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _392_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xnor2_1 _394_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__xor2_1 _395_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .X(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _396_ (
    .A(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o211ai_1 _397_ (
    .A1(_082_),
    .A2(_085_),
    .B1(_086_),
    .C1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _398_ (
    .A(tl_i[62]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand3_1 _399_ (
    .A(_089_),
    .B(_090_),
    .C(tl_i[63]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _400_ (
    .A(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _401_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _402_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [0]),
    .B1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [8]),
    .B(_084_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _404_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [16]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _405_ (
    .A1(_094_),
    .A2(_095_),
    .B1(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_092_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _407_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__clkinv_1 _409_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _410_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_101_),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _412_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _413_ (
    .A1(_100_),
    .A2(_103_),
    .B1(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__or2_2 _414_ (
    .A(_099_),
    .B(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _415_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(tl_i[63]),
    .B(_090_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _418_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _419_ (
    .A(_072_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(tl_o[16]),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a31oi_1 _421_ (
    .A1(_081_),
    .A2(_098_),
    .A3(_110_),
    .B1(_112_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _422_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [1]),
    .B1(_093_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _423_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [9]),
    .B(_084_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _424_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [17]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _425_ (
    .A1(_113_),
    .A2(_114_),
    .B1(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a221oi_1 _426_ (
    .A1(reg2hw[27]),
    .A2(_078_),
    .B1(_092_),
    .B2(_116_),
    .C1(_080_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__clkinv_1 _427_ (
    .A(_099_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _428_ (
    .A(_105_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _430_ (
    .A(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _431_ (
    .A(_121_),
    .B(_109_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _432_ (
    .A(tl_o[17]),
    .B(_111_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _433_ (
    .A1(_117_),
    .A2(_122_),
    .B1(_123_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a21oi_1 _434_ (
    .A1(reg2hw[28]),
    .A2(_078_),
    .B1(_080_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o211ai_1 _435_ (
    .A1(_082_),
    .A2(_085_),
    .B1(_086_),
    .C1(_087_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _436_ (
    .A(_125_),
    .B(_107_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(_126_),
    .B(_109_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _438_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [2]),
    .B1(_093_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [10]),
    .B(_084_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3_1 _440_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [18]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(_128_),
    .A2(_129_),
    .B1(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(_092_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(tl_o[18]),
    .B(_111_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a31oi_1 _444_ (
    .A1(_124_),
    .A2(_127_),
    .A3(_132_),
    .B1(_133_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(_089_),
    .B(_107_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(_134_),
    .A2(_109_),
    .B1(_080_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [3]),
    .B1(_093_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _448_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [11]),
    .B(_084_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand3_1 _449_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [19]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o21ai_0 _450_ (
    .A1(_136_),
    .A2(_137_),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(_092_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(tl_o[19]),
    .B(_111_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _453_ (
    .A1(_135_),
    .A2(_140_),
    .B1(_141_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _454_ (
    .A(_072_),
    .B(_091_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _455_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [4]),
    .B1(_093_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _456_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [12]),
    .B(_084_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _457_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [20]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _458_ (
    .A1(_143_),
    .A2(_144_),
    .B1(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a221o_1 _459_ (
    .A1(tl_o[20]),
    .A2(_072_),
    .B1(_142_),
    .B2(_146_),
    .C1(_075_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _460_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [5]),
    .B1(_093_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [13]),
    .B(_084_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand3_1 _462_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [21]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _463_ (
    .A1(_147_),
    .A2(_148_),
    .B1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a221o_1 _464_ (
    .A1(tl_o[21]),
    .A2(_072_),
    .B1(_142_),
    .B2(_150_),
    .C1(_075_),
    .X(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _465_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [6]),
    .B1(_093_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [14]),
    .B(_084_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand3_1 _467_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [22]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _468_ (
    .A1(_151_),
    .A2(_152_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a221o_1 _469_ (
    .A1(tl_o[22]),
    .A2(_072_),
    .B1(_142_),
    .B2(_154_),
    .C1(_075_),
    .X(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _470_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [7]),
    .B1(_093_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _471_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [15]),
    .B(_084_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand3_1 _472_ (
    .A(_084_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .C(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [23]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _473_ (
    .A1(_155_),
    .A2(_156_),
    .B1(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a221o_1 _474_ (
    .A1(tl_o[23]),
    .A2(_072_),
    .B1(_142_),
    .B2(_158_),
    .C1(_075_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _475_ (
    .A(_072_),
    .B(tl_o[47]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(_076_),
    .B(_159_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(_111_),
    .B(tl_i[92]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _478_ (
    .A(_072_),
    .B(tl_o[49]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(_160_),
    .B(_161_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _480_ (
    .A(_111_),
    .B(tl_i[93]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _481_ (
    .A(_072_),
    .B(tl_o[50]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(_162_),
    .B(_163_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _483_ (
    .A(_111_),
    .B(tl_i[94]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _484_ (
    .A(_072_),
    .B(tl_o[51]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _485_ (
    .A(_164_),
    .B(_165_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(_111_),
    .B(tl_i[95]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(_072_),
    .B(tl_o[52]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(_166_),
    .B(_167_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _489_ (
    .A(_111_),
    .B(tl_i[96]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(_072_),
    .B(tl_o[53]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(_168_),
    .B(_169_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _492_ (
    .A(_111_),
    .B(tl_i[97]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _493_ (
    .A(_072_),
    .B(tl_o[54]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _494_ (
    .A(_170_),
    .B(_171_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(_111_),
    .B(tl_i[98]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(_072_),
    .B(tl_o[55]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_172_),
    .B(_173_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(_111_),
    .B(tl_i[99]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(_072_),
    .B(tl_o[56]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(_174_),
    .B(_175_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _501_ (
    .A(_111_),
    .B(tl_i[100]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _502_ (
    .A(_072_),
    .B(tl_o[57]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(_176_),
    .B(_177_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _504_ (
    .A(_111_),
    .B(tl_i[101]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(_072_),
    .B(tl_o[58]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(_178_),
    .B(_179_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _507_ (
    .A1(tl_o[0]),
    .A2(tl_i[0]),
    .B1(_072_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _508_ (
    .A(tl_i[25]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand3_1 _509_ (
    .A(_075_),
    .B(_071_),
    .C(_078_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _510_ (
    .A(_181_),
    .B(reg2hw[27]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o21ai_0 _511_ (
    .A1(_180_),
    .A2(_181_),
    .B1(_182_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand3_1 _512_ (
    .A(_106_),
    .B(reg2hw[0]),
    .C(_107_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__or2_2 _513_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _514_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_184_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21oi_1 _515_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .A2(_183_),
    .B1(_003_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nor2_1 _516_ (
    .A(reg2hw[27]),
    .B(_185_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(_101_),
    .B(_184_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_1 _518_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .A2(_183_),
    .B1(_004_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor2_1 _519_ (
    .A(reg2hw[27]),
    .B(_186_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _520_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__clkinv_1 _521_ (
    .A(_183_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(_188_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__clkinv_1 _523_ (
    .A(reg2hw[27]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21ai_0 _524_ (
    .A1(_187_),
    .A2(_189_),
    .B1(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _525_ (
    .A1(_187_),
    .A2(_189_),
    .B1(_191_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _526_ (
    .A(tl_i[26]),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _527_ (
    .A(_181_),
    .B(reg2hw[28]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21ai_0 _528_ (
    .A1(_192_),
    .A2(_181_),
    .B1(_193_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _529_ (
    .A(tl_i[24]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _530_ (
    .A(_181_),
    .B(reg2hw[26]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o21ai_0 _531_ (
    .A1(_194_),
    .A2(_181_),
    .B1(_195_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _532_ (
    .A(_073_),
    .B(tl_i[107]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _533_ (
    .A(tl_i[105]),
    .B(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__clkinv_1 _534_ (
    .A(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand2_1 _535_ (
    .A(_072_),
    .B(tl_o[62]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(_198_),
    .B(_199_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _537_ (
    .A(_120_),
    .B(\u_spi_host_core.tx_fifo_rready ),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _538_ (
    .A(_102_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__clkinv_1 _539_ (
    .A(_200_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nor2_1 _540_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(_202_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(_204_),
    .B(_190_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor3_1 _543_ (
    .A(_201_),
    .B(_203_),
    .C(_205_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _544_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(_201_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nor2_1 _545_ (
    .A(_206_),
    .B(_205_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _546_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o21ai_0 _547_ (
    .A1(_207_),
    .A2(_204_),
    .B1(_190_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__a21oi_1 _548_ (
    .A1(_207_),
    .A2(_204_),
    .B1(_208_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _549_ (
    .A(_125_),
    .B(\u_spi_host_core.rx_fifo_wvalid ),
    .C(_107_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _550_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__clkinv_1 _551_ (
    .A(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _552_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_211_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21oi_1 _553_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .A2(_209_),
    .B1(_000_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _554_ (
    .A(reg2hw[28]),
    .B(_212_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _555_ (
    .A(_083_),
    .B(_211_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a21oi_1 _556_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .A2(_209_),
    .B1(_001_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _557_ (
    .A(reg2hw[28]),
    .B(_213_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _558_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand4_1 _559_ (
    .A(_125_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .C(\u_spi_host_core.rx_fifo_wvalid ),
    .D(_107_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__clkinv_1 _560_ (
    .A(reg2hw[28]),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _561_ (
    .A1(_214_),
    .A2(_215_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__a21oi_1 _562_ (
    .A1(_214_),
    .A2(_215_),
    .B1(_217_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _563_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .B(_198_),
    .C(_091_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand4_1 _564_ (
    .A(_092_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .C(_107_),
    .D(_197_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21ai_0 _565_ (
    .A1(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .A2(_218_),
    .B1(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(_218_),
    .B(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(_221_),
    .B(_216_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor2_1 _568_ (
    .A(_220_),
    .B(_222_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _569_ (
    .A1(_093_),
    .A2(_219_),
    .B1(_222_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _570_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o21ai_0 _571_ (
    .A1(_223_),
    .A2(_221_),
    .B1(_216_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__a21oi_1 _572_ (
    .A1(_223_),
    .A2(_221_),
    .B1(_224_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _573_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .B(\u_spi_host_core.sclk ),
    .Y(_225_)
  );
  sky130_fd_sc_hd__clkinv_1 _574_ (
    .A(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__clkinv_1 _575_ (
    .A(\u_spi_host_core.current_state [0]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nor2_1 _576_ (
    .A(\u_spi_host_core.current_state [1]),
    .B(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__clkinv_1 _577_ (
    .A(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nor2_1 _578_ (
    .A(_226_),
    .B(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__clkinv_1 _579_ (
    .A(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__clkinv_1 _580_ (
    .A(\u_spi_host_core.current_state [1]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nor2_1 _581_ (
    .A(\u_spi_host_core.current_state [0]),
    .B(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__clkinv_1 _582_ (
    .A(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o21ai_0 _583_ (
    .A1(\u_spi_host_core.current_byte_q [7]),
    .A2(_231_),
    .B1(_234_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor2_1 _584_ (
    .A(\u_spi_host_core.byte_cnt_q [1]),
    .B(\u_spi_host_core.byte_cnt_q [2]),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _585_ (
    .A(_236_),
    .B(\u_spi_host_core.r_wn_q ),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _586_ (
    .A(_237_),
    .B(_229_),
    .Y(\u_spi_host_core.sdioz_d )
  );
  sky130_fd_sc_hd__clkinv_1 _587_ (
    .A(\u_spi_host_core.sdioz_d ),
    .Y(_238_)
  );
  sky130_fd_sc_hd__a21oi_1 _588_ (
    .A1(_230_),
    .A2(_237_),
    .B1(spi_sdio_o),
    .Y(_239_)
  );
  sky130_fd_sc_hd__a21oi_1 _589_ (
    .A1(_235_),
    .A2(_238_),
    .B1(_239_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _590_ (
    .A(\u_spi_host_core.current_byte_q [0]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__clkinv_1 _591_ (
    .A(\u_spi_host_core.byte_cnt_q [1]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nor4_1 _592_ (
    .A(\u_spi_host_core.byte_cnt_q [0]),
    .B(\u_spi_host_core.byte_cnt_q [2]),
    .C(\u_spi_host_core.current_state [1]),
    .D(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand3_1 _593_ (
    .A(_188_),
    .B(reg2hw[26]),
    .C(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _594_ (
    .A(_243_),
    .B(_229_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand2_1 _595_ (
    .A(\u_spi_host_core.sdioz_d ),
    .B(_225_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_244_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__clkinv_1 _597_ (
    .A(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(_247_),
    .B(_121_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor2_1 _599_ (
    .A(_225_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__clkinv_1 _600_ (
    .A(_249_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor2_1 _601_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [0]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__clkinv_1 _602_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o21ai_0 _603_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [8]),
    .A2(_102_),
    .B1(_252_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor2_1 _604_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(_252_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nand2_1 _605_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [16]),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o21ai_0 _606_ (
    .A1(_251_),
    .A2(_253_),
    .B1(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__clkinv_1 _607_ (
    .A(_237_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a21oi_1 _608_ (
    .A1(_248_),
    .A2(_256_),
    .B1(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__o21ai_0 _609_ (
    .A1(_240_),
    .A2(_250_),
    .B1(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__o211ai_1 _610_ (
    .A1(spi_sdio_i),
    .A2(_237_),
    .B1(_228_),
    .C1(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _611_ (
    .A(_228_),
    .B(_119_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__a21oi_1 _612_ (
    .A1(_256_),
    .A2(_261_),
    .B1(_246_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a22oi_1 _613_ (
    .A1(_240_),
    .A2(_246_),
    .B1(_260_),
    .B2(_262_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _614_ (
    .A(\u_spi_host_core.current_byte_q [1]),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _615_ (
    .A(_225_),
    .B(_257_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor2_1 _616_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [1]),
    .Y(_265_)
  );
  sky130_fd_sc_hd__o21ai_0 _617_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [9]),
    .A2(_102_),
    .B1(_252_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _618_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [17]),
    .Y(_267_)
  );
  sky130_fd_sc_hd__o21ai_0 _619_ (
    .A1(_265_),
    .A2(_266_),
    .B1(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__a22oi_1 _620_ (
    .A1(_248_),
    .A2(_268_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [1]),
    .Y(_269_)
  );
  sky130_fd_sc_hd__o22ai_1 _621_ (
    .A1(_240_),
    .A2(_264_),
    .B1(_257_),
    .B2(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _622_ (
    .A(_270_),
    .B(_228_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__a21oi_1 _623_ (
    .A1(_261_),
    .A2(_268_),
    .B1(_246_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__a22oi_1 _624_ (
    .A1(_263_),
    .A2(_246_),
    .B1(_271_),
    .B2(_272_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _625_ (
    .A(\u_spi_host_core.current_byte_q [2]),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nor2_1 _626_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [2]),
    .Y(_274_)
  );
  sky130_fd_sc_hd__o21ai_0 _627_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [10]),
    .A2(_102_),
    .B1(_252_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _628_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [18]),
    .Y(_276_)
  );
  sky130_fd_sc_hd__o21ai_0 _629_ (
    .A1(_274_),
    .A2(_275_),
    .B1(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__a22oi_1 _630_ (
    .A1(_248_),
    .A2(_277_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [2]),
    .Y(_278_)
  );
  sky130_fd_sc_hd__o22ai_1 _631_ (
    .A1(_263_),
    .A2(_264_),
    .B1(_257_),
    .B2(_278_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand2_1 _632_ (
    .A(_279_),
    .B(_228_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__a21oi_1 _633_ (
    .A1(_261_),
    .A2(_277_),
    .B1(_246_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__a22oi_1 _634_ (
    .A1(_273_),
    .A2(_246_),
    .B1(_280_),
    .B2(_281_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _635_ (
    .A(\u_spi_host_core.current_byte_q [3]),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nor2_1 _636_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [3]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__o21ai_0 _637_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [11]),
    .A2(_102_),
    .B1(_252_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _638_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [19]),
    .Y(_285_)
  );
  sky130_fd_sc_hd__o21ai_0 _639_ (
    .A1(_283_),
    .A2(_284_),
    .B1(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__a22oi_1 _640_ (
    .A1(_248_),
    .A2(_286_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [3]),
    .Y(_287_)
  );
  sky130_fd_sc_hd__o22ai_1 _641_ (
    .A1(_273_),
    .A2(_264_),
    .B1(_257_),
    .B2(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__nand2_1 _642_ (
    .A(_288_),
    .B(_228_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a21oi_1 _643_ (
    .A1(_261_),
    .A2(_286_),
    .B1(_246_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__a22oi_1 _644_ (
    .A1(_282_),
    .A2(_246_),
    .B1(_289_),
    .B2(_290_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _645_ (
    .A(\u_spi_host_core.current_byte_q [4]),
    .Y(_291_)
  );
  sky130_fd_sc_hd__nor2_1 _646_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [4]),
    .Y(_292_)
  );
  sky130_fd_sc_hd__o21ai_0 _647_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [12]),
    .A2(_102_),
    .B1(_252_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _648_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [20]),
    .Y(_294_)
  );
  sky130_fd_sc_hd__o21ai_0 _649_ (
    .A1(_292_),
    .A2(_293_),
    .B1(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__a22oi_1 _650_ (
    .A1(_248_),
    .A2(_295_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [4]),
    .Y(_296_)
  );
  sky130_fd_sc_hd__o22ai_1 _651_ (
    .A1(_282_),
    .A2(_264_),
    .B1(_257_),
    .B2(_296_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nand2_1 _652_ (
    .A(_297_),
    .B(_228_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__a21oi_1 _653_ (
    .A1(_261_),
    .A2(_295_),
    .B1(_246_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__a22oi_1 _654_ (
    .A1(_291_),
    .A2(_246_),
    .B1(_298_),
    .B2(_299_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _655_ (
    .A(\u_spi_host_core.current_byte_q [5]),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nor2_1 _656_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [5]),
    .Y(_301_)
  );
  sky130_fd_sc_hd__o21ai_0 _657_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [13]),
    .A2(_102_),
    .B1(_252_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nand2_1 _658_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [21]),
    .Y(_303_)
  );
  sky130_fd_sc_hd__o21ai_0 _659_ (
    .A1(_301_),
    .A2(_302_),
    .B1(_303_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__a22oi_1 _660_ (
    .A1(_248_),
    .A2(_304_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [5]),
    .Y(_305_)
  );
  sky130_fd_sc_hd__o22ai_1 _661_ (
    .A1(_291_),
    .A2(_264_),
    .B1(_257_),
    .B2(_305_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2_1 _662_ (
    .A(_306_),
    .B(_228_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__a21oi_1 _663_ (
    .A1(_261_),
    .A2(_304_),
    .B1(_246_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__a22oi_1 _664_ (
    .A1(_300_),
    .A2(_246_),
    .B1(_307_),
    .B2(_308_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _665_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [6]),
    .Y(_309_)
  );
  sky130_fd_sc_hd__o21ai_0 _666_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [14]),
    .A2(_102_),
    .B1(_252_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nand2_1 _667_ (
    .A(_254_),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [22]),
    .Y(_311_)
  );
  sky130_fd_sc_hd__o21ai_0 _668_ (
    .A1(_309_),
    .A2(_310_),
    .B1(_311_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__a22oi_1 _669_ (
    .A1(_248_),
    .A2(_312_),
    .B1(_249_),
    .B2(\u_spi_host_core.current_byte_q [6]),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o22ai_1 _670_ (
    .A1(_300_),
    .A2(_264_),
    .B1(_257_),
    .B2(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nand2_1 _671_ (
    .A(_314_),
    .B(_228_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__a21oi_1 _672_ (
    .A1(_261_),
    .A2(_312_),
    .B1(_246_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__clkinv_1 _673_ (
    .A(_246_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nor2_1 _674_ (
    .A(\u_spi_host_core.current_byte_q [6]),
    .B(_317_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__a21oi_1 _675_ (
    .A1(_315_),
    .A2(_316_),
    .B1(_318_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _676_ (
    .A(\u_spi_host_core.current_byte_q [7]),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _677_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .B(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [7]),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nor2_1 _678_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [15]),
    .B(_102_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__nor3_1 _679_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .B(_320_),
    .C(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__a21oi_1 _680_ (
    .A1(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [23]),
    .A2(_254_),
    .B1(_322_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__or2_2 _681_ (
    .A(_323_),
    .B(_119_),
    .X(_324_)
  );
  sky130_fd_sc_hd__nand2_1 _682_ (
    .A(_324_),
    .B(_229_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__nand2_1 _683_ (
    .A(_317_),
    .B(_325_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__clkinv_1 _684_ (
    .A(_264_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__clkinv_1 _685_ (
    .A(_248_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__o22ai_1 _686_ (
    .A1(_328_),
    .A2(_323_),
    .B1(_319_),
    .B2(_250_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__a221oi_1 _687_ (
    .A1(\u_spi_host_core.current_byte_q [6]),
    .A2(_327_),
    .B1(_329_),
    .B2(_237_),
    .C1(_229_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__o22ai_1 _688_ (
    .A1(_319_),
    .A2(_317_),
    .B1(_326_),
    .B2(_330_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _689_ (
    .A(spi_cs_o),
    .B(\u_spi_host_core.current_state [1]),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nand2_1 _690_ (
    .A(_331_),
    .B(\u_spi_host_core.current_state [0]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _691_ (
    .A(\u_spi_host_core.byte_cnt_q [0]),
    .Y(_332_)
  );
  sky130_fd_sc_hd__nand2_1 _692_ (
    .A(_188_),
    .B(reg2hw[26]),
    .Y(_333_)
  );
  sky130_fd_sc_hd__nor2_1 _693_ (
    .A(\u_spi_host_core.current_state [0]),
    .B(_333_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__a211oi_1 _694_ (
    .A1(_228_),
    .A2(_248_),
    .B1(_233_),
    .C1(_334_),
    .Y(_335_)
  );
  sky130_fd_sc_hd__a21oi_1 _695_ (
    .A1(_332_),
    .A2(_234_),
    .B1(_335_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__a21oi_1 _696_ (
    .A1(_332_),
    .A2(_335_),
    .B1(_336_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _697_ (
    .A(\u_spi_host_core.byte_cnt_q [0]),
    .B(\u_spi_host_core.byte_cnt_q [1]),
    .Y(_337_)
  );
  sky130_fd_sc_hd__nor2_1 _698_ (
    .A(_332_),
    .B(_241_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__nor2_1 _699_ (
    .A(_337_),
    .B(_338_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__nor2_1 _700_ (
    .A(_229_),
    .B(_339_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__nor2_1 _701_ (
    .A(_340_),
    .B(_335_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nand3_1 _702_ (
    .A(_339_),
    .B(_229_),
    .C(_234_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__a22oi_1 _703_ (
    .A1(_241_),
    .A2(_335_),
    .B1(_341_),
    .B2(_342_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _704_ (
    .A(_228_),
    .B(_338_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__clkinv_1 _705_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .Y(_344_)
  );
  sky130_fd_sc_hd__nor2_1 _706_ (
    .A(_337_),
    .B(_229_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__a2111oi_0 _707_ (
    .A1(_234_),
    .A2(_343_),
    .B1(_344_),
    .C1(_345_),
    .D1(_335_),
    .Y(_346_)
  );
  sky130_fd_sc_hd__nor4_1 _708_ (
    .A(_233_),
    .B(_343_),
    .C(_345_),
    .D(_335_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__nor2_1 _709_ (
    .A(\u_spi_host_core.byte_cnt_q [2]),
    .B(_347_),
    .Y(_348_)
  );
  sky130_fd_sc_hd__nor2_1 _710_ (
    .A(_346_),
    .B(_348_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _711_ (
    .A(_334_),
    .B(_242_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__nand2_1 _712_ (
    .A(_349_),
    .B(\u_spi_host_core.r_wn_q ),
    .Y(_350_)
  );
  sky130_fd_sc_hd__o21ai_0 _713_ (
    .A1(_324_),
    .A2(_349_),
    .B1(_350_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _714_ (
    .A(_236_),
    .B(\u_spi_host_core.bit_cnt_q [3]),
    .Y(_351_)
  );
  sky130_fd_sc_hd__o21ai_0 _715_ (
    .A1(_351_),
    .A2(_120_),
    .B1(_228_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__nand2_1 _716_ (
    .A(_349_),
    .B(_352_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor3_1 _717_ (
    .A(_229_),
    .B(_351_),
    .C(_120_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand4_1 _718_ (
    .A(_075_),
    .B(tl_i[62]),
    .C(tl_i[63]),
    .D(_071_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__clkinv_1 _719_ (
    .A(_353_),
    .Y(\u_spi_host_reg.u_wdata.qe )
  );
  sky130_fd_sc_hd__nand2_1 _720_ (
    .A(_353_),
    .B(reg2hw[1]),
    .Y(_354_)
  );
  sky130_fd_sc_hd__o21ai_0 _721_ (
    .A1(_194_),
    .A2(_353_),
    .B1(_354_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _722_ (
    .A(_353_),
    .B(reg2hw[2]),
    .Y(_355_)
  );
  sky130_fd_sc_hd__o21ai_0 _723_ (
    .A1(_180_),
    .A2(_353_),
    .B1(_355_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _724_ (
    .A(_353_),
    .B(reg2hw[3]),
    .Y(_356_)
  );
  sky130_fd_sc_hd__o21ai_0 _725_ (
    .A1(_192_),
    .A2(_353_),
    .B1(_356_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _726_ (
    .A(\u_spi_host_reg.u_wdata.qe ),
    .B(tl_i[27]),
    .Y(_357_)
  );
  sky130_fd_sc_hd__nand2_1 _727_ (
    .A(_353_),
    .B(reg2hw[4]),
    .Y(_358_)
  );
  sky130_fd_sc_hd__nand2_1 _728_ (
    .A(_357_),
    .B(_358_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _729_ (
    .A(\u_spi_host_reg.u_wdata.qe ),
    .B(tl_i[28]),
    .Y(_359_)
  );
  sky130_fd_sc_hd__nand2_1 _730_ (
    .A(_353_),
    .B(reg2hw[5]),
    .Y(_360_)
  );
  sky130_fd_sc_hd__nand2_1 _731_ (
    .A(_359_),
    .B(_360_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _732_ (
    .A(\u_spi_host_reg.u_wdata.qe ),
    .B(tl_i[29]),
    .Y(_361_)
  );
  sky130_fd_sc_hd__nand2_1 _733_ (
    .A(_353_),
    .B(reg2hw[6]),
    .Y(_362_)
  );
  sky130_fd_sc_hd__nand2_1 _734_ (
    .A(_361_),
    .B(_362_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _735_ (
    .A(\u_spi_host_reg.u_wdata.qe ),
    .B(tl_i[30]),
    .Y(_363_)
  );
  sky130_fd_sc_hd__nand2_1 _736_ (
    .A(_353_),
    .B(reg2hw[7]),
    .Y(_364_)
  );
  sky130_fd_sc_hd__nand2_1 _737_ (
    .A(_363_),
    .B(_364_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _738_ (
    .A(\u_spi_host_reg.u_wdata.qe ),
    .B(tl_i[31]),
    .Y(_365_)
  );
  sky130_fd_sc_hd__nand2_1 _739_ (
    .A(_353_),
    .B(reg2hw[8]),
    .Y(_366_)
  );
  sky130_fd_sc_hd__nand2_1 _740_ (
    .A(_365_),
    .B(_366_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _741_ (
    .A(\u_spi_host_core.bit_cnt_q [0]),
    .Y(_367_)
  );
  sky130_fd_sc_hd__nand2_1 _742_ (
    .A(_249_),
    .B(_351_),
    .Y(_368_)
  );
  sky130_fd_sc_hd__a21oi_1 _743_ (
    .A1(_368_),
    .A2(_228_),
    .B1(_233_),
    .Y(_369_)
  );
  sky130_fd_sc_hd__nor2_1 _744_ (
    .A(_367_),
    .B(_369_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__a21oi_1 _745_ (
    .A1(_367_),
    .A2(_231_),
    .B1(_370_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _746_ (
    .A(\u_spi_host_core.bit_cnt_q [0]),
    .B(\u_spi_host_core.bit_cnt_q [1]),
    .Y(_371_)
  );
  sky130_fd_sc_hd__a31oi_1 _747_ (
    .A1(_247_),
    .A2(_234_),
    .A3(_371_),
    .B1(_369_),
    .Y(_372_)
  );
  sky130_fd_sc_hd__nor2_1 _748_ (
    .A(\u_spi_host_core.bit_cnt_q [1]),
    .B(_370_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__nor2_1 _749_ (
    .A(_372_),
    .B(_373_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _750_ (
    .A(_371_),
    .B(_231_),
    .Y(_374_)
  );
  sky130_fd_sc_hd__nor2_1 _751_ (
    .A(\u_spi_host_core.bit_cnt_q [2]),
    .B(_374_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__a21oi_1 _752_ (
    .A1(_372_),
    .A2(\u_spi_host_core.bit_cnt_q [2]),
    .B1(_375_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a22o_1 _753_ (
    .A1(\u_spi_host_core.bit_cnt_q [2]),
    .A2(_374_),
    .B1(_369_),
    .B2(\u_spi_host_core.bit_cnt_q [3]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _754_ (
    .A(\u_spi_host_core.sclk ),
    .B(_352_),
    .Y(\u_spi_host_core.u_clk_div2.d_i )
  );
  sky130_fd_sc_hd__clkinv_1 _755_ (
    .A(\u_spi_host_core.sclk ),
    .Y(_376_)
  );
  sky130_fd_sc_hd__nor2_1 _756_ (
    .A(spi_cs_o),
    .B(_376_),
    .Y(\u_spi_host_core.u_sclk_driver.d_i )
  );
  sky130_fd_sc_hd__nor2_1 _757_ (
    .A(_247_),
    .B(_238_),
    .Y(\u_spi_host_core.rx_fifo_wvalid_d )
  );
  sky130_fd_sc_hd__nor2_1 _758_ (
    .A(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_215_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _759_ (
    .A(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .B(_189_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o21ai_0 _760_ (
    .A1(_229_),
    .A2(_328_),
    .B1(_349_),
    .Y(\u_spi_host_core.tx_fifo_rready_d )
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _761_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(tl_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _762_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(tl_o[16]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _763_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(tl_o[17]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _764_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(tl_o[18]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _765_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(tl_o[19]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _766_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(tl_o[20]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _767_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(tl_o[21]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _768_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(tl_o[22]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _769_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(tl_o[23]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:140.5" *)
  sky130_fd_sc_hd__dfrtp_1 _770_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(tl_o[47]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _771_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(tl_o[49]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _772_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(tl_o[50]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _773_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(tl_o[51]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _774_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(tl_o[52]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _775_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(tl_o[53]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _776_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(tl_o[54]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _777_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(tl_o[55]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _778_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(tl_o[56]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _779_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(tl_o[57]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _780_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(tl_o[58]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:94.3" *)
  sky130_fd_sc_hd__dfrtp_1 _781_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(tl_o[65]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _782_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(reg2hw[27]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _783_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _784_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _785_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _786_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(reg2hw[28]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _787_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(reg2hw[26]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _788_ (
    .CLK(clk_i),
    .D(\u_spi_host_reg.u_wdata.qe ),
    .Q(reg2hw[0]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/tlul/tlul_adapter_reg.sv:100.3" *)
  sky130_fd_sc_hd__dfrtp_1 _789_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(tl_o[62]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _790_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.u_clk_div2.d_i ),
    .Q(\u_spi_host_core.sclk ),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_flop.sv:17.3" *)
  sky130_fd_sc_hd__dfrtp_1 _791_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.u_sclk_driver.d_i ),
    .Q(spi_sclk_o),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _792_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _793_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _794_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _795_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _796_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:112.5" *)
  sky130_fd_sc_hd__dfrtp_1 _797_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:68.5" *)
  sky130_fd_sc_hd__dfstp_2 _798_ (
    .CLK(clk_i),
    .D(1'h0),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.under_rst ),
    .SET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _799_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _800_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync_cnt.sv:124.5" *)
  sky130_fd_sc_hd__dfrtp_1 _801_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _802_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(spi_sdio_o),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _803_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(\u_spi_host_core.current_byte_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _804_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(\u_spi_host_core.current_byte_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _805_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(\u_spi_host_core.current_byte_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _806_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(\u_spi_host_core.current_byte_q [3]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _807_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(\u_spi_host_core.current_byte_q [4]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _808_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(\u_spi_host_core.current_byte_q [5]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _809_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(\u_spi_host_core.current_byte_q [6]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _810_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(\u_spi_host_core.current_byte_q [7]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfstp_2 _811_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(spi_cs_o),
    .SET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _812_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(\u_spi_host_core.byte_cnt_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _813_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(\u_spi_host_core.byte_cnt_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _814_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(\u_spi_host_core.byte_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _815_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\u_spi_host_core.r_wn_q ),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _816_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.sdioz_d ),
    .Q(spi_sdioz_o),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _817_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.tx_fifo_rready_d ),
    .Q(\u_spi_host_core.tx_fifo_rready ),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _818_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.rx_fifo_wvalid_d ),
    .Q(\u_spi_host_core.rx_fifo_wvalid ),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:156.3" *)
  sky130_fd_sc_hd__dfrtp_1 _819_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(\u_spi_host_core.current_state [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:156.3" *)
  sky130_fd_sc_hd__dfrtp_1 _820_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(\u_spi_host_core.current_state [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _821_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(reg2hw[1]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _822_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(reg2hw[2]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _823_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(reg2hw[3]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _824_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(reg2hw[4]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _825_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(reg2hw[5]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _826_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(reg2hw[6]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _827_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(reg2hw[7]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_subreg.sv:55.3" *)
  sky130_fd_sc_hd__dfrtp_1 _828_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(reg2hw[8]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _829_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(\u_spi_host_core.bit_cnt_q [0]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _830_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(\u_spi_host_core.bit_cnt_q [1]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _831_ (
    .CLK(clk_i),
    .D(_069_),
    .Q(\u_spi_host_core.bit_cnt_q [2]),
    .RESET_B(rst_ni)
  );
  (* src = "../workspace/runs/spi_host/dev/rtl/spi_host_core.sv:166.3" *)
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(clk_i),
    .D(_070_),
    .Q(\u_spi_host_core.bit_cnt_q [3]),
    .RESET_B(rst_ni)
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _833_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [7])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _834_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [15])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _835_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [7]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [23])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _836_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [7])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _837_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [15])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _838_ (
    .CLK(clk_i),
    .D(reg2hw[8]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [23])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _839_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [16])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _840_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [17])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _841_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [18])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _842_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [19])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _843_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [20])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _844_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [21])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _845_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_005_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [22])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _846_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [0])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _847_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [1])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _848_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [2])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _849_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [3])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _850_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [4])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _851_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [5])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _852_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_003_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [6])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _853_ (
    .CLK(clk_i),
    .D(reg2hw[1]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [8])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _854_ (
    .CLK(clk_i),
    .D(reg2hw[2]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [9])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _855_ (
    .CLK(clk_i),
    .D(reg2hw[3]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [10])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _856_ (
    .CLK(clk_i),
    .D(reg2hw[4]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [11])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _857_ (
    .CLK(clk_i),
    .D(reg2hw[5]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [12])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _858_ (
    .CLK(clk_i),
    .D(reg2hw[6]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [13])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _859_ (
    .CLK(clk_i),
    .D(reg2hw[7]),
    .DE(_004_),
    .Q(\u_spi_host_core.u_spi_txfifo.gen_normal_fifo.storage [14])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _860_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [16])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _861_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [17])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _862_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [18])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _863_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [19])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _864_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [20])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _865_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [21])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _866_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_002_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [22])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _867_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [0])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _868_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [1])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _869_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [2])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _870_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [3])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _871_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [4])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _872_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [5])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _873_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_000_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [6])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _874_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [0]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [8])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _875_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [1]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [9])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _876_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [2]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [10])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _877_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [3]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [11])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _878_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [4]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [12])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _879_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [5]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [13])
  );
  (* src = "../hw/ips/prim_opentitan/prim_fifo_sync.sv:122.7" *)
  sky130_fd_sc_hd__edfxtp_1 _880_ (
    .CLK(clk_i),
    .D(\u_spi_host_core.current_byte_q [6]),
    .DE(_001_),
    .Q(\u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.storage [14])
  );
  assign reg2hw[25:10] = 16'b0x0x0x0x00000000;
  assign { tl_o[64:63], tl_o[61:59], tl_o[48], tl_o[46:24], tl_o[15:2] } = { 6'h00, tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], tl_o[47], 14'h0000 };
  assign \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_rptr ;
  assign \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_rxfifo.gen_normal_fifo.fifo_wptr ;
  assign \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.rptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_rptr ;
  assign \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.u_fifo_cnt.wptr_wrap_cnt_q [1:0] = \u_spi_host_core.u_spi_txfifo.gen_normal_fifo.fifo_wptr ;
endmodule
